### PR TITLE
af_lavfi: tell aformat filter which channel layouts mpv accept from lavfi

### PR DESCRIPTION
**Pull request by richardpl**
This fixes issues with bunch of lavfi filters

### CODE REVIEW

**Comment by wm4** [comment]
You're just hardcoding some channel layouts, and in a bad way.

**Comment by richardpl** [comment]
Those are channel layouts supported both by mpv and by lavfi, there is no other way to do this.

**Comment by richardpl** [comment]
Fixed differently.

**Comment by kevmitch** [comment]
> Fixed differently.

How? Or is that pending?

There's always mp_chmap_is_lavc().

**Comment by wm4** [comment]
>There's always mp_chmap_is_lavc(). 

There are 2^32 channel layouts, or 2^64 if you count lavc's (potential) extensions. A bit too much to enumerate them all.

**Pull request closed without merging**
