### PR TITLE
w32_common: fix --geometry parameter being constrainted to the incorrect monitor

### PR DESCRIPTION
**Pull request by ZenoArrows**
Currently the `--geometry` parameter is constrained by the size of the primary monitor even if the position of the window is located on another monitor. This PR attempts to fix this in two ways:

1. Don't constrain the window size if `VO_WIN_FORCE_POS` is set, this is set when either `--geometry` or `--force-window-pos` is used.
2. Fix the root cause issue by fetching the monitor based on the cached window bounds when the window is not yet visible.

### CODE REVIEW

**Review by Dudemanguy — APPROVED** [review]
Not familiar with windows but looks reasonable.

**Comment by Traneptora** [comment]
Could someone familiar with windows programming such as @kasper93 or @DeadSix27 take a look at and/or test this to make sure it works? I would but I'm just not a Windows API programmer.

**Comment by sfan5** [comment]
ready for merge? yes or no?

**Comment by Dudemanguy** [comment]
Merge it and see if anyone complains since nobody tests windows anyway? ¯\_(ツ)_/¯ It's true that the `--geometry` option should fetch the wrong monitor on initialization at least unless maybe you pass options like `--screen` to work around it.

**Comment by kasper93** [comment]
> Merge it and see if anyone complains since nobody tests windows anyway?

I try to avoid `w32_common.c` as much as possible. mpv window has a lot of quirks, there is status quo that is accepted by most. Those PR are adding glue on top while the code need proper refactor. That's say, just merge it and wait for reports...

**Pull request merged**
