### PR TITLE
cocoa-cb: fall back to software renderer when everything fails

### PR DESCRIPTION
**Pull request by Akemi**
~~i would have liked to add an options for this, but since we need to pre-allocate the opengl context before any options access is available to us this is sadly not possible.~~

besides making mpv usable in VMs, this should also fix a problem with homebrews automatic jenkins testing (https://github.com/Homebrew/homebrew-core/pull/30369). @ilovezfs do you think you can test and confirm that this fixes the testing problem with homebrew?

### CODE REVIEW

**Comment by JCount** [comment]
Thanks @Akemi, I was just about to ask if you had any advice on CI testing.

**Comment by JCount** [comment]
Ok, I've added this PR as a patch to 
https://github.com/Homebrew/homebrew-core/pull/30369, triggering a rebuild. Now I must wait. 😑

**Comment by JCount** [comment]
Ok, I can confirm that this fixes the issue on Homebrew's CI. Thank you. 🙇

**Comment by Akemi** [comment]
waiting for a dev with push rights to review and merge this PR.

**Comment by jeeb** [comment]
Tested locally.

**Comment by Akemi** [comment]
@JCount @ilovezfs just a heads up that we released 0.29.1 with this fix backported.

**Pull request merged**
