### PR TITLE
player/ytdl_hook: create --ytdl-path option

### LINKED ISSUE #7940: custom ytdl path
Before requesting a new feature make sure it hasn't been requested yet.
https://github.com/mpv-player/mpv/labels/meta%3Afeature-request

### Expected behavior of the wanted feature
provide the path to ytdl to force using it instead of $(which youtube-dl), like:
```
mpv --ytdl-path=/bin/custom-ytdl https://www.youtube.com/watch?v=fwA_0N5NyEY
```

### Alternative behavior of the wanted feature
no idea

### Log file

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt, paste
it to https://0x0.st/ or attach it to the github issue, and replace this text
with a link to it.
nani?

### PR DESCRIPTION
**Pull request by thebombzen**
This commit creates a --ytdl-path option to allow users to point mpv
to a specific youtube-dl binary. This allows users to test against
various youtube-dl versions, or provide their own youtube-dl should
their distribution's copy be out of date - without modifying their
environment. If unset (which is the default) then mpv should behave
exactly as it has before, but if set then mpv will use the provided
path instead of its usual scan.

Fixes #7940.

### CODE REVIEW

**Comment by wm4** [comment]
No. Users can just set PATH.

**Comment by thebombzen** [comment]
What if youtube-dl isn't "named" youtube-dl? Or a different version?

**Comment by thebombzen** [comment]
We also have precedent for providing configurability that can be controlled with environment variables - like how `--config-dir` is an option but can also be controlled by MPV_HOME.

**Comment by wm4** [comment]
`--config-dir` is a central thing that may also be needed to be used by libmpv applications.
The youtube-dl path is an extremely obscure thing because normally there's no reason to change the youtube-dl path or even its binary name.

**Comment by selfisekai** [comment]
> The youtube-dl path is an extremely obscure thing because normally there's no reason to change the youtube-dl path or even its binary name.

@wm4 objection. I'm forking youtube-dl under a new name. registering the `youtube-dl` entry point by the fork *will* obviously conflict with the upstream youtube-dl.

**Comment by thebombzen** [comment]
Yea, youtube-dl is going through some maintainment management hell right now so I figured if anyone wanted to do something like fork it, mpv should at least be able to seamlessly work with those sorts of things.

**Comment by blackjack4494** [comment]
> Yea, youtube-dl is going through some maintainment management hell **right now** so I figured if anyone wanted to do something like fork it, mpv should at least be able to seamlessly work with those sorts of things.

https://github.com/ytdl-org/youtube-dl/issues/26462

I wouldn't say it just occured now. If you check repo stats you can see a huge decline lately.

**Comment by wiiaboo** [comment]
Superseeded by #8207

**Pull request closed without merging**
