### PR TITLE
Use libav to play RIST streams

### PR DESCRIPTION
**Pull request by The-head-obamid**
Reliable Internet Stream Protocol is an open specification streaming protocol targeted to be a more reliable successor to Secure Reliable Transport and has been supported in things like ffmpeg and obs for a while now.

I've had better experiences using rist than srt for the time I've been testing it for my, admittedly very simple streaming use cases, in mpv and it supports a nice feature set with things like encryption and retransmission of lost packets all while maintaining a good latency, that being said, it's a simple addition and would be nice to have, and is shaping up to be a good candidate for the next generation of streaming protocols, so could potentially be important for future adoption depending on the direction we're headed.

### CODE REVIEW

**Comment by The-head-obamid** [comment]
So more correct commit messages for my second two commits would be:
osxbundle: add RIST protocol to app metadata
mpv.desktop: add RIST protocol to desktop entry

And secondly, would those distributions not having librist and by proxy, ffmpeg rist support, cause issues in usage, I must admit my highly personalized gentoo config has led me to completely overlook that possibility and the status of librist itself in linux distributions (there is not even an official ebuild for gentoo or any public repositories I use), I did not even consider that end of it and try to test it, if that is not a problem, I will fix those commits and this addition will hopefully be fine

**Comment by sfan5** [comment]
> So more correct commit messages for my last two commits would be:
> osxbundle: add RIST protocol to app metadata
> mpv.desktop: add RIST protocol to desktop entry

yes

**Comment by The-head-obamid** [comment]
It appears I am retarded...  I don't know what I should have done to just reformat the commits

**Comment by christoph-heinrich** [comment]
You can edit your past commits using `git rebase -i`, so for your last two commits you could use `git rebase -i HEAD^^` and then replace the `pick` with `e` or `edit` on the commits you want to change.

**Pull request closed without merging**
