### PR TITLE
codepage autodetection for .ass turned on back

### PR DESCRIPTION
**Pull request by FeiWongReed**
Fix for https://github.com/mpv-player/mpv/issues/2669 and https://github.com/mpv-player/mpv/issues/2633

### CODE REVIEW

**Comment by wm4** [comment]
Actually read the contribution guidelines.

Remove the comment from the code. It's unnecessary and noisy. Add it to the commit messages instead - explaining strange changes belongs there, not in the code.

**Comment by FeiWongReed** [comment]
I have updated p/r.

**Comment by wm4** [comment]
Commit message still violates the conventions used in this project.

**Comment by FeiWongReed** [comment]
Is it better now?

**Comment by wm4** [comment]
No. You forgot multiple things: keeping the subject short, adding an empty line between subject and commit message body, limiting the length of the lines in the message, and minor ones like adding a dot at the end of the subject (which looks completely different from all other commits in mpv in the last 3 years).

Anyway, I edited the commit message and pushed it. I also changed the first sentence in the subject.

**Comment by FeiWongReed** [comment]
Thanks a lot for your kindest help from all the russian-speaking anime watchers.

**Pull request closed without merging**
