### PR TITLE
ytdl_hook: consistant behavior for single format

### PR DESCRIPTION
**Pull request by christoph-heinrich**
One would expect that e.g.
`--script-opts=ytdl_hook-all_formats=no --ytdl-format=bestaudio` and
`--script-opts=ytdl_hook-all_formats=yes --ytdl-format=bestaudio`
to play the exact same tracks without manual intervention.
This already worked when two formats were requested.
For a single format with `all_formats=yes` it would also play a track
that was not requested when available. This was inconsistant with the
behavior of `all_formats=no` (default), which would not play a second
track when only a single one was requested.
This combined with #10395 now plays the exact same tracks with
`all_formats=yes` as without, even when only one format is requested.

### CODE REVIEW

**Comment by christoph-heinrich** [comment]
This is not a nice solution, but it works without a problem for me so far.
Alternatively the same could be achieved by changing the EDL format to not only have a flag for default tracks, but also a flag for tracks that should not be automatically selected.

**Comment by guidocella** [comment]
It's better to use `mp.set_property("file-local-options/` to not affect other playlist entries.

**Comment by christoph-heinrich** [comment]
Thanks, I've corrected that and it now also respects `vid` and `aid` when they are not set to `"auto"`.
I think with that in place, this isn't all that bad anymore.

**Review by Dudemanguy — APPROVED** [review]
I'm by no means familiar with this script, but the solution looks reasonable to me and fixes a bug. I wouldn't expect anything involving youtube to be perfectly pretty and clean anyways.

**Comment by christoph-heinrich** [comment]
Honestly looking at that code now, I don't know why I was keeping track of the aid and vid.

**Comment by Dudemanguy** [comment]
Even better now. Thanks!

**Pull request merged**
