### PR TITLE
[RFC] Reapply "demux_mkv: PAR should be calculated after applying crop"

### PR DESCRIPTION
**Pull request by kasper93**
Follow the spec for better or for worse.

This reverts commit 81102b0f6c7db956cd222ea3e81debda36de5a78.

### CODE REVIEW

**Comment by wiwaz** [comment]
My thoughts:
"DisplayWidth" and "DisplayHeight" are not used as exact dimensions the player should resize to. These values are instead used as a PAR transform to be applied.

Matroska spec states:
> 5.1.4.1.28.12.  DisplayWidth Element
>    definition:  Width of the video frames to display.  Applies to the
>       video frame after cropping (PixelCrop* Elements).

When I read "Applies to the video frame after cropping" I believe it means "Applies (the PAR transform) to the video frame after cropping". This makes sense, but the matroska spec never seems to specify whether the PAR should be calculated using the original dimensions, or the cropped dimensions. This key detail being left out has lead to confusion here with how this feature should actually be implemented. Despite the spec leaving this detail out, I believe we can make a perfectly reasonable assumption on how PAR is to be calculated.

My opinion is that PAR should always be calculated using the original image dimensions, here is why:
- This means PAR will stay the same (and thus correct) even if cropping is not applied.
- Because PAR is not tied to the crop this means players that do not support matroska crop will still play such files with the correct PAR.
- Lastly, this means when creating these files the user does not need to recalculate what the PAR should be every time they change or add cropping metadata.

It would be nice if the spec was clear on this subject, and I suppose this can also serve as a pitch for what the spec should be. 🙂

**Comment by astiob** [comment]
If you assume it talks about applying some particular, fixed transform, then it wouldn’t matter whatsoever when this transform is applied. To me, it very clearly says that the picture, after cropping, is to be rescaled to have the size specified by DisplayWidth/Height. In fact, if you follow the letter of the spec, then DisplayUnit=0 says DisplayWidth/Height are absolutely exact pixel dimensions that you must rescale the picture to. But even if DisplayUnit is something else or you ignore this stipulation, DisplayWidth divided by DisplayHeight still unambiguously defines the aspect ratio of the resulting picture. I genuinely fail to see how else this can be interpreted.

See also the [section on cropping](https://datatracker.ietf.org/doc/html/draft-ietf-cellar-matroska-21#name-cropping):

> Cropping has to be performed before resizing and the display dimensions given by `DisplayWidth`, `DisplayHeight` and `DisplayUnit` apply to the already cropped image.

**Comment by kasper93** [comment]
In the meantime I found related discussion here https://gitlab.com/mbunkus/mkvtoolnix/-/issues/2389

> As you know, the majority of players don't honour the Matroska cropping flags and this not going to change anytime soon so that files should be compatible with both types of players (those that honour the flags and those that ignore them). The fact that the display dimensions specify the target dimensions after the cropping has taken place complicates this.

This is exactly my main issue. I don't want to make mpv become not compatible with seemingly all matroska files with cropping metadata. I think cropping should not change the pixel aspect ratio of the target rect. Which would makes files compatible with both crop-aware and crop-unaware players.

That's why the commit was reverted to fix the playback of existing matroska files, which most of them from what I've seen are setting DisplayWidth/Height to uncropped values.

That's also why I pinged @mbunkus, because I would like to have authoritative statement on cropping behavior. So that we can refer to that if users complain about "broken" files. 

Also as you know we can just make matroska cropping disabled behind a configuration flag, but I would really like to avoid that, because it is merely workaround and forces user to control something that should be done automatically be the player.

**Comment by astiob** [comment]
To recap what I said elsewhere:

As it stands now, I think the best solution would be to change the spec. Of course, we’ll need co-operation from spec maintainers for this. But if spec maintainers should insist otherwise, then I don’t like the prospect of making mpv consciously violate the spec.

I think the original intention of Matroska spec writers, as well as the intention and meaning of the current spec text, is that crop should be very hard crop that happens before anything else including any aspect ratio calculations, and that the non-cropped size shouldn’t be exposed or used during rendering in any way other than to apply the crop. This is indeed how Haali originally implemented it, barring some conflict between Matroska crop and bitstream-embedded crop. This is also how I would define container crop myself if I were adding it as a new container feature today.

But the problem is compatibility with software that makes no attempt to support Matroska crop. The spec says crop merely “should” be supported. Most players ignore Matroska crop and apply display aspect ratio to the video rectangle spit out by the decoder (nominally described by PixelWidth/PixelHeight—to be clear, this is the rectangle after the decoder has already applied bitstream-embedded crop). On the muxing side, too, MKVToolNix has apparently been writing values where DisplayWidth/Height match PixelWidth/Height _without_ subtracting the crop offsets, and people have apparently been producing real files containing such crops. Further, if we assume that those people have been targeting a real player, then this means that _somewhere_ out there there is a player other than mpv that actually supports crop—and it treats it the same way as MKVToolNix.

**Comment by astiob** [comment]
Oh, one thing that will need to be considered and made abundantly clear in the wording if the spec is changed is whether the crop values refer to pre-stretching pixels or post-stretching. @wiwaz Could this be what you meant earlier by any chance?

That is, this is clear:

```
PixelWidth: 1920
PixelHeight: 1080
DisplayWidth: 1920
DisplayHeight: 1080
CropTop: 80
CropBottom: 80
```

But this is less clear:

```
PixelWidth: 720
PixelHeight: 480
DisplayWidth: 864
DisplayHeight: 480
CropLeft: 4
CropRight: 5
```

Is this `clip.scale(864, 480).crop(4, 5, 0, 0)` or `clip.crop(4, 5, 0, 0).scale(864 / 720 * (720 - 4 - 5), 480)`? I assume mpv currently treats it as the latter, but this isn’t exactly clear when you just look at the property names and values. (And this is another reason why I think the current spec wording is more intuitive, but I digress.)

**Comment by wiwaz** [comment]
> Oh, one thing that will need to be considered and made abundantly clear in the wording if the spec is changed is whether the crop values refer to pre-stretching pixels or post-stretching. @wiwaz Could this be what you meant earlier by any chance?

Not exactly, the spec does make it explicitly clear that cropping is *always* applied before resizing the image according to DisplayWidth/DisplayHeight

> Is this clip.scale(864, 480).crop(4, 5, 0, 0) or clip.crop(4, 5, 0, 0).scale(864 / 720 * (720 - 4 - 5), 480)? I assume mpv currently treats it as the latter

The latter, your former example does not adhere to the spec.

The concern I brought up is whether the amount the image should be stretched by is calculated using the original dimensions, or those set in DisplayWidth/DisplayHeight. The spec has no information on which is to be used, so I've laid out why always using the original dimensions should be the desired behavior.

**Comment by astiob** [comment]
> Not exactly, the spec does make it explicitly clear that cropping is always applied before resizing the image according to DisplayWidth/DisplayHeight

I may have phrased the question poorly, but sounds like a yes to me: that is, you think that what the spec does define is exactly this.

> The latter, your former example does not adhere to the spec.

Of course. To the current spec. Neither does mpv’s current behaviour, because the spec does define what its transform is: it transforms “the video frame after cropping” (in your own quote above) to the dimensions specified by DisplayWidth/Height. But if we do change the spec, then these examples become intuitively unclear and need additional clarification in the spec.

**Comment by astiob** [comment]
Worth adding that according to matroska.org, crop is also part of WebM, which sounds like it might have a bigger impact beyond the bunch of old-fashioned anime fans that we are.

But from a few quick tests, it seems Blink completely ignores the crop properties and applies DisplayWidth/Height to the whole encoded video (matching the hypothetical adjusted spec wording), whereas Gecko does something weird.

I’m not quite sure, but I think Gecko’s support for crop is just broken and is worse than no support. Depending on the aspect ratios, it either crops nothing or crops various amounts off the bottom even when my crop says Top. I haven’t been able to deduce a pattern.

I’ve only tested these two engines.

**Comment by kasper93** [comment]
After thinking about it, discussing and testing with samples that I have I decide to close this PR.

I think we can agree that the current Matroska specification is not perfect. I agree that we should aim to amend it to resolve current issues with cropping.

I also tested multiple samples that I have found and they are not only "anime", I gathered some archival stuff from archive.org, they surprisingly have crop parameters in some of the videos. 

It has been confirmed that MKVToolNix currently does not consider crop values when calculating default DisplayWidth/DisplayHeight values. Which effectively produces non-spec compliant files, unless user manually calculate the correct values. But I honestly think, no one is doing that, as it is even not that trivial to calculate the value...

Given that if we would follow current version of specification to the letter, mpv would play most if not all files incorrectly. That's why the conclusion is the same as before and the commit in question will be kept reverted.

We can still discuss here, but I suggest consolidating discussion over here https://gitlab.com/mbunkus/mkvtoolnix/-/issues/2389

I will also try to summarize the issue in short email to IETF ML as suggested, for visibility and possibly to kick-start discussion on updating the spec.

**Comment by jmuchemb** [comment]
I don't deny the advantages of applying PAR first but then I really hope that the spec will be changed to match it.

I also feared that cropping was applied on a resized (by DisplayWidth/DisplayHeight) image which would be an issue in several ways. Good to see that the current implementation crops the original pixels. In fact, the whole issue comes from the existence of DisplayWidth/DisplayHeight properties: there should be only PAR properties.

Apart from that I'm curious what other software supports MKV cropping. I see none mentioned but they should exist if there already are cropped videos in the wild.

**Comment by forthrin** [comment]
I do `--video-crop=(width)x876` to fit videos underneath the 24 pixel top bar on a 900 pixel Mac. I fixed the script by multiplying the height with `mp.get_property('video-params/par')`.

However, when cropping from the command line, one must now first find the DAR value with FFmpeg, fire up "Calculator" to crunch on "876 * DAR", and then change the command line accordingly. Not so funny...

Just weighing in on an aspect of the change for future considerations.

**Pull request closed without merging**
