### PR TITLE
macos: add default handler function

### PR DESCRIPTION
**Pull request by jdek**
Kinda WIP and taking suggestions on best way to get extensions. Would be nice to be able to set the default handler from within mpv i.e. without duti which is kinda broken on arm64

### CODE REVIEW

**Comment by Akemi** [comment]
first you should fix the build errors. i am not sure if this makes sense, eg setting 'all' extensions as default might be overkill. the list we support is pretty exhaustive (see https://github.com/mpv-player/mpv/blob/master/TOOLS/osxbundle/mpv.app/Contents/Info.plist). wouldn't it make more sense to only set it fpr the currently played file and its extension?

also shouldn't this be a bundle only function but not for the plain binary?

**Comment by jdek** [comment]
> setting 'all' extensions as default might be overkill

Yes I agree, thats why I think some 'sensible' defaults might be better. The other thought I had was a custom command so a user could `set default-application webm mkv mov` in the .conf and then did it from there rather than having it in the menu.

> wouldn't it make more sense to only set it for the currently played file and its extension?

This is just as bad as having to do them all individually by-file-type in Finder. The point of this PR is to automate many file type associations

> also shouldn't this be a bundle only function but not for the plain binary?

I think most people will have it installed as a bundle even if they are using the binary from the cli

**Comment by Akemi** [comment]
> This is just as bad as having to do them all individually by-file-type in Finder. The point of this PR is to automate many file type associations

tbh i think this isn't something mpv should do anyway. hardcoding a not definable list of extensions that mpv should be set as default App seems imo to be a bad idea. it's very likely that a user might want one or more of those default App associations not to change and keep the current default app.

> I think most people will have it installed as a bundle even if they are using the binary from the cli

this is an assumption we should not make. if a bundle with the identifier is not installed, it should not be set as a default App. hardcoding that identifier for that matter is a bad idea. with that being said, this should only be available for the bundle (and possibly the binary launched from within the bundle), and only for the identifier retrievable from the NSBundle.

**Comment by Akemi** [comment]
on a side note, i would say the build doesn't work because UTType is only available on macOS 11+ https://developer.apple.com/documentation/uniformtypeidentifiers/uttype. so including other things won't help.

**Comment by jdek** [comment]
Better as a script. See https://github.com/jdek/openwith

**Pull request closed without merging**
