### PR TITLE
cocoa: don't change Space on quit in fullscreen

### PR DESCRIPTION
**Pull request by Akemi**
i have a bit more sophisticated branch [here](https://github.com/Akemi/mpv/commits/cocoa_spacefix2). the difference is that the linked branch waits for the space transition animation to finish before releasing the window, whereas the this PR closes the window immediately.

i like the behaviour if this PR better, though i am not too sure if it might break some obscure corner case.

### CODE REVIEW

**Comment by enoposix** [comment]
Without this with mpv in native FS it exits a lot faster, what is the intended behaviour? I don't really see any benefit to this

**Comment by Akemi** [comment]
see issue #3957.

**Comment by Akemi** [comment]
i found another bug with this where changing the video track (underscore _ ) lead to some kind of undefined behaviour in an Apple framework. i just moved the window closing to a separate thread instead of exiting the fullscreen beforehand. will merge the commits later.

the bug it triggered.
```
NSWindow Full Screen Error: Please log a bug (associated with 24435927). The dock callback happened but we are in the 4 state instead of NSExitingFullScreen. 
(
	0   AppKit                              0x00007fff93930c54 -[_NSFullScreenTransition startExitFullScreenTransitionForCGWindow:targetFrame:duration:completionHandler:] + 329
	1   AppKit                              0x00007fff93930b00 -[_NSWindowFullScreenTransition _exitFullScreenModeForWindow:duration:completionHandler:] + 156
	2   AppKit                              0x00007fff93750ddc NSPerformVisuallyAtomicChange + 147
	3   AppKit                              0x00007fff940607fd __123-[_NSWindowFullScreenTransition _performExitFullScreenModeForWindow:windowController:options:customWindows:doKitAnimation:]_block_invoke + 895
	4   AppKit                              0x00007fff93b1bd5c __NSFullScreenDockConnectionSendExitForTransition_block_invoke + 88
	5   libxpc.dylib                        0x00007fffab347d99 _xpc_connection_reply_callout + 45
	6   libxpc.dylib                        0x00007fffab347d27 _xpc_connection_call_reply + 36
	7   libdispatch.dylib                   0x00007fffab0b40b8 _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x00007fffab0c1b4b _dispatch_main_queue_callback_4CF + 925
	9   CoreFoundation                      0x00007fff95b2c669 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	10  CoreFoundation                      0x00007fff95aed65d __CFRunLoopRun + 2221
	11  CoreFoundation                      0x00007fff95aecb54 CFRunLoopRunSpecific + 420
	12  HIToolbox                           0x00007fff95077acc RunCurrentEventLoopInMode + 240
	13  HIToolbox                           0x00007fff95077901 ReceiveNextEventCommon + 432
	14  HIToolbox                           0x00007fff95077736 _BlockUntilNextEventMatchingListInModeWithFilter + 71
	15  AppKit                              0x00007fff9361dae4 _DPSNextEvent + 1120
	16  AppKit                              0x00007fff93d9821f -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 2789
	17  AppKit                              0x00007fff93612465 -[NSApplication run] + 926
	18  mpv                                 0x0000000108d07da6 cocoa_main + 854
	19  libdyld.dylib                       0x00007fffab0ea255 start + 1
```

**Comment by enoposix** [comment]
Code looks fairly sane and it WorksForMe™. LGTM.

**Pull request merged**
