### PR TITLE
Add 128x128 icon support for X11.

### PR DESCRIPTION
**Pull request by xuzhao9**
I agree that my changes can be relicensed to LGPL 2.1 or later.

### CODE REVIEW

**Comment by rossy** [comment]
Is that image sourced from the .svg? The play symbol is a different shape to the bitmap icons and it's missing grain and some shadows and highlights. It's probably better to use the original here:
https://raw.githubusercontent.com/mpv-player/random-stuff/master/icon/png_exports/icon-osx.iconset/icon_128x128.png

Note: When using those image files, remember to strip the colour profile and convert to sRGB. I think the GIMP can do this. Also, if you haven't already done this, consider compressing the images with something like zopflipng to reduce the impact on repo size.

**Comment by xuzhao9** [comment]
@rossy Thanks for your reviews. I have applied the fixes:
- use the original 128x128 png
- remove color profile and convert to sRGB
- compress the png file using zopflippng

**Comment by rossy** [comment]
Hmm, something about that new image looks wrong. It looks too pink/saturated compared to the others. Maybe "remove" was the wrong word. I meant you should apply the colour profile and convert the image to sRGB (in the GIMP this is done by clicking "convert" when importing the file.)

**Comment by xuzhao9** [comment]
Right. I have converted the image in GIMP during import and optimized with zopflippng.

**Comment by rossy** [comment]
Nice, thanks. It looks good to me. Please squash the commits and change the commit message to match the project standards (it should probably start with the "x11:" prefix.)

**Comment by xuzhao9** [comment]
No problem. I have done that.

**Comment by xuzhao9** [comment]
@rossy Sorry to disturb, just wondering when will the PR be merged?

**Comment by wm4** [comment]
I don't like it at all to add new binary files to the git repo, but I guess I give up my resistance.

Though, one thing I'm wondering about, is whether we could create the x11 image binary at build time, without requiring imagemagick as build dependency.

**Comment by wm4** [comment]
Would a build dependency on `pngtopnm` be reasonable?

**Comment by wm4** [comment]
OK, redid how x11 icons are loaded in 9127939.

Feel free to add a 128x128 icon that is also loaded this way.

**Comment by xuzhao9** [comment]
@wm4 Thanks a lot! I have created a new PR and added 128x128 icon loaded in the new way. I have already run png optimizer on the png file.

**Pull request closed without merging**
