### PR TITLE
af_rubberband: add new engine option for rubberband 3.0.0

### LINKED ISSUE #10417: Rubberband - Add option for new engine in Rubberband 3.0
Rubberband 3.0 added a new higher quality engine called R3. This needs a new option to activate. I would really appreciate it if someone could add this. Thank you.

Rubberband Option Doc: https://breakfastquay.com/rubberband/code-doc/classRubberBand_1_1RubberBandStretcher.html#a5ccb68a043bb4f51efabc9997d9e5cd0
Related mpv source file: https://github.com/mpv-player/mpv/blob/master/audio/filter/af_rubberband.c

### PR DESCRIPTION
**Pull request by christoph-heinrich**
Rubber Band Library version 3.0.0 has been released with a new processing engine and accompanying option `OptionEngineFiner`. With `OptionEngineFaster` the old engine is used.

So far the minimum version for rubberband was 1.8.0.

I don't know how CI has to be changed for this (or if it has to be changed at all).

Closes #10417

### CODE REVIEW

**Comment by Dudemanguy** [comment]
Instead of bumping the library version, you could do a version check in the build systems and enable the new engine option if the version is new enough. Like how JPEGXL detection works.

**Comment by christoph-heinrich** [comment]
It's now in line with JPEGXL.

**Comment by christoph-heinrich** [comment]
Now that arch updated to rubberband 3 I finally tested it, and not only does it work without a problem, but the new engine sounds substantially better then the old one. Makes me wonder if we should choose the new one by default.

**Comment by CoelacanthusHex** [comment]
Upstream said the new engine will cause higher cpu usage, they choose to continue using the old engine by default.  I think we just follow the upstream selection.
But we should document that there is a better but more expensive option.

**Comment by christoph-heinrich** [comment]
The documentation does say to run `--af=rubberband=help` to get all the options and since the old one (default) is called `faster`, I think it's self explanatory that the other one is slower but better.

**Review by Dudemanguy — APPROVED** [review]
I haven't gotten around to testing this yet, but LGTM. I'll try to give it a whirl tomorrow.

**Comment by llyyr** [comment]
I think it makes more sense to default to the newer engine. According to the docs, scaletempo2 already achieves higher audio quality than rubberband with the faster engine. Considering mpv already defaults to scaletempo2, there is little reason to use `af=rubberband` if not to use the better engine.

**Comment by Dudemanguy** [comment]
Sorry for the delay, I finally got around to testing this.

>Now that Arch updated to rubberband 3 I finally tested it, and not only does it work without a problem, but the new engine sounds substantially better then the old one. Makes me wonder if we should choose the new one by default.

I agree with @llyyr's reasoning. The finer engine has dramatically better quality. If someone opts into rubberband, it should default to finer. Do you mind changing that real quick? Also, I think this is worth noting in `interface-changes.rst`. Aside from that, this is good.

**Comment by christoph-heinrich** [comment]
The new engine is now the default and I noted it in `interface-changes.rst`.

**Pull request merged**
