### PR TITLE
dylib-unhell: fix build with Xcode 13.3

### PR DESCRIPTION
**Pull request by kiracus**
please check the code change

### CODE REVIEW

**Comment by kiracus** [comment]
Xcode 13.3 beta 2 is out, and the issue is still there. We can assume that the path change will be in the final release.

any thought ?  cc @Akemi

**Comment by kiracus** [comment]
Xcode 13.3 beta 3 is out, and the issue is still there. @Akemi , would you mind taking a look when you have time? thanks

**Comment by Akemi** [comment]
i don't have time right now, sry. since it's still beta it's very unlikely that i will look at it before the final version is out.

**Comment by mxsrm** [comment]
@Akemi For me right now dylib-unhell is broken with the stable Xcode 13.2.1 on M1 macs and has been for some time. Many of the required dylibs are missing.

This patch, however, does not fix that problem.

**Pull request closed without merging**
