### PR TITLE
vdpau and vaapi aren't linux only

### PR DESCRIPTION
**Pull request by coypoop**
so don't mention it being OS-specific

I agree that my changes can be relicensed to LGPL 2.1 or later.

### CODE REVIEW

**Comment by coypoop** [comment]
I've tested vaapi and vdpau on NetBSD 7.99.61 and nouveau, and they worked :-)

**Comment by Hrxn** [comment]
Splitting hairs...

**Comment by wm4** [comment]
That's a bit too imprecise.

**Comment by wm4** [comment]
Rejecting as contributor is not making requested changes.

**Pull request closed without merging**
