### PR TITLE
input.conf: remove redundant comments

### PR DESCRIPTION
**Pull request by guidocella**

### CODE REVIEW

**Comment by avih** [comment]
Thanks, I'll leave it open for a while to allow people to comment before we merge it.

**Comment by avih** [comment]
Also, keep in mind that these reductions come after a relatively big additions of comments, resulting from recently merging #9026 as 0b56e1c00a57fdb767674462c299a5c973a9e373 .

So the wait will allow people to experience the current relatively verbose set of comments at the stats page 4 (shift+i, then 4).

**Comment by avih** [comment]
No comments on this one?

I'll merge it soon, so if you have an opinion, please let it be heard. Thanks.

**Comment by jeeb** [comment]
Content wise while I kind of feel bad for removing stuff that someone wrote, I do agree that the actual command portion should be self-explanatory (adding/removing to a self-defining property, quit etc).

**Pull request merged**
