### PR TITLE
player: change cover-art-auto behavior

### PR DESCRIPTION
**Pull request by guidocella**
This makes cover-art-auto behave more like sub-auto and audio-file-auto:

- load cover art with a language, e.g. if playing foo.mp3, foo.en.jpg
will be loaded with lang=en
- load cover art containing the media filename with fuzzy and all, e.g.
'foo (large).jpg'
- make all/2 load all images in the directory, and make fuzzy/1 the
default

These are all uncommon use cases, but synchronizing the behavior of the
external file options simplifies the code.

### CODE REVIEW

**Comment by Dudemanguy** [comment]
I'm not sure I agree with making `exact` the default. I think `fuzzy` probably is what most people would want (to get `cover.jpg`) and so on.

**Comment by guidocella** [comment]
The default is indeed fuzzy. exact is 0 and fuzzy is 1.

**Comment by Dudemanguy** [comment]
Oh oops, I can't read. Anyways, LGTM.

**Comment by dardoor** [comment]
FWIW, I don't like fuzzy being the default. It can be annoying if you have audio files with short names in a misc/general folder, like on the desktop. For instance, playing a.wav will load any image that contains an a (like saturday.jpg).

IMO a better default would be just whitelist (cover.*, folder.*) or whitelist + exact.

**Comment by guidocella** [comment]
We could move the whitelist check to exact and make exact the default.

**Comment by dardoor** [comment]
I think such "bundling" of whitelist with another option is not very intuitive and could leave some users frustrated. Rather, the whitelist should have its own separate switch, like: _--cover-art-auto-whitelist=yes/no_.
Or maybe a possibility to combine options like _--cover-art-auto=exact+whitelist_. Is something like this possible? If not, what about using _--cover-art-auto=exact_ and _--cover-art-auto=whitelist_ at the same time?
I don't know if stuff like this works in mpv or not.
In any case and regardless of defaults, I think it would be nice to have fine grained control and not be forced to use one with the other.

**Pull request merged**
