### PR TITLE
libplacebo

### PR DESCRIPTION
**Pull request by haasn**
Rip out the vulkan implementation and replace it by libplacebo

Solves many issues (and introduces about half as many)

### CODE REVIEW

**Comment by jeeb** [comment]
Looks like with static libplacebo mpv and placebo fight over some symbols (multiple definitions of the same symbols)
```
/home/jeeb/ownapps/mingw64_prefix/lib/libplacebo.a(ta.c.obj): In function `ta_set_parent':
/home/jeeb/projects/libplacebo/mingw_build/../subprojects/xtalloc/ta.c:117: multiple definition of `ta_set_parent'
ta/ta.c.19.o:/home/jeeb/projects/mpv/build/mingw64/../../ta/ta.c:116: first defined here
/home/jeeb/ownapps/mingw64_prefix/lib/libplacebo.a(ta.c.obj): In function `ta_alloc_size':
/home/jeeb/projects/libplacebo/mingw_build/../subprojects/xtalloc/ta.c:147: multiple definition of `ta_alloc_size'
ta/ta.c.19.o:/home/jeeb/projects/mpv/build/mingw64/../../ta/ta.c:146: first defined here
/home/jeeb/ownapps/mingw64_prefix/lib/libplacebo.a(ta.c.obj): In function `ta_zalloc_size':
/home/jeeb/projects/libplacebo/mingw_build/../subprojects/xtalloc/ta.c:167: multiple definition of `ta_zalloc_size'
ta/ta.c.19.o:/home/jeeb/projects/mpv/build/mingw64/../../ta/ta.c:166: first defined here
/home/jeeb/ownapps/mingw64_prefix/lib/libplacebo.a(ta.c.obj): In function `ta_realloc_size':
/home/jeeb/projects/libplacebo/mingw_build/../subprojects/xtalloc/ta.c:196: multiple definition of `ta_realloc_size'
ta/ta.c.19.o:/home/jeeb/projects/mpv/build/mingw64/../../ta/ta.c:195: first defined here
/home/jeeb/ownapps/mingw64_prefix/lib/libplacebo.a(ta.c.obj): In function `ta_get_size':
/home/jeeb/projects/libplacebo/mingw_build/../subprojects/xtalloc/ta.c:236: multiple definition of `ta_get_size'
ta/ta.c.19.o:/home/jeeb/projects/mpv/build/mingw64/../../ta/ta.c:235: first defined here
/home/jeeb/ownapps/mingw64_prefix/lib/libplacebo.a(ta.c.obj): In function `ta_free_children':
/home/jeeb/projects/libplacebo/mingw_build/../subprojects/xtalloc/ta.c:245: multiple definition of `ta_free_children'
ta/ta.c.19.o:/home/jeeb/projects/mpv/build/mingw64/../../ta/ta.c:244: first defined here
/home/jeeb/ownapps/mingw64_prefix/lib/libplacebo.a(ta.c.obj): In function `ta_free':
/home/jeeb/projects/libplacebo/mingw_build/../subprojects/xtalloc/ta.c:260: multiple definition of `ta_free'
ta/ta.c.19.o:/home/jeeb/projects/mpv/build/mingw64/../../ta/ta.c:256: first defined here
/home/jeeb/ownapps/mingw64_prefix/lib/libplacebo.a(ta.c.obj): In function `ta_set_destructor':
/home/jeeb/projects/libplacebo/mingw_build/../subprojects/xtalloc/ta.c:290: multiple definition of `ta_set_destructor'
ta/ta.c.19.o:/home/jeeb/projects/mpv/build/mingw64/../../ta/ta.c:286: first defined here
/home/jeeb/ownapps/mingw64_prefix/lib/libplacebo.a(ta.c.obj): In function `ta_find_parent':
/home/jeeb/projects/libplacebo/mingw_build/../subprojects/xtalloc/ta.c:303: multiple definition of `ta_find_parent'
ta/ta.c.19.o:/home/jeeb/projects/mpv/build/mingw64/../../ta/ta.c:299: first defined here
/home/jeeb/ownapps/mingw64_prefix/lib/libplacebo.a(ta.c.obj): In function `ta_enable_leak_report':
/home/jeeb/projects/libplacebo/mingw_build/../subprojects/xtalloc/ta.c:411: multiple definition of `ta_enable_leak_report'
ta/ta.c.19.o:/home/jeeb/projects/mpv/build/mingw64/../../ta/ta.c:403: first defined here
/home/jeeb/ownapps/mingw64_prefix/lib/libplacebo.a(ta.c.obj): In function `ta_dbg_set_loc':
/home/jeeb/projects/libplacebo/mingw_build/../subprojects/xtalloc/ta.c:428: multiple definition of `ta_dbg_set_loc'
ta/ta.c.19.o:/home/jeeb/projects/mpv/build/mingw64/../../ta/ta.c:421: first defined here
/home/jeeb/ownapps/mingw64_prefix/lib/libplacebo.a(ta.c.obj): In function `ta_dbg_mark_as_string':
/home/jeeb/projects/libplacebo/mingw_build/../subprojects/xtalloc/ta.c:438: multiple definition of `ta_dbg_mark_as_string'
ta/ta.c.19.o:/home/jeeb/projects/mpv/build/mingw64/../../ta/ta.c:431: first defined here
/home/jeeb/ownapps/mingw64_prefix/lib/libplacebo.a(xtalloc.c.obj): In function `ta_talloc_strdup_append':
/home/jeeb/projects/libplacebo/mingw_build/../subprojects/xtalloc/xtalloc.c:24: multiple definition of `ta_talloc_strdup_append'
ta/ta_talloc.c.19.o:/home/jeeb/projects/mpv/build/mingw64/../../ta/ta_talloc.c:24: first defined here
/home/jeeb/ownapps/mingw64_prefix/lib/libplacebo.a(xtalloc.c.obj): In function `ta_talloc_strdup_append_buffer':
/home/jeeb/projects/libplacebo/mingw_build/../subprojects/xtalloc/xtalloc.c:30: multiple definition of `ta_talloc_strdup_append_buffer'
ta/ta_talloc.c.19.o:/home/jeeb/projects/mpv/build/mingw64/../../ta/ta_talloc.c:30: first defined here
/home/jeeb/ownapps/mingw64_prefix/lib/libplacebo.a(xtalloc.c.obj): In function `ta_talloc_strndup_append':
/home/jeeb/projects/libplacebo/mingw_build/../subprojects/xtalloc/xtalloc.c:36: multiple definition of `ta_talloc_strndup_append'
ta/ta_talloc.c.19.o:/home/jeeb/projects/mpv/build/mingw64/../../ta/ta_talloc.c:36: first defined here
/home/jeeb/ownapps/mingw64_prefix/lib/libplacebo.a(xtalloc.c.obj): In function `ta_talloc_strndup_append_buffer':
/home/jeeb/projects/libplacebo/mingw_build/../subprojects/xtalloc/xtalloc.c:42: multiple definition of `ta_talloc_strndup_append_buffer'
ta/ta_talloc.c.19.o:/home/jeeb/projects/mpv/build/mingw64/../../ta/ta_talloc.c:42: first defined here
/home/jeeb/ownapps/mingw64_prefix/lib/libplacebo.a(xtalloc.c.obj): In function `ta_talloc_vasprintf_append':
/home/jeeb/projects/libplacebo/mingw_build/../subprojects/xtalloc/xtalloc.c:48: multiple definition of `ta_talloc_vasprintf_append'
ta/ta_talloc.c.19.o:/home/jeeb/projects/mpv/build/mingw64/../../ta/ta_talloc.c:48: first defined here
/home/jeeb/ownapps/mingw64_prefix/lib/libplacebo.a(xtalloc.c.obj): In function `ta_talloc_vasprintf_append_buffer':
/home/jeeb/projects/libplacebo/mingw_build/../subprojects/xtalloc/xtalloc.c:54: multiple definition of `ta_talloc_vasprintf_append_buffer'
ta/ta_talloc.c.19.o:/home/jeeb/projects/mpv/build/mingw64/../../ta/ta_talloc.c:54: first defined here
/home/jeeb/ownapps/mingw64_prefix/lib/libplacebo.a(xtalloc.c.obj): In function `ta_talloc_asprintf_append':
/home/jeeb/projects/libplacebo/mingw_build/../subprojects/xtalloc/xtalloc.c:60: multiple definition of `ta_talloc_asprintf_append'
ta/ta_talloc.c.19.o:/home/jeeb/projects/mpv/build/mingw64/../../ta/ta_talloc.c:60: first defined here
/home/jeeb/ownapps/mingw64_prefix/lib/libplacebo.a(xtalloc.c.obj): In function `ta_talloc_asprintf_append_buffer':
/home/jeeb/projects/libplacebo/mingw_build/../subprojects/xtalloc/xtalloc.c:70: multiple definition of `ta_talloc_asprintf_append_buffer'
ta/ta_talloc.c.19.o:/home/jeeb/projects/mpv/build/mingw64/../../ta/ta_talloc.c:70: first defined here
collect2: error: ld returned 1 exit status
```

**Comment by CounterPillow** [comment]
Last I checked it also crashed with `video-sync=display-resample`, I gave haasn the backtrace of this on IRC and he was looking into it, though that was just as FOSDEM happened so I'm not sure if he fixed it already or was busy. Noting it here so this doesn't accidentally get forgotten should it still be an issue.

**Comment by aufkrawall** [comment]
@CounterPillow Here (radv Polaris) `--video-sync=display-resample` doesn't crash with haasn's mpv repo & libplacebo.

**Comment by jeeb** [comment]
Added a change log and rebased manually.

This has now been merged.

**Pull request closed without merging**
