### PR TITLE
Update bootstrap.py

### PR DESCRIPTION
**Pull request by perfect7gentleman**
waf update to 1.8.16

### CODE REVIEW

**Comment by wm4** [comment]
Any reason for this?

**Comment by perfect7gentleman** [comment]
new version

**Comment by wm4** [comment]
Reason not good enough.

**Comment by perfect7gentleman** [comment]
what reason do you need?

**Comment by wm4** [comment]
Well, does it fix anything? Does it even work? We've had some problems with this in the past. waf is not designed to be upwards or downwards compatible.

**Comment by perfect7gentleman** [comment]
it fixes nothing, but it works
as i see
> All checks have passed
1 successful check

**Pull request closed without merging**
