### PR TITLE
player: load cover art with the media filename

### LINKED ISSUE #8666: Request: Auto load %filename%.jpg as cover art
Foobar2000 support configure to auto load %filename%.jpg and %album%.jpg as cover art.   
e.g. "artist - title.mp3" will auto load "artist - title.jpg" as cover art.   
It is very useful when different album music files are in the same directory.   
Please support this feature.

### PR DESCRIPTION
**Pull request by guidocella**
Closes #8666.

### CODE REVIEW

**Comment by CogentRedTester** [comment]
Just a suggestion, but it might be more universally useful to add property expansion support to the `cover-art-files` option. Currently, the files are loaded without any property expansion, and if the item does not exist then an error message is displayed.

I don't know how easy it is to do, but I do think it would be more useful in a wider range of circumstances than just adding special support for filenames, such as also supporting album names taken from metadata.

**Comment by guidocella** [comment]
Adding support for filenames is trivial because mpv already looks for sub and audio files with the same filename.
I personally never wanted to search for %album%.jpg or other patterns, and it seems that the person who opened the issue is also asking for just %filename%.jpg and %album%.jpg is just an example is just an example of how foobar2000 works, so I think that support for something like `--cover-art-files=${metadata/album}.jpg` can be added later. Even then it's useful if autoloading by filename is already being done separately, or we would have to code a special case for `${path}` stripping its audio extension for `--cover-art-files=${path}` to work. I would also expect cover art with matching filename to take priority over arbitrary patterns like the album.

**Comment by hooke007** [comment]
In some forms, I see more people prefer to use the "cover.jpg" which is located in the same directory of the album's folder as the cover. Because the different songs (belong to the same album) could not share the same name.

**Review by Dudemanguy — APPROVED** [review]
Seems good and works as advertised.

**Pull request merged**
