### PR TITLE
context_drm_egl: Use eglGetPlatformDisplayEXT if available

### PR DESCRIPTION
**Pull request by mihailescu2m**
Check if eglGetPlatformDisplayEXT is available and try to
use it to obtain the display connection. Fall back to eglGetDisplay
if eglGetPlatformDisplayEXT is not available or failing.

I agree that my changes can be relicensed to LGPL 2.1 or later.

### CODE REVIEW

**Comment by xantoz** [comment]
LGTM

**Comment by xantoz** [comment]
Can you add a test using eglQueryString, as described in the linked mail conversation?

**Comment by mihailescu2m** [comment]
I've added eglQueryString and also used EGL_PLATFORM_GBM_KHR when EGL_KHR_platform_gbm extension is present, or EGL_PLATFORM_GBM_MESA when EGL_MESA_platform_gbm extension is present.

**Comment by xantoz** [comment]
Looks good. Although at this point it would be best to split it off into its own helper function for code clarity.

**Comment by xantoz** [comment]
Merged as 0bdcbd75e001f6f344f28378227d5fbff0ed9a06

Thanks for contributing.

**Pull request closed without merging**
