### PR TITLE
Fix typo in ytdl_hook error message

### PR DESCRIPTION
**Pull request by dnnr**

### CODE REVIEW

**Comment by Akemi** [comment]
read our [contribution.md](https://github.com/mpv-player/mpv/blob/master/DOCS/contribute.md) and either resubmit or adjust this PR.

**Comment by dnnr** [comment]
I did read it and then removed the template because it doesn't add any value to my PR. You wanted me to leave it in, because reasons? Okay then.

**Comment by Argon-** [comment]
I'm pretty sure his comment was caused by your commit title/message. The document you were supposed to read contains a clear "format" that is to be followed to consistency reasons.

**Comment by dnnr** [comment]
Better now? I'm all for being nitpicky about rules and commit messages, but if that was really the issue, you might want to consider replacing that little word "should" with a clear "must" in your guidelines about prefixing the message.

**Comment by Akemi** [comment]
> Better now?

nope. the commit message and body is the crucial part.

**Comment by dnnr** [comment]
> > Better now?
> 
> nope. the commit message and body is the crucial part.

You are aware that you can squash-merge PRs and choose the PR title as commit message, right? You could even make it say whatever you like, saving us both a lot of time. But sure, here you go, on a silver platter, an updated commit message in my branch. GitHub doesn't seem to update the PR, I'm guessing because it is closed.

I can't think of any meaningful message body to be added. In case you do, feel free to make the change yourself.

**Comment by CounterPillow** [comment]
It's not hard to `git commit --amend` my man.

**Comment by wm4** [comment]
The repository's settings only allow rebase merges through github's web-interface. We don't normally squash-merge, because it's basically a git usage anti-pattern. Yes, we could merge it manually and fix all the tiny things that might be wrong, but that's additional effort, and it's much easier for the PR author to do this (plus it's the author's job/responsibility/usage of time).

And also, if the PR is relatively trivial, and if the effort we need to put into making the PR merge-ready is above what we'd need to spend to fix it ourselves, it's not surprising that we wouldn't bother.

This may be different from some other projects, where people just press the merge button without regards for consistency and even quality.

**Comment by Akemi** [comment]
sure i can do a lot of things. i prefer to make you do the work that we expect you to do.

i hope you are aware that we can also decide not to interact with you at all because of your attitude and i personally will do so now.

**Pull request closed without merging**
