### PR TITLE
stream: accept dav:// and davs:// urls

### PR DESCRIPTION
**Pull request by Y0J1G3N**
#11080 has been submitted to mpv for handling webdav:// and webdavs:// links. However, the GNOME Nautilus file manager that I'm using does not support browsing of webdav:// and webdavs:// links.

The GNOME Nautilus file manager supports browsing of dav:// and davs:// links only. Additionally, dav:// and davs:// are also types of webdav links. Therefore, adding an "or" operation to include support for dav:// and davs:// links.

### CODE REVIEW

**Review by Y0J1G3N — COMMENTED** [review]
Modified to sort alphabetically

**Comment by Traneptora** [comment]
Please squash the two commits together, you can do that easily with `rebase -i master` and changing the second one to "fixup"

**Comment by Y0J1G3N** [comment]
Sorry, this is my first time submitting pull requests, and it seems like I have already performed a "rebase -i" on the master branch. I have updated the latest source code in my forked repository, compiled it on my own machine, and tested the webdav-related features successfully. Is there anything else I need to do? Could you give me some guidance?

**Comment by Traneptora** [comment]
Generally speaking you want to make these changes on a local branch that isn't master. For now, the easiest thing for you to do would be to reset the master branch to be inline with upstream, run `git checkout -b patch1` and then re-commit your changes.

**Comment by Y0J1G3N** [comment]
I already reset the master branch to be inline with upstream, and I created a new branch called patch1 in my fork repository. Then, I re-committed my changes. What should I do next? Should I open another pull request?

**Comment by Traneptora** [comment]
Yes

**Pull request closed without merging**
