### PR TITLE
vo_gpu: raise deband-threshold to 64

### PR DESCRIPTION
**Pull request by llyyr**
Since we no longer activate deband in any default profiles, doing this shouldn't destroy any files.

We can discuss whether this should go even further than 64, but 64 seems fine to me even on files with heavy banding

### CODE REVIEW

**Comment by wiwaz** [comment]
Do you have samples where threshold 64 provides a noticeable benefit?

**Comment by llyyr** [comment]
I did some testing on simulcast anime video sources around September last year when we initially raised it 48 from 32. https://github.com/mpv-player/mpv/pull/12441#issuecomment-1728234133

I can provide comparisons in a couple of days if needed, but this should be easy to test.

**Comment by hooke007** [comment]
It's recover not raise actually. Because it was 64 previously.
https://github.com/mpv-player/mpv/blob/b5d3e43198b9d57af5620b63537885aaa41fa8cd/DOCS/man/options.rst#L5687

**Comment by wiwaz** [comment]
> I did some testing on simulcast anime video sources around September last year when we initially raised it 48 from 32. #12441
> 
> I can provide comparisons in a couple of days if needed, but this should be easy to test.

Likely needs to be re-evaluated now that the debanding behavior has changed. I should be able to prepare some samples & comparisons myself in the following days..

**Comment by kasper93** [comment]
> We can discuss whether this should go even further than 64
> September last year when we initially raised it 48

So in the recent history it was lowered/raised multiple times. Could we do proper research this time and agree on default value? I warned you there will be bikesheeding, but if we raise it to 64 again on a whim, what if next week we get PR to reduce it to 53.78, because someone finds out 64 is too much?

**Comment by Raza-0007** [comment]
But why change the defaults? Current values are perfect, and provide an excellent balance between removing banding and other artifacts, without losing significant image details. 

~Raza

**Comment by llyyr** [comment]
> Current values are perfect, and provide an excellent balance between removing banding and other artifacts, without losing significant image details.

If this was true then deband would've never been removed from the `high-quality` profile. The issue with having deband turned on unconditionally in a "high quality" profile was that it could never be made aggressive enough where it actually gets rid of banding on a bad video without losing details, since most videos don't actually have that much banding nowadays.

The idea was always for users to press `b` to turn on deband where needed, and if deband is needed then it should probably be more aggressive than what it is right now since it basically does nothing on a video that actually has banding.

But this PR has received more opposition than I expected, and it's much faster to just put a line in my config so I'm not interested in trying to push this.

**Comment by Raza-0007** [comment]
> But this PR has received more opposition than I expected, and it's much faster to just put a line in my config so I'm not interested in trying to push this.

I am sorry if I offended. I was not trying to appose you, I just wanted to know if there were a lot of people asking for the change. I agree with you that banding is very rare nowadays. I always have debanding turned on in my config as it gives me a slight improvement in picture quality then with it off. This is why I was concerned that raising the values might make it too aggressive. 

~Raza

**Comment by kasper93** [comment]
Maybe `b` keybind (or `B` to add separate one) should cycle through some threshold values? something like off, low(32), medium(48), high(96), insane(128). Of course values are only examples, but maybe this way it would be easier to dial the correct value during playback without going to edit config.

**Pull request closed without merging**
