### PR TITLE
osc: remove enable/disable controls and add unified visibility never/auto/always

### PR DESCRIPTION
**Pull request by avih**
- Fix the enable/disable controls
- add always-on mode
- add global mode cycle
- remove user control for enable/disable/alwayson and combine them into a single visibility mode which is supported as user-opts and as script message, as well as cycling between them.

### CODE REVIEW

**Comment by avih** [comment]
I think it would be fine to squash the last two commits (and fix the docs sample), but the first two commits should probably stay on their own for clarity.

I'll do those together with addressing any other comments you might have, if there are any.

**Comment by ChrisK2** [comment]
What's reasoning for moving the DEL keybinding into etc/input.conf?

**Comment by avih** [comment]
It's a good central place for all default KB shortcuts.

**Comment by avih** [comment]
Merged by @ChrisK2  as 3ab6af4 and ad2d10a.

**Pull request closed without merging**
