### PR TITLE
Use sent messages to wake up the Win32 thread

### PR DESCRIPTION
**Pull request by rossy**
This prevents a glitch if a VOCTRL is dispatched while the user is clicking the titlebar, but not moving the mouse.

I just want to make sure the dispatch queue's wakeup function is only called when dispatching a message between threads. If it's called on the same thread, this will deadlock (but I don't think it does this?)

### CODE REVIEW

**Comment by wm4** [comment]
>If the window was created by the calling thread, SendNotifyMessage calls the window procedure for the window and does not return until the window procedure has processed the message. 

I'm not sure if this appropriate. It could cause a deadlock.

**Comment by rossy** [comment]
Yeah, I figured this could be the case. In practice, I think messages are only sent from the VO thread to the Win32 thread, but it's still probably a bad idea to write a wakeup_fn that breaks dispatch queue semantics.

Though, maybe it's okay. I noticed wakeup_fn() is called outside the queue lock here:
https://github.com/mpv-player/mpv/blob/master/misc/dispatch.c#L131

This should mean that any same-thread messages will just be processed synchronously before mp_dispatch_enqueue() returns and they won't cause a deadlock.

**Comment by wm4** [comment]
Maybe it works out, not sure. It's possible that wakeup_fn doesn't even get called on the window thread in the current code. Would it be possible to check the thread and skip the wakeup or assert or so?

**Comment by rossy** [comment]
It should be fairly straightforward to fall back to PostMessage in this case, in which case the dispatch queue will be processed when the thread returns to the event loop. Amending now.

**Comment by wm4** [comment]
Yeah, I think that looks good now. (Didn't get any notification of the code update.)

**Comment by rossy** [comment]
Ah, sorry. It's weird how GitHub is showing the new commit before my last comment when I definitely pushed it afterwards.

**Pull request merged**
