### PR TITLE
vo_gpu_next: fix win32 io wrap

### PR DESCRIPTION
**Pull request by na-na-hi**
Fixes 84015959cc5d36d8973b2f07ece066902bbbdbe7

### CODE REVIEW

**Review by sfan5 — APPROVED** [review]

**Comment by kasper93** [comment]
@na-na-hi: Do you think we could resolve this std function override fiasco? Or at least have better compile time check for it not to break?

**Comment by kasper93** [comment]
Do anyone wants to pick up this task? I think it would be good to resolve it. Some time ago I had used `puts` which is not wrapped and spend too much time to figure out why is it failing sometimes.

I can look into it, maybe during weekend or the next one, but I ask to not duplicate work, if anyone want to do it instead.

**Comment by sfan5** [comment]
I think the redefinition approach has its merits and that we should keep it here.

It ensures you write clean C code that directly uses the standard APIs¹ and functions.
It's less burden for writing and working with C code (e.g. with an IDE that has go-to definition). For example if you look at other big C projects you have wrappers for everything `calloc`, `snprintf`, `strcasecmp`, `fwrite` or *worse* custom abstractions with different semantics, which raises the bar for new contributors to get into the codebase.
In the end you have shit like `mp_strlen` because some obscure platform fucked up the implementation² 7 years ago but the wrapper still lives on.
With `stdio.h` we also don't have the weird header inclusion issues like with pthread³ since we're simply extending it.

¹: standard can be something like C11 but also POSIX, which mpv is mostly written to expect (e.g. we also wrap `dlsym` for win32).
²: This isn't as unlikely as you might think, for example Android fucked up [strnlen](https://github.com/mpv-player/mpv/commit/ff0112e08df32e88549d142371d49a2a8ac8a798#diff-d630035c4220d863364388854d5f5f617af514657bdcb9b9ed7114e33fece666).
³: https://github.com/mpv-player/mpv/commit/3fb4eb2ba47fea78e69937971974f42cba82d1df

**Comment by mitzsch** [comment]
> Honestly this looks like incorrect debugging to me.

Jup, was incorrect debugging on my side. Sorry! The wasapi commit had nothing to do with the issue...

**Pull request merged**
