### PR TITLE
Remove OpenAL

### PR DESCRIPTION
**Pull request by Forcer78**
> @wm4: "[My standpoint is that you shouldn't use OpenAL. If you insist on using it, make a PR to fix it.](https://github.com/mpv-player/mpv/issues/6601#issuecomment-545866029)"

This is a patch to fix mpv's OpenAL support.

Since OpenAL use is discouraged above and its code is unmaintained, the only realistic fix is to delete it.

Untested.

### CODE REVIEW

**Comment by CounterPillow** [comment]
5 commits for a troll PR, you can do better.

**Comment by wm4** [comment]
I mean I wouldn't mind.

**Comment by CounterPillow** [comment]
They should probably still first read the contribution guidelines to make something mergeable, and also test it, but I feel like the entire point of the PR is to be passive aggressive about a lack of OpenAL development, which the PR submitter could've alleviated by being a developer.

**Comment by Forcer78** [comment]
I thought I _was_ following the guidelines by splitting my changes into multiple commits.

**Comment by Forcer78** [comment]
A lack of OpenAL development is different from recent breakage that was tracked down, detailed in an issue, and then summarily dismissed as wontfix by a member whose changes I've already had to [revert](https://github.com/mpv-player/mpv/issues/3763) [before](https://github.com/mpv-player/mpv/issues/5759).

**Comment by wm4** [comment]
Not sure what #5759 has to do with this.

In general, if something is unmaintained, and you really care about it, you should probably become maintainer. Otherwise it will bitrot more, until inadvertently removed. Such is the nature of open source.

**Pull request closed without merging**
