### PR TITLE
Colorspace Stuff

### PR DESCRIPTION
**Pull request by lachs0r**
A few missing bits and fixes.

### CODE REVIEW

**Comment by wm4** [comment]
All ok, except ``csputils: add some missing colorspaces``. What's the use of most of the additional colorspaces? Only MP_CSP_TRC_GAMMA28 can be triggered by any input files (because it's mapped from AVCOL_TRC_GAMMA28), the rest can only be selected manually by using options.

**Comment by haasn** [comment]
The reason they're useful in particular is for vo_opengl's target-trc and target-prim options. I personally use mpv as my go-to “render something in a certain color space” thing, mostly because it's the only viewer where I trust it to actually get things right. Eg. if I'm rendering out something as an sRGB JPEG I would use :target-prim=bt709:target-trc=srgb.

Things like ProPhotoRGB and AdobeRGB in particular see some use, and Apple RGB is basically the colorspace used by older apple monitors, so we might as well support it alongside sRGB.

For this use case, whether or not it gets delivered by libavcodec or not is more or less irrelevant - the reason why it was added to vf_format's primaries option as well is just “consistency” at this point. Already changed all of the names to be uniform, might as well make “primaries=<colorspace>” a consistent type of parameter throughout the API.

**Comment by haasn** [comment]
Ping? Do you still have issues with 7061c16?

**Comment by wm4** [comment]
>Ping? Do you still have issues with 7061c16?

No.

**Pull request closed without merging**
