### PR TITLE
add an input command prefix for displaying volume in decibels

### PR DESCRIPTION
**Pull request by myQwil**
Use the input prefix `dB` before a volume change.
Aims to address feature request #3545.

You'll notice that the display method for `volume` is slightly different from the method for `ao-volume`. This is because soft volume gets cubed, so we need to account for that when translating it over to decibels.

To change volume in whole decibel increments, you can add something like this to your `input.conf` file:
```ini
# Soft Volume
9 dB multiply    volume 0.9261187281287935 # -2 dB  10^(-2/60)
0 dB multiply    volume 1.0797751623277097 # +2 dB  10^(+2/60)

# AO Volume
/ dB multiply ao-volume 0.7943282347242815 # -2 dB  10^(-2/20)
* dB multiply ao-volume 1.2589254117941672 # +2 dB  10^(+2/20)
```
Also, to make the max volume more compatible with decibels, something like this can be added to `mpv.conf`:

```ini
volume-max=125.892541179416721 # 10^(126/60) or 100% + 6 dB
```

Read-only input properties `volume-db` and `ao-volume-db` have been added so that volume percentage and decibels can be printed in the same message, like so:
```ini
a show-text "Volume: ${volume} (${volume-db})"
```

### CODE REVIEW

**Comment by t-8ch** [comment]
Is it expected that all ao-volumes share the same pattern?

Currently ao_pulse uses cubic volume and ao_pipewire uses linear volume.
Match their respective sound servers.

**Comment by Dudemanguy** [comment]
Instead of being an option, this should be an additional optional argument to the `volume` property since all it does is change how the value is printed. Also, @t-8ch's point is valid (I personally do not know the answer).

**Comment by myQwil** [comment]
If it's already been cubed by the time we get it, then it doesn't make a difference.

The only reason we have to worry about it with soft-vol is because the value stored in `opts->softvol_volume` is in its un-cubed state, but we know that it gets cubed somewhere else in the code.

**Comment by haasn** [comment]
How do you handle the case of `volume=0` (corresponds to -Infinity dB)?

Also, the change to add ` (Muted)` should be in a separate commit.

**Comment by myQwil** [comment]
> Also, the change to add ` (Muted)` should be in a separate commit.

I didn't exactly add that. If you mute the volume on the master branch, you will get that message. It's just that messages for volume used to be handled with a free-form message like this:

`.msg = "Volume: ${?volume:${volume}% ${?mute==yes:(Muted)}}${!volume:${volume}}"`

> How do you handle the case of `volume=0` (corresponds to -Infinity dB)?

Currently, if volume is set to 0, it will print `-inf dB`. However, that isn't based on any condition that I wrote, and log(0) may cause a pole error depending on its implementation, so I'll add a condition to prevent that.

**Comment by Dudemanguy** [comment]
I still think this should be a sub property or maybe another property altogether (whatever implementation is nicer). It's not an option that actually affects the player.

**Comment by myQwil** [comment]
I'll see what I can do about making it a sub property of volume

**Comment by Dudemanguy** [comment]
Not really, although your suggestion isn't necessarily bad either. Some potential things I was thinking of would be:
1. Just add a read-only property that displays volume in decibels. Easy to do. Maybe not as useful.
2. Add an input command prefix that displays volume in decibels. That way one could modify their input.conf so changing the volume would display the value in decibels.
3. Go all out and actually add a brand new option that writes volume as decibels(???). Probably hard and not worth it; don't do this.

**Comment by myQwil** [comment]
I came to the realization that this can also be achieved with a lua script:
`scripts/decibel.lua`:
```lua
function on_volume_change(name, value)
   if value <= 0 then
      mp.commandv("show-text", "Volume: -∞")
   else
      value = 26.0576689141951097 * math.log(value / 100)
      value = math.floor(value * 100 + 0.5) / 100
      mp.commandv("show-text", string.format("Volume: %+g dB", value))
   end
end
mp.observe_property("volume", "number", on_volume_change)
```
Then when adding input commands, use the prefix `osd-bar` and it will prevent mpv from trying to print its own message.

**Comment by myQwil** [comment]
I think we're good to close this PR. The lua solution is actually better, in my opinion, because we can directly enter how many decibels we want, as opposed to having to first calculate what it would be in factor form.

And if it does turn out that the formula needs to be different for different audio servers, then it's just a simple matter of going into the script and changing a number.

**Comment by terrancewong** [comment]
Hi [myQwil](https://github.com/myQwil)

The dB calculation is a little off. In PCM audio, ratio is applied to voltage, so the dB should be calculated  `log10(V1/V2) * 20`. but why is 50%/200% "volume"  -18dB and +18dB?

**Comment by terrancewong** [comment]
I got this. This "%" is actually been cubed, eg: "50%" is actually 12.5%, "90%" is actually 72.9%. cubic function is somehow kinda close to exp function, thus can simulate natural volume control.

following list is volume from "5%" to "100%", [1] is real ratio, [2] is "50%" as -18.065dB
````
[[5, 0.00012500000000000003, 0.019223169706051927],
 [10, 0.0010000000000000002, 0.02366736998334486],
 [15, 0.0033749999999999995, 0.029139023922375627],
 [20, 0.008000000000000002, 0.03587566830392615],
 [25, 0.015625, 0.04416975598365893],
 [30, 0.026999999999999996, 0.05438135192710727],
 [35, 0.04287499999999999, 0.06695376443813694],
 [40, 0.06400000000000002, 0.08243279016759804],
 [45, 0.09112500000000001, 0.10149040837119395],
 [50, 0.125, 0.12495395303749496],
 [55, 0.16637500000000005, 0.15384202931365948],
 [60, 0.21599999999999997, 0.18940873344153417],
 [65, 0.274625, 0.23319809589082682],
 [70, 0.3429999999999999, 0.2871111111879825],
 [75, 0.421875, 0.3534882643561098],
 [80, 0.5120000000000001, 0.4352111366239772],
 [85, 0.6141249999999999, 0.5358275013360013],
 [90, 0.7290000000000001, 0.6597053407575061],
 [95, 0.8573749999999999, 0.812222469990523],
 [100, 1.0, 1.0]]
```

**Pull request closed without merging**
