### PR TITLE
Add DVB-S2 and (partial) vdr-style channel-lists support

### PR DESCRIPTION
**Pull request by olifre**
With this changeset, mpv: 
* Can read VDR-style channel-lists (and, at least for DVB-S, extract all information as before). 
* Uses S2API (DVB-API v. 5, since 2.6.28 the older API is deprecated) for tuning, for DVB-S tuners. 

The new API allows to tune to DVB-S2 channels, and as the classic mplayer-styles "channels.conf" do not contain a "DVB-S2" flag, I added vdr-style channel-list support. With this, mpv can now tune to most FullHD-broadcasts via satellite using a vdr-style channel.conf e.g. created with w_scan. 

I tried to be as non-invasive as possible: 
* S2API is only used if DVB-API >= 5.x, and for DVB-S devices. 
* On channel.conf reading, it is tested with a sscanf-pattern whether the line matches the VDR-style format (see http://www.vdr-wiki.de/wiki/index.php/Channels.conf , sadly german only). If not, classic parsing is done. 

I also fixed a broken ifdef (which meant that ATSC should not have worked since a while) and cleaned up some debug-output. The commits are fine-grained and hopefully contain enough commentary to explain what I changed. 

Disclaimer: The non-DVB-S-code paths should function as before, but I only have DVB-S(2) hardware here, and some DVB-T stick with bad reception floating around. I only tested all changes with DVB-S on old and new channel-config-files, DVB-S and DVB-S2 channels, but not on pre-2.6.28 kernels (there are many DVB-S drivers missing there...). 
The VDR-style channel.confs contain a lot more information usable for non-DVB-S cards (e.g. FEC, ROLLOFF etc.). I do not parse this, since I have no hardware to test whether it works as expected, so VDR-style config files will probably not work with this hardware (but not much is missing). As a fallback to the classic config format is in, no old setup should be broken. 

As this is my first (planned) contribution to mpv, feel free to RTFM me or teach me how to better agree with the coding guidelines (I mostly do C++ in real life).

### CODE REVIEW

**Comment by olifre** [comment]
Just a heads up, in case you want to see it: I have reported the teletext-detection issue(s) in ffmpeg here: https://trac.ffmpeg.org/ticket/4221

**Comment by olifre** [comment]
Another heads-up: I learnt in the linked bug-report that missing PMT causes this mis-detection issue. 
It actually is a wonder that video / audio streams are detected fine without PMT. 

Knowing this, I will add to this PR (in the near future) another commit with some code to extract the PMT-PID from PAT and also demux this. Then teletext-support can be reactivated, and also ffmpeg has to guess a lot less what is going on (i.e. playback will start much faster, now it is still taking a few seconds to collect enough data for the guesswork-magic of ffmpeg). 

I have working example code for PMT-PID-extraction in szap-s2 and will adapt from this + publicly available documentation.

**Comment by wm4** [comment]
That is good to hear. So apparently this stuff was pretty broken. Maybe the old mplayer mpegts demuxer (which was removed from mpv ages ago) didn't have issues with this. What's your take on #239 btw.?

**Comment by olifre** [comment]
With this patch, I now get: 
`   cplayer: [stream] Subs      --sid=1 --slang=deu (dvb_teletext)`
`   cplayer: [stream] Subs      --sid=2 --slang=deu (dvb_subtitle)`
and dvb_subtitle works fine. 
I am not so sure about dvb_teletext. There, I see: 
`    ffmpeg: libzvbi_teletextdec: page filter: *`
during the demuxer-setup (can you tell me how to pass an option to a decoder, i.e. "txt_page=111" ?). 

Later, switching subtitles, I get:
`       sub: Could not find subtitle decoder for format 'dvb_teletext'.`
Apart from that, it seems the PMT also helps ffmpeg with the analysis. I will add a gist to #239.

**Comment by wm4** [comment]
Well, the teletext decoder is strange, so it's not enabled in sd_lavc.c. The problem is probably that teletext has lots of state (like past pages), which doesn't match with the lavc subtitle API at all, so the result is nonsense.

**Comment by olifre** [comment]
> Well, the teletext decoder is strange, so it's not enabled in sd_lavc.c. The problem is probably that teletext has lots of state (like past pages), which doesn't match with the lavc subtitle API at all, so the result is nonsense.

Indeed. I just activated it to see what happens, and got to see the full teletext-pages flipping through. I suppose it could work in a limited way if filtering for a real subtitle txt_page, but I am not sure whether it is worth the effort to add an option to mpv for that. 
Anyways, for most DVB-S transmissions around here, they now finally start to use the real dvb_subtitle streams, and these work perfectly well by now.

**Comment by olifre** [comment]
The last two commits add some documentation and also parse SDT (service description) and EIT (program / EPG information). 
SDT allows ffmpeg to learn the channel name and more human readable information. 
EIT is (as far as I know) only parsed by VLC, it can learn about the program guide  from that. Should be extremely helpful for stream-dump recordings with mpv.

**Comment by olifre** [comment]
I just realized I accidentally also enabled `stream->streaming` in one of the commits - do you agree this is a good idea for now?

**Comment by olifre** [comment]
I figured, to allow users of old-style channels.conf to get PMT, SDT etc. into ffmpeg, it would be useful to just allow to pass the full transponder to ffmpeg with no filtering at all. This also allows multi-channel recording or recording of channels which switch PID over time (some do this for regional news). ffmpeg can handle that from what I read in their code, but I do not believe reproducing such functionality in mpv is worth the effort. 

Let me just add to the two last commits: Adding option parameters to mpv is extremely easy. I love the codebase (the DVB part really looks much more "rotten" than the rest of mpv). 
Thanks!

**Comment by wm4** [comment]
>I just realized I accidentally also enabled stream->streaming in one of the commits - do you agree this is a good idea for now?

Yes. Though leaving the commits in this way doesn't make too much sense. Either separate them cleanly, or just squash everything into a single commit. I don't care much which it is; but leaving everything in chaos is unhelpful when traversing the history (e.g. when trying to find out why something was done in the way it's done).

>I figured, to allow users of old-style channels.conf to get PMT, SDT etc. into ffmpeg, it would be useful to just allow to pass the full transponder to ffmpeg with no filtering at all.

Sounds useful. Actually, I thought this is why there is a way to switch .ts "programs" (mp_property_program).

>This also allows multi-channel recording or recording of channels which switch PID over time (some do this for regional news). ffmpeg can handle that from what I read in their code, but I do not believe reproducing such functionality in mpv is worth the effort.

I think this is actually needed for correct playback? But I don't know.

**Comment by olifre** [comment]
> Though leaving the commits in this way doesn't make too much sense. Either separate them cleanly, or just squash everything into a single commit.

I fully agree. It wasn't too clear to me whether it really is fine to restructure the commits when they are already in a PR, but you are right, like this it is useless. I will clean up the situation soon. 
Should I also rewrite the "earlier" commits in this PR to e.g. have at least the first line of the commit-message limited to 80 chars? 

> Actually, I thought this is why there is a way to switch .ts "programs" (mp_property_program).

Actually, I did not know that (yet)... The fun fact is that it works perfectly well when giving the full transponder to ffmpeg or recording a full transponder. Then you can switch via property between the different programs on that transponder, pretty useful. 

> I think this is actually needed for correct playback? But I don't know.

Here in Germany, I know of two channels which use such a trick to do regional news - once in a day, just for the news, they switch their video and audio PIDs to "explode" into a set of multiple channels (with reduced bitrate). The rest of the day, all these channels "link" to the same set of PIDs to conserve bandwidth. 

For these few special channels which switch the PIDs on the fly, it would really be needed for correct playback. But then, we also need to parse the PAT ourselves to find all channel PIDs, i.e., we should not look at most of the channels.conf (if the scan was done when the program was sending regional news, it will have different PIDs in the channels.conf). Note that some older consumer set-top-boxes to receive DVB-S (I know at least one personally) had problems with such changes, too (e.g. it needed a channel switch to re-scan PMT/PAT). 

I believe to get a "clean" playback of these, the best way is to give the full transponder to ffmpeg and let ffmpeg handle that - if we handle it ourselves, we have to do full PAT/PMT parsing, and add demuxer-FDs on the fly to get the new PIDs into the stream (which probably causes quite some discontinuities). Maybe I should add a sentence on that to the manpage, but it really is rare (for users recording such channels, it might be best to add the magic 8192-PID to the channels.conf to always get the full transponder for these). Using the full transponder by default is probably not a good idea, since it will make all stream-dump functionality for recording / cache-file functionality for time-shifting less useful.

**Comment by olifre** [comment]
I hope I fixed up the history (the messages are now hopefully in line with common git style), and I added two more commits, with some info on usage of dump-transponder for channels with PID-switching, and the unneeded initialization dropped.

**Comment by wm4** [comment]
Hm, ok. I think some commits could really be squashed, though. Like strtok->av_strtok->dvb_strtok, or "stream_dvb: Drop unneeded intialization.", which merely removes a single line that was added in a commit in the same pull request.

Anyway, let me know when I should merge.

**Comment by olifre** [comment]
> Hm, ok. I think some commits could really be squashed, though.

You are right. This is also the first time I contribute to a major open source project, so I am happy about any advice. 
I have squashed some commits, renamed the parameter to `--dvbin-full-transponder` and also removed the ifdef-change (maybe I just did something stupid like forgot to compile before, I have no other explanation). 

If travis is also happy now, I would be fine with merging now. If you have more comments, I will gladly accept them and squash more.

**Comment by wm4** [comment]
So, ok if I merge?

**Comment by wm4** [comment]
PS: I'll also add a commit reformatting all the files when doing it.

**Comment by olifre** [comment]
> So, ok if I merge?

Yes - and thanks again for all your advice! The mpv codebase is really nice to work with. 
I will also look into the other issue with ffmpeg, but I am not sure when (my time will be very limited in the next weeks, "holidays" are running out...). 

> PS: I'll also add a commit reformatting all the files when doing it.

Looking forward to it. If I find any issues later (new card should arrive next week), I might come back with smaller changes, but the S2-support is complete enough, I believe.

**Comment by wm4** [comment]
Done.

**Comment by wm4** [comment]
Btw., what's with all those usleep() calls?

**Comment by olifre** [comment]
> Btw., what's with all those usleep() calls?

I believe they are fine - one is in `check_status()` in the polling-loop (which is really needed, some tuners take ages to lock on a channel), all others are after DISEqC-commands (I have no DISEqC device to test). I assume most DISEqC-hardware (which can be switches or even dish-moving motors) takes some time after the command to finish the switching. I don't have such hardware, but I assume there is no clear / standard conforming indication when it is finished, so I assume the values which are used here are mostly guesswork - I have no way to improve them. 

Maybe the full DISEqC stuff and the `usleep` in `tune_it` could be done in a more clever way (i.e. only if the DISEqC command is really needed). I see now it is always executed unconditionally... 

I will have a look sometime later, for most standard-setups (without multi-switches), the DISEqC commands and the sleeping should be completely unnecessary.

**Comment by olifre** [comment]
> I will have a look sometime later, for most standard-setups (without multi-switches), the DISEqC commands and the sleeping should be completely unnecessary.

It seems for my hardware, it works without any `usleep`. Still, I guess the sleeping is there as a compatibility hack and might be required for DISEqC switches, so I would leave it in. 

The DISEqC function in `dvb_tune.c` also takes care e.g. of switching the polarization, so it should also stay in by default - sending the DISEqC commands in addition is harmless if no hardware is there, only a few ms are lost, so I would leave it in by default for better compatibility with people's setups.

**Comment by wm4** [comment]
This was merged; forgot to close it.

**Pull request closed without merging**
