### PR TITLE
zsh-completion: complete av://lavfi:testsrc and av://lavfi:sine

### PR DESCRIPTION
**Pull request by guidocella**
It is annoying to type these over and over.

### CODE REVIEW

**Review by Dudemanguy — APPROVED** [review]
Probably common enough to warrant autocompletion.

**Comment by kasper93** [comment]
> Probably common enough to warrant autocompletion.

I honestly don't think so. For me it looks like specific development shortcut, which no one would ever use in real mpv usage.

**Comment by guidocella** [comment]
It's mainly for developers but it's not like completing them harms user in any way. It even checks if the user set custom url completion before enabling it.

**Comment by kasper93** [comment]
I don't mind having it. Just think it is not that useful, but it's fine.

**Pull request merged**
