### PR TITLE
player: fix segfault

### LINKED ISSUE #8922: mpv crashes if an image file has the same name as the video file
Hello!
I am using mpv version 0.33.0-184-g03b9f8e323 from sourceforge build mpv-x86_64-20210613-git-03b9f8e.
My OS is Windows 8.1 Professional x64.

I have a folder with two files:
abcd.mp4
abcd.jpg

mpv crashes with the standard windows alert "mpv has stopped working" if I try to play abcd.mp4
The issue is reproduced with --no-config too.

mpv works normally after deleting abcd.jpg file or renaming it.
The issue presents only if the image file has the same name as the video file name. The extension can be jpg or png or bmp.

The sourceforge build mpv-x86_64-20210530-git-fd8c673 introduced this problem, the previous build mpv-x86_64-20210523-git-6c1dd02 had no problem.

The log is attached.
[output.txt](https://github.com/mpv-player/mpv/files/6663191/output.txt)

Thanks in advance.

### PR DESCRIPTION
**Pull request by guidocella**
Removes the goto which caused lang to be used in the sub->lang
assignment without being initialized when adding cover art. lang is
normally initialized to a garbage value like {start = 0x0, len =
94415366337024}, and so sub->lang was assigned nullptr whether lang was
initialized on not due to safety checks in bstrdup0's internals
(ta_strndup checks if the pointer is null first), but a segfault happens
only on Windows 8 on certain builds of GCC 10.2 with optimization,
assumedly because lang.start is initialized to a non-null value which
bstrdup0 tries to use.

Also remove the check that the external filename is not the same as the
currently playing one, preventing mpv from loading images again as
external cover art, which isn't necessary because cover art is only
added when playing standalone audio. I had only added that check because
I would otherwise get a segfault only when compiling with GCC 10.2 with
optimize and changing position within a playlist of multiple images, but
this was also caused by the uninitialized lang which is now fixed.

Fixes #8922.

### CODE REVIEW

**Comment by avih** [comment]
I approve the `player: fix segfault` commit. No idea about the other two. Maybe @Dudemanguy knows?

**Comment by Dudemanguy** [comment]
First two are good. I haven't thought too hard about the third commit yet.

**Comment by garoto** [comment]
Working on my day-to-day 8.1 installation. Also tested working on a fully up-to-date 8.1 VM. Amazing job!

**Review by Dudemanguy — APPROVED** [review]
Yeah, it makes sense. I think this is the cleanest way to handle all the prio stuff too. Thanks for fixing this.

**Pull request merged**
