### PR TITLE
corrected typo

### PR DESCRIPTION
**Pull request by szebrowski**

### CODE REVIEW

**Comment by wm4** [comment]
This got overlooked.

Though, can you change the email address? "vagoo" apparently means "vagina", and that's clearly offensive. We don't want to hurt anyone's feelings.

**Comment by maletor** [comment]
Where do you see "vagoo"?

**Comment by haasn** [comment]
> Where do you see "vagoo"?

The commit's author is listed as ```dflt@vagoo```.

**Comment by wm4** [comment]
Rejected due to offensive stuff.

**Pull request closed without merging**
