### PR TITLE
build: add quotes to all Swift build related paths

### LINKED ISSUE #6220: Fail to compile on MacOS 10.14
### mpv version and platform
MacOS 10.14 (18A391)
mpv git 0f3e25c

### Reproduction steps
compile with `./bootstrap.py && ./waf configure && sudo ./waf build -v`

### Actual behavior
`Build failed
 -> task in 'osdep/macOS_swift.o osdep/macOS_swift.h osdep/macOS_swift.swiftmodule' failed with exit status 1: 
	{task 4407275224: osdep/macOS_swift.o osdep/macOS_swift.h osdep/macOS_swift.swiftmodule macOS_mpv_helper.swift,events_view.swift,video_layer.swift,window.swift,cocoa_cb_common.swift -> macOS_swift.o,macOS_swift.h,macOS_swift.swiftmodule}
''`
### Log file
[https://0x0.st/sElM.txt](https://0x0.st/sElM.txt)

### PR DESCRIPTION
**Pull request by Akemi**
this doesn't seem very nice. i suppose using an argument list would probably better than quoting everything in a string?

Fixes #6220

### CODE REVIEW

**Comment by Akemi** [comment]
okay i changed the code to use an args list instead. i am not too happy about the need of [splitting](https://github.com/mpv-player/mpv/pull/6222/commits/7f3ff0af3db49208dbb6d92ea7bf60d0b9b44f04#diff-dc6134e3d3c869a052520d86f46371dcR1056) the `ctx.options.SWIFT_FLAGS` from the `--swift-flags` options, since it can make problems with arguments with spaces. is there a better way to pass flags or split a string into args? how does ffmpeg handle their `--extra-cflags` option, it's also just a string?

i also added another commit to make the module configurable instead of hardcoding it, it just takes the name of the `.swiftmodule` file.

**Comment by jeeb** [comment]
Shell is perverse, and at the end of the day everything is a string. So yes, it basically just evaluates and echos the strings as required.

And yes, I do agree. This might give you some more peace of mind, though?
```python
>>> options = "--option --cc=\"cc -E\""
>>> options
'--option --cc="cc -E"'
>>> from shlex import split as shell_split
>>> shell_split(options)
['--option', '--cc=cc -E']
```

**Comment by Akemi** [comment]
yep that is nicer, thx. updated it to use shlex split instead.

**Comment by Akemi** [comment]
i added a third commit to fix another problem with escaping/quoting/spaces. the cocoa check failed since the include path was spilt and that failed on spaces. hopefully the proposed fix to use a list for includes instead makes sense.

**Pull request merged**
