### PR TITLE
mac: add rotation entries to the menubar (using video-rotate)

### PR DESCRIPTION
**Pull request by pokemaniac05**
This PR reflects #11935, using video-rotate instead of video filters

### CODE REVIEW

**Comment by Akemi** [comment]
pls squash both commits and use the commit prefix already used on the most recent commits of that file, "mac:".

**Comment by pokemaniac05** [comment]
May this PR be merged?

**Comment by Akemi** [comment]
could you please rename "Reset rotation" to "Reset Rotation" and rename all "Rotate (X°)" entries to "Rotation X°", to be consistent with other namings and "Rotate (X°)" sounds like "rotate another X°" from the current rotation.

probably hard to implement right now but "Rotate Right" and "Rotate Left" would be better.

**Comment by Akemi** [comment]
alternate version merged with #12926

**Pull request closed without merging**
