### PR TITLE
w32_common: fix a minor snapping issue

### PR DESCRIPTION
**Pull request by pavelxdd**
Sometimes when restoring from maximized state or from aero snapping, the window position becomes incorrect - the mouse is in one part of the screen, and the window in another. This only happens when an option `snap-window` is active.

Better show this on webm:
before the fix: https://a.pomf.cat/wuhgwk.webm
after the fix: https://a.pomf.cat/wyuowz.webm

### CODE REVIEW

**Comment by jeeb** [comment]
Thanks for the clips for easy check of what this is supposed to fix.

So if I understand this correctly:
* Adds an early exit in `snap_to_screen_edges` if the rectangle is not of the size we expect (rc width != wr width || rc height != wr height), which would mean that Windows took care of the scaling already.
* Properly initializes moving/snapped/snap_d{x,u} in `gui_thread`.
* When receiving from the system:
  * `WM_MOVING`:
    * set the moving flag
    * add checks for if we're not currently in full screen and not embedded before trying to snap.
  * `WM_ENTERSIZEMOVE`
    * set the moving flag
  * `WM_EXITSIZEMOVE`
    * unset the moving flag
  * `WM_SIZE`
    * if moving flag is set, we're no longer snapped (Due to `WM_ENTERSIZEMOVE` enabling this flag, which is supposed to get fired first when the user clicks down on the bar).

So all in all, this does a partial rework of the state machine for window management. In general, this sounds good enough. Will have to build locally to test it out. @rossy , any opinions?

**Comment by pavelxdd** [comment]
> Adds an early exit in `snap_to_screen_edges` if the rectangle is not of the size we expect, which would mean that Windows took care of the scaling already

Yes, this check is specifically for the case, when we are trying to move an aero-snapped window. It was reported by @erengy [here](https://github.com/erengy/windows/pull/4#issuecomment-346251781), thanks to him for finding it.

The rest of your points are correct.

There's still a small issue with dragging an aero-snapped window with mouse over the VO,
here's a video:
https://a.pomf.cat/aknmwj.webm

I spent a lot of time trying to fix this, and still have no idea how to do it properly. Any help is appreciated.

**Comment by jeeb** [comment]
(Finally) after various amounts of stupidity I was able to reproduce the issue - and most likely reproduced that it was fixed. Thankfully the over-VO drag is much more easily reproducible :)

**Comment by jeeb** [comment]
@pavelxdd , I'd like to take this in, but after discussing with @kevmitch / @rossy I would prefer to separate the two pieces of it into something like the two topmost commits of https://github.com/jeeb/mpv/commits/test_snapping . Is that OK by you?

**Comment by pavelxdd** [comment]
Yeah, sure!

**Comment by jeeb** [comment]
Pushed as 483437ba91e85c14236d9ccc5986c4d6faaaf7ff and 665173d8b24372672e81787ed2aff6415b5cc3a1 . Thank you for your contribution.

**Pull request closed without merging**
