### PR TITLE
cocoa: layer backed view

### LINKED ISSUE #3746: Volume/dock flickering regression on Mac
### mpv version and platform

0.21.0 and current master (issue was not present in 0.20.0). Have been using release builds so not sure which commit it started on.
macOS 10.12
### Reproduction steps

Playing an MKV (h264 or HEVC) in full screen, and then triggering an OS volume change, or revealing the auto-hiding dock. Does not happen when playing an h264 MP4.
### Expected behavior

No flickering or artifacts.
### Actual behavior

When changing volume, the macOS volume overlay appears, then flickers between a black square as it disappears. When revealing the dock, similar issue as there is a flickering black bar artifact along the bottom. Neither of these issues happen if the video is paused, however.
### Log file

http://pastebin.com/JzaYkSQj
### Sample files

Seems to be anything in MKV container.

### LINKED ISSUE #3944: Issues with macOS native FS
Greetings,
I finally managed to try out the new cocoa native-fs merged a bunch of days ago, and first of all I want to thank you all: IMHO it's a sensible improvement over the old method, and mpv taking a new space in fs fits way better with my workflow.

However, I had some troubles with it that I didn't see mentioned in the PR or in any issues in the tracker:

- [x] 1. **Issues with playback restore in fullscreen**
Using the playback restore function (Shift+q) with the player in fullscreen results in two weird issues, both always reproducible. 
First of all, when the file is opened again and mpv proceeds to restore playback, for half a second of so it only shows a black window in fullscreen, with some white flashes on the left (leftovers of an animation of some sort?), then the video starts to play without issue. (**solved by system update 10.12.4**)
But then, if you go back to windowed, instead of showing a regular window as big as the video, the windows itself is always 960x480 no matter what. To show you, I took a screenshot of this happening: the source video file is 1280x720, and it's been fullscreened, closed with Shift+q, restored then windowed: https://0x0.st/97j.png. 
Note that taking a screenshot with `screenshot window` keeps the black bars: https://0x0.st/97p.jpg. (**solved by** 4fe45fb)

- [x] 2. **Black flash entering or exiting fullscreen**
This doesn't happen all the times, and it doesn't seems to follow a precise pattern: some random times, regardless if the video is playing or paused, the window goes black for a split second. I wasn't able to catch any significant log, nor the player shows any dropped frame.

- [x] 3. **Small delay with keyboard input after going fullscreen**
For a very short time, mpv is not responsive to keyboard's inputs right after going fullscreen. I actually suspect this happens because, even though the resize is instantaneous, behind the window the system-wide space transition animation is going, so the player isn't in control until the animation is ended. Correct me if I'm wrong, but if that's the case I fear there's nothing to do about that (it's not a big issue, either), but I thought it was worth of a report nonetheless. (**solved by** 063ca8f)

I'm using the latest master on macOS 10.12.2, but I'm sure all of this is easily reproducible in 0.23.

### PR DESCRIPTION
**Pull request by Akemi**
this is a WIP so there is still some debugging shit in the commits and the commit messages don't conform to the standard yet.

i am doing it this way since it potentially fixes 7 issues and i kinda want a central place where issues can be reported and fix confirmations can be posted. the issues in question that most likely will be fixed are:
#2217 
#2392 
#2873 
#3739 - confirmed fixed
#3746 - confirmed fixed
#3944 
#3978 - confirmed fixed (most likely)

known issues of this WIP branch:
- the layer is not in sync with the resizing on live-resize, so black edges can occur on the right and bottom. this makes the fullscreen animation look a bit choppy.
- if display aspect ratio and video aspect ratio are different the video will be stretched for the time of the animation from window to fullscreen and vise versa.

since there is a dislike for animations and the native fullscreen (#4014) i will also add a none native fs after everything has been worked out.

### CODE REVIEW

**Comment by AirPort** [comment]
I did a couple of tests, and generally it works very well (it seems to solve the flickering overlays issue, the fs animation looks really smooth and has a "native" feel) but I seem to have stumbled upon a remarkable regression playing this clip: https://a.pomf.cat/kdhdza.mp4
Current master, with display-resample or audio sync + `opengl-early-flush=no`, plays the clip smooth both in windowed and in fullscreen mode. 
The cocoa_animation branch plays the clip smooth with player windowed, but in fullscreen playback is glaringly choppy. `opengl-early-flush=no` has no effect on it.
The "strange" thing is that, unlike the old performance issue, the player reports no dropped frames whatsoever.
I tested the issue with a "regular" 24 fps video file and it's not nearly as glaring, playback seems fine, only I think sometimes I noticed some little "jump" during pans. 
I'll re-test tomorrow with the morning and a clearer mind, if you need anything or you have some specific test you need me to run please tell me.

(For the sake of thoroughness, I can play the clip smooth in fs with this branch using the dGPU or a barebones configuration (basically cutting out opengl-hq), yet the Iris Pro should be more than able to handle this stress, as it's shown by the fact it's capable to do it with the current master).

**Comment by wm4** [comment]
For testing display-sync, check the usual frame statistics like vsync-jitter and vsync-ratio.

**Comment by Akemi** [comment]
a performance regression isn't something i would have expect tbh. though since it replaces the backing storage with the 'layer', it could be that the layer itself is just slower since it can be animated via Core Animation. i was thinking of replacing the CALayer with a CAOpenGLLayer/NSOpenGLLayer, though the latter wants that all rendering is done in its drawInCGLContext/drawInOpenGLContext method which makes it really hard to use. theoretical it might be possible to get mpv to sync to it or to use a shared context, a frame buffer and render that frame buffer to the OpenglLayer's context. for the latter i have no clue how do it (yet).

**Comment by Akemi** [comment]
@AirPort i made a small [test app](https://github.com/Akemi/libmpv-CAOpenGLLayer-test) with libmpv and a CAOpenGLLayer. so i was wondering if you can build and test it. if you built mpv with libmpv you just need to call `make` and then `./test file.mkv` to play a file in the directory of that repository. does it also have the performance regression you described?

**Comment by AirPort** [comment]
Sure, as soon as I'll get back home I'll try it and report.
I had also collected some data in the past couple of days, but unfortunately I had no time yesterday to post it in an useful way.

**Comment by AirPort** [comment]
Unfortunately I have to say that the test program changes nothing over the previous results.

Yesterday though, I tried to collected some numerical data with the clip I linked before. 
I usually set the player with **video-sync=audio**, and in that mode the total frame timings property values are ~06000-0900 on average, and occasionally 11000-15000 on peaks with both master and cocoa_animation branch. 
The player doesn't report dropped frames in any case, but with cocoa_animation in fullscreen (or with a resized, big, window) playback is stuttery.
In **video-sync=display-resample** mode the vsync-ratio is stable at 1.000 and vsync-jitter is ~0.02-0.03 (with occasional peaks) with both branches, both windowed and in fullscreen. Again, master is smooth, cocoa_animation is stuttery enlarging the window or going fullscreen. No frames are dropped or mistimed, every now and then a frame get delayed.

So in the end it seems that, whatever performance regression is happening, mpv is actually unaware of it. Maybe there are some system tools that could help me shedding some light on what's happening behind the scenes?

**Comment by Akemi** [comment]
i first thought it might be related to the layer not 'syncing' properly as seen in one of the issues i mentioned. though i am pretty sure that my example app, which uses CAOpenGLLayer, properly syncs and since you still get that problem it is probably something else. which is kinda bad since now i have no idea what can be done about it.

i pushed something to my cocoa_animation branch, removing the kCGLPFAAllowOfflineRenderers and kCGLPFABackingStore attributes from the context creation. i doubt they cause the performance regression but can't hurt trying without them. if you could test it again it would be appreciated.

**Comment by tmkk** [comment]
On an external display attached to retina MBP, a video is rendered inside a quarter of a player window. After resizing the window (or switching to fullscreen playback) it renders properly. Playback in built-in retina display is fine.
Screenshot:
mpv

**Comment by Akemi** [comment]
very weird issue. anyway my recent commit should fix it.

**Comment by tmkk** [comment]
Getting better, but still not perfect. It switches to a proper rendering almost instantly, but getting a quarter rendering at the beginning of a playback.

Calling `[s->nsgl_ctx update]` once when `vo_cocoa_swap_buffers` is called for the first time (i.e. before the first `CGLFlushDrawable` call) completely solves the problem. It seems `[s->nsgl_ctx update]` in `vo_cocoa_config_window` doesn't take effect at all for some reason.

**Comment by Akemi** [comment]
> It seems [s->nsgl_ctx update] in vo_cocoa_config_window doesn't take effect at all for some reason.

hence why i said it's weird and why i change it.

**Comment by Akemi** [comment]
unfortunately i can also reproduce some performance regressions. vsync jitter drastically increases from under 0.03 to 0.03-0.3 (very unstable) causing quite a lot mistimed and delayed frames. though visually it's really hard to spot so i wonder if the layer might mess with the statistics somehow.

**Comment by Akemi** [comment]
@AirPort would you mind testing [this](https://github.com/Akemi/libmpv-CAOpenGLLayer-test) again? i made a few changes.

**Comment by AirPort** [comment]
Unlike before, as far as I can see now is perfectly smooth both in fs and resizing the window!

(Just to be sure and not lead you astray, since I have no clue about the libmpv API and I have no way to check: it does pick up the VO options from my config, right?)

**Comment by Akemi** [comment]
yeah i made sure it loads the config file from [~/.config/mpv](https://github.com/Akemi/libmpv-CAOpenGLLayer-test/blob/master/test.m#L85). if you have stats.lua in your scripts folder you can toggle it visible via `echo 'script-binding stats/display_stats_toggle' | socat - /tmp/mpvsocket` in a separate terminal. though you need to install socat from brew for it. i also kinda forgot to mention, that test only works properly on a the main screen for now and assumes 60hz as initial value for the display refresh rate.

since it works for you and it also improved the performance for me drastically this seems to be the only way to go. we have to use CAOpenGLLayer somehow and also have to use a 'discouraged' way of updating that layer to make it work properly. the big problem here though is that opengl-cb/libmpv use a different different way of rendering, which is the opposite of how mpv internally works. so it's sadly non-trivial to use a CAOpenGLLayer and might not work at all.

**Comment by Akemi** [comment]
going to close this, since i too see some bad performance regressions and we need a completely different approach with a CAOpenGLLayer.

**Pull request closed without merging**
