### PR TITLE
Cocoa: Displaylink and screen event improvements

### PR DESCRIPTION
**Pull request by Akemi**
i wrote quite a bit in the commit messages about the changes.

### CODE REVIEW

**Comment by wm4** [comment]
Seems fine.

One thing: when nominal and actual fps are quite close, wouldn't it be better to use nominal? My feeling is that nominal is an ideal value, while the actual fps is subject to jitter, so it could actually be off. But I'm not really sure about that.

**Comment by Akemi** [comment]
from my tests, though they are kinda limited:
1. the nominal values is very close to mpv's estimated value (<=0.2Hz difference)
2. the actual value was mostly within ~0.1Hz difference of mpv's estimated value.
3. the actual value can be quite off (max observed ~1Hz) in the worst case, in comparison to mpv's estimated value

so the nominal value is the most stable but not always the most exact, probably expected. maybe it's really better to just always use the nominal value and get rid of any over-sophisticated heuristic?

**Comment by enoposix** [comment]
This looks good, the usage of 60Hz as a default as discussed with @Akemi on IRC.

**Comment by Akemi** [comment]
so i ran some more tests. i moved the window between two screens. got the estimated-display-fps value while waiting a bit till it was nearly 'constant' after the screen change. the actual fps were always closer to the estimated one in comparison to the nominal value (no big outliers in that test). i think the below image speaks for itself. from that i would like to keep it like it is, but maybe lowering the threshold value from 1.0 to 0.1. the average difference between the estimated and nominal value was around ~0.04, doubling that and rounding would lead to 0.1. this is also a bit higher than the highest actual value (~0.06) in that test. so everything higher 0.1 could be considered an outlier and in that case the nominal value would be more accurate.
screen shot 2017-01-30 at 17 59 10

**Comment by Akemi** [comment]
i pushed a slight optimisation, since we don't need to update the displaylink when a mode change occurs on the same display. will squash the commit later.

also changed the threshold to 0.1.

**Pull request merged**
