### PR TITLE
vo_gpu_next/vo_gpu: support crop in video_screenshot

### PR DESCRIPTION
**Pull request by kasper93**

### CODE REVIEW

**Review by llyyr — APPROVED** [review]

**Review by haasn — APPROVED** [review]
LGTM

**Comment by Dudemanguy** [comment]
One small nit, software screenshots (`--screenshot-sw`) with video crop are still broken.

**Comment by kasper93** [comment]
> One small nit, software screenshots (--screenshot-sw) with video crop are still broken.

Pushed also patch for `image_writer`

**Comment by Dudemanguy** [comment]
I just realized that there may be some confusion here. I'm not actually sure what behavior is desired, but there's some inconsistency.

With `--vo=gpu-next`, I get the original video resolution with `screenshot` and the actual cropped image with `screenshot window`.
With `--vo=gpu`, I get the crop with both `screenshot` and `screenshot window`.
With software screenshots, I get the crop with `screenshot` but `screenshot window` is still broken.

If we go with the historical behavior and the description in the manpages, then the `gpu-next` implementation is right. Although one could argue that the crop should be taken into account when doing normal screenshots, mpv doesn't do this for other similar things that alter the video (like panning, panscan, or zoom).

**Comment by kasper93** [comment]
Thanks for testing, will fix it.

> With --vo=gpu-next, I get the original video resolution with screenshot and the actual cropped image with screenshot window.

This is actually different issue. It depends on other factors, how it actually works.

> Although one could argue that the crop should be taken into account when doing normal screenshots

It should, same as rotate it is image metadata. Unlike pan which is viewing metadata. Anyway, I need to fix those remaining cases first.

**Comment by kasper93** [comment]
@Dudemanguy: Fixed remaining issues, thanks for spotting them.

**Comment by Dudemanguy** [comment]
Yup that works. Thanks.

**Pull request merged**
