### PR TITLE
w32_common: fix bad window style for no-border window

### PR DESCRIPTION
**Pull request by CrendKing**
Currently on Windows, the no-border window (`--no-border`) has window style `WS_OVERLAPPED | WS_MINIMIZEBOX`. According to [Microsoft doc](https://docs.microsoft.com/en-us/windows/win32/winmsg/window-styles#ws_minimizebox), when `WS_MINIMIZEBOX` is specified, `WS_SYSMENU` must also be specified.

The inconsistency causes some apps relying on the correct combination of flags to miss, e.g. https://github.com/valinet/ExplorerPatcher/issues/161.

This small change adds `WS_SYSMENU` to the no-border window style, making it exactly the same as the fullscreen window style.

Locally built and tested that the two functionalities originated the [previous change](https://github.com/mpv-player/mpv/commit/bf5727a60fbae12510238c23a38b89822b128baa) still exist:

1) Clicking taskbar minimizes the window;
2) Win+Down arrow minimizes the window.

### CODE REVIEW

**Comment by CrendKing** [comment]
Any update? Thanks.
@avih @rossy

**Comment by avih** [comment]
Without promising to reviwe it further:
- If you feel some commits should be squashed then please do that.
- The commit message[s] should describe the problem which is being addressed at each commit (e.g. maybe what doesn't work), and if needed, why/how the patch is the correct way to address it.
- The commit message should be limited to 72 chars per line (except long links etc).
- There still seem to be a manual resize issue with the latest patchset. With the same test invocation as before `mpv --no-config --idle --force-window --no-border`, if you try to resize the window manually (using the mouse at the window edge) then the aspect ratio of the window changes once - it becomes slightly taller (caption height maybe?). Further resize and/or new resizes maintains this incorrect taller aspect ratio

In general, as you can probably tell by now, managing the states and window styles can be a very delicate task, and changing one thing can easily break things elsewhere (especially on platforms which you don't test extensively, but clearly also where you do test - as already demonstrated twice).

Therefore, in general we prefer to take strict and very specific fixes, which can be explained exactly (not in some generic description), to minimize the impact on other working and delicate aspects of the behavior.

**Comment by CrendKing** [comment]
I'm sorry for the issue you mentioned, which I can confirm. I'm able to solve this issue specifically by commenting out the [`subtract_window_borders()` call in `WM_SIZING`](https://github.com/mpv-player/mpv/blob/1c49d5735dc5231b9bebcdcab5b182a7e62771d4/video/out/w32_common.c#L1118). However, since my proposed code basically changes what "border" means, there may well be other corner cases problematic (such as the `WM_DPICHANGED` right below).

As you said, this whole window styling and message handling code is quite complex and I can't manually test every single possible use cases. So if you guys would rather not touch the delicate matter, feel free to close the PR.

If on the other hand you guys decide to use this opportunity to come up with a checklist of what to test whenever anyone changes this area of code, I'd be happy to help.

**Comment by avih** [comment]
> However, since my proposed code basically changes what "border" means

Not sure I understand this statement, and I don't see it explained at the commit message[s] either. Do feel free to elaborate.

So far, other than the issues mentioned with the patches, the only described problem is at the first commit message:
> when WS_MINIMIZEBOX is specified, WS_SYSMENU must also be specified.
> The inconsistency causes some apps relying on the correct combination....

On the face of it, the solution to this problem is either removing WS_MINIMIZEBOX, or adding WS_SYSMENU. And apparently you have another way to solve this problem.

In all cases we'd need to understand the best we can what the implications are, weight them, and decide which is overall best for mpv (including not changing anything, and knowingly living with the issue you described).

> If on the other hand you guys decide to use this opportunity to come up with a checklist of what to test whenever anyone changes this area of code

Not sure what "this area of code" means, but I don't have such checklist, and I'd generally consider this whole file as one unit of code which need to keep working as a whole.

"the checklist" is the documentation (initial fit, geometry, related properties, selected monitor, etc), common sense (behavior is consistent and reasonable), and use cases which we know the code tries to handle (e.g. manual resize of a borderless window). And also embedding into an external window.

I understand it's not what you hoped for, but I don't think I can come up with some specific list of things to test (and then having to deal with "but that wasn't on your list").

**Comment by CrendKing** [comment]
Sorry took long to reply this. I experimented different approaches, and I can't find a perfect solution. I think it's better just close this.

Basically, the original request is to add `WS_SYSMENU` to the window style to fulfill the requirement of Microsoft doc. However, I think that "requirement" may be outdated and not taking borderless window into consideration. Sure, for bordered window it doesn't make sense to have `WS_MINIMIZEBOX` without `WS_SYSMENU`. However, `WS_MINIMIZEBOX` and `WS_MAXIMIZEBOX` themselves control separate window behaviors (able to minimize and maximize) without the need of `WS_SYSMENU`, which is exactly what a borderless window needs. So I think it makes sense to just have `const DWORD NO_FRAME = WS_OVERLAPPED | WS_MINIMIZEBOX;`.

On the other hand, it is weird that while not having `WS_SYSMENU` (e.g. just `WS_OVERLAPPED | WS_MINIMIZEBOX`) somehow gives the window the resizing handles, adding `WS_SYSMENU` without `WS_THICKFRAME` suddenly disables the resizing. Unfortunately, adding `WS_THICKFRAME` introduces more complexity such as requiring handling `WM_NCCALCSIZE`. I can't find a way to workaround this easily.

There are many talks on the Internet about how to properly implement borderless window. Every one of them has some kind of drawbacks. For example, https://social.msdn.microsoft.com/Forums/en-US/c273dead-ea91-4138-a057-cceb4db111cd/borderless-window-creation listed two GitHub impls, both are kind of hacks. And they are not simple.

Hence, I'm closing this.

**Comment by avih** [comment]
> I can't find a perfect solution. I think it's better just close this.

OK. Thanks.

**Pull request closed without merging**
