### PR TITLE
Support log100 and log316 transfer functions

### PR DESCRIPTION
**Pull request by kodabb**
as discussed on IRC :)

### CODE REVIEW

**Comment by kodabb** [comment]
oh in case it's needed, "I agree that my changes can be relicensed to LGPL 2.1 or later."

**Comment by kodabb** [comment]
PR updated, i also dropped the `f' qualifier while at it

**Comment by haasn** [comment]
Why do you have the max() in both halves of the equation?

**Comment by kodabb** [comment]
fixed

**Comment by kodabb** [comment]
fixed once again!

**Comment by kodabb** [comment]
hmm something is not right with colors again... the text should be white not pink, any ideas what could be?

**Comment by haasn** [comment]
@kodabb Does it work in `--gpu-dumb-mode`?

**Comment by kodabb** [comment]
with `gpu-dumb-mode` the pink shift is slightly reduced but is still present

**Comment by wm4** [comment]
I don't know what happened to this, but I assume nobody has interest in this anymore. Closing, reopen if this gets alive again.

**Pull request closed without merging**
