### PR TITLE
[WIP/RFC] Consuming raw audio from ao drivers

### PR DESCRIPTION
**Pull request by tmm1**
A number of platforms (for instance, iOS and Android) now have the ability to decode common audio codecs during audio playback. On embedded/mobile devices, these often also take advantage of hardware decoding.

At the moment, the audio infrastructure in mpv assumes all AO drivers want PCM or SPDIF (which looks the same as PCM as far as the audio code is concerned). This makes it impossible to receive the raw audio packets in an audio driver, since the audio timing and buffering code expects PCM samples at a fixed sample rate.

With this PR, I hacked in a copy of ad_spdif called ad_raw, which skips the SPDIF wrapping and forwards the raw audio frames to the consumer. It also extracts the bitrate, which is assumed to be constant and used instead of the samplerate for timing/buffer calculations.

Using this PR, I was able to implement a version of ao_audiotrack for Android which forwards raw AC3 audio packets directly to the OS for playback. It works quite well, and also lets Android OS make spdif/passthrough decisions based on the underlying hardware.

The code isn't pretty, and a lot of refactoring could be done to improve it:

- ad_spdif and ad_raw could be combined, since they're almost identical
- there may be a simpler way to access the audio container's bitrate rather than propagating it through mp_aframe and struct ao
- some or all of the audio timing/buffer hacks may become unnecessary with @wm4's planned audio timing refactor

### CODE REVIEW

**Comment by wm4** [comment]
Seems like you really use the bitrate of the first packet only. So why not set a fake samplerate to achieve the same effect?

**Comment by tmm1** [comment]
>So why not set a fake samplerate to achieve the same effect?

That would indeed simplify the code immensely. One reason was, atleast in the case of AudioTrack, I need the actual samplerate to initialize the driver.

**Comment by wm4** [comment]
Using the ffmpeg parser API to do that in the AO driver would probably still be less "wild". Also, we're hoping that this code can be dropped again once the audio stuff is rewritten.
Another requirement to get this merged would be adding the raw functionality to ad_spdif, instead of duplicating it. Could be an additional mode like "ac3-raw" (like dts vs. dts-hd can switch modes for the same codec).

**Comment by tmm1** [comment]
After some more testing, I found some streams where the CBR assumption falls apart. In one such sample, when the stream switches from a program to a commercial break, the audio switches from 5.1 to 2ch and also from 384kbps to 192kbps.

If the audio pipeline was able to pass whole frames to the ao, the driver would not need to care about bitrate anymore and could use the ac3 sync header to figure out how many samples were contained within. (For ac3, the number of samples is always 1536, but other codecs like eac3 can contain variable number of samples).

**Comment by rolandjon** [comment]
I'm sorry to disturb you so abrupt，I'm curious about why this feature has not been merged into upstream. I guess it may be the most distinctive and valuable feature compared with other player frameworks, such as VLC. For TV or IPTV boxes, this function is really really really  needed.

**Pull request closed without merging**
