### PR TITLE
Improve release policy text to better describe the reality

### PR DESCRIPTION
**Pull request by lekeke**

### CODE REVIEW

**Comment by wiiaboo** [comment]
When there are known breaking bugs in master close to being fixed or some interesting features coming, the release can be postponed. There's no strict schedule to the releases.

**Comment by wiiaboo** [comment]
Also, that sentence just reads as a snarky comment, be it the truth or not.
And the commit message doesn't follow the project guidelines.

**Comment by lachs0r** [comment]
(It’s true, though.)

**Comment by lekeke** [comment]
The README states a new version of mpv is released every other month.
The release-policy states a new version of mpv is released every month and sometimes twice a month.
That alone is a contradiction.
And neither is true, you say?
Then it's better to update both the README and the release-policy to make it clear that the releases don't follow any schedule, no?

**Comment by Hrxn** [comment]
As seen on 4chan...

**Comment by wiiaboo** [comment]
> And neither is true, you say?

I don't remember writing anything like that.

>Then it's better to update both the README and the release-policy to make it clear that the releases don't follow any schedule, no?

Sure. Make sure the commit message follows project guidelines, be less aggressive on the language, and it will probably be accepted. You can reopen this if you know how to git rebase.

**Comment by lekeke** [comment]
> I don't remember writing anything like that.

"There's no strict schedule to the releases."

> Make sure the commit message follows project guidelines, be less aggressive on the language, and it will probably be accepted.

It was just a joke.
Whatever.

**Pull request closed without merging**
