### PR TITLE
Edit man page and mpv.conf, clarify how to find all options

### PR DESCRIPTION
**Pull request by jimbo1qaz**
See issue #6561.

I agree that my changes can be relicensed to LGPL 2.1 or later.

### CODE REVIEW

**Comment by haasn** [comment]
The changes seem fine but your commits don't follow the code style guide at all. Also, I'm confused about why you are making a change only to then undo it later. Doesn't that defeat half the purpose of your PR?

**Comment by jimbo1qaz** [comment]
> The changes seem fine but your commits don't follow the code style guide at all.

can you squash it or something, or do I force push? Is the PR expected to be 1 commit or not?

- https://github.com/mpv-player/mpv/blob/master/DOCS/contribute.md#sending-patches What's the "sub system"?

> Also, I'm confused about why you are making a change only to then undo it later. Doesn't that defeat half the purpose of your PR?

The first time I read the file, I didn't notice the block of text that says:

> # The commented example options usually do _not_ set the default values. Call
# mpv with --list-options

So I added a concise message at the top of the file.

During the issue "discussion", I noticed that the information was already in the file (though it doesn't look like something you can copy into the terminal. coincidentally, mpv ignores `with` when calling `mpv with --list-options`.) so I removed my addition. Which method is more obvious?

**Comment by Akemi** [comment]
because the github search is dumb, try "--sub-font".
squash and force push is what you should do. one commit is sufficient.
subsystem in your case is "man" or "manpage", see [the history](https://github.com/mpv-player/mpv/commits/master/DOCS/man/mpv.rst) of the file you are changing. commit messages that change the man are prefixed with "man: " or manpage: ". as two examples analog to that, changes to the options would be prefixed with "option: " or changes to vo=gpu would be prefixed with "gpu: ".

also on a side note, you can also do "man mpv".

**Comment by jimbo1qaz** [comment]
I may look at this later...

**Pull request closed without merging**
