### PR TITLE
ytdl: retrieve only sub languages from --slang if set

### PR DESCRIPTION
**Pull request by wiiaboo**
Remade #2138 so that I can work on a separate branch.

Added start_time detection too (requested by #1519)

### CODE REVIEW

**Comment by ChrisK2** [comment]
Two things:

What's the reason for ``--write-sub``? Doesn't this cause the subs to get written to disk?

And the comment for start_time also says something about end time, which the code doesn't actually use.

**Comment by wm4** [comment]
Merged the last 2 commits. The other 2 still require some discussion.

**Comment by ChrisK2** [comment]
> Rejected

Okay, then what? Add another --ytdl-* option?

**Comment by wiiaboo** [comment]
>What's the reason for --write-sub? Doesn't this cause the subs to get written to disk?

If you don't use `write-sub` requested_subtitles comes up null.

I think it's reasonable to not want subtitles restricted. What would be better then, a separate option especifically for ytdl? We should probably wait for whatever they do to fix Crunchyroll's extraction first.

**Comment by ChrisK2** [comment]
Issue over at ytdl for reference: https://github.com/rg3/youtube-dl/issues/6264

**Comment by wm4** [comment]
I'm not sure either what to do about additional subtitle streams. Ideally, they could be downloaded in the background somehow. But we don't even get subtitle URLs from youtube-dl, just the subtitle data itself. Plus, youtube-dl converts subtitles from whatever proprietary abomination the sites use.

**Comment by ChrisK2** [comment]
> youtube-dl, just the subtitle data itself.

AFAIK, at least youtube actually returns URLs to SRT subtitle scripts, but this is completely different from Crunchyroll, which serves encrypted subs that NEED to go through ytdl to be usable at all.

**Comment by wiiaboo** [comment]
--ytdl-subs ( #2211 ) is a good replacement for this, at least for extractors than don't actually download all subtitles.

**Pull request closed without merging**
