### PR TITLE
ci: delete freebsd job

### PR DESCRIPTION
**Pull request by haasn**
This job has been intermittently causing issues for years. Disable it until a better solution, one that is not built upon a hack (recursively hosting a VM under _macOS_ of all things), comes around.

This OS has a tiny market share even among posix-based servers, and the people insane enough to use it as a desktop system are probably the type of power user who will loudly complain if something doesn't work, so why exactly do we need continuous integration for it?

### CODE REVIEW

**Comment by Dudemanguy** [comment]
I agree that this job is annoying and wish it wasn't based on a hack, but it's still useful imo. Just a couple of weeks ago, it prevented me from breaking BSDs since apparently <inttypes.h> was implicitly included on linux somewhere but not BSD. As long as trivial differences between BSD and Linux exist, stuff like that will happen eventually. And sure BSD users are the type to actually give us a patch, but we can save them time and save ourselves some time too with this stupid job by.

So with that in mind, I would not be in favor of removing it unless there's a better replacement. Considering that this action has like a 50/50 chance of bootlooping now, the bar can't be that high.

**Comment by kasper93** [comment]
> I agree that this job is annoying and wish it wasn't based on a hack, but it's still useful imo.

The issue currently is it fails more often than not, so it's usefulness is very limited. If you manually don't re-trigger until it passes. And most won't or can't do that. And freebsd status gets implicitly ignored, because it is know that it fails, so why bother checking why.

**Comment by Dudemanguy** [comment]
Looking at the past few hours of builds, the failure rate does indeed seem to have dramatically increased for some reason. Dunno if that's just bad luck or if it's getting even worse somehow. Obviously if it just mostly always fails, that makes it useless.

There's other third party solutions out there though. I'll look into it.

**Comment by Dudemanguy** [comment]
Ended up switching to a different action instead in #12722. Seems reasonably reliable at least (spent a bunch of time trying to fix other unrelated stuff).

**Pull request closed without merging**
