### PR TITLE
Don't 'save position on quit' if we're (approximately) at the end of the video.

### LINKED ISSUE #2045: "save-position-on-quit" shouldn't save the position after you've finished the video
Enabling these two options causes an edge case:
- keep-open=yes
- save-position-on-quit=yes

This causes the mpv window to stay open after the video ends, and that mpv should save the position when you quit. The result is that whenever you quit after finishing a video, the end becomes the saved position, and when you re-open the video, it starts at the end.

Ideally, quitting the video after it's finished should clear the saved position.

### PR DESCRIPTION
**Pull request by epitron**
This fixes #2045.

### CODE REVIEW

**Comment by wm4** [comment]
I did this once, but someone complained, so I removed it.

**Comment by epitron** [comment]
Someone complained? Who was it! Let me at 'em!! ;)

What was their concern? That they wanted to `save` the fact that they'd finished watching something?

**Comment by wm4** [comment]
If you for example play multiple file at once, then being within 10 seconds of the end would break resuming from playlists (because playlists are are resumed by checking whether any of the files in it need to be resumed). In the end I found a better way - the player doesn't write the resume config when playback is stopped by switching to the next file.

Honestly, in case of #2045, I'd just say do not use --save-position-on-quit, and use shift+q instead.

**Comment by wm4** [comment]
Rejected in this form. (Sorry.)

But I think you have alternatives. You could implement your own behavior in a Lua script, and dispatch between ``quit`` and ``quit-watch-later`` as you need.

**Comment by epitron** [comment]
I've never used mpv for playlists...

I could make it a lua script. I feel like this is a good default behaviour though, don't you?

**Comment by wm4** [comment]
Well, if you have a playlist with 2 files, and you're at the end of the first one, and the per-file keep-open mode is used, then quit_watch_later + resuming should end up in the same place where I left off: at the end of the first file. This is the behavior I'd expect. But see what I wrote in #2045.

**Comment by epitron** [comment]
Ah, so you can make a whole TV series a playlist, and quit/resume! That is a nice feature.. I didn't know you could do that!

**Comment by wm4** [comment]
And it works like this: ``mpv file1.mkv file2.mkv``. I use this very often, and mix it with save/resume too.

**Comment by epitron** [comment]
It would be neat if you could mpv a directory, and it would treat that as a playlist, and use a single saved position file for the directory. Good for TV serieses.

**Comment by wm4** [comment]
This works already. (Except sub-directories are not loaded eagerly, so resume won't work as expected. Also, it's not implemented on Windows.)

**Comment by epitron** [comment]
Ah, I see. Well, sounds thinking of a playlist as one long video does simplify the save position thing.

**Pull request closed without merging**
