### PR TITLE
Make osd-msg-bar default for seeking and pausing.

### LINKED ISSUE #3028: OSD not show on user interaction on Windows 10
I've set `osd-level=1` in my `mpv.conf` file and the OSD is never shown, even when I "interact" by pause/seek etc. with either my mouse or my keyboard. Other levels work fine (e.g. 2 shows time, 3 shows time+status)

### PR DESCRIPTION
**Pull request by kevmitch**
Fixes  #3028 (OSD not shown on user interaction). Some white-space cleanup to command.c as well.

I agree that my changes can be relicensed to LGPL 2.1 or later.

### CODE REVIEW

**Comment by wm4** [comment]
Yeah, that essentially changes the default osdmsg/osdbar for some commands. Personally I'm fine with it (I'll switch back to the old behavior for `pause` in my input.conf), not sure about others.

Did you check if there's any text in the manpage that needs to be updated?

**Comment by kevmitch** [comment]
wraped commit messages at 72

**Comment by kevmitch** [comment]
updated man page

**Comment by Kagami** [comment]
How to disable this behavior? Only with:

```
MBTN_RIGHT no-osd cycle pause
p no-osd cycle pause
SPACE no-osd cycle pause
PLAY no-osd cycle pause
PAUSE no-osd cycle pause
PLAYPAUSE no-osd cycle pause
AR_PLAY no-osd cycle pause
AR_CENTER no-osd cycle pause
```

? Kinda messy in case if default bindings will be changed…

**Pull request merged**
