### PR TITLE
Random changes

### PR DESCRIPTION
**Pull request by wm4**
f_decoder_wrapper change: CC @tmm1 for testing with MediaCodec
client API change: CC @LongChair

The client API change is actually untested. Maybe some could test the following things:
- does hardware decoding still work with vaapi and d3d/gl interop things with mpv CLI?
- does hardware decoding still work with opengl-cb API with vaapi on X11 and Wayland?
- does hardware decoding work with new render API users?

### CODE REVIEW

**Comment by LongChair** [comment]
@wm4 : looks good to me as well, will try to get drm / atomic to use that over the weekend.

**Comment by wm4** [comment]
Squashed, added another load of unrelated commits.

**Comment by sametceylan** [comment]
Hello sir, my name is Samet Ceylan and I am a designer. If you want and let me, I want to design a creative logo for MPV. I want you to know that I will do it for you. I do not want any compensation. If you would like me to design and if you have any particular detail, please contact me.

**Comment by LongChair** [comment]
@wm4 : is this one ready to go ? :)

**Comment by kevmitch** [comment]
237de35: "multiple libmpv user*s* *who*", "but if *a* user"
970f9d1: "just *be* stopped"

**Comment by kevmitch** [comment]
merged in 965ba23303..af9c6c1133 with some grammatical fixes to the commit message of f60826c3a14ba3b49077f17e5364b7347f9b468a. 

f60826c3a14ba3b49077f17e5364b7347f9b468a probably breaks hooks for js scripts, but I confirmed that a simple js script not using hooks still works. @avih, do you want to update the js api for this?

**Comment by wm4** [comment]
The old API should still work, but yes, JS needs to update.

**Comment by wm4** [comment]
> Hello sir, my name is Samet Ceylan and I am a designer. If you want and let me, I want to design a creative logo for MPV. I want you to know that I will do it for you. I do not want any compensation. If you would like me to design and if you have any particular detail, please contact me.

Well, thanks for your offer, but we already have a logo. If you feel like it, you can try to make a better one, and then we can hold some sort of vote whether to accept it. Or there is other design work that could be done. For example, the OSC tends to look ugly at places, and could use some improvements in style and look&feel. (Forgot to reply to this.)

**Pull request closed without merging**
