### PR TITLE
osc: display Santa hat for idle logo in December

### PR DESCRIPTION
**Pull request by TheAMM**
```
During the 12th month (checked during script initialization), draw a Santa hat
on top of the idle message's logo.
Slightly refactors and optimizes the drawing process as well: reorder original
logo layers and remove redundant holes in them, use a shared line prefix
to clear the style and set start position.
```
As requested.

Open to bikeshedding over colors and whatnot, like `month == 12` maybe being too wide, or adding an option to forbid the hat.

image
image

### CODE REVIEW

**Comment by CounterPillow** [comment]
Finally we have VLC feature parity

**Comment by wm4** [comment]
Looks good.

**Comment by paulguy** [comment]
It's cute. :)

**Comment by wm4** [comment]
Merged as 6d93e4c.

**Comment by Hrxn** [comment]
But what about the Julian calendar? Won't somebody please think of the Julian calendar?

**Comment by blackarcher21** [comment]
please make it optional. thanks

**Comment by Hrxn** [comment]
..but keep it as default to commemorate the festive spirit of the season!

**Pull request closed without merging**
