### PR TITLE
macOS menubar refactor

### PR DESCRIPTION
**Pull request by Akemi**
yeah this is just some eye candy because i felt like doing something simple. i put all the menubar related code into its own file since it would just mess up the application file.

in general this should make the life of unexperienced macOS users easier. i put things into the menu which i thought were commonly used, but feel free to suggest other functions you think should be added. i mostly didn't add any shortcuts (yet), though this can be discussed here too.

the "Preferences" menu item just opens the config file from two predefined locations in TextEdit. if no config file is found an alert is shown which asked the user to create one. this could probably improved.

the "Open File" menu item opens the usual open file dialog from macOS. it can open multiple files and folders.

the "Manual" menu item under Help opens the manual on mpv.io.

most useful feature is probably the Search in the help menu.

see below how the new menu looks like.

about

### CODE REVIEW

**Comment by sCreami** [comment]
It was 'bout time! I was also thinking about including Force Touch features such as a longer press would generate a new key to seek forward faster.

**Comment by sCreami** [comment]
Also, instead of opening the config file with TextEdit, why not use use the `$VISUAL` env if it has been defined or simply open the folder with Finder. Using TextEdit for the configuration seems like a hassle.

**Comment by sCreami** [comment]
There's probably a better way than making all these one-liner functions. Maybe a dictionary.

**Comment by Akemi** [comment]
> Also, instead of opening the config file with TextEdit, why not use use the $VISUAL env if it has been defined or simply open the folder with Finder. Using TextEdit for the configuration seems like a hassle.

hm the menu is for 'none pro' users, i can't imagine anyone would define that env var. on a side note, it's also possible to open the file with the associated App, though nothing will happen if not App is associated. we could try that first and if that doesn't work use TextEdit.

> There's probably a better way than making all these one-liner functions. Maybe a dictionary.

yes definitely. i was thinking the same thing. similar to what i did in the touchbar code.

**Comment by sCreami** [comment]
Would it be too difficult to list the watch_later entries in the File submenu?

**Comment by Argon-** [comment]
Do you want to "reverse" the hashed names...?

**Comment by sCreami** [comment]
>Do you want to "reverse" the hashed names...?

Oh right they're hashed by default. Sorry my stupidity peaked

**Comment by Akemi** [comment]
i rewrote the menu creation and i could reduce the lines of code significantly. also renamed all the "Cycle" instances to "Toggle" or "Next" depending if we cycle through more than two items.

i also added some more useful menu items. added audio and sub delay (positive, negative, reset), show playlist and reworked the Help menu with the most useful links. see screenshots below.

screen shot 2017-07-30 at 23 52 10
screen shot 2017-07-30 at 23 51 41
screen shot 2017-07-30 at 23 51 31
screen shot 2017-07-30 at 23 51 21
screen shot 2017-07-30 at 23 51 09

**Comment by sCreami** [comment]
How about showing the available sub, audio, and video tracks within the corresponding submenu?

**Comment by Akemi** [comment]
> How about showing the available sub, audio, and video tracks within the corresponding submenu?

not impossible but quite a bit of work. i want to keep it simple for now. maybe for a later point of time.

**Comment by Argon-** [comment]
I'd rather add an entry to display them (using the OS**C**), for all the people not aware of the OSC controller's capabilities. I also don't think it would be a good idea to introduce another place to present information, rather use the existing ones (OSD/OSC).

**Comment by Akemi** [comment]
wonder if it would be better to use the OSD messages instead of the OSC one?

**Comment by sCreami** [comment]
Some peoples like me have the osc disabled. I'd prefer the OSD messages.

**Comment by Argon-** [comment]
The OSC has one has a bunch of heuristics to resize the text in order to display longer lists. The OSD is too naive, overflows too fast. 

You don't need to disable the whole OSC just because you don't want the actual controler btw

**Comment by sCreami** [comment]
The OSD and the OSC have both a specific name, one is to display informations and the other one controls. If the player start showing vaguely related informations on the controls why not mix everything once for all, it breaks the purpose of the OSD. Those heuristics could be applied to the OSD instead.

> You don't need to disable the whole OSC just because you don't want the actual controler btw

Could you teach me about that?

**Comment by Argon-** [comment]
No they can't, the OSC is really more than the controller by now. I asked about this back when `osc-playlist/chapterlist/...` was implemented and got this answer.  
The OSC basically provides a framework for ASS related stuff that used to be exclusively for a controller. This "environment", if one may call it like that, is not available to the OSD. Of course one could change that but that's a huge amount of work for little, little gains. I'd rather unify this stuff (even more work though).

We can either use what we have (and works) now, or wait until someone makes significant changes to the OSC/OSD.
Also, let's not forget this is intended for novice users and they usually don't have the OSC disabled.

> Could you teach me about that?
Well, for one you can overwrite the script bindings it uses to get triggered. I used to do that some time ago. Other than that, you can abuse options like `minmousemove` to prevent the "controller" part of the OSC from showing up.

**Comment by Akemi** [comment]
i changed the Preferences menu a bit. if the config file exists it tries to open it with the associated app, if no app is associated it opens the config folder and tells the user to open the mpv.conf file. if the config file doesn't exist it tries to open the config path, if it exists it opens that folder and tells the user to create a mpv.conf file, if it doesn't exist it tells the user to create that path and a config file.

**Comment by AirPort** [comment]
Maybe an option like this one for Preferences/mpv.conf could be useful for Input Keys/input.conf too?

**Comment by Akemi** [comment]
here we go. if wanted we could also discuss possible shortcuts for some of the menu items. though keep in mind, all shortcuts used in the menu won't be propagated to the mpv core and can't be rebound in the input.conf. that's the reason why i only used the standard macOS keyboard shortcuts for some of the menu items.

**Comment by Akemi** [comment]
i predefined the menu tree in a generic way via arrays and dicts to separate the menu definition and the creation. this should make it more maintainable and readable.

**Comment by AirPort** [comment]
>that's the reason why i only used the standard macOS keyboard shortcuts for some of the menu items.

That's probably the best choice. Adding additional binding for mpv functions would only generate confusion in case of customized input.conf, I think.

**Comment by Akemi** [comment]
added a "Open URL" menu item. i think this is probably something people want. i 'misused' an NSAlert for that.

copy/paste/cut/etc. only works with a working "Edit" menu and the appropriate menu items. it would be kinda weird not being able to paste an URL into the "Open URL" dialog. as an alternative we could do what was suggested [here](https://stackoverflow.com/a/3176930), if the "Edit" menu is not wanted.

the last commit is a bit questionable. i was a bit irritated that the TextField wasn't focused when opening the dialog. though since it's a modal NSAlert it's not possible to just set the focus after the dialog opens. so we have to delay the focus call asynchronously. it's a bit hacky and i might just remove it.

**Comment by AirPort** [comment]
The Open URL dialog is actually a quite useful feature. Maybe a keybind could be assigned to it, since it's not a standard mpv function and there's no risk of conflict? Looking at other video players, it seems that VLC uses ⌘N for opening network streams, QuickTime (a more "native" choice?) ⌘L.

**Comment by Akemi** [comment]
there is also the possibility of "Shift-Command-O". xcode uses it for an alternative open dialog, so it shouldn't conflict with any global macOS shortcuts either.

**Comment by AirPort** [comment]
Makes sense, since we have ⌘O for opening local files.

**Comment by Akemi** [comment]
if i didn't overlook anything this should be done. this is just a little heads up before i merge it, in the case anyone wants to add or suggest something else.

**Comment by sCreami** [comment]
I'd rather see the "Customize TouchBar…" label in the Window menu than the View one. I consider it more like an offscreen window but it's just a personal feeling. I have nothing more to say.

**Comment by Hrxn** [comment]
What about this `Playback > Cycle Loop`?

As far as I know, this has changed recently or is about to be changed soon, split up into two distinct options, `--loop-file` and `--loop-playlist`

Maybe this should be reflected in the menu..

**Comment by Akemi** [comment]
> I'd rather see the "Customize TouchBar…" label in the Window menu than the View one. I consider it more like an offscreen window but it's just a personal feeling. I have nothing more to say.

it's just the standard position in all Apple Apps and the suggested preferred position. i don't think we should deviate from that.

> What about this Playback > Cycle/Toogle Loop?
> 
> As far as I know, this has changed recently or is about to be changed soon, split up into two distinct options, --loop-file and --loop-playlist
> 
> Maybe this should be reflected in the menu..

do you suggest two distinct menu items or just renaming "Toogle Loop" to "Toogle Loop Playlist"?

**Comment by Hrxn** [comment]
Only speaking for myself, but since I use both options quite regularly I think having two menu items here would make sense.

**Pull request merged**
