### PR TITLE
Improve wayland keymap handling

### PR DESCRIPTION
**Pull request by mahkoh**

### CODE REVIEW

**Review by Dudemanguy — APPROVED** [review]
The changes make sense to me.

**Review by Dudemanguy — CHANGES_REQUESTED** [review]
Okay actually, I lied. Using xkb_keymap_new_from_buffer results in a segfault when using `mpv --idle --input-test --force-window`. It wasn't exactly clear to me looking at the gdb output why this happens.

**Comment by mahkoh** [comment]
Which compositor did you test this with?

**Comment by Dudemanguy** [comment]
Sway/wlroots.

**Comment by mahkoh** [comment]
My original assumption that `xkb_keymap_new_from_buffer` would work with trailing null bytes was incorrect. I've updated the code.

**Review by Dudemanguy — APPROVED** [review]
Thanks, that seems to do the trick now.

**Pull request merged**
