### PR TITLE
mac/remote: refactor and new features

### LINKED ISSUE #11233: Now Playing menu bar item not behaving properly on macOS
### Important Information

- mpv version
  - 0.34.0-501-g161bdd9359
- macOS Version
  - Ventura 13.2
- Source of the mpv binary or bundle
  - Built from source [using this guide](https://gist.github.com/dbrookman/74b8bcfb37a23452f7137b83bca9580f)
- If known which version of mpv introduced the problem
  - Always been an issue IIRC
- Possible screenshot or video of visual glitches
image

### Reproduction steps

Open .mkv or .mp3 file in mpv from terminal using `mpv --no-config <path to file>` or open said file in mpv from Finder. Check Now Playing menu bar item (enabled in macOS by default, but make sure it's enabled).

### Expected behavior

Progress bar should update in the Now Playing menu bar item. There should be a current and end timestamp. You should be able to navigate the progress using the progress bar bar. It should show the title of what is being played.

### Actual behavior

Progress bar shows no progress. No current/end timestamps show. Can't navigate progress using the progress bar bar. No title is shown.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/10530593/output.txt)

### PR DESCRIPTION
**Pull request by Akemi**
just a small refactor and some newly added features that were requested.

fixes #11233

Screenshot 2024-02-10 at 00 55 28

### CODE REVIEW

**Comment by m154k1** [comment]
Nice :) The only issue I found is seeking to the start (00:00) via macOS UI doesn't work:
```
[input] Option seek: invalid time: '3.910064697265625e-05'
[input] Command seek: argument 1 can't be parsed: option parameter could not be parsed.
[input] Command was defined at .
```

**Comment by Akemi** [comment]
@m154k1 should be fixed now. i am rounding the time to 2 digits after the decimal point now.

**Comment by m154k1** [comment]
Yea it's perfect now. Good job!
Is it possible to add artist and album art for audio files? That'd be a cool feature too.

**Comment by Akemi** [comment]
> Yea it's perfect now. Good job! Is it possible to add artist and album art for audio files? That'd be a cool feature too.

former probably somehow. latter probably not. we don't have an api to extract an 'album art', since it's just treated as a video stream.

**Comment by Akemi** [comment]
@m154k1 i added album and artist info.

**Comment by guidocella** [comment]
You can probably make it show external cover art when available (`current-tracks/video/albumart` and `current-tracks/video/external` are true).

**Comment by m154k1** [comment]
@Akemi works great, thanks!

**Comment by Akemi** [comment]
for the album art feel free to open a new feature request. we probably need to discuss our options.

**Pull request merged**
