### PR TITLE
Audit

### PR DESCRIPTION
**Pull request by stnert**
Read this before you submit this pull request:
https://github.com/mpv-player/mpv/blob/master/DOCS/contribute.md

Reading this link and following the rules will get your pull request reviewed
and merged faster. Nobody wants lazy pull requests.

### CODE REVIEW

**Comment by Dudemanguy** [comment]
I have no idea what this is about, but no.

**Comment by stnert** [comment]
I just wanted to run a security automation test (CI/CD) to check if the code has any vulnerabilities. 

@Dudemanguy

**Comment by CounterPillow** [comment]
So your method of proposing a new CI action is to open a pull request with the descriptive title "Audit", an unmodified PR template, and GitHub web upload commits of files?

Suggestion: go run your snakeoil scanners on your own computer.

**Comment by stnert** [comment]
> So your method of proposing a new CI action is to open a pull request with the descriptive title "Audit", an unmodified PR template, and GitHub web upload commits of files?
> 
> Suggestion: go run your snakeoil scanners on your own computer.

Yes. Okay, thanks!

**Pull request closed without merging**
