### PR TITLE
stats.lua: add codec profile

### PR DESCRIPTION
**Pull request by kasper93**

### CODE REVIEW

**Comment by kasper93** [comment]
> Why did this become a draft? It worked fine.

Previous version has been rejected on IRC. New version is available now.

**Comment by kasper93** [comment]
I would like to have it in this release, but if it don't get reviewed in time, we can drop it.

**Review by jeeb — COMMENTED** [review]
Code-wise for the new properties LGTM.

Not sure how much of an API promise we have regarding these existing properties, but at least the commit message now mentions that there are changes regarding `{video,audio}-codec`'s contents.

**Comment by kasper93** [comment]
> Not sure how much of an API promise we have regarding these existing properties, but at least the commit message now mentions that there are changes regarding {video,audio}-codec's contents.

Coded description is unlikely to be used differently than just printing its value. For format matching the short name should be used. Also the new behavior arguably matches current documentation. (and the value of this prop has been changed not so long ago and there was no complaints)

**Pull request merged**
