### PR TITLE
Alsa sample format detection

### PR DESCRIPTION
**Pull request by kevmitch**
This addresses #2238.  

With this commit, mpv will fall back on the best supported format when the specifically requested one is not available. 

This is useful for direct hardware access like 

```
pcm.!default { type hw; card "NAS" }
```

### CODE REVIEW

**Comment by wm4** [comment]
I think this is not quite right. E.g. if ALSA supports s32, float, and double formats, then s16 would revert to double. Which is probably no problem, but still sounds like overkill. 

You can look at ao_lavc.c and see what it does in ``select_format()``. Maybe this could be factored into a common function used by all AOs. (Of course only ao_alsa.c would use it at first.) Actually, I imagine it could be as simple as:

```C
void get_preferred_formats(int format, int out_formats[AF_FORMAT_COUNT]);
```
where out_formats would contain all defined audio formats, sorted by compatibility to the input format. The AO would then loop over the formats in this order, and try them until it finds one that works.

**Comment by wm4** [comment]
Well, if you want, I can implement my suggestion myself. Feel free to push this too.

**Comment by wm4** [comment]
OK, implemented my own suggestion. See e9822f6012193bf00e81b38b61f3ccbf6fe25cdb for a trivial example.

**Comment by kevmitch** [comment]
replaced by #2310

**Pull request closed without merging**
