### PR TITLE
command: add property track-list/N/selected-order

### PR DESCRIPTION
**Pull request by wnoun**
Read this before you submit this pull request:
https://github.com/mpv-player/mpv/blob/master/DOCS/contribute.md

Reading this link and following the rules will get your pull request reviewed
and merged faster. Nobody wants lazy pull requests.

### CODE REVIEW

**Comment by wm4** [comment]
I think it should be called something other than "order", but I don't know what exactly. Until now, the term "order" appeared only in the source code.
Also, a track can still be selected even if it's not in the ``current_track`` array (if --lavfi-complex is used).

**Comment by wnoun** [comment]
> Also, a track can still be selected even if it's not in the `current_track` array (if --lavfi-complex is used).

maybe I should update docs to clarify its behaviour, since in this case the `*id` properties are also unreliable. getting `track-list` and `*id` properties separately is annoying and the results may mismatch (tracks may switch between function calls).

the name is indeed derived from the source code, I have no idea to find a better name.

**Comment by forworldm** [comment]
`main-selection` seems to be a boolean value? if so, the `false` and absent value can cause confusion, people need to remember the difference.

**Comment by wm4** [comment]
No, it'd just be a different name for the thing added in the PR.

**Comment by wnoun** [comment]
`main-selection` is ok

**Comment by wnoun** [comment]
I changed the name to `main-selection` and updated the manpage.

**Pull request merged**
