### PR TITLE
Match libplacebo peak detection and debanding defaults

### PR DESCRIPTION
**Pull request by haasn**

### CODE REVIEW

**Comment by dokur0chan** [comment]
Deband changes LGTM.

The new default seems like an improvement for unfiltered non-web sources, like DVDs. Using a low resolution source makes the grain change more obvious.

no deband

default

new default

For funsies, here's `--deband-threshold=64` and `deband-grain=24`, which would be the next step up from this.

64t24g

**Comment by llyyr** [comment]
These values mostly came from my testing, I think grain could go down to 16 tbh but I really don't believe we can increase deband threshold any further and still justify enabling deband by default in any profiles. The majority of videos don't have severe banding anymore, so it makes little sense to lose detail trying to remove whatever mild amounts of banding there is.

I'll do more extensive testing over the next few days to see if this can be optimized further with various sources, but in general I wouldn't use a test image with banding that severe for testing this. Just use a simulcast anime for animated content sample and some Netflix TV show for real life content sample, these are going to be more representative of real world content played back in mpv than anime encodes from 2012 era.

**Comment by llyyr** [comment]
> If you don't expect your source to have banding you should just turn deband off

This is probably true, but I don't think most people expect to have severe banding in their source majority of the time. This is an argument against enabling it in the high-profile preset, which is probably worth discussing at least.

Point stands that if we enable debanding by default, it can't be optimized for 10 year old DVD sources. It has to be a balancing act between more modern video sources that are less bitrate starved, and older sources where we need more aggressive debanding.

**Comment by christoph-heinrich** [comment]
The defaults could be tuned for typical content, and then have a profile with sensible values for content that needs more aggressive debanding (or provide such values in the documentation).

**Pull request merged**
