### PR TITLE
win32: change the log level of 'move window' msg

### PR DESCRIPTION
**Pull request by pavelxdd**
Can this line be removed please? It is really annoying since it spams terminal a lot and it's really hard to see other console messages.

### CODE REVIEW

**Comment by wiiaboo** [comment]
Make it debug level instead of removing it altogether, maybe?

**Comment by pavelxdd** [comment]
Will the debug level make this line hidden in a verbose mode? If so, then I agree.

**Comment by wiiaboo** [comment]
That's how the levels work. --log-file only enables verbose, iirc.

**Comment by pavelxdd** [comment]
Changed to debug level.

**Comment by wm4** [comment]
Seems fine.

**Comment by wm4** [comment]
Merged.

**Pull request closed without merging**
