### PR TITLE
clear: GL_DEPTH_BUFFER_BIT

### PR DESCRIPTION
**Pull request by myk1343**
Read this before you submit this pull request:
https://github.com/mpv-player/mpv/blob/master/DOCS/contribute.md

Reading this link and following the rules will get your pull request reviewed
and merged faster. Nobody wants lazy pull requests.

### CODE REVIEW

**Comment by haasn** [comment]
Apart from making the commit title match conventions, can you, at minimum, explain why this change is necessary, or what bug it's solving?

**Comment by myk1343** [comment]
In the working environment of embedded environment, the memory can be used as video memory. It is necessary to completely clear the data in the data video memory to prevent memory growth.

> Apart from making the commit title match conventions, can you, at minimum, explain why this change is necessary, or what bug it's solving?

**Comment by myk1343** [comment]
In the working environment of embedded environment, the memory can be used as video memory. It is necessary to completely clear the data in the data video memory to prevent memory growth.

**Comment by myk1343** [comment]
> Apart from making the commit title match conventions, can you, at minimum, explain why this change is necessary, or what bug it's solving?
In the embedded system with memory as video memory, the video memory data is cleaned in real time to prevent memory leakage.

**Pull request closed without merging**
