### PR TITLE
Use mnemonic names instead of numbers for mouse buttons

### PR DESCRIPTION
**Pull request by rossy**
This makes it easier to remember the names of each button, both as a developer and as a user. The old numbered names are kept as aliases, so this should be backwards compatible with existing scripts and input.confs.

I'm open for bikeshedding about what the buttons should be called. MOUSE_BTN_PRIMARY and MOUSE_BTN_SECONDARY might be preferable to LEFT/RIGHT and cater for eg. left handers who swap those buttons around, but they're also pretty long names.

### CODE REVIEW

**Comment by wm4** [comment]
OK.

Probably needs an entry in interface-changes.rst.

**Comment by rossy** [comment]
Oh, I forgot. Will do.

**Comment by rossy** [comment]
Updated with interface-changes.rst and a fix for macOS.

**Comment by haasn** [comment]
We should also do a better job of communicating this change in the release notes. Is it at all possible to make the behavior backwards compatible with the current names? (+ a deprecation warning)

**Comment by haasn** [comment]
Oh, yes, looking at the code, it is backwards compatible (or appears to be)

**Comment by rossy** [comment]
Yep. I'm kind of tempted to not deprecate the old names at all, since they're consistent with the high-numbered buttons (MOUSE_BTN9 and up.)

**Comment by Akemi** [comment]
a reply is probably not needed, but the macOS changes work as intended. thx @rossy.

**Comment by wiiaboo** [comment]
> MOUSE_BTN_PRIMARY and MOUSE_BTN_SECONDARY might be preferable to LEFT/RIGHT and cater for eg. left handers who swap those buttons around, but they're also pretty long names.

Depends if LEFT always means the left button or does it mean PRIMARY button as specified in something like:
image
or if it depends on the OS(?)

**Comment by rossy** [comment]
Just tested and it does swap the meaning of the left and right mouse buttons, so the physical right button triggers MOUSE_BTN_LEFT. This makes sense, I guess, since switching the meaning of the buttons at the OS level ensures every program responds to the changes.

So MOUSE_BTN_PRIMARY is technically correct, but it's also a long name. and maybe more confusing? I think most users would think of the mouse buttons as left/right.

**Comment by wiiaboo** [comment]
Left-handed people are probably used to left meaning right physical button then, I'd assume? So calling it LEFT should be fine.

**Comment by Akemi** [comment]
> Left-handed people are probably used to left meaning right physical button then, I'd assume? So calling it LEFT should be fine.

being left-handed, though i can't speak for all of them, i never changed my mouse buttons and use the same config as right-handed people. left being primary and right being secondary click. though maybe i am just an oddball.

**Comment by haasn** [comment]
To be fully honest, I'm sure left handed users who've changed this setting globally are very much aware that “left button” now means “right”.

**Comment by rossy** [comment]
@Akemi Yeah, I think that's pretty common. I've only known a couple of people who actually switch the buttons to match their handedness.

**Comment by rossy** [comment]
By the way there was also discussion of using shorter names in IRC, like MBTN_LEFT/MWHEEL_UP. It would be more work, because all the numbered buttons would probably have to be changed too, but maybe it's worth changing them now. What do people think?

**Comment by wiiaboo** [comment]
If they're going to be changed anyway, might as well do it now.

**Comment by rossy** [comment]
Updated with a few changes:
- Button names are shorter now, since they were getting pretty long with the new names.
- The old names are explicitly deprecated, since all mouse buttons have new names now.
- MOUSE_BTN3_DBL and up have been removed without replacement or deprecation, since the code that generates double-click events doesn't use them. See [input.c][1].

I think I'm pretty happy with this now.

@wiiaboo Not on Windows, but both MWHEEL_UP and AXIS_UP can be generated independently on Wayland and macOS. That's why I'm hesitant to make one an alias of the other, since it's technically a reduction in functionality for those platforms. Reconciling the difference between those two names is probably out of scope of this PR.

[1]: https://github.com/mpv-player/mpv/blob/037c7a9/input/input.c#L735-L738

**Comment by haasn** [comment]
Restating my idea here: You could keep MBTN_ID and AXIS_UP as-is and make MWHEEL_UP a “meta-alias” for both. That way there's no reduction in functionality, but MWHEEL_UP still maps to what you'd expect. (But that would require also making sure that both don't get triggered at the same time, thus leading to a doubling of effects)

**Comment by rossy** [comment]
@haasn I just pushed a change that addresses this. AXIS_* is now WHEEL_*, and the mouse wheel on X11 will act as WHEEL_* as long as there are no commands bound to the legacy mouse button keycodes.

**Comment by Akemi** [comment]
> The mouse buttons that correspond to the mouse wheel will still
> generate mouse button keycodes (MBTN_3/4/5/6 and MOUSE_BTN3/4/5/6,) but
> if there are no commands bound to them, they will fall back to commands
> bound to the WHEEL keycodes.

this works as intended, though with `mpv --input-test --force-window --idle` the bindings/fallbacks for the notched wheel are not shown (shown as unbound).

**Comment by wiiaboo** [comment]
Working fine in Windows, using a mouse with frwrd/back + wheel_up/down + wheel_left/right.

**Comment by rossy** [comment]
Ok, so I just pushed a new version of the mouse wheel change.

Implementing a pseudo-alias like @haasn suggested turned out to be pretty complex and my old solution didn't handle key sequences that include WHEEL keycodes. Rather than introduce a whole bunch of complexity into input.c for this niche use case (that probably no-one uses,) I'm starting to think it's better to give up on trying to maintain the old AXIS semantics.

The latest version of this PR makes MOUSE_BTN\*, AXIS_\* and WHEEL_\* _real_ aliases of each other. This means input configs on Wayland and macOS that try to bind different commands to precise and non-precise devices will no longer work. If everyone is okay with this, I'm happy to merge this version.

**Comment by haasn** [comment]
> This means input configs on Wayland and macOS that try to bind different commands to precise and non-precise devices will no longer work. If everyone is okay with this, I'm happy to merge this version.

+1

**Comment by Akemi** [comment]
i personally wouldn't have a problem with that change.

**Pull request merged**
