### PR TITLE
hwtransfer: make probe_formats logging less spammy

### PR DESCRIPTION
**Pull request by llyyr**
[This spams about 2k lines with just `-v` when using hwdec on every new video.
](https://0x0.st/HpEC.txt)

If this is useful then I could also make it print all the supported formats as a comma separated list in one line with MP_DBG, instead of TRACE.

### CODE REVIEW

**Comment by haasn** [comment]
Looking at this list I would honestly suggest just removing the printout altogether, calling `MP_TRACE` O(n^2) times for absolutely no reason is not useful to anybody.

**Comment by llyyr** [comment]
Changed the patch to remove them altogether

**Comment by philipl** [comment]
This logging is actually useful, at least for someone trying to write hwtransfer code (ie: me). You need to know what formats it ends up deciding are supported, and why. Reworking it to print the probe results more efficiently would be great, but yeah, it's actually significant information.

**Comment by llyyr** [comment]
Is it fine if I make it print `  supports gray, gray16, grayf32 ...` in one line for each format then? And change it to DEBUG, instead of VERBOSE?

**Comment by philipl** [comment]
> Is it fine if I make it print `  supports gray, gray16, grayf32 ...` in one line for each format then? And change it to DEBUG, instead of VERBOSE?

Yes, that's fine. Just remember that it does need to actually log separately for each source format, as the set of destination formats can differ each time.

**Comment by llyyr** [comment]
I've changed this again to print with MP_DBG and try to list formats in one line

**Comment by philipl** [comment]
@llyyr thanks for doing this. It still doesn't produce great results with vaapi, because of the various formats that are rejected by the VO - it only prints them on one line if they're all succeeding as we go along.

The overkill way of approaching this is really to accumulate all the successes and failures and then group all input formats that have the same set of available output formats and print those groups. That will minimise the amount of output and maximise clarity. Of course, this is tedious as hell in C...

**Comment by llyyr** [comment]
Yeah, I was trying to avoid going too overkill with this but I'll try to see if I can do that

**Comment by llyyr** [comment]
@philipl I tried to minimize output as much as I could without making it overly complex, I think I'm pretty happy with this now. In the worst case scenario, the most prints I get is about 80 lines with vulkan hwdec, and the vaapi case is improved a lot from the previous iteration of this PR.

**Review by philipl — APPROVED** [review]
Thanks for doing this!

**Pull request merged**
