### PR TITLE
Series of refactors to improve the vo_opengl code layout and reduce overall directory and file size

### PR DESCRIPTION
**Pull request by haasn**
Summary of changes:

1. gl_* files moved to their own sub-dir, with the gl_ prefix stripped
2. The configuration for the "scale-*" options was moved to a macro to reduce the code bloat.
3. Large and (mostly) self-contained sections of gl_video.c moved to their own .c files which simply get imported by the former at the relevant places.

The last one is not the most idiomatic approach, but it's the easiest refactor I could come up with that wouldn't take several hours of refactoring structures, visibility and making all the involved signatures larger and uglier.

This way, they're essentially still part of the self-contained gl_video.c, but at least the files themselves are more manageable.

### CODE REVIEW

**Comment by wm4** [comment]
I'm against splitting the thing by including .c files. It's a big WTF and everyone editing the code will hate you for it. What's even the purpose? Do you have an editor that can't handle larger files? Logically it helps with nothing, because there's no logical separation between them and the files just get concatenated, freely referencing the other "files" without any sort of separation.

**Comment by haasn** [comment]
> What's even the purpose? Do you have an editor that can't handle larger files?

Large files are difficult to work with.

> I'm against splitting the thing by including .c files. It's a big WTF and everyone editing the code will hate you for it.

I'm not sure of a better way to split them up, so if this is a hard no feel free to leave out those three commits.

**Comment by wm4** [comment]
Without a proper split, the moving code around is also pretty pointless.

**Comment by haasn** [comment]
I will give this refactor another try, but this time I'll be slightly less ambitious about moving code out. (eg. by just moving the bulky and self-contained primitives that only need the sc either way)

**Comment by haasn** [comment]
I've given this another go. Does this approach look okay-ish?

Note that video_shaders.c will most likely also be a dumping ground for stuff like super-xbr (if it gets merged upstream), NNEDI3, the debanding shader (which I want to make part of vo_opengl now), and more.

I'll also try to move some of the dither routines and more of the color management helpers there in the future.

**Comment by haasn** [comment]
Another thing I'd like to do is move some of the options out of video.c into video_shaders.c, and simply pass the entire substruct - this could be done eg. for super_xbr-related options, for dither-related options, for debanding-related options and so forth. (And probably some others)

**Comment by wm4** [comment]
Well, ok. I'll merge this in a moment.

**Comment by wm4** [comment]
Is everything ok here? https://github.com/mpv-player/mpv/compare/944fa1214a14%5E...95d5bee832f3

**Comment by wm4** [comment]
Merged.

**Pull request closed without merging**
