### PR TITLE
wayland: cancel prepared reads when no events

### PR DESCRIPTION
**Pull request by kkartaltepe**
A read can be prepared on the wayland display FD that is never actually
read. This occurs when events are triggered on other FDs in the fd set.
This change cancels a prepared read if poll reported no events for it.

This fixes some hangs due to how nvidia's EGL implementation polls on
the wayland fd unlike mesa implementations. It is based on nvidia's
proposed fix for qt's similar message pump in
https://codereview.qt-project.org/c/qt/qtwayland/+/373473

Testing this locally with gnome-shell it resolves issues where mpv
would only update once every second or so if nvidia's egl-wayland
implementation was loaded. Unfortunately it doesnt solve wayland
output not working on nvidia drivers.

Signed-off-by: Kurt Kartaltepe <kkartaltepe@gmail.com>

### CODE REVIEW

**Comment by Dudemanguy** [comment]
Hmm, I think I would prefer a structure like this for this particular part so it stays a simple if/else. The fatal error stuff can be a special case by itself.

```
if (fds.revents[0] & POLLIN) {
    wl_display_read_events(wl->display);
} else {
   wl_display_cancel_events(wl->display);
}

if (fds[0].revents & (POLLERR | POLLHUP | POLLNVAL))
  // fatal error crap here

if (fds[1].revents & POLLIN)
  // wakeup pipe thing

wl_display_dispatch_pending(wl->display);
```

**Comment by kkartaltepe** [comment]
You would prefer for wl_display_dispatch_pending to be called unconditionally? I didnt notice in difference in doing this unconditionally or not so I'm happy to do it, just wanted to make sure.

**Comment by Dudemanguy** [comment]
Yeah, it's harmless and non-blocking. It's probably better to just always try and send events here instead of the current conditional.

**Comment by Dudemanguy** [comment]
Looks good. Thanks!

**Pull request merged**
