### PR TITLE
Appveyor: Use latest build image for fixed MSYS2 installation.

### PR DESCRIPTION
**Pull request by Biswa96**
As MSYS2 installer issues are fixed, remove the workaround from previous commits b8104a013d958e3f177891b22949fc2e66eab955 and ea91162802432aabc8a86216d56223f690e49a67

### CODE REVIEW

**Comment by Biswa96** [comment]
Appveyor CI seems to be disabled for pull requests. Enabling it would may help to check this. Also if developers want to use GitHub Actions only I know some Genie 🧞

**Comment by Biswa96** [comment]
Appveyor CI seems to be disabled for pull requests. Enabling it may help to check this. Also if developers want to use GitHub Actions only I know some Genie 🧞

**Comment by jeeb** [comment]
Looks good to me, will push it to the `appveyor` branch to cause it to run.

**Review by jeeb — APPROVED** [review]
Tested and pushed to master as 5de72613b9cfd0c313a249a332b96eb069dca602 and b95c7dd6cc7fd2edef523c41a7ea2293f4272e35 .

**Comment by jeeb** [comment]
Thank you for the contribution.

**Pull request closed without merging**
