### PR TITLE
[RFC] ytdl_hook blacklist

### PR DESCRIPTION
**Pull request by wiiaboo**
Requested in IRC for sites which youtube-dl seems to have trouble with parsing (private sites with http auth), or, with direct URLs, saving whole 2 seconds.

### CODE REVIEW

**Comment by atomnuker** [comment]
I think every URL ending with a known extension should be blacklisted as well.

**Comment by wiiaboo** [comment]
Would it be safe to assume every url ending in a known extension is handled the same way by all servers? 🤔 
Thinking of stuff like imgur's gifv, for example.

**Comment by wiiaboo** [comment]
Looking at youtube-dl code, they check the mimetype returned by the server so it's likely more accurate than just a hardcoded list of extensions.

**Comment by atomnuker** [comment]
imgur's gifv is not a known extension and is definitely non-standard, so it doesn't count.

**Comment by Hrxn** [comment]
`gifv` on Imgur isn't even an extension at all, just MP4 embed in HTML.

**Comment by wiiaboo** [comment]
I meant as an hypothetical example of what sites can do depending on the extension. Dropbox is another actual example, where ending with a valid extension doesn't necessarily mean it's a direct URL.

**Comment by atomnuker** [comment]
Yeah, I guess its fine as long as you can manually blacklist extensions in the option.

**Comment by wiiaboo** [comment]
Any opinion on:
1. `--ytdl-blacklist` accepting only simple (non-pattern) substrings
2. `--ytdl-blacklist` with simple substrings and `--ytdl-blacklist-pattern` accepting lua patterns
3. `--ytdl-blacklist` accepting only patterns

**Comment by Hrxn** [comment]
Good question, depends on how many real-world use cases can possibly exist, I guess.

Right off the bat, I'd say _1._ is enough, but someone will come and complain sooner or later, I assume..

**Comment by Ulrar** [comment]
What would be the advantage of 2 compared to 3 ? I feel like 3 covers all use cases already, but I might be missing something.

To me 1 is enough (my use case is just blacklisting one specific domain name), but if it's not too much work I'd say patterns cover more uses cases, and would therefore be better.

**Comment by avih** [comment]
> patterns cover more uses cases, and would therefore be better.

While true, it also requires users to use lua patterns syntax, so e.g. `--ytdl-blacklist=youtube.com` doesn't really mean what it seems to mean, since the dot is now a pattern dot (any char) for instance, and I think in lua to use literal dot it's be `%.`.

So IMO if 1 is enough for anyone which wants this feature for now, and 2 can extend 1 while being backward compatible to it, so 1 is a good choice for now and also more accessible to more users IMO. If in the future it turns out that it's not enough, then 2 can be added too for those who need it.

**Comment by wiiaboo** [comment]
I don't expect to be using this feature myself, since I rarely watch URLs that don't need ytdl parsing. I'd personally prefer being able to use patterns.

**Comment by Ulrar** [comment]
Could also be something like --ytdl-blacklist-pattern=true to enable / disable pattern parsing in the blacklist. With a default to false, that would make the option work as expected to anyone without having to know what a pattern is.

**Comment by atomnuker** [comment]
I'm for just always making it accept lua patterns. Most people are just going to copy the examples and modify them.

**Comment by wiiaboo** [comment]
@wm4 any opinion on this? Yes or "no, enough options", and if yes, between these https://github.com/mpv-player/mpv/pull/4583#issuecomment-313878973.

**Comment by wm4** [comment]
Just a pattern option, and as an implicit script-opt would probably be best.

Also maybe it should just try to open the URL with a demuxer first, and if that doesn't work, use youtube-dl. Originally this wasn't done because it seemed architecturally more complex.

**Comment by wiiaboo** [comment]
> Just a pattern option, and as an implicit script-opt would probably be best.

So like it was in the first commit? And document it under --ytdl?

> Also maybe it should just try to open the URL with a demuxer first, and if that doesn't work, use youtube-dl. Originally this wasn't done because it seemed architecturally more complex.

I assume this can't be done in lua only? Unless there's some other hook between `on_load` and `on_preloaded`?

**Comment by wm4** [comment]
> I assume this can't be done in lua only? Unless there's some other hook between on_load and on_preloaded?

Not without considerable work in the C code. If anyone wants to do that, it should probably include some support or at least planning for preloading support.

**Comment by wiiaboo** [comment]
I'll leave that part to someone else, then. I'm still at the "copypaste and tinker a bit" stage with C.

**Pull request merged**
