### PR TITLE
wayland: don't get data device if wl_seat is null

### LINKED ISSUE #7058: core dump when using wayland output and no input devices
### mpv version and platform

Using Arch Linux ARM on a Raspberry Pi 4.

```
$ mpv --version
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Sun Oct  6 21:40:18 UTC 2019
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: n4.2.1
```

### Reproduction steps

do not have a mouse and keyboard attached and run `mpv` within `weston`.

I usually do this over ssh and ensuring that the `WAYLAND_DISPLAY` value is set.

`~/.config/weston.ini`:
```
[core]
require-input=false
idle-time=0

[shell]
locking=false
clock-format=none
background-color=0xFF000000
animation=none
close-animation=none
startup-animation=none
focus-animation=none
```

`~/.config/mpv/mpv.conf`:
```
fullscreen=yes
loop-playlist=inf
input-cursor=no
input-terminal=no
osc=no
osd-bar=no
terminal=yes
input-default-bindings=no
```

### Expected behavior

mpv runs in fullscreen in weston.

### Actual behavior

```
$ ./start
[playlist] Reading plaintext playlist.
Playing: /home/alarm/videos/1.x265.mp4
 (+) Video --vid=1 (*) (hevc 1280x720 24.000fps)
 (+) Audio --aid=1 --alang=eng (*) (aac 2ch 48000Hz)
error marshalling arguments for get_data_device (signature no): null value passed for arg 1
Error marshalling request: Invalid argument
./start: line 16:   469 Aborted                 (core dumped) /usr/bin/mpv --playlist=playlist
```

### Log file

* mpv [log file](https://0x0.st/zxVy.log)
* `WAYLAND_DEBUG=1` [log file](https://0x0.st/zxVv.log)

### Sample files

none required.

### PR DESCRIPTION
**Pull request by Dudemanguy**
Possibly fixes #7058. @syphoxy, does this work for you?

### CODE REVIEW

**Comment by syphoxy** [comment]
I don't have the device directly in front of me right now but I remotely tested it and it does appear to work. I will confirm tomorrow that this patch does indeed work (at least for my purposes).

thanks so much for the swift effort on this bug. much appreciated.

**Comment by Dudemanguy** [comment]
No problem. I use the wayland backend myself very often, so it's good whenever someone finds an issue with it that needs to be fixed.

**Comment by syphoxy** [comment]
just confirmed on the real deal. it works for my purposes.

**Comment by Dudemanguy** [comment]
Awesome, this one can go in then.

**Pull request merged**
