### PR TITLE
vo_gpu/vo_gpu_next: enable gpu shader and icc cache by default

### PR DESCRIPTION
**Pull request by Dudemanguy**

### CODE REVIEW

**Comment by haasn** [comment]
Maybe update manpage?

**Comment by Dudemanguy** [comment]
>Maybe update manpage?

I left the `Normally, shader compilation is very fast, so this is not usually needed.` sentence in the `gpu-shader-cache` section but should that still be there?

**Comment by haasn** [comment]
> > Maybe update manpage?
> 
> I left the `Normally, shader compilation is very fast, so this is not usually needed.` sentence in the `gpu-shader-cache` section but should that still be there?

Looks fine to me now. I mean you're basically saying that you don't need this option if and only if you're using OpenGL, which is true.

**Review by haasn — APPROVED** [review]

**Comment by kasper93** [comment]
This reminds me to look into default cache paths on Windows. Currently it drops everything into config dir, which is suboptimal.

**Comment by Dudemanguy** [comment]
>I mean you're basically saying that you don't need this option if and only if you're using OpenGL, which is true.

Thanks, that was my understanding as well.

**Comment by kasper93** [comment]
> Could copy what QT does? I think they have document somewhere.

I have an idea where the files should go, just need to spend few minutes to point mpv to right place.

**Comment by Jules-A** [comment]
I literally just enabled the shader cache yesterday and found that it fixed the long startup times I was getting in gpu-next.
>It mostly matters for GPU APIs that require internally recompiling shaders to other languages, for example anything based on ANGLE or Vulkan. 
I was using D3D11 so this is a little confusing to me :/

**Comment by kasper93** [comment]
> So that means that any change to the code requires a new cache file (delete the previous one and create a new one)?
> At which point can one cache file be outdated?

No, not every code change of libplacebo would invalidate cache. Shaders are cached individually and program cache would be invalidated if the shader code changes. Also in libplacebo every API change clear cache, as a way to not let the cache to grow in size with old cached code.

So in practice it is cleared quite often, depending how frequently you updated libplacebo, it is likely to clear on every update. But you don't have to worry about it as it is done automatically and doesn't require any manual intervention.

**Pull request merged**
