### PR TITLE
options: rename subtitle options

### PR DESCRIPTION
**Pull request by DanOscarsson**
Rename the text subtitle options from --sub-text- to --sub-
and --ass- options to --sub-ass-.
The intention is to common sub options to prefixed --sub-
and special ASS option be seen as a special version of sub options.
The OSD options that work like the --sub- options are still named
--osd-.
Man page updated including a short note about renamed --sub-text-*
and --ass-* options to --sub-* and --sub-ass-*.

### CODE REVIEW

**Comment by wm4** [comment]
I'm still ok with this.

Comments from anyone else?

**Comment by wiiaboo** [comment]
There's still references to `--sub-text-*` that weren't changed:
DOCS/man/options.rst:1493:        rendering. Use with care, or use ``--sub-text-font-size`` instead.
DOCS/man/options.rst:1534:        rendering. Use with care, or use ``--sub-text-margin-y`` instead.
DOCS/man/options.rst:1602:    :force: Try to force the font style as defined by the ``--sub-text-*``
DOCS/man/options.rst:1711:    as specified by the ``--sub-text-`` options instead.
DOCS/mplayer-changes.rst:269:    ``-subfont-*``              ``--sub-text-*``, ``--osd-*``
DOCS/mplayer-changes.rst:271:    ``-subfont``                ``--sub-text-font``

DOCS/man/mpv.rst:146:    ``--ass-style-override`` for more info.
DOCS/man/mpv.rst:150:    ``--ass-vsfilter-aspect-compat`` for more info.

**Comment by DanOscarsson** [comment]
Hope I have fixed all places with --ass/--sub-text now.
I also added in mplayer-changes that sub-text-* is now -sub-*

**Comment by wm4** [comment]
Still missing interface-changes.rst.

**Comment by DanOscarsson** [comment]
Missed that there was one file for interface changes too. Fixed.

**Comment by wm4** [comment]
Merged, also had to throw in my own fixup commit.

**Pull request closed without merging**
