### PR TITLE
sub/lavc_conv: don't strip ASS style header

### PR DESCRIPTION
**Pull request by kasper93**
This fixes converted subtitles that are styled.

This reverts commit 5e2c211a4e1d67748348295b191acb2dfb76d024.

Most of the subtitle decoders in libavcodec sets meaningful style values. For the rest we can conditionally strip style.

### CODE REVIEW

**Comment by kasper93** [comment]
I need opinion about this one, because the unconditional style strip breaks subtitles, but at the same time I understand that in some cases we may want to use out `Default` style for text.

`AV_CODEC_ID_DVB_TELETEXT` is pretty nice, because it appends own style `Teletext` and `Subtitle`. So we could override `Default` with our style. But more commonly subtitle decoders just use `Default` for everything, even though they define format specific options/styles. `AV_CODEC_ID_ARIB_CAPTION` is such example. Many others do some small format specific modifications, if the format provide some information. But they seem to use `Default` and well, many of default style would be inherited.

We could have a list of formats that are allowed to inject style. We could have an option to control that. We could have smarter way of merging style.

Thoughts?

**Comment by kasper93** [comment]
Converting to draft, because this doesn't fully unbreak subtitles, there are a lot of overrides when `converted` is true.

**Comment by DanOscarsson** [comment]
There are unfortunately many uses of "subtitles".
For example, teletext can be used to present pages of text like your example, but also to present normal subtitles. When used to present normal subtitles positioning and styles should be removed.
My experience shows that the absolute majority of all subtitles are for texting of speech (and song), most often in form of .srt data.
There are also additions of SDH data (unfortunately not marked in .srt) and positioning like used with .ass for anime to show things like translation of signs.
Then some people have good sight and can easily read text anywhere, others need text show in expected places and suitable fonts and sizes.
I have also seen converted subtitles from one format to ".srt" including things that should not be there like .ass positioning.
There exists subtitle files where users have done a lot of work to make them good, but the majority is just to make normal subtitles for speaking.
Basically I think the normal subtitle handling in mpv should be for normal subtitles and they should be presented as the user wants, not the creator of the subtitles.
This means that attributes like those available in .srt, like colour, bold and italic are ok. But font, font size, positioning and alignment must follow the users preferences.
In my version of mpv the default for subtitles is that all non .srt attributes are stripped from the subtitles (due to some converters adding bad things) and my preferences are applied so subtitles are shown in a way I can easily read.
That should be good for the majority of all people.
For some, like those wanting to see teletext pages or anime, they can have an option to enable that. I cannot see that you can detect what is correct by looking at the subtitle file. For example a teletext file or an .ass file can be for only subtitles and should then have all positioning and other user disturbing things removed.
At least we need an option given a choice between "show normal subtitles" and preserve non subtitle attributes (like positioning, size changes, etc). There may be more choices needed.

**Comment by kasper93** [comment]
> There are unfortunately many uses of "subtitles".

I fully understand and that's why I'm uncertain what to do here. Because I think conceptually we should respect the upstream styling, because it may convey important information like in Teletext case and similar, where positioning for example is there or style in general.

But for generic subtitle conversion, which uses "default" lavc style, it is certainly not desirable to use it.

Actually what would be best is to have ability to set all parameters of default style in lavc subtitle decoders. So it would use the one configured in mpv, unless specific decoder overrides it. We cannot do now and we also don't have information from the decoder if the style is actually relevant or just some placeholder.

Right now to avoid modifying upstream lavc, I'm leaning to add `--sub-respect-lavc-style` or something similar. That can be used in case decoder style make sense.

> For example, teletext can be used to present pages of text like your example, but also to present normal subtitles. When used to present normal subtitles positioning and styles should be removed.

Teletext decoder is actually quite good in what it does. It provides separate style for teletext pages and subtitles. So it is easy to differentiate what we are working with, but unfortunately this is not true for all other subtitle decoders.

```
[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,16,&Hffffff,&Hffffff,&H0,&H0,0,0,0,0,100,100,0,0,1,1,0,2,10,10,10,1
Style: Teletext,Monospace,11,&Hffffff,&Hffffff,&H0,&H0,0,0,0,0,160,100,0,0,3,0.1,0,5,1,1,1,0
Style: Subtitle,Monospace,16,&Hffffff,&Hffffff,&H0,&H0,0,0,0,0,100,100,0,0,1,1,1,8,48,48,20,0
```

**Comment by kasper93** [comment]
I decided to preserve style only for `AV_CODEC_ID_DVB_TELETEXT`, if other providers have meaningful styling it can be extended.

**Comment by kasper93** [comment]
Let's gather feedback on this, we can always fix in case of issues.

**Pull request merged**
