### PR TITLE
ci/mingw: remove cache

### PR DESCRIPTION
**Pull request by kasper93**

### CODE REVIEW

**Review by sfan5 — APPROVED** [review]
macOS isn't exactly a good example of a non-slow build but whatever

**Comment by sfan5** [comment]
Alternatively maybe we could incorporate a date into the cache key so that everything is automatically rebuilt every week. If you just want to quickly check something waiting 30m for mingw results can be quite annoying.

**Comment by kasper93** [comment]
> Alternatively maybe we could incorporate a date into the cache key so that everything is automatically rebuilt every week. If you just want to quickly check something waiting 30m for mingw results can be quite annoying.

I would like to have CI validate current status and flag PR before getting merged. So building current master, especially of libplacebo, but also ffmpeg is nice.

Proper solution would probably to compute cache hash based on dependencies version/git hash. So we can skip rebuilt if we are up to date and only do clone. But I'm not sure how to do it nicely. I have some idea, but it would require a lot of changes to make it work.

> If you just want to quickly check something waiting 30m for mingw results can be quite annoying.

Agreed. fwiw, for quickly check other build should finish sooner.

For me more annoying are sporadic failures... Either the macos build fails or msys2 due to https://github.com/msys2/MINGW-packages/issues/11864 It is really like playing bowling, you need to have a little luck to get them all ;p

**Comment by sfan5** [comment]
> Proper solution would probably to compute cache hash based on dependencies version/git hash that are currently built.

It's easy to do the conditional caching for everything: https://github.com/actions/cache#creating-a-cache-key
Could adjust the script to always rebuild ffmpeg and libplacebo then.

> For me more annoying are sporadic failures... Either the macos build fails or msys2 due to msys2/MINGW-packages#11864 It is really like playing bowling, you need to have a little luck to get them all ;p

Agreed.

**Pull request merged**
