### PR TITLE
Improve osc title readability

### PR DESCRIPTION
**Pull request by wiiaboo**
### bottombar/topbar change
before:
image
after:
image

---

#### before
image
after:
*until 100 chars*
image
after 100 chars:
image

### CODE REVIEW

**Comment by wm4** [comment]
Would it be possible to do an alpha fade? Doesn't require knowing the length of text, and looks not too bad.

Example on chromium: https://0x0.st/OlW.png

**Comment by wiiaboo** [comment]
Probably, but ASS doesn't have a native way to do gradients.

**Comment by ChrisK2** [comment]
Why don't you add the ellipsis on top of the squeezing?

**Comment by wiiaboo** [comment]
>Why don't you add the ellipsis on top of the squeezing?

Fine with that too.

**Comment by wiiaboo** [comment]
No perfect way to ellipsis, but I'd compromise on this:
image
image
image

**Comment by wiiaboo** [comment]
Or with higher max stretching:
image
image
image
With Ubuntu Medium:
image

**Comment by ChrisK2** [comment]
looks okay

**Pull request merged**
