### PR TITLE
DOCS/compile-windows.md: update msys2 instructions again

### PR DESCRIPTION
**Pull request by kevmitch**
they keep changing things. . .

### CODE REVIEW

**Comment by wm4** [comment]
Fine with me...

**Comment by kevmitch** [comment]
On hold until msys2 updates their installer so that consistent instructions can be given both before and after initial update.

**Comment by rossy** [comment]
The new installers are (finally) up on https://msys2.github.io/, so it might be okay to merge this. I haven't tried them out yet.

**Comment by kevmitch** [comment]
merged

**Pull request closed without merging**
