### PR TITLE
vaapi-wayland: clean up code

### PR DESCRIPTION
**Pull request by boxerab**
1. Remove sync/desync calls in resize.  The resize() method only changes the subsurface's position, which is always synchronized with the parent surface. Reference:
https://wayland-book.com/surfaces-in-depth/subsurfaces.html

2. Only need to attach solid buffer once to main surface, on creation.

### CODE REVIEW

**Comment by boxerab** [comment]
@Dudemanguy do you have time to review ?

**Comment by Dudemanguy** [comment]
Could you abbreviate the commits with `vo_vaapi_wayland:`?

**Comment by Dudemanguy** [comment]
Makes sense. The subsurface is initially synchronized so we don't need this. Thanks!

**Comment by boxerab** [comment]
great, thanks!

**Pull request merged**
