### PR TITLE
vf_vapoursynth: remove excessive locking when reading/writing frames

### PR DESCRIPTION
**Pull request by chainikdn**
Single-threaded data copying becomes a real performance bottleneck in case of 4K, especially with 10 bit color depth and high frame rates.

I agree that my changes can be relicensed to LGPL 2.1 or later.

### CODE REVIEW

**Comment by chainikdn** [comment]
Not so sure about 2nd one (writing), because we probably need to protect "img" from being deleted from "p->buffered". Anyway it works in real tests w/o crashes.

**Comment by chainikdn** [comment]
Somebody please take a look! W/o this one it's impossible to watch 4K/10bit with a real time motion interpolation.

**Comment by jeeb** [comment]
@chainikdn sorry for not being able to get to this earlier, but since you're a first time contributor could you please add the note to your PR that you agree with the licensing? See https://github.com/mpv-player/mpv/blob/master/.github/PULL_REQUEST_TEMPLATE  for the sentence.

**Comment by chainikdn** [comment]
@jeeb first message edited

**Comment by jeeb** [comment]
Thanks.

**Pull request merged**
