### PR TITLE
audio: report EOF also for untimed AO mode

### PR DESCRIPTION
**Pull request by kasper93**
Example file [ao-eof.zip](https://github.com/mpv-player/mpv/files/15268562/ao-eof.zip)

### CODE REVIEW

**Comment by kasper93** [comment]
@ruihe774 @na-na-hi Thoughts?

**Comment by ruihe774** [comment]
Will frame of type EOF be signaled to ao?

**Comment by kasper93** [comment]
> Will frame of type EOF be signaled to ao?

This is different case than the other one, we basically fail to stop playback after error.

**Comment by ruihe774** [comment]
> > Will frame of type EOF be signaled to ao?
> 
> This is different case than the other one, we basically fail to stop playback after error.

Ok then.

**Comment by kasper93** [comment]
I'm merging this, feel free to report if anything is not working correctly. I will think about solutions, but this exception for untimed AO here doesn't make much sense.

**Pull request merged**
