### PR TITLE
os x: handle multiple dropped files on the window

### PR DESCRIPTION
**Pull request by Nyx0uf**
Should fix a part of : https://github.com/mpv-player/mpv/issues/3076

### CODE REVIEW

**Comment by wm4** [comment]
What happens in cocoa if memory allocations fail?

**Comment by Nyx0uf** [comment]
You mean for the `NSMutableArray* ar = [[NSMutableArray alloc] init];` line ?

`ar` will be `nil` so ultimately we will pass nil to the adapter, should not crash.

**Comment by wm4** [comment]
Well, as long as such possible failures are somehow taken care of.

**Comment by pigoz** [comment]
You have to release or autorelease `ar`. Like this the code would be leaking.

**Comment by Nyx0uf** [comment]
Ohhh still no ARC ?

**Comment by pigoz** [comment]
Nope, no ARC!

**Comment by wm4** [comment]
Merged, with the two new commits squashed.

**Pull request closed without merging**
