### PR TITLE
wayland vo: various fixes for paused rendering

### PR DESCRIPTION
**Pull request by mahkoh**
Commit 1 fixes

https://user-images.githubusercontent.com/1882250/152243424-d8685ef2-d175-4d06-a3d8-6da52c167a8e.mp4

Commit 2 fixes

https://user-images.githubusercontent.com/1882250/152243454-2b2b54e6-61f4-40bf-a4a6-0d3e75813101.mp4

### CODE REVIEW

**Comment by Dudemanguy** [comment]
Unfortunately, not always swapping breaks `display-resample` when the window is hidden. Even though the swap interval is 0, we still rely on the compositor to send events and poll it. I'm not sure what exactly the underlying semantics of swap buffers is in wayland-world in the paused case. My guess is that the `wl_surface`'s pending state and applied state are exactly the same (the surface is always double buffered I believe). So the swap should just do nothing (I think). The second commit looks good and seems logically correct though. FWIW, I'm not actually able to reproduce either of your two examples (also on sway).

**Comment by mahkoh** [comment]
>Unfortunately, not always swapping breaks display-resample when the window is hidden.

How would I reproduce this? Maybe I can find a way to make it work.

>So the swap should just do nothing (I think). 

It's more of a question of what `eglSwapBuffers` does. The vulkan backend does not have this problem.

As far as I understand it, we always recreate the egl swapchain after receiving a resize event. At this point, the contents of the swapchain are obviously undefined garbage. If we then don't render to, let's say, the first image in the swapchain, calling `eglSwapBuffers` will obviously put garbage on the screen. This should have nothing to do with wayland. The only place where wayland comes into play is that only on wayland (I haven't checked X11) we sometimes don't render the image.

>FWIW, I'm not actually able to reproduce either of your two examples (also on sway).

I'm currently writing a new wayland compositor. I cannot reproduce the problem in sway either. I believe this is because sway buffers resize events. That is, if the window is rapidly resized, wayland will only send a resize event once ever N milliseconds. So far, my compositor sends resize events as fast as they happen, that is, as fast as it sends all other kinds of mouse movements. This will cause mpv to recreate the swapchain an order of magnitude more often than it would with sway. This exposes the problems with the current `hidden` logic since it causes mpv to submit new buffers an order of magnitude more frequently than with sway, therefore far exceeding the refresh rate of the monitor.

Since the bug doesn't exist with the vulkan backend and chromium and all other applications that I have tested seem to work fine, I believe that this is not a bug in my compositor.

**Comment by mahkoh** [comment]
I believe that there is no problem on vulkan because https://github.com/mpv-player/mpv/blob/899850bedc95751f224da36e7d02bb8fab33909a/video/out/vulkan/context.c#L251-L252 is called only after the `hidden` check. So if we don't render, then we also don't move to the next image in the swapchain. Therefore, calling `pl_swapchain_submit_frame` should indeed be a no-op as you said.

On the egl side, I believe that `eglSwapBuffers` unconditionally moves to the next image in the swapchain. And since this function is called unconditionally, the problem occurs.

**Comment by Dudemanguy** [comment]
>How would I reproduce this? Maybe I can find a way to make it work.

If you use `--video-sync=display-resample` and then move the window out of view, the audio/video sync should go completely out of whack if you don't use eglSwapBuffers.

>Since the bug doesn't exist with the vulkan backend and chromium and all other applications that I have tested seem to work fine, I believe that this is not a bug in my compositor.

Oh yeah I don't disagree with you there. It should be an mpv bug.

>On the egl side, I believe that eglSwapBuffers unconditionally moves to the next image in the swapchain. And since this function is called unconditionally (whether we rendered or not), the problem occurs.

I think I see the issue. The wayland egl external swapchain implementation omits `ra_gl_ctx_submit_frame` completely for some reason. Probably if that piece is added and it simply doesn't submit the next frame, I think the rest of mpv's existing logic should work correctly. I can open up a PR for that bit if you don't want to dig through mpv internals yourself (or if you want to do it yourself I won't stop you heh).

**Comment by mahkoh** [comment]
>If you use --video-sync=display-resample and then move the window out of view, the audio/video sync should go completely out of whack if you don't use eglSwapBuffers.

I tested it with two files but I couldn't reproduce it. With one of the files I kept the video hidden for 5 minutes but it was still in sync. This was with sway.

>I can open up a PR for that bit 

That would be great.

**Comment by Dudemanguy** [comment]
>I tested it with two files but I couldn't reproduce it. With one of the files I kept the video hidden for 5 minutes but it was still in sync. This was with sway.

In my case with the first commit, it happens instantly. This is on amdgpu. I think intel behaves the same way.

**Comment by mahkoh** [comment]
Curious. Can you link me a video with which it happens?

**Comment by mahkoh** [comment]
Ok I can reproduce it when I start sway from a VT.

**Pull request merged**
