### PR TITLE
x11: support xorg present extension

### PR DESCRIPTION
**Pull request by Dudemanguy**
The xorg present extension is extremely similar to wayland's presentation time protocol (or I guess it's probably the other way around given that the xorg one came first). So the first commit refactors the wayland's internal implementation into its own separate code that can be used by both wayland and X11. The second commit is the actual implementation of it. In theory, it could be nicer to use xcb and get the information in an async manner like wayland does instead of using xlib, but maybe we'll save that for another day since this is simple and works. The actual main advantage of this is that x11vk now supports presentation feedback (as well as all the the other x11 VOs but those are not really meant to be used). `vo_vdpau` was left out of this since it's surprisingly complicated and I have no way to test it.

This also completely replaces the `oml_sync` stuff (only used by x11 egl/glx) so it is removed.

### CODE REVIEW

**Comment by DanOscarsson** [comment]
Interesting. I have missed that there was a present extension to X11.
vdpau have had preset information since the beginning and I have always used it in my code (wm4 wanted his own implementation so it never got added).
As vdpau returns when a frame was display one can also detect it a frame was display on wrong vsync.

In my code the vo should have two things: the vsync interval (i.e. the time between two vsyncs) and time of a resent vsync (need not be the last one). I have them as atomic variables on the vo for easy access. With these two mpv can schedule display of frames on best vsync and easily sync audio to video.
Slightly different way compared to what is used in standard mpv but I have used my code longer then mpv as I also had it in mplayer, and it works very well.
So I still prefer to use vdpau as there you can schedule frames for display on a vsync and get feedback when they were displayed (and correct when display system failed to display frame on intended vsync). Unfortunately vulkan have not yet gotten a presentation extension added.
To get vsync data from vdpau you just read the presentation info available on a queued frame when it has been displayed.

**Comment by Dudemanguy** [comment]
Thanks for the information! So yeah it does look like `vo_vdpau` has its own presentation stuff in it that is already used. In that case, there's no need to touch it.

>Unfortunately vulkan have not yet gotten a presentation extension added.

This was my main motivator for writing this heh. I was annoyed that opengl had presentation feedback on x11 but not vulkan. The wayland code fixes this by using its own present protocol, and there's no reason why xorg can't do exactly the same. For whatever reason, barely anyone actually uses this but it's been around for as long as DRI3 (strictly speaking: libxpresent came like a couple of years later but still).

**Comment by DanOscarsson** [comment]
One other thing you might think about for the future.
Unless I am wrong mpv outputs first video frame and after that gets the time for the vsync.
In my code I get the time of the vsync before first frame in the video is output.
This way I can plan when to output first video frame and audio frame so they start in sync.
In my mpv code for vdpau I do it by having vdpau at init output a blank minimal frame and wait for it to be presented to get the time of the vsync. For other X11 vo I create a thread with an opengl context that uses the old extension to wait on vsyncs. That thread will the record time of each vsync if receives. During vo init when the thread is created the vo will wait until first vsync before returning from init.
So in both cases my code, for a X11 vo, will start with time of a recent vsync and the interval between two vsyncs.

Maybe that could also be used in the normal mpv to enhance audio/video sync handling.

**Comment by Dudemanguy** [comment]
Yup, that's correct. The presentation feedback times in mpv always operate after the fact. This is why the first few frames are always technically a bit out of sync before it "adjusts" to the correct timings. Xorg's present extension does support sending a pixmap at a target msc or ust so this is theoretically possible. Mesa uses it actually. Wayland has no such mechanism. It only gives you information after the presentation has occurred.

**Comment by Dudemanguy** [comment]
I thought about it and decided the original implementation was unnecessarily complicated. I made it much more simple just now.

**Comment by DanOscarsson** [comment]
I see that vsync_duration is calculated from present data.
Does not VOCTRL_GET_DISPLAY_FPS return better value?
In X11 is uses xrander data and is quite good. For wayland I have no knowledge how good the value is.
vsync_duration can be calculated from display fps and is not dependent on present data. So present handling could focus on just returning a good data on when a vsync occurs.
In my code I have used the display fps for many years and it works fine for me.

**Comment by Dudemanguy** [comment]
The vsync duration here is basically the delta between presentation events (wm4 was the one who originally wrote this calculation). It should be better than relying on the display fps.

**Comment by DanOscarsson** [comment]
Actually I started with delta but as it took several presentation values before I got a stable value, I found that getting the reported refresh rate from the graphics card was better/stabler. That is on my system with X11. Other operating systems or display systems may do it differently.

**Comment by Dudemanguy** [comment]
Well in practice here, there's not really a difference since it just evaluates to the display fps anyway. In theory, the ust/msc calculation could account for slight fluctuations but I doubt that would happen beyond like changing the output mode during playback (but of course the windowing backend takes that into account anyway). As a plus, this method doesn't require you to pass a separate display fps value. Just ust/msc. There is a refresh_interval in here, but that is wayland specific and not even used in this. I probably should just stick it somewhere else.

**Comment by Dudemanguy** [comment]
Just an FYI, this apparently behaves badly on NVIDIA (thanks guys...). Blocked until I figure out the right way to deal with that.

**Comment by Dudemanguy** [comment]
Used randr to determine what the drivers (or well providers) are and specifically excluded nvidia so this should be OK. With this PR though, the CI needs to install libxpresent otherwise it doesn't actually build x11 (would add it in another commit but the CI is currently broken for other, unrelated reasons...).

**Comment by Dudemanguy** [comment]
This one should finally be all OK now.

**Comment by DanOscarsson** [comment]
When you have nvidia you could do like I do in my mpv patches.
Create a thread using GLXGetVideoSyncSGI and GLXWaitVideoSyncSGI looping
for ever getting the vsyncs and recording when they occur.
I do that for all non vdpau vo which are using X11 and I have not had any
problems with it.

**Pull request merged**
