### PR TITLE
Shader for barrel distortion of Oculus Rift DK2 (GLSL)

### PR DESCRIPTION
**Pull request by masand**
This is the try to move the changes I had in a previous pull request to the
GLSL. The shader is working, and you could watch a 3D side by side movie
this way, but there are some issues:
- mirroring effects (see below)
- Chromatic Aberration is not taken care of (maybe this can be derived from
  the original libOVR shader in the future)
- personal eye distance is not configurable
- For me the shader seemed to fit best to the scaling shaders - but I´m not
  sure whether it should be placed somewhere else maybe
- Also I´m not sure whether the GLSL code could be optimized

The mirroring effects are the most disturbing issue for me at the moment.
I don´t really understand why they appear at some places, but not at all.
Please see the picture for details, I put different colors in the output for
the different checks, and put some numbers into the areas for better
explanation.
So the checks in the code at the end of pass_sample_riftdk2 raise some
questions:
(startx and stopx are set depending on whether we are on the left or right 
side of the image - as we are working with side by side videos here...)
- the check "newx < startx" does make the area 4 purple, but:
- the same check does _not_ make area 6 purple, we see a mirrored image
  there
- the check "newx > stopx" does work fine for the left and right half of the
  image, in contrast (area 3 and 5 are red)
- the check "newy > 1.0" works fine and give area 7 a green color.
- the check "newy < 0.0" does not seem to work at all in contrast. Areas 1,
  2 and 8 should be cyan, but the also show a mirrored image.

Any help here is appreciated :-)
screenshot_gl_riftdk2

### CODE REVIEW

**Comment by haasn** [comment]
Are you sure the upscaler is the right place for this? Personally I would have made it a GLSL shader in the style of ```post-shaders```.

**Comment by wm4** [comment]
>Are you sure the upscaler is the right place for this?

I suppose it could do some fancy resampling in theory.

>I never intended to suggest this should be part of the mpv source code.

This would be fine, if we had a good way to modularize gl_video.c, which is a bit too monolithic right now.

**Comment by haasn** [comment]
> I suppose it could do some fancy resampling in theory.

This can be done in theory, indeed. That might actually be a good way to merge the two concepts and keep it in-source, while allowing us to use the actual resamplers to sample the pixels accurately (no aliasing artifacts).

Basically it would mean transforming source_pos before calling the usual scaler routine. It wouldn't replace ewa_lanczos etc., but rather it would tell ewa_lanczos etc. which pixels to sample from.

That way we can get actual GPU-tier deformation quality, ie. the thing EWA was actually developed for.

(It probably wouldn't work with separated scaling at all, though, meaning yet more special cases in the scaler configuration logic.. ugh)

**Comment by masand** [comment]
Sorry, I couldn´t find out what you mean with "post-shaders"? Is it possible to give a "user" shader to mpv from command line input/a file?

**Comment by haasn** [comment]
Yes, but this functionality is currently sitting in a branch. You can try it out in https://github.com/haasn/mpvhq for now.

(See the documentation for the “post-shaders” option, present in that version)

**Comment by masand** [comment]
Ok. I got it working with that branch and the post-shader option.
What would you propose to do now? Open an own git repository and maintain the shader there?
(still facing the mirroring problems as described above, by the way. Any help is welcome :-) )

**Comment by haasn** [comment]
Three options:

1. Maintain your own git repo and link to it from the wiki.
2. Paste it as a gist and link to it from the wiki. (Arguably a special case of 1)
3. If it's usable and polished enough, (eventually) submit it for contribution to TOOLS/glsl (or similar).

**Comment by wm4** [comment]
So what's the status?

By the way, the user shaders got merged into mpv proper.

**Comment by masand** [comment]
Lost the time for further development:-(

Tested the user filter it was Wirkung

But no time for setting up an own gut project/repository

Am 9. Juni 2015 22:11:00 MESZ, schrieb "V. Lang" <notifications@github.com>:

**Comment by wm4** [comment]
What do we do with this?

**Comment by masand** [comment]
I added a github repository for the shader: https://github.com/masand/mpvrift
-> Please close this pull request

**Comment by haasn** [comment]
>  What do we do with this?

I plan on getting a VR headset. When I can test it, I'll think about maybe merging it in with upscaling (for quality).

**Comment by wm4** [comment]
Closing then. You can add a link to the shader here, if you want: https://github.com/mpv-player/mpv/wiki/User-Scripts#pixel-shaders

**Pull request closed without merging**
