### PR TITLE
m_option: add print callback to color type

### PR DESCRIPTION
**Pull request by occivink**
This lets script query the value of 'background' and similar properties

I agree that my changes can be relicensed to LGPL 2.1 or later.

### CODE REVIEW

**Comment by wm4** [comment]
(Wouldn't it be better to use hex formatting? But I don't mind.)

**Comment by wiiaboo** [comment]
Maybe pretty-print as hex and `${=` as float?

**Comment by occivink** [comment]
Printing as hex probably makes more sense, yes. 
I don't really have an opinion on other formats but I don't think having multiple representations is too useful in this case.

**Comment by wiiaboo** [comment]
Hex representation is probably more useful for scripts (at least the ones that then use it with libass), so sure.

**Comment by wm4** [comment]
(I like that better, also maybe break on 80 cols.)

**Comment by occivink** [comment]
Break narrowly avoided

**Pull request merged**
