### PR TITLE
mpv_talloc.h: rename from talloc.h

### PR DESCRIPTION
**Pull request by czarkoff**
This change helps avoiding conflict with talloc.h from [libtalloc](https://talloc.samba.org/), which is dependency of samba at least on OpenBSD. To date this issue was being solved in port by prepending `CFLAGS` with `-I. -I..`, so that `talloc.h` in root of mpv distribution was picked before `talloc.h` from system include directory.

### CODE REVIEW

**Comment by wm4** [comment]
What is this needed for? Either the include directories are setup correctly, then nothing needs to be done. Or it's broken, then it should be fixed.

**Comment by czarkoff** [comment]
OK, I see the issue now. By default waf doesn't add `-I/usr/local/include` to `CFLAGS`, so I have to pass it through environment. That gets prepended to effective `CFLAGS`, so `talloc.h` is found in `/usr/local/include/talloc.h` instead of `${top_dir}/include`. So my issue should probably be fixed by forcing waf into prepending flags to `CFLAGS` from environment instead of appending them.

That said, shadowing well-known header files is a bad habbit, so I would still suggest to pull this commit.

**Comment by wm4** [comment]
It can happen with any other header file that has a somewhat generic name, so I'm not interested in that.

What we should do is finishing renaming all talloc calls to ta, but that's a bit more work.

**Comment by wm4** [comment]
Applied it anyway, since there's no reason not to.

**Pull request closed without merging**
