### PR TITLE
path-win: refine state and cache location

### PR DESCRIPTION
**Pull request by kasper93**

### CODE REVIEW

**Comment by Dudemanguy** [comment]
If you're moving watch later to `%LOCALAPPDATA%/mpv` wouldn't that mean that everything ends up the `watch_later` subdirectory in there? If you put the cache in a subdirectory as well, then that would mean %LOCALAPPDATA%/mpv would have nothing but two directories in it. I mean I don't really care either way, but I just wanted to make sure that's what you really intended.

The path changes should be documented (`mpv.rst`) though.

**Comment by kasper93** [comment]
> then that would mean %LOCALAPPDATA%/mpv would have nothing but two directories in it.

Yes.

```
mpv
├── cache
│   ├── AF98941730CC5CA0
│   └── libplacebo.cache
└── watch_later
    ├── 28320DEB36A755D70BB48CEDEE643D7C
    └── AFF05D9D25056DA09182CDD401983CCC
```

If we have a directory with undefined number of files created (and without meaningful filenames), they should have own directory to encapsulate them. What if I want to remove only cache or watch_later?

If we are talking single files, with descriptive name like `libplacebo.cache` it could go into root mpv dir. But since vf=gpu spams files, it deserves directory to contain them. Also if 'state' dir is used for anything more, it will not conflict with existing files.

> The path changes should be documented (mpv.rst) though.

Added a note about that.

**Comment by Dudemanguy** [comment]
I guess this should probably be mentioned in `interface-changes.rst` changes too.

**Comment by kasper93** [comment]
> I guess this should probably be mentioned in interface-changes.rst changes too.

Added entry about change from `%appdata%` to `%localappdata%`, because this changes behavior. For cache subdirectory, I think it is a detail not worth mentioning there. Would you agree?

**Pull request merged**
