### PR TITLE
[DO NOT MERGE] ci/mingw: add librempeg builds

### PR DESCRIPTION
**Pull request by kasper93**
Librempeg is a fork of FFmpeg from @richardpl with improvements mostly in audio filtering, but also in other parts. See comment [1] for the short summary of the changes.

[1] https://github.com/librempeg/librempeg/issues/12#issuecomment-2388310100

### CODE REVIEW

**Comment by kasper93** [comment]
> Other (overlapping) sources of fixes to ffmpeg that i know users would benefit from.

Those are builders, I'm not interested in random patches, which should have been sent upstream instead. Librempeg is maintained and regularly updated.

**Comment by kasper93** [comment]
Rejected on IRC. Build it yourself if needed.

**Comment by richardpl** [comment]
Can I use this in my own fork of mpv*someting to provide mpv builds with librempeg? Because Last time I tried I failed miserably to create one...

**Comment by kasper93** [comment]
> Can I use this in my own fork of mpv*someting to provide mpv builds with librempeg? Because Last time I tried I failed miserably to create one...

Sure.

**Pull request closed without merging**
