### PR TITLE
command: demuxer-ahead-duration property

### PR DESCRIPTION
**Pull request by xylosper**
Approximate aheaded time in demuxer, in seconds. This is similar with
`demuxer-cache-duration` but returns duration measured from current
`time-pos`. Also, this property returns remaining time after bufferred
data in demuxer reach end-of-file.

The problem of `demuxer-cache-duration` is there's no way to figure out where the reported timestamp starts from. Also, once cache reaches eof, `demuxer-cache-duration` just returns 0.
This property is useful, for instance, to indicate current filled demuxer time in time slider in GUI.

### CODE REVIEW

**Comment by xylosper** [comment]
Sorry, I've overwritten the intial commit with -f so maybe you can't see the comment any more?
I copy yours and mines here:

--

wm4:
This will make it return -1 instead of 0. Also, AFAIK the EOF flag can be set if the demuxer reaches EOF, even if there's still queued unplayed data between player and demuxer. So I'm not sure if this is right at all?

xylosper:
Oops, my mistake. the documentation was outdated.
I used -1 to indicate eof. I though it's more useful to notify eof state instead of remaining time in eof state because one can easily calculate remaining time but cannot figure out cache is eof or not.
I want to update documentation instead of fixing return value for eof, if you don't mind.

--

wm4:
The property needs to be added to MPV_EVENT_TICK as well, because it depends on the current playback time.

xylosper:
Ah, yes, you're right. And in that case, I didn't need to add cache_eof flag to notify eof state...

**Comment by xylosper** [comment]
I'm confused a bit for notification.
When this property depends on MPV_EVENT_TICK, does it still need to depend on MPV_EVENT_CACHE_UPDATE?

**Comment by wm4** [comment]
I don't like that it returns -1 in some special cases. MPlayer was full of this stuff, and I've been trying to get rid of it (e.g. by replacing magic values in options with choices).

Again, when the demuxer reaches EOF, nothing changes about the fact that there's still data queued between decoder and demuxer. So I see no point in doing something special here.

>When this property depends on MPV_EVENT_TICK, does it still need to depend on MPV_EVENT_CACHE_UPDATE?

Yes, MPV_EVENT_TICK is not sent every playloop iteration. So if playback is paused, and the cache adds more data or so, something still needs to update it.

**Comment by xylosper** [comment]
> I don't like that it returns -1 in some special cases. MPlayer was full of this stuff, and I've been trying to get rid of it (e.g. by replacing magic values in options with choices).

> Again, when the demuxer reaches EOF, nothing changes about the fact that there's still data queued between decoder and demuxer. So I see no point in doing something special here.

Okay, let's make it return remaining time for eof. But, eof still need to be checked because in eof, ts_range always returns MP_NOPTS_VALUE.

**Comment by wm4** [comment]
>But, eof still need to be checked because in eof, ts_range always returns MP_NOPTS_VALUE.

This can happen in other situations as well, not just EOF.

**Comment by xylosper** [comment]
That's why I check eof first and MP_NOPTS_VALUE next.

**Comment by xylosper** [comment]
I recalled why I had changed the behavior in eof state.
This is mainly for streaming because cache state is usually not important for local files.
However, the DASH formats from YouTube does not provide proper duration and in this case, remaining time cannot be determined by `time-start + time-length - time-pos`.
So, I took the way notifying eof state instead of returning remaining time.

Can you make the demuxer set proper ts_range even if it's in eof?

**Comment by wm4** [comment]
>Can you make the demuxer set proper ts_range even if it's in eof?

I'll check what's actually going on. I would like better behavior too.

**Comment by wm4** [comment]
Done. See commit debf57bb0d5896fc68e6acc293112eaaf0d3f2d4. It should now report the full duration.

**Comment by xylosper** [comment]
Thank you.
Now I start to think add a new property demuxer-cache-time to report largest timestamp in cache(that is, ts_range[1]) instead of this propery.
In fact, at the very first time, what I wanted was to figure out the time not duration.
But while I was trying things, I settled down this workaround.
What do you think? If you agree, please close this, then I'll make a new pull request.

**Comment by wm4** [comment]
Sounds ok. Also, maybe the current cache duration property could be fixed to add the amount of otherwise buffered data between demuxer and outputs. Which is basically what you wanted to achieve here.

**Comment by xylosper** [comment]
Opened new one. I want to keep demuxer-cache-duration as it is because this property has its own merit which does not depends on TICK event.

**Pull request closed without merging**
