### PR TITLE
options: remove ::allow_unknown_entries, constify instances

### PR DESCRIPTION
**Pull request by evelikov**
Trivial series that I've hard around for ages. Should be a no brainer

- remove `m_obj_list::allow_unknown_entries` - always true
- const annotate all `m_obj_list` instances/accessors
- const annotate all `m_opt_choice_alternatives` instances/accessors

### CODE REVIEW

**Comment by evelikov** [comment]
Humble poke anyone?

@avih I think you've been around the options codebase recently - any input will be appreciated.

**Comment by avih** [comment]
> Should be a no brainer

Should be, and looks OK (because it seems that there would be compile errors if the patch was wrong), but I don't have the time to study carefully such non-local changes. Sorry.

**Comment by evelikov** [comment]
@Dudemanguy are you willing to take a look? Alternatively any ideas who might be interested?

**Comment by Dudemanguy** [comment]
Oh yeah it looks fine. I've been meaning to get to this PR eventually.

**Review by Dudemanguy — APPROVED** [review]

**Pull request merged**
