### PR TITLE
mpv on OpenBSD

### PR DESCRIPTION
**Pull request by czarkoff**
Following changes are applied to `old-configure` in OpenBSD's ports. Basically they boil down to
* removal of `--tmpdir` flag of `mktemp`,
* disabling wayland GL backend if wayland isn't found,
* names of Lua binaries, and
* CD and DVD device names.

### CODE REVIEW

**Comment by wm4** [comment]
old-configure is not supposed to be used. Basically I'm keeping it around for personal use on Linux; I should probably remove it from the repo entirely. Use waf instead.

But fine, these changes can't hurt. I don't agree with the ``--tmpdir`` removal, though. Maybe it should just be changed to hardcode /tmp as directory, instead of just letting it use the current directory.

**Comment by czarkoff** [comment]
The OpenBSD port avoids using waf because it proved problematic with other ports in past. That said, it works fine IIRC.

My rationale for removing `--tmpdir` is that writes outside source distribution violate encapsulation, and thus are discarded in OpenBSD ports infrastructure. That said, there is nothing bad about using `mktemp` for writes to `tmp`, and this use don't affect building `mpv` by hand, so I reintroduced this option as `-p` (which BSDs have) in the next commit.

**Comment by wm4** [comment]
Merged, with the mktemp commits squashed.

>The OpenBSD port avoids using waf because it proved problematic with other ports in past.

Not really an argument. Anyway, just be aware that old-configure is unsupported, might break randomly, and might not enable or detect some features waf enables.

**Comment by czarkoff** [comment]
I guess I'll submit diffs to unbreak it then.

**Pull request closed without merging**
