### PR TITLE
Cleanup matroska timeline

### PR DESCRIPTION
**Pull request by mathstuf**
---
Cleaning up some nasty code in here. Not yet ready for merge (behavior has changed for some of the example files I made since I added this code; bisecting now for what's causing it). Really interested in a better name than `inner_timeline_info`.

### CODE REVIEW

**Comment by mathstuf** [comment]
Oops, missed that it needs to be `*timeline` since it's a `**`.

**Comment by mathstuf** [comment]
OK, so the behavior change is due to fcdbaf78f23f57f6c493efa9ec1689696db9a2d1 which, before made a 0-length "video" whereas now it warns and doesn't have much of anything other than to say that 6 seconds are missing from the timeline (a sensible change; was more curious whether I had introduced it somewhere).

**Comment by wm4** [comment]
Hm, what happened to this? I think it looks good and acceptable for merge. I probably overlooked the update to the PR (or it didn't send a mail notification) and forgot about it.

Just a small thing: maybe do ``s/tl_info/ctx`` (or something else of your preference - I think ``tl_info`` is a bit long and the ``_`` makes it awkward too).

**Comment by mathstuf** [comment]
Renamed to `ctx`. GitHub doesn't send emails for updated commits on a PR.

**Comment by wm4** [comment]
Merged.

**Pull request closed without merging**
