### PR TITLE
csputils: compute the exact luma coefficients directly

### PR DESCRIPTION
**Pull request by haasn**
Instead of ugly hard-coded numbers, we can just re-use our definitions
of the colorspace primaries to compute the luma coefficients.

In the case of BT.601 primaries, I picked the colorspaces that give rise
to the same coefficients as before (and which also match the respective
documents). The mixed-up naming between BT.601, BT470M and SMPTE 240M is
sort of annoying but that's history for you.

The total deviation from the "reference" values introduced was in the
0.001 range for all the colorspaces.

### CODE REVIEW

**Comment by wm4** [comment]
>The total deviation from the "reference" values introduced was in the
0.001 range for all the colorspaces.

That sounds a bit high?

**Comment by haasn** [comment]
It's 0.1%, which is not much. Keep in mind most of these figures are rounded to 0.01 or 0.001 precision even in the official documents, so that's most likely where the deviation came from.

Also, I didn't measure the exact error, I just look at the first digit that was different. Probably the exact errors was within 0.0005 (since the difference is most likely just due to rounding in the documents).

**Comment by wm4** [comment]
AFAIK you're supposed to use these _rounded_ coefficients. This is why the current code reproduces these exact numbers, instead of using more precision.

**Comment by haasn** [comment]
I think we've agreed this is unnecessary, no reason to have it rot around

**Pull request closed without merging**
