### PR TITLE
video: add pure gamma TRC curves for 2.0, 2.4 and 2.6.

### PR DESCRIPTION
**Pull request by wsldankers**
I agree that my changes can be relicensed to LGPL 2.1 or later.

### CODE REVIEW

**Comment by haasn** [comment]
I've been wondering if we can't somehow parametrize a generic MP_CSP_TRC_GAMMA, rather than extending the enum by lots of hard-coded values like this.

**Comment by haasn** [comment]
I mean in theory we could reserve a special enum range to encode the gamma, like `MP_CSP_TRC_GAMMA_BASE + floor(gamma * 1000)` or w/e.

**Comment by wsldankers** [comment]
Agreed in principle, but using that enum range like that sounds a bit hacky. Probably better to introduce a parameter in the spirit of `--tone-mapping-param`.

Might also be useful to parameterize bt.1886 with a black level.

Come to think of it, `--tone-mapping-param` is a bit annoying if you want to switch between tone mapping algorithms. So perhaps a seperate `--target-trc-gamma=2.4` option with a warning that you need to `--target-trc=gamma` for that to be effective?

**Comment by haasn** [comment]
Dunno; it's annoying that we use these gamma values in multiple places (specifically `--vf=format`, `--target-trc`). And yeah, tone mapping param not being tied to the tone mapping curve is annoying indeed.

It might make more sense if we could somehow parametrize options as part of the option specification itself, like `--tone-mapping=gamma=1.8` rather than `--tone-mapping=gamma --tone-mapping-param=1.8`.

**Comment by wm4** [comment]
@haasn so OK or rejected?

**Comment by wm4** [comment]
@haasn ping

**Comment by haasn** [comment]
Seems fine I guess. I assume there's a use case for it?

Would be nice if we could map them to avcol trc values but I guess those don't exist? (Would hardly be the first curve we added before libav* though)

**Comment by wm4** [comment]
> to avcol trc values but I guess those don't exist?

I'd say it depends on whether any standard defined them, as that enum and its raw values are derived from those.

**Pull request merged**
