### PR TITLE
autoload: load only files that make sense

### PR DESCRIPTION
**Pull request by rr-**
This should improve things for #1840's OP.
Additionally, added a few blank lines because navigating was a PITA.

### CODE REVIEW

**Comment by wm4** [comment]
A bit too many unrelated cosmetic changes for my taste, but it doesn't matter.

Are you sure the code works at all? EXTENSIONS has entries like 1, 2, 3... not the values themselves.

**Comment by rr-** [comment]
If I wasn't sure, I wouldn't commit it.
The only thing I'm not sure of though is whether I can do `table.remove(t, k)` when iterating with `pairs(t)`, forgot to test it - which I'm going to do ASAP.

**Comment by rr-** [comment]
Wait. What the heck am I doing indeed. 

How it even worked?

**Comment by wm4** [comment]
The indices are 1, 2, 3... and not '.mkv', '.avi', ... So I don't see how this can work at all.

Also .mpv is not a common extension, you probably mean .mkv.

**Comment by rr-** [comment]
You're absolutely right.

**Comment by haasn** [comment]
Do we really need a redundant ```.``` in front of every extension in the list?

**Comment by rr-** [comment]
Should be good now.
(The `pairs()` iterating did need to happen in reverse order.)

**Comment by wm4** [comment]
Merged.

**Pull request closed without merging**
