### PR TITLE
player: change window-scale to be only a property

### LINKED ISSUE #9066: when starting with "--geometry=NNNNxNNN" "window-scale" is always "1"
### Important Information

- mpv version : mpv-x86_64-20210725-git-e2109b6.7z
- Windows Version : Windows 10 20H2

### Reproduction steps

mpv-bug-window-scale

```
1.
1280x720.mp4

input.conf----------
8 set window-scale 1
9 set window-scale 0.5
--------------------


2.
mpv.exe --geometry=1600x900 1280x720.mp4

or

mpv.conf------------
geometry=1600x900
--------------------

mpv.exe 1280x720.mp4


3.
press key 8
```

### Expected behavior

"--geometry=1600x900" makes "windows-scale" "1.25"  (1.25 == 1600/1280)

so "set windows-scale 1" changes mpv screen size 1280x720.

### Actual behavior

The "window-scale" of "--geometry=1600x900" is "1".

There is no mpv screen size change.

### PR DESCRIPTION
**Pull request by Dudemanguy**
We've gotten a few complaints about how `window-scale` currently works in mpv. I think probably the best approach is to just drop the option illusion with that and make it a strictly RW property. The chances of people actually setting `--window-scale=<number>` in their config file is probably really low compared to someone that presses the default `alt+1` binding and expects the window actually do a resize. If someone needs to set a specific scaling in their config file or on the command line, they can just very trivially use `--geometry` instead which is exactly designed for this. So to sum it up, with this PR, `--window-scale` is removed (as an option), `current-window-scale` is deprecated in favor of `window-scale` and `window-scale` itself is now just a normal RW property.

Fixes #9066 and is an alternative to #8247.

### CODE REVIEW

**Comment by avih** [comment]
There seems to be an issue with the code:
```
../player/command.c: In function ‘mp_property_window_scale’:
../player/command.c:2336:9: error: a label can only be part of a statement and a declaration is not a statement
 2336 |         double scale = *(double *)arg;
      |         ^~~~~~
```

Specifically about the change, not sure about it. Can't it be fixed to work also when set to 1? it does seem to work when setting it to 2 or 1/2. For instance, maybe make it do something if it's set to a value which is different than current-window-scale?

**Comment by Dudemanguy** [comment]
>There seems to be an issue with the code:

Woops, I put the `;` in the wrong spot (wonder why gcc didn't complain to me).

>Specifically about the change, not sure about it. Can't it be fixed to work also when set to 1? it does seem to work when setting it to 2 or 1/2. For instance, maybe make it do something if it's set to a value which is different than current-window-scale?

Yeah this gets tricky. Originally, `window-scale` was an option that also always changed with the window size. wm4 changed this later because basically what would happen is that the value of the option would silently change whenever you resized the window manually and things of that nature. That is inconsistent with how every other option works (they only change when the user actually changes them).

As far as my understanding of it goes, mpv's option system is designed to only do anything on changes. Changes on runtime work because it registers a callback. However merely setting the same value again (which is something a user would likely do via `set window-scale 1`), does not trigger any callback thus nothing happens (hence the source of these issues). Sure it's probably possible to code some specific exception for just this value but I don't think we would want to go that route.

Sidenote: I realized I misunderstood how `geometry` works so it's not exactly a one-to-one replacement unfortunately.

**Comment by avih** [comment]
Well, however hard it might be to straighten things up, I think it's typically more useful as an option than a property. I.e. IMHO removing the option would hurt users of this feature.

Additionally, I'd guess that the current-window-scale value can somehow be derived from osd-dimensions.

Also, I think this is the only option which allows you to change the window size without changing to a different file (like geometry), though I'm guessing this would still work even if it's only a property.

**Comment by Dudemanguy** [comment]
Closed in favor of #8247.

**Pull request closed without merging**
