### PR TITLE
TOOLS/lua/autoload.lua: add support for more file extensions

### PR DESCRIPTION
**Pull request by Obegg**
Add support for 'm2ts' files (BDMV)

### CODE REVIEW

**Review by Natural-Harmonia-Gropius — CHANGES_REQUESTED** [review]
Could you add more types? like `ape, dsd, dsf, dff` to audio and `jfif, heif` to image

**Comment by ObsessedHacker** [comment]
> Could you add more types? like `ape, dsd, dsf, dff` to audio and `jfif, heif` to image

Added

**Comment by Obegg** [comment]
@Natural-Harmonia-Gropius It hasn't been merged yet, any reason? Something wrong with what I added?

**Comment by Natural-Harmonia-Gropius** [comment]
> @Natural-Harmonia-Gropius It hasn't been merged yet, any reason?

I don't know, i'm not a member of MPV.

**Comment by Dudemanguy** [comment]
@Obegg: you would need to at least squash the commits together and fix the commit message as per the contribution guidelines.

**Comment by Obegg** [comment]
@Dudemanguy I have no idea how to do it, I can't squash commits together or edit the commit message on GitHub (website).
I tried to google it and it looks overcomplicated, so I'll just close this PR.

**Comment by garoto** [comment]
I feel you. Those bozos at the SanFran (lol, imagine that) GH HQ can't do anything worthwhile regarding their web-interface. This website never progressed beyond a meme with tons of storage avaiable.

**Pull request closed without merging**
