### PR TITLE
ao/pulse: wait for command completion

### PR DESCRIPTION
**Pull request by t-8ch**
Muting the stream also directly triggers an update to the OSD.
When not waiting for the command completion this read of the mute
property may read the old state. A stale read.

Note that this somehow was not triggered on native Pulseaudio, but it is
an issue on Pipewire.

See https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/868

Note: this also triggered a bug in Pipewire (see the mentioned ticket) and currently needs a Pipewire git version to validate the fix.

### CODE REVIEW

**Comment by jeeb** [comment]
In general the idea of consistency appeals to me. :) . Doing some digging to just double-check things.

**Comment by jeeb** [comment]
I did some digging and testing with
```
m cycle ao-mute
p cycle-values ao-volume 25 50 75 100
```

Seems to Just Work, and makes the behavior of all of the control messages consistent.

**Comment by jeeb** [comment]
Thank you for the pull request.

Applied it as 4f07607888541e6eb40fc5c3a1edfeb84aacb0f7 after slightly rewording the commit message.

**Comment by t-8ch** [comment]
Thanks!

**Comment by t-8ch** [comment]
@jeeb On the other hand this now freezes the player when changing volume by keeping pressed the relevant buttons.

**Comment by jeeb** [comment]
That is `9 add volume -2`, which I do utilize - so I guess it's not just `ao-*` that are affected :) .

**Comment by t-8ch** [comment]
I have a small stuttering on ao/alsa. But on ao/pulse everything is frozen.

**Comment by jeeb** [comment]
Will test after $dayjob, but if it is just the amount of commands (and possibly the longer time it takes for PA/Pipewire to do/ack that change), then most likely will do a partial revert since I do not think we will be reworking the command structure any time soon. Commands will wait until completion so blocking the command queue doesn't sound like a good idea, even if it's not the perfect thing.

AO Mute I think is just less likely to be spammed as much, so that can most likely be not fire-and-forget but actually sync.

If there's any weirdness with returned values, we can just cache them.

**Comment by t-8ch** [comment]
It seems the simple act of sending the message and retrieving the result via the callback function only takes 0.1 milliseconds while going through the blocking APIs via `waitop()` blows this up to 40 milliseconds.

**Comment by t-8ch** [comment]
Passing `context_success_cb` to `pa_context_set_sink_input_volume()` and `pa_context_set_sink_input_mute()` like the other users of `waitop()` makes everything much smoother.

**Pull request closed without merging**
