### PR TITLE
build: generate version.h with python

### PR DESCRIPTION
**Pull request by Dudemanguy**
Basically replace `version.sh` with `version.py` instead so the build system is more (all?) python. It should be nicer and more portable. Some seemingly obsolete/pointless things  in `version.sh` were removed and not implemented in `version.py`.

### CODE REVIEW

**Comment by qmega** [comment]
> Sidenote: Is it bad to automatically update the copyright year based on the datetime? I added that in just because but I dunno if that would make some lawyers angry.

I don't know about lawyers, but it's not great for reproducible builds.

When configuring with `--disable-build-date` (which defines `NO_BUILD_TIMESTAMPS`), the build date is replaced by "UNKNOWN" in the version output, but the copyright will still be there as is.

**Comment by Dudemanguy** [comment]
>I don't know about lawyers, but it's not great for reproducible builds.

Yeah I removed it.

**Comment by avih** [comment]
I don't think we should rewrite things which don't have any known issues.

As far as I know we had no reports of missing or incompatible sh on any system where mpv can build. If there were such known issues then sure, a rewrite can be considered.

But as long as there are no known issues, then a rewrite can only regress things, sometimes in subtle ways which are not apparent initially.

**Comment by avih** [comment]
> Going to just include bundle this with #8840.

Please don't sneek it in via the meson PR.

**Pull request closed without merging**
