### PR TITLE
Disallow world-read access to the IPC pipe on Windows

### PR DESCRIPTION
**Pull request by rossy**
More details in the commit message. This may or may not be paranoia, depending on how dangerous it is to let anyone read from (but not write to) the IPC pipe. In any case, I think it makes the pipe security closer to how it is on Linux.

Before/after:
image

Disclaimer: I'm definitely not an expert in Windows security.

### CODE REVIEW

**Comment by wm4** [comment]
That seems very complicated, but if there's no simpler way, ok.

**Comment by rossy** [comment]
Yeah, I tried to make it as simple as possible. SDDL strings seem like the least-awful way of making a security descriptor in terms of awkward memory management. Chromium uses them too for security/sandbox related stuff, so they must have come to the same conclusion.

Docs are here if anyone is feeling masochistic:
https://msdn.microsoft.com/en-us/library/windows/desktop/aa379570.aspx

**Comment by haasn** [comment]
At some point one begins to wonder what mpv's threat model is. What security guarantees are we reasonably expected to provide?

**Comment by rossy** [comment]
I guess the threat I was thinking of was the exposure of sensitive information due to the differences in permissions between Windows and Linux. In Linux (as far as I understand) the pipe is only readable and writable by the owner, but on Windows (before this commit) it was readable by everyone. Someone with only Linux in mind could write a plugin or a change to mpv that broadcasts sensitive information in an event, and that could be read by anyone on Windows.

I'm not sure what that sensitive information could be though. I guess mpv plugins have access to the filenames being played and possibly website passwords for streaming sites.

**Pull request merged**
