### PR TITLE
stats: show sample format of audio track

### PR DESCRIPTION
**Pull request by sfan5**
like this:
mpv-shot0001

### CODE REVIEW

**Comment by Argon-** [comment]
Is the height of the total text output still okay on a 16:9 window? (that's what I usually use as a "baseline")

**Comment by sfan5** [comment]
There's more than enough space left, even with the default font size.

**Comment by Argon-** [comment]
Well then LGTM

**Comment by wm4** [comment]
Slightly misleading, because it doesn't reflect the actual depth, just what the decoder outputs. So 24 bit FLACs are shown as s32. Just something to be aware of.

**Pull request merged**
