### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by Moiman**
Found by codespell

### CODE REVIEW

**Comment by thebombzen** [comment]
Can you please squash these commits? They all sort of do the same very minor, and having 8 different commits for it doesn't seem ideal.

**Comment by Moiman** [comment]
> Can you please squash these commits? They all sort of do the same very minor thing, and having 8 different commits for it doesn't seem ideal.

Ok. I squashed commits.

**Comment by thebombzen** [comment]
Make sure you add a commit message that references what you fixed, in this case "various"

e.g. `various: fix typos`

**Comment by Moiman** [comment]
> Make sure you add a commit message that references what you fixed, in this case "various"
> 
> e.g. `various: fix typos`

Okay. I also added changes from #11514

**Review by Dudemanguy — APPROVED** [review]
Every single misspelling of `explicitly` was me. Unbelievable.

**Pull request merged**
