### PR TITLE
vo_gpu: hwdec_vaapi: avoid drm_fourcc.h dependency

### PR DESCRIPTION
**Pull request by airlied**
This is a bit ugly, we could decompose it.

Read this before you submit this pull request:
https://github.com/mpv-player/mpv/blob/master/DOCS/contribute.md

Reading this link and following the rules will get your pull request reviewed
and merged faster. Nobody wants lazy pull requests.

### CODE REVIEW

**Comment by philipl** [comment]
I agree it's a bit ugly. The other option is to ifdef it and not set modifiers if libdrm is unavailable.

**Comment by haasn** [comment]
Hi, this is what I use in libplacebo

```c
#ifndef DRM_FORMAT_MOD_LINEAR
#define DRM_FORMAT_MOD_INVALID  ((UINT64_C(1) << 56) - 1)
#endif
```

**Comment by airlied** [comment]
okay I've gone with that suggestions, seems easiest.

**Review by philipl — APPROVED** [review]
Great.

**Pull request merged**
