### PR TITLE
Add support for HDR10+ dynamic tonemapping

### PR DESCRIPTION
**Pull request by haasn**
Blocked by https://code.videolan.org/videolan/libplacebo/-/merge_requests/360

### CODE REVIEW

**Review by philipl — APPROVED** [review]

**Comment by fabianbees** [comment]
Would this PR also allow passthrough of the HDR10+ metadata to a display, which supports HDR10+ natively, or tonemapping only?

If not, are there any plans to support passthrough of the HDR10+ metadata to displays in the future?

**Comment by haasn** [comment]
> Would this PR also allow passthrough of the HDR10+ metadata to a display, which supports HDR10+ natively, or tonemapping only?

No. Do you know of any APIs that allow HDR10+ metadata passthrough?

**Comment by jeeb** [comment]
> > Would this PR also allow passthrough of the HDR10+ metadata to a display, which supports HDR10+ natively, or tonemapping only?
> 
> No. Do you know of any APIs that allow HDR10+ metadata passthrough? Vulkan and OpenGL both don't.

Direct3D 11 has
```
typedef struct DXGI_HDR_METADATA_HDR10PLUS
    {
    BYTE Data[ 72 ];
    } 	DXGI_HDR_METADATA_HDR10PLUS;
```

which can be set with the same API as the static metadata if I understand it correctly.

**Comment by Doofussy2** [comment]
Doesn't the Windows 'HDR' platform support all forms of 'HDR'? That was my understanding, and why DoVi can be played via Dolby's plugin.

**Comment by haasn** [comment]
> `DXGI_HDR_METADATA_HDR10PLUS`

72 bytes of raw unstructured data? How are we supposed to set this again?

**Comment by jeeb** [comment]
> > `DXGI_HDR_METADATA_HDR10PLUS`
> 
> 72 bytes of raw unstructured data? How are we supposed to set this again?

They probably just gave up and want the data bits as defined in CTA-861-H or so.

The hilarious bit is that this is completely and utterly undocumented. So yea, "lol".

**Pull request merged**
