### PR TITLE
x11_common: misc style fixes

### PR DESCRIPTION
**Pull request by N-R-K**
No change in functionality intended.

### CODE REVIEW

**Comment by llyyr** [comment]
NULL argument is a no-op only on [libX11 1.6.4 or newer](https://gitlab.freedesktop.org/xorg/lib/libx11/-/commit/78851f6a03130e3c720b60c3cbf96f8eb216d741), but mpv allows building with any version newer than 1.0.0. Unless we're bumping libX11 requirement, I don't think this can be merged.

According to https://github.com/mpv-player/mpv/commit/3afff3fe9be3b37650cb9d9154de581a56b82939, 
> Also, the Xlib manual says you must use XAllocSizeHints() (for ABI reasons), so do that.

**Comment by N-R-K** [comment]
> NULL argument is a no-op only on [libX11 1.6.4 or newer](https://gitlab.freedesktop.org/xorg/lib/libx11/-/commit/78851f6a03130e3c720b60c3cbf96f8eb216d741)

AFAIK it has always been no-op, that commit only changed the documentation to make it explicitly allowed.

> Also, the Xlib manual says you must use XAllocSizeHints() (for ABI reasons), so do that.

I didn't notice any such thing on the `XAllocSizeHints` manpage but [this document](https://tronche.com/gui/x/xlib/ICC/client-to-window-manager/wm-normal-hints.html) does mention it. I've dropped that commit.

(Although, I must say, this seems like a weird and unexpected thing to require. Usually, if forcing allocation is the goal then struct definition is also hidden from the user, i.e an opaque type. And if the struct definition isn't hidden, then there's usually some explicit `reserved` spaced at the end of the struct for future addition.)

**Comment by llyyr** [comment]
You're right, it appears that `#define Xfree(ptr) free((ptr))` has always been true. Seems fine to me then

**Review by Dudemanguy — APPROVED** [review]
LGTM

**Pull request merged**
