### PR TITLE
libplacebo v6 updates

### PR DESCRIPTION
**Pull request by haasn**
Also includes the new HDR contrast recovery option. I included it by default in the `gpu-hq` profile.

Question: Should we "downgrade" HDR peak detection from on-by-default to on-in-gpu-hq as well? It's really punishing for slower devices, even after libplacebo v6's optimizations.

### CODE REVIEW

**Comment by haasn** [comment]
This is probably blocked by VLC 3 being incompatible with libplacebo v6

**Comment by haasn** [comment]
Well, this breaks CI, which expects mpv to build with whatever versions of libplacebo are available on the CI image.

Maybe we should hold off on requiring v6 for the time being? Thoughts?

**Comment by christoph-heinrich** [comment]
Without v6 `--hdr-contrast-recovery` and `--hdr-contrast-smoothness` aren't available which is a shame.
They could be gated with defines, so that they are available to those running newer versions. In that case the documentation would have to mention that for those v6 is required.

Downgrading HDR peak detection seems reasonable, but I don't know how slow we're talking of here.
It works fine on my ADM R9 380, which is slow by today's standards, but I haven't tried it on any iGPUs.

**Comment by sfan5** [comment]
> Maybe we should hold off on requiring v6 for the time being? Thoughts?

I suggest waiting for the release at least, so that distributions can at least support vulkan for vo_gpu.
gpu_next is out of reach as the only libpl release that matches the requirement is v6.

**Comment by llyyr** [comment]
I think distributions can ship multiple versions of libplacebo, I don't know how long you can keep waiting for VLC since both mpv and ffmpeg 6.1 do want latest libplacebo. 

But if we aren't bumping libplacebo to v6, then I think it makes sense to also put #11875 behind preprocessors, since this one change is the only reason why libplacebo v5 can't have libplacebo-next

**Comment by philipl** [comment]
> Also includes the new HDR contrast recovery option. I included it by default in the `gpu-hq` profile.
> 
> Question: Should we "downgrade" HDR peak detection from on-by-default to on-in-gpu-hq as well? It's really punishing for slower devices, even after libplacebo v6's optimizations.

With your latest optimisations, it became much more usable (4k60 worked on a UHD770 for the first time) but `gpu-hq` is too heavy for the UHD770 and not quite usable on the Iris Xe class iGPU. And given how visually distorted things look without peak detection, I would keep it on my default. It now works on more low end hardware, and I think it's a better trade-off to make people turn it off for being slow than for other people to work out how to turn it on for hardware where `gpu-hq` is too much.

ie: I think that going into the future, hardware that is too slow for peak detection is going away while hardware that can do peak detection but cannot do gpu-hq will be the more common low end combination.

**Comment by philipl** [comment]
You can simplify this too:

image

(github doesn't let you comment on lines that are "too far away" from the changes in the diff)

**Comment by philipl** [comment]
> intel's iGPUs have ASIC video processors, so if everything else is offloaded to ASIC (scaling, format conversion, etc.), maybe peak detection will become feasible?

Theoretically? Maybe. It would require extensive and invasive changes to the libplacebo pipeline to actually do properly - you can't achieve identical results using vaapi/qsv filters as-is, as steps will happen in the wrong order. You'd also be giving up the superior algorithms in libplacebo for whatever the hardware gives you. You can take that to the logical conclusion and just use the hardware tone-mapping and offload everything and be happy with whatever that gives you. Of course, the Intel iGPUs with hardware tone mapping are also the ones that can do peak detection anyway, so...

**Comment by llyyr** [comment]
There's not much point in that, the UHD 770 is good enough to do 4k60 peak detection on a DDR5 system, but lags when I underclock the same memory to DDR4 speeds. The bottleneck here is purely due to the igpu not having fast enough dedicated memory. Even if you used the hardware better you can't make the memory bus go faster

**Comment by kasper93** [comment]
> This is probably blocked by VLC 3 being incompatible with libplacebo v6, as well as ffmpeg 6.0 (6.1 will have a fix for it)

(also in response to #11991, but I don't want to split discussion)

When is the plan to release stable mpv? Maybe we could wait until dust settles? And release it once all new fancy features are available out of the box, at least in Arch.

Currently neither new HDR Tone Mapping, nor Vulkan decoding would be available. With stable versions of available packages.

Of course this works only if it would be relatively short time frame. I'm not suggesting blocking release indefinitely.

**Comment by sfan5** [comment]
> When is the plan to release stable mpv?

I was thinking today or early next week.

**Comment by haasn** [comment]
Rebased and re-introduced the pl_dispatch_info_move commit.

**Comment by haasn** [comment]
The CI issues still need to be resolved, we can't merge this until libplacebo6 exists on the appropriate platforms, unless we can somehow vendor it in as a meson subproject / git submodule.

**Comment by nekopsykose** [comment]
could probably add libplacebo into https://github.com/mesonbuild/wrapdb and then the wrapdb fallback would easily work. since waf is dropped that makes it much easier to maintain

**Comment by nekopsykose** [comment]
alternatively just a wrap, like in the referenced mr

**Comment by kasper93** [comment]
> The CI issues still need to be resolved, we can't merge this until libplacebo6 exists on the appropriate platforms, unless we can somehow vendor it in as a meson subproject / git submodule.

Here is my view on this topic. While it is important to test against latest master of libplacebo, which ironically only mingw build do. It is also important that mpv is buildable on some common or maybe not so common platforms. And compatible with latest stable packages they provide.

If the idea, moving forward, is that mpv supports _only_ libplacebo6 it is fine, gpu-next and vulkan support will not be available on platforms that does not package libplacebo6. It is not a CI _issue_, it is just something that CI shows.

I understand libplacebo is close to mpv, but I don't like the idea of coupling them together with wraps. Otherwise why not do the same for ffmpeg or libass? Package maintainers will not use wrap/submodules anyway, so I don't see added value of them. If you want to use newer libplacebo just build it yourself.

Maybe we should just wait a bit until libplacebo6 is available... anywhere. As I see we are locked on vlc3. We can push maintainers to package libplacebo6 as separate package, I can do that for msys2.

**Comment by llyyr** [comment]
Packaging an older libplacebo version for VLC is the way to go here, I think. I've already sent a request for TW, it's up to others to push their distro to do it as well. This shouldn't be hard considering there are already distros that package multiple versions of fast moving libraries, like wlroots.

**Comment by nekopsykose** [comment]
speaking as a distro maintainer (though one that's a little biased, because i maintain this stack there): having a library with a distinct filename/soname isn't extremely rare (not preferred, but not insurmountable). the only risk that occurs is:

- 'development' packages conflict with eachother because of include-dir/non-suffixed-.so location (this is irrelevant really)
- loading multiple versions of the same library into the same process doesn't work without being broken (assuming they conflict in symbols, which is pretty much always the case, and here). in this case, ffmpeg can also link to libplacebo- so if a distro builds ffmpeg with libplacebo support, it must use the same one as mpv (assuming mpv also uses that same ffmpeg). in this case, the ffmpeg for vlc3 (4) would be distinct anyway (assuming a distro had two ffmpeg packages), and the latest release of ffmpeg cannot use libplacebo 6 without applying two patches. but this is not really much work to fix... (also most distros have more than one version of ffmpeg already, as an example, because of the large 4->5 break)

overall this is a chicken-and-egg problem. nobody will update libplacebo if they have no reason to duplicate it, since it's preferred to have one library. if you don't want to require 'v6 only' (as opposed to the ifdefs allowing both), then every distro will probably just keep v5-only for as long as vlc needs it (theoretically vlc3 can't even use v5 without a patch..). you can very easily give them a gentle nudge to use the newer one by making it the only compatible one- and this would only happen on master, as 0.36 was released without these changes.

the only actual negative effect that would probably happen, is people building mpv themselves while relying on their own distro packages for the deps (as opposed to using e.g. mpv-build). those might suddenly show up wanting support :)  

> then every distro will probably just keep v5-only for as long as vlc needs it  

another solution- i'm not aware of any libplacebo users in distro packages aside from mpv, vlc, and ffmpeg. the former is this, the latter is just two small patches, and the middle one is the odd one out. if someone ported the 3.x vlc branch to v6 (i tried once actually, but that is not a small change :D), then everyone could just use that patch and then that solves the whole issue here too.

**Comment by llyyr** [comment]
> loading multiple versions of the same library into the same process doesn't work without being broken (assuming they conflict in symbols, which is pretty much always the case, and here). in this case, ffmpeg can also link to libplacebo- so if a distro builds ffmpeg with libplacebo support, it must use the same one as mpv (assuming mpv also uses that same ffmpeg).

This is a good point actually, I hadn't thought about it but fortunately this shouldn't be a problem considering VLC3 already requires ffmpeg-4 to build which doesn't even have libplacebo while mpv can build with ffmpeg-6. Nearly all distros already carry both ffmpeg-4 and ffmpeg-6 already.

> latest release of ffmpeg cannot use libplacebo 6 without applying two patches

ffmpeg 6.1 should be very soon so those patches won't be needed anymore.

> if someone ported the 3.x vlc branch to v6

This would be very not trivial, you may as well just build off the master branch for VLC 4 at that point

**Comment by kasper93** [comment]
> ffmpeg [...] don't see major API changes very often, and new features (mainly various decoders?) will not have a major impact on the user experience

I don't agree with this assessment. Right now big feature that some people want to try is Vulkan decoding. Also ffmpeg is quite a bigger library, used ubiquitously. There is much more effort put to keep API/ABI compatible and rules when the API/ABI can be broken and so on. And in fact ffmpeg4.4 is still packaged for project that weren't updated to newer version and likely will never be.

> This is a good point actually, I hadn't thought about it but fortunately this shouldn't be a problem considering VLC3 already requires ffmpeg-4 to build which doesn't even have libplacebo while mpv can build with ffmpeg-6. Nearly all distros already carry both ffmpeg-4 and ffmpeg-6 already.

vlc3 is indeed build with ffmpeg4.4 on Arch, but I just taken a look at msys2 and they seem to build it with ffmpeg6.

**Comment by llyyr** [comment]
> I just taken a look at msys2 and they seem to build it with ffmpeg6.
VLC3 fails to build with ffmpeg-6, so that can't be possible

**Comment by ionenwks** [comment]
> > I just taken a look at msys2 and they seem to build it with ffmpeg6.
> 
> VLC3 fails to build with ffmpeg-6, so that can't be possible
> 
> edit: https://code.videolan.org/videolan/vlc/-/merge_requests/1245 Apparently it should work, just without vaapi support

Yes, gentoo (for one) allows this -- albeit there can let users pick to disable or enable vaapi and either get or not get the restriction. Most likely harder for other distributions and I imagine they'd sooner patch it than drop vaapi.

**Comment by sfan5** [comment]
> Since most users are using gpu-next these days, it seems to me that having libplacebo as a submodule [...].

I think you're overestimating the amount here. The largest share of mpv users probably have nothing configured at all.
Even as a technically minded user I haven't been able to use all the fancy stuff in gpu-next for the last 6 months as compiling both from source is a hassle (notable exception being Windows where pre-made builds exists)

**Comment by christoph-heinrich** [comment]
> Even as a technically minded user I haven't been able to use all the fancy stuff in gpu-next for the last 6 months as compiling both from source is a hassle

For Arch users the AUR + AUR helper make it pretty easy to always use the latest commit (+own patches) of mpv and libplacebo via [-git](https://aur.archlinux.org/packages/mpv-git) [packages](https://aur.archlinux.org/packages/libplacebo-git).

**Comment by kasper93** [comment]
For msys2 build I guess we can just disable libplacebo. Can be re-enabled one day (TM)... 
``` diff
diff --git a/ci/build-msys2.sh b/ci/build-msys2.sh
index c681a69c95..b4226379ad 100755
--- a/ci/build-msys2.sh
+++ b/ci/build-msys2.sh
@@ -12,7 +12,6 @@ meson setup build            \
   -D libarchive=enabled      \
   -D libbluray=enabled       \
   -D libmpv=true             \
-  -D libplacebo=enabled      \
   -D lua=enabled             \
   -D pdf-build=enabled       \
   -D rubberband=enabled      \
@@ -20,8 +19,7 @@ meson setup build            \
   -D spirv-cross=enabled     \
   -D tests=true              \
   -D uchardet=enabled        \
-  -D vapoursynth=enabled     \
-  -D vulkan=enabled
+  -D vapoursynth=enabled
 meson compile -C build
 cp ./build/player/mpv.com ./build
 ./build/mpv.com -v --no-config 
```

**Comment by haasn** [comment]
Judging by discussion on IRC it seems disabling CI on MSYS2 (to unblock this PR) is not a big deal, because we already test building libplacebo on mingw.

With that out of the way, any last objections to this PR?

**Pull request merged**
