### PR TITLE
SVG version of the icon (with symbolic counterpart)

### PR DESCRIPTION
**Pull request by evgenyz**
Before:
mpv-before

After:
mpv-after

### CODE REVIEW

**Comment by avih** [comment]
- Shouldn't the symbolic version use white background instead of transparent? what happens if the menu bar is light instead of dark? (personally I like the non symbolic one at the menu bar, but this could depend on system guidelines).
- At the "after" image, wouldn't it be better that the actual icon (at the bottom below the mpv window) is the gradient one? It's overall nicer than the flat one IMO, and the other icons you have there (Incscape, file manager) don't seem to use a flat style, so why should mpv be different? (though again, it might depend on system guidelines).

**Comment by evgenyz** [comment]
1) No. It'll be colored automagickally. Look at it on the screenshot (it's white) and in the file it is actually black.
2) I've created both versions - with a gradient and a flat one. For the maintainer to choose, maybe?

**Comment by wm4** [comment]
CC @lachs0r

**Comment by wm4** [comment]
Hoped for some feedback, but whatever. Merged, thanks.

**Pull request closed without merging**
