### PR TITLE
win32: fit to screen and window-scale fixes; --geometry positioning fix

### LINKED ISSUE #2397: --geometry does not work in Windows 10
The --geometry option does not work properly in Windows 10 anymore. Setting geometry = 50%:50% but the window is not centered in the screen (single monitor).

There was no such issue in the official 2015-09-03 build but appears in the 2015-09-23 build.

### LINKED ISSUE #3164: Changing window-scale via commands should keep the video centered
When changing the window-scale property via commands (such as `input.conf`), the window remains positioned at its top-left x and y coordinates. It would be much nicer if the window would move accordingly to make its center position static instead.
When the window would exceed a monitor's screen estate, it should then adjust its position to not exceed it, assuming there's enough space left on the other sides (while considering https://github.com/mpv-player/mpv/issues/2935).

mpc-hc has this behavior. I can record a video (or gif) if desired.

Related: https://github.com/mpv-player/mpv/issues/2397, https://github.com/mpv-player/mpv/issues/2301

(I'm on Windows 7.)

### PR DESCRIPTION
**Pull request by maniak1349**
1. Properly update stored client area size and position when the window is resized to fit screen. This was causing wrong behavior with window-scale - when window size was becoming too big the window was resized but the video was not.

2. Center the window on the original window center when the window is resized to fit screen. If user moved the window, he probably did it for a reason and he probably don't want it to get back to the center of the screen when he is resizing it (with window-scale for example).

3. Make VOCTRL_SET_UNFS_WINDOW_SIZE resize the window around its center. This will not affect resizes made by the user (dragging window edge).
Fixes #3164.

4. Center window position after applying W and H parameters of the --geometry option. Passing valid X and Y values will still override the position.
Fixes #2397.

Last change should affect all platforms. I was able to check only windows and x11.

Interestingly enough, it had no effect on x11 for me. Also geometry resize is not always working correctly for me. In some cases (low % values) it centers the window just fine, in other cases (high % values) window shows up in the left-top or bottom-right corner. Maybe it's just my broken test config on VM I don't know.

### CODE REVIEW

**Comment by wm4** [comment]
Merged.

**Comment by bitingsock** [comment]
Is there a way to retain the previous behavior of number 3? I liked it the way it was.

**Comment by bitingsock** [comment]
I've always wanted this as an option, but I often do rely on the previous behavior.

**Comment by maniak1349** [comment]
> Is there a way to retain the previous behavior of number 3? I liked it the way it was.

It is possible I guess. However, it was win32 only and it probably was not intended to be that way. So in order to correctly implement such an option across all the platforms it will require much more work then just revert those changes.

I was actually thinking about an option that will allow user to choice around which part of the window he want the window to scale - one of four corners / one of four window sides / center of the window.

Unfortunately, I have not much time to work on mpv lately. I hope I'll be able to look at it in a week or two.

**Comment by bitingsock** [comment]
I agree, a window anchor option would be pretty handy

**Pull request closed without merging**
