### PR TITLE
win32: stop fullscreen window from moving while dragging hack is active

### PR DESCRIPTION
**Pull request by na-na-hi**
Fixes https://github.com/mpv-player/mpv/issues/1921.

### CODE REVIEW

**Comment by kasper93** [comment]
Except two nitpicks, LGTM

**Comment by sfan5** [comment]
fyi needs a rebase

**Comment by pbaykalov** [comment]
Is it possible to let the autohiding taskbar pixel row show? I used this "bug" to maximize MPV while still being able to use autohiding taskbar. Is it possible to re-enable this "bug"?

**Comment by pbaykalov** [comment]
nvm did it in AHK: 

```
$<#\::
	WinMove A, , 1, 0
	return

```

**Pull request merged**
