### PR TITLE
vo_opengl: make size of cropped INPUT available to user shaders

### PR DESCRIPTION
**Pull request by igv**
Can be useful for some user shaders to be compatible with pan-and-scan.

I agree that my changes can be relicensed to LGPL 2.1 or later.

### CODE REVIEW

**Comment by wm4** [comment]
That's not really "scaled" - more like "cropped".

**Comment by haasn** [comment]
I fully agree with what @bjin said here.

**Comment by igv** [comment]
This will be used only in RPN expressions to specify WIDTH and HEIGHT of your temporary texture. Then you will be able to use that cropped source image (that's what I meant by "compatible with pan-and-scan") in your main shader.
`vec2 pos = pos + floor((PREKERNEL_size - TMP_size) / 2.0);` - left/top border
`vec2 pos = pos + ceil((PREKERNEL_size - TMP_size) / 2.0);` - right/bottom border

Not sure if it requires offsets, so far it worked fine without them.

**Comment by igv** [comment]
Documented INPUTCROPPED variable

**Comment by wm4** [comment]
@haasn @bjin ok with this?

**Comment by haasn** [comment]
I'm still not sure if the documentation is clear enough. “INPUT” is pretty arbitrary to begin with, and nothing else in the hook system uses that name.

You also still haven't solved the (real) problem of actually properly aligning texture access. Are you sure this works as expected in a real world shader, even when combined with video-pan-x/y, video-zoom-x/y, panscan etc.?

**Comment by bjin** [comment]
I still can't agree.

1. A temporary texture was created just to pass its size to shader. A sane approach should use uniform variable instead.

2. The pan-and-scan problem is still not solved at all. Offset is not considered (centering positioning is assumed), so as texture offset.

**Comment by haasn** [comment]
> A temporary texture was created just to pass its size to shader.

It's not actually a temporary texture. In the concept of szexprs, they're just arbitrary variables.

**Comment by igv** [comment]
> when combined with video-pan-x/y, video-zoom-x/y
Works fine with video-zoom, but video-pan-x/y requires right border - left border (or bottom - top) to be set as uniform variable and added to TMP_size (and should be set only if video-pan-x/y isn't 0). Maybe this can be made later, I just don't want to change anything and not sure how to do it properly from aspect.c.

> naming of this variable
SRCIMGCROPPED ?
PREKERNELCROPPED ?

> A temporary texture was created just to pass its size to shader.
I need that temporary texture anyway, not only for its size. And set additional uniform variable, that will be used very rarely, for every shader also isn't a very good approach.

**Comment by bjin** [comment]
Random thought. Maybe we can add an extra pre-kernel pass to do the cropping (with an option enabled)?

**Comment by igv** [comment]
Added pan_offset variable for compatibility with video-pan-x/y.

Also I tried this with prescalers and everything seems to work fine, just need to double NATIVECROPPED. Offset can be added to texture position calculation, e.g:
`vec2 pos = PREKERNEL_pos + pan_offset - vec2(0.5);`
With this texture position is exactly the same as with general scalers.

**Comment by wm4** [comment]
@haasn @bjin so what's your opinion?

**Comment by bjin** [comment]
I somehow feel `NATIVE_CROPPED` would be more readable (`PREKERNEL` is the texture after prescaling). Other than that, I still have some doubts over the benefits and usefulness of those variables. But if it's really necessary, I don't feel that I have strong reason against it. (There are better ways though)

**Comment by igv** [comment]
>PREKERNEL is the texture after prescaling

Yes, which is cropped, and I guess this is how it would be called after additional cropping pass that you suggested (also I agree it would be a "better way", but impacts performance).

**Comment by haasn** [comment]
> Random thought. Maybe we can add an extra pre-kernel pass to do the cropping (with an option enabled)?

This would technically be possible - you'd have to split the upscaling `gl_transform` into two components: cropping + integer panning, and scaling + subpixel offset, with a separate hook in between. The former can be derived from the `src_rect`. With that information you could expose an optional hook to the user that happens immediately before upscaling. (If the user does not hook here, it would be a no-op, and the two decomposed `gl_transform`s would just apply in succession to form the same thing as they do now)

Of course, the big problem here is that you're still suffering from subpixel offsets due to the scaling. I don't have a general solution here. Either you could export the subpixel as a uniform, or you could rely on shader authors to just not care. I mean, the status quo is that shader authors don't care about subpixels for stuff like chroma upscaling in general, so maybe they just won't notice.

**Comment by igv** [comment]
I have updated this PR, added support for offsets and prescalers.
[Shader](http://pastebin.com/Gs0DAzyx) that makes use of this PR in case some one wants to try/test it.

**Comment by wm4** [comment]
@haasn @bjin

**Comment by wm4** [comment]
So I'm ready to merge this, but you shouldn't remove the image_size uniform. Make it do something that most likely won't break existing scripts using it, even if the correctness/usefulness of it is questionable.

**Comment by igv** [comment]
There is MAIN_size now, shaders should use that instead of image_size.
Also I've never seen a shader that uses image_size.

**Comment by wm4** [comment]
OK, good enough. Just making sure we don't go around breaking user shaders. I still added a note to interface-changes.rst. Merged.

**Pull request closed without merging**
