### PR TITLE
ytdl_hook: don't preappend ytdl:// to non-youtube links in playlists

### PR DESCRIPTION
**Pull request by wiiaboo**

### CODE REVIEW

**Comment by wm4** [comment]
Seems fair?

**Comment by kevmitch** [comment]
Works here on the sample from #5003, youtube live, crunchyroll. I know the changes are small, but I'm not sure how related they are. Should they be two separate commits?

**Comment by wiiaboo** [comment]
@kevmitch split them.

**Comment by kevmitch** [comment]
great, thanks.

**Pull request merged**
