### PR TITLE
vo_gpu_next: fix interpolation

### PR DESCRIPTION
**Pull request by kasper93**
I was rebased on top of @Dudemanguy's changes, pushed them too, to avoid conflict resolve...

### CODE REVIEW

**Comment by christoph-heinrich** [comment]
Yesterday there was a state of this PR that fixed #12316, but now it doesn't anymore and I can't check out any of the old states to see when it broke again :neutral_face: 
I think it still worked with https://github.com/mpv-player/mpv/commit/d581865e6f2b12cd1446d14bdfbe410a6b75c9b5

**Comment by kasper93** [comment]
> Yesterday there was a state of this PR that fixed https://github.com/mpv-player/mpv/issues/12316

@christoph-heinrich: Does this helps you? If not the other change with resetting queue on speed change was not fully correct and needs different solution.

``` diff
diff --git a/video/out/vo.c b/video/out/vo.c
index 9e763d3811..684e38212d 100644
--- a/video/out/vo.c
+++ b/video/out/vo.c
@@ -873,6 +873,10 @@ static bool render_frame(struct vo *vo)
                (in->current_frame->display_synced && in->current_frame->num_vsyncs < 1) ||
                !in->current_frame->display_synced)
     {
+        if (in->current_frame) {
+            in->current_frame->vsync_offset = 0;
+            in->current_frame->ideal_frame_vsync = 0;
+        }
         goto done;
     }
```

**Comment by christoph-heinrich** [comment]
> Does this helps you?

This works.

**Comment by kasper93** [comment]
> Edit: Somehow I'm now unable to reproduce that flicker even without that diff... no idea what I did differently before.

So, does it help or not? I don't want to include this change without good reason to do so, it should almost never be triggered in practice.

**Comment by christoph-heinrich** [comment]
> > Edit: Somehow I'm now unable to reproduce that flicker even without that diff... no idea what I did differently before.
> 
> So, does it help or not? I don't want to include this change without good reason to do so, it should almost never be triggered in practice.

Doesn't make a difference, no need to change anything.

**Review by Dudemanguy — APPROVED** [review]
Might be nicer if this could be solved without adding two extra fields that only vo_gpu_next will ever use, but that can be for the future. It's strict improvement as far as I can tell.

**Comment by kasper93** [comment]
> Might be nicer if this could be solved without adding two extra fields that only vo_gpu_next will ever use, but that can be for the future. It's strict improvement as far as I can tell.

Initial version didn't have those fields, but after discussion on IRC, they are added.

**Pull request merged**
