### PR TITLE
Fix DXVA2 interop on Nvidia

### PR DESCRIPTION
**Pull request by rossy**
Sharing off-screen plain surfaces causes Nvidia drivers to crash. This makes the shared surface a rendertarget instead. Untested on AMD and Intel.

Ping @kevmitch.

### CODE REVIEW

**Comment by kevmitch** [comment]
works for me / looks good

**Comment by rossy** [comment]
Thanks for testing. Merged.

BTW, nice work on DXVA2 interop. It's great to see mpv finally support it.

**Comment by wm4** [comment]
>BTW, nice work on DXVA2 interop. It's great to see mpv finally support it.

It's not very good yet, though. It requires the dxinterop backend and uses driver-specific RGB conversion. Going beyond that is much harder.

**Comment by rossy** [comment]
It could probably be ported to the ``win`` backend pretty easily if it created its own D3D device when MPGetNativeDisplay doesn't return one and used D3D 9Ex share handles to share frames between the decoder's device and its own private one.

The RGB conversion thing is a pain though, but maybe not too much of a deal breaker for people who are just using hwdec to save battery on laptops?

**Comment by kevmitch** [comment]
> It could probably be ported to the win backend pretty easily if it created its own D3D device when MPGetNativeDisplay doesn't return one and used D3D 9Ex share handles to share frames between the decoder's device and its own private one. 

I was thinking about this too. Wouldn't we also need to create the offscreen window? On the other hand why would someone use backend=win if they had dxinterop capabilities? 

Also why couldn't it just pass the same refcounted D3D device onto the decoder like it does here? Should I not be doing that here?

**Comment by rossy** [comment]
The off-screen window in dxinterop is for the OpenGL context. It should be fine to do interop with the on-screen OpenGL context in backend=win.

> On the other hand why would someone use backend=win if they had dxinterop capabilities?

Yeah, I didn't think of that. Assuming dxinterop works, I can't think of any reason to prefer backend=win either. Maybe porting to backend=angle would be more worthwhile. (Chrome does it, so it has to be possible.)

> Also why couldn't it just pass the same refcounted D3D device onto the decoder like it does here?

I guess it depends on what's easier to implement. I don't think there would be a problem with using multiple D3D devices and using share handles to pass frames around.

**Comment by kevmitch** [comment]
> Maybe porting to backend=angle would be more worthwhile.

Yes, this is what I'm looking at next. Looks like ANGLE gives you a D3D11 device, which @wm4 says allows you to access the NV12 planes and avoid the RGB conversion.

**Comment by wm4** [comment]
Two problems with that:
- d3d9 probably doesn't, just d3d11
- angle allow only importing rgb textures, though I wonder if this can be easily worked around

**Pull request merged**
