### PR TITLE
ao_pipwire: Various fixes

### LINKED ISSUE #10003: Pipewire audio output driver errors when quitting
### Important Information

MPV Version (Git built locally):
```sh
mpv 0.34.0-234-gfcc81cd940 Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
 built on Mon Mar 21 08:01:18 2022
FFmpeg library versions:
   libavutil       57.24.100
   libavcodec      59.24.100
   libavformat     59.19.100
   libswscale      6.5.100
   libavfilter     8.28.100
   libswresample   4.5.100
FFmpeg version: N-106266-g9805a0004c
```

OS: archlinux 5.16.15-zen1-1-zen 
WM: river

### Reproduction steps

Play an audio file with `mpv --no-config --ao=pipewire file.mp3` and subsequently quit using `q`

### Expected behavior

Quit Cleanly

### Actual behavior

Error shown below
```sh
Exiting... (Quit)
'!impl->polling' failed at ../pipewire/spa/plugins/support/loop.c:856 impl_clear()
[1]    525848 IOT instruction (core dumped)  mpv --no-config --ao=pipewire dvsn\ -\ SEPT\ 5TH\ -\ 01\ -\ With\ Me.mp3
```

### Log file

https://0x0.st/oN4a.txt

### Solution

A solution was pointed out here on the [pipewire repo](https://gitlab.freedesktop.org/pipewire/pipewire/-/merge_requests/1171#note_1298824) stating: 

> I would consider that a bug in mpv: it does not destroy its pw_context, so the data loop is not stopped, and thus the assertion fails. 

additionally

> I think it also shouldn't call pw_context_connect() without locking the thread loop.

### PR DESCRIPTION
**Pull request by t-8ch**
Details in the commit messages.

Fixes #10003 and #9992

### CODE REVIEW

**Comment by t-8ch** [comment]
Cc @philipl

**Comment by philipl** [comment]
The increased buffer size just brings us back to where we were before. I get stuttering in the video stream - seemingly in any video sync mode except `desync`.

**Comment by t-8ch** [comment]
Do you think it would help to migrate the AO to be push based? This would also solve a few other bugs.

**Comment by philipl** [comment]
I get the impression that pull-based AOs are second class citizens. If it's possible to rework to push based, I think it would help.

**Comment by t-8ch** [comment]
I'll take a look then.

I dropped the commit with the increased buffer size. Could you merge the other fix?

**Comment by philipl** [comment]
@t-8ch I can merge it, but can you update the commit description to explain the problem and the fix.

**Comment by philipl** [comment]
Thanks!

**Comment by etircopyh** [comment]
> are you sure this is correct? [docs.pipewire.org/page_thread_loop.html](https://docs.pipewire.org/page_thread_loop.html) says:
> 
> > Stopping the thread is done using [pw_thread_loop_stop()](https://docs.pipewire.org/group__pw__thread__loop.html#ga856c3aec5718bceb92d6169c42062186), which must be called without the lock (see below) held.

@t-8ch

**Comment by t-8ch** [comment]
Ouch, that looks indeed broken then. I think it worked for me when testing. I'll send a revert for that specific lock

**Comment by Hello71** [comment]
more broadly, how did you determine which calls need to be done with the lock held and which don't? for example I doubt `pw_thread_loop_start` needs the lock held; if there is no thread loop running, there shouldn't be any race condition.

**Comment by t-8ch** [comment]
@Hello71 I tried to put as many API calls into the locked section as possible.
While `ps_thread_loop_start()` probably doesn't need the lock held, it doesn't seem to be an issue.

**Pull request merged**
