### PR TITLE
fix memory leak on 2ch audio

### PR DESCRIPTION
**Pull request by mistraid121**
Hi,
I have found that this pull request:
https://github.com/mpv-player/mpv/pull/9594
did not fully solved the problem on 2 channel audio

I propose the attached pull request to solve the problem

### CODE REVIEW

**Comment by mistraid121** [comment]
Thanks kasper93, but I don't see how to change the commit message.

**Comment by kasper93** [comment]
Mostly prefix, and you can add description... like
```
af_lavcac3enc: fix memory leak on 2ch audio

If processing is not required, the frame would be leaked as it is not used.
```

**Comment by mistraid121** [comment]
Ok I am trying again, sorry it is my first pull request...

**Comment by kasper93** [comment]
Ah, if you meant you don't know how to change commit message in git. Look at this, for the future https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message

**Comment by mistraid121** [comment]
that's it; I am doing it again

**Pull request closed without merging**
