### PR TITLE
options: make osd-bar less intrusive

### PR DESCRIPTION
**Pull request by kasper93**

### CODE REVIEW

**Comment by kasper93** [comment]
@dokur0chan: What do you think about making osd-bar smaller?

**Comment by Hrxn** [comment]
Strongly in favor of this idea. To be honest, I've already thought about opening an issue about this and suggesting a change.

**Comment by dokur0chan** [comment]
~~I was mostly just joking around, I didn't expect this to be a real PR~~

If I'm being honest, even with these changes, I would probably still use `--osd-bar=no` in my personal config.

I don't think it's necessary at all. `osd-on-seek=msg` is both less intrusive and more informative, since it gives exact timestamps instead of just being a huge and inferior version of the seekbar. Reducing the size of it isn't really going to solve the heart of the issue, at least for me. 

Feedback from users who actually use `--osd-bar` is probably more useful.

**Comment by dokur0chan** [comment]
Also, if anyone is too lazy to read the commit, this is the new `--osd-bar` size.

mpv-shot0001

**Comment by wiwaz** [comment]
A step in the right direction, but I don't think any size adjustment will make this "feature" not obnoxious.

**Comment by Dudemanguy** [comment]
I wasn't aware this was controversial. I find it a useful reference to see roughly how far into the video you seeked at a quick glance. I guess `osd-on-seek=msg` is technically better for that though. I don't see the point in making the bar comically small for what it's worth.

**Comment by llyyr** [comment]
I also believe osd-on-seek=msg should be the default, or heck even just show the OSC at that point instead of the osd-bar. This has no real reason to exist except for some weird lua-less build of mpv where you don't have OSC at all

**Comment by Hrxn** [comment]
Well, of course we should use the screen width, it's good for a quick glance at the position in the video.

I'm only in favor of making it smaller, in, like less height.

**Comment by kasper93** [comment]
> I was mostly just joking around, I didn't expect this to be a real PR

I know, but for me `osd-bar` as it is today is very unnecessary big and intrusive. Maybe _obnoxious_ is not the best word to describe it, but I think most will agree it doesn't fit well even with the current OSC.

> I don't think it's necessary at all. osd-on-seek=msg is both less intrusive and more informative, since it gives exact timestamps instead of just being a huge and inferior version of the seekbar. Reducing the size of it isn't really going to solve the heart of the issue, at least for me.

Yes, I believe default should be at least `osd-on-seek=msg-bar`, for more informative display. But still the issue of huge rectangle covering your screen remains. `osd-on-seek=msg` is a solution for that, but `bar` is useful still.

> inferior version of the seekbar

is very good way to describe it. Maybe instead of `bar` we should show whole OSC on seek? Little bit much, but at least wouldn't show big white bar at the middle of the screen.

> Also, if anyone is too lazy to read the commit, this is the new --osd-bar size since there are no screenshots.

Yes, that's it. I believe is mostly useful for volume control.  So the main idea is mimic the bar size/position that is used in this cases by various wm. And most are not using huge bars in the center of the screen. 

As you can see, I'm using `osd-on-seek=msg-bar` myself. And of course this PR is RFC, I put those dimension in 1 minute, but I still think making bar "full screen" is unnecessary. It probably could be scaled up, so it needs only one read arrow to point it, instead of 4.

image

(probably without better solution, we will not agree on anything, just changing the size is not enough of a change)

**Comment by Hrxn** [comment]
Even better: What about making the osc bar configurable, analogous to `osc.conf`, basically?

**Comment by kasper93** [comment]
> Even better: What about making the osd bar configurable, analogous to osc.conf, basically?

It is configurable.

```
--osd-bar-align-x=<-1-1>
    Position of the OSD bar. -1 is far left, 0 is centered, 1 is far right. Fractional values (like 0.5) are allowed.
--osd-bar-align-y=<-1-1>
    Position of the OSD bar. -1 is top, 0 is centered, 1 is bottom. Fractional values (like 0.5) are allowed.
--osd-bar-w=<1-100>
    Width of the OSD bar, in percentage of the screen width (default: 75). A value of 50 means the bar is half the screen wide.
--osd-bar-h=<0.1-50>
    Height of the OSD bar, in percentage of the screen height (default: 3.125).
```

**Comment by Hrxn** [comment]
Oh, that's nice. Wasn't aware, and I've been using mpv for quite some time now.. 😆

Guess I've tried this some time ago and it was not behaving as I thought, like for example the show playlist position, length and full title info from the OSC, which *should* follow `osd-font-size`, and it kinda does, but I think the scaling factors are kinda skewed here, not sure..

**Comment by kasper93** [comment]
> msg (the text that says "volume: X%") should be centered and above (preferably configurable location) the bar

Not sure we want to move standard OSD msg position. 

> bar border and "colors" should be configurable since sometimes it's hard to "read" it because the video might have same colors.

**Comment by Artoriuz** [comment]
>I know, but for me osd-bar as it is today is very unnecessary big and intrusive. Maybe obnoxious is not the best word to describe it, but I think most will agree it doesn't fit well even with the current OSC.

It's big when you're up close watching things on a computer monitor, but the size definitely helps when you're a bit far away watching things on a TV or projector.

Point is just that size is relative.

**Comment by kasper93** [comment]
> It's big when you're up close watching things on a computer monitor, but the size definitely helps when you're a bit far away watching things on a TV or projector.

Set system-wide DPI correctly for your viewing conditions. Or `osd-scale`. 

Also actually the height is not that bad it is more that the 75% of the width.

Adjusting volume in Gnome, Windows, macOS and so on, does not put huge bar on the full screen. Unless you are [wob](https://github.com/francma/wob) enjoyer.

There is no denying mpv UX/UI is not great, not sure if making bar smaller helps, but at least it doesn't slap you in the face every time you push a button.

**Comment by llyyr** [comment]
This can overlap subtitles now, I believe the ideal thing to do here is just disable it by default and/or make seeking flash the osc instead of this

**Comment by kasper93** [comment]
> or make seeking flash the osc instead of this

What about volume? For volume it is quite useful to have bar.

**Comment by kasper93** [comment]
Updated with more sane size. Still smaller though. And changed `--osd_on_seek` to `msg`. I think `bar` is useful, just not really for seeking, but if you disagree, we can go with `msg-bar`. I think showing timestamp is important.

**Comment by llyyr** [comment]
This looks fine now I suppose, but personally I'd prefer if the bar for volume was somewhere in a corner, this PR along with `--osd-bar-align-x` set to +/- 0.8 or so is what satisfies my autism personally.

**Comment by kasper93** [comment]
`.osd_bar_align_y = 0.8` is safe, because it is centered, and doesn't have to align with anything. Although I agree, it overlaps subtitles, which is not a big deal, but still. So we could go back to `0.5` or `0.6`, but this doesn't resolve the bar sticking in the middle of fov

I was thinking
```
.osd_bar_align_y = -0.88,
.osd_bar_align_x = 0.9,
```
image

but depending on the osd font and so on it is not aligned perfectly, so might trigger some people. Although it puts the bar out of the way, so if you want to look at it, you can, but you are not forced to.

**Comment by Artoriuz** [comment]
I'd settle with one or another, honestly. Having both of them (text + bar) simultaneously seems unnecessary.

**Comment by kasper93** [comment]
> I'd settle with one or another, honestly. Having both of them (text + bar) simultaneously seems unnecessary.

Not easy to do without breaking everything. `osd-auto` defaults to msg+bar. It would be really awkward to change that.

**Comment by haasn** [comment]
I don't think this commit improves the status quo.

Can't we just make seeking bring up the OSC bar, and then remove `osd-bar` altogether?

**Comment by sfan5** [comment]
Agreed. While the small bar makes sense together with volume (because you don't need to see it precisely) it does not make sense in other cases, e.g. you can barely see any chapter marks when seeking.
If you don't like the bar disable it for yourself and we can even disable it by default if osc.lua is loaded.
But no need to make drastic changes or remove it entirely.

**Comment by ProxyVT** [comment]
If anyone reopens a PR on this topic, here is my version of the updated OSD.
mpv-shot0001

Of course, changes to the OSD will always be a topic of debate, and I'm open to criticism if needed. In my opinion, such a layout and size are quite balanced for informing the user, but at the same time not too distracting from viewing (that’s why I adjusted the size of osd-bar and osd-text to the size of stats, and also centered them).

<p>
<details>
<summary>More examples</summary>

Scrolling video
mpv-shot0002

Changing volume
mpv-shot0003

Secondary subtitles
mpv-shot0004

</details>
</p>

In my opinion, the only possible drawback is the overlap of the OSD with secondary subtitles, but in general, osd-bar located high enough to the edge of the screen so this does not happening when scrolling through the video (last screenshot). In the case of full OSD, there will be overlap, but I think this is not so significant.

My config:

    osd-on-seek=bar
    osd-align-x=center
    osd-font-size=20
    osd-bar-h=1.3
    osd-bar-w=30
    osd-bar-align-x=0
    osd-bar-align-y=-0.988
    osd-border-size=2.3
    osd-border-color=0.15/0.15/0.15
    osd-blur=0.1

**Pull request closed without merging**
