### PR TITLE
subprojects: add a libplacebo wrap

### PR DESCRIPTION
**Pull request by nekopsykose**
helps with https://github.com/mpv-player/mpv/pull/11952, since distros don't have v6 yet

### CODE REVIEW

**Comment by nekopsykose** [comment]
i have it set to v5 because this is what builds presently. this looks something like:  

```
$ meson setup -Dlibplacebo=enabled -Dlibplacebo-next=enabled . out
....
Run-time dependency libplacebo found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency libplacebo

Executing subproject libplacebo 

libplacebo| Project name: libplacebo
libplacebo| Project version: 5.264.1
....
```

using it would need the makedepends for libplacebo added to CI too (glad, ...)

**Comment by nekopsykose** [comment]
> i have it set to v5 because this is what builds presently  

actually master builds with v6 too, so may as well use the latest tag.

this could also theoretically just be a wrap-file and use the tarballs, but git allows using any revision if needed later.

**Comment by nekopsykose** [comment]
ready as-is. the actual v6 bump in https://github.com/mpv-player/mpv/pull/11952 could also make the requisite CI changes there to add needed dependencies for the subproject to build in the CI. should just be glad/mako/lcms2/dovi/glslang/spirv-tools iirc

**Comment by nekopsykose** [comment]
for specifics on how the fallback already works, refer to https://mesonbuild.com/Wrap-dependency-system-manual.html#provide-section

since we use `required: get_option('libplacebo')`, that means the fallback won't happent with `disabled` or `auto`- meaning this only happens when it's both explicitly =enabled and not already found on the system

**Comment by haasn** [comment]
Is it possible to do this in a way that only affects the CI? I'm not sure I'm comfortable pinning some arbitrary libplacebo version (that somebody then has to remember to update on new releases) in the mpv default build process.

**Comment by nekopsykose** [comment]
> Is it possible to do this in a way that only affects the CI?  

theoretically, one could just write this file from a ci script (i.e. ci starts, runs make-something.sh, that writes the .wrap file before meson runs). that would work for ci and not leave around anything for regular git use.

**Comment by nekopsykose** [comment]
that said, since it currently requires >=6.292 and nobody has complained (and the ci for mingw just clones libplacebo manually instead), there isn't really anything to fix

**Comment by kasper93** [comment]
@haasn @nekopsykose Can we reopen this and also remove `libplacebo` option form `meson_options.txt`? Thanks.

**Comment by nekopsykose** [comment]
> and also remove libplacebo option form meson_options.txt?  

only there, or to make it entirely non-optional?

**Comment by kasper93** [comment]
I would like to make gpu-next/libplacebo mandatory dependency of mpv. This may be controversial change. But it would allow to reduce some code duplication and eventually make gpu-next default vo.

I think good first step would be to have wrap and make libplacebo not optional. @haasn thoughts?

**Pull request closed without merging**
