### PR TITLE
vo_drm: improve signal handling

### PR DESCRIPTION
**Pull request by rr-**
Should fix point 3 from wm4's comment in #2435.

### CODE REVIEW

**Comment by rr-** [comment]
The references to SIGUSR1 and SIGUSR2 were used all over the place.

1. I didn't want to hardcode them like this any further.
2. It wasn't clear whether SIGUSR1 was used for acquire, or release - one had to look up the usage in the middle of the file.

**Comment by rr-** [comment]
BTW I noticed that `osdep/terminal-unix.c` doesn't seem to check for sigaction results.

**Comment by wm4** [comment]
If they're just constants, maybe ``#define`` them.

> BTW I noticed that osdep/terminal-unix.c doesn't seem to check for sigaction results.

Maybe it should. On the other hand, maybe this is not worth checking. Actually, let's just consider it not worth checking. In the interest of a minor robustnest improvement, you should still zero-init the ``act`` variable.

**Comment by rr-** [comment]
Updated~

**Comment by wm4** [comment]
Just one thing: move the signal uninstallation above the ``close()`` calls which close the wakeup pipe. Otherwise you have (theoretical) race conditions.

**Comment by rr-** [comment]
Done

**Comment by wm4** [comment]
Nice. Will merge later.

**Comment by wm4** [comment]
Merged, thanks.

**Pull request closed without merging**
