### PR TITLE
win32: support get display fps

### PR DESCRIPTION
**Pull request by avih**
A bit ugly, but apparently I'm not the first to use this exact trick.

### CODE REVIEW

**Comment by wm4** [comment]
Well, this looks certainly weird... and is probably completely wrong. Where did you get this trick and why do you think it works?

AFAIK the only way to get the actual display FPS on windows is to measure it, or in some cases using certain other APIs. See #1543.

I'd rather want to be careful with this, because the display FPS is used for framedropping. So if a display FPS lower than real is reported, the player will drop frames that it shouldn't.

Also, this value should probably be cached, because this function will be called on every frame.

**Comment by avih** [comment]
This member is integer type and is used when setting the refresh rate or reading the current or supported refresh rates. So the practice for drivers and windows, in order to distinguish 23.97 from 24 etc, is to use 23 as representing 23.97, and 24 for 24, and same for the other values.

**Comment by avih** [comment]
I rebased and added the new signal.

However, the new mpv code seems to distort the value which the this PR produces. Prior to the rebase, reading the property display-fps from a script would return exactly what the PR produces: e.g. 59.940060 or 60.000000, but after the rebase it returns values such as 59.941258 or 60.002400 respectively.

Also, possibly unrelated, both before and after the rebase: observing the display-fps property from a script produces an event once when the video starts, but not after changing the refresh of the display, even if mpv knows the correct value (polling the display-fps property from a script does produce the correct value, and still no event is fired for the observer).

Resizing the window after a display refresh rate change finally triggers the event for the observer.

**Comment by wm4** [comment]
Apparently the microsecond rounding matters.

> both before and after the rebase: observing the display-fps property from a script produces an event once when the video starts, but not after changing the refresh of the display, even if mpv knows the correct value (polling the display-fps property from a script does produce the correct value, and still no event is fired for the observer).

Shouldn't happen, not sure why it does.

**Comment by wm4** [comment]
Merged, thanks.

I fixed the wrongly rounded fps return.

Does the fps not being updated still happen?

**Comment by avih** [comment]
> Does the fps not being updated still happen?

Seems to be fixed now - the event fires correctly right after screen fps change. Thanks.

**Pull request closed without merging**
