### PR TITLE
lavfi_complex: enable it conditionally

### PR DESCRIPTION
**Pull request by mfcc64**
based on number audio/video tracks and attached picture

change it to OPT_STRING_APPEND_LIST so it can be specified
multiple times and choosed based on track numbers

I agree that my changes can be relicensed to LGPL 2.1 or later.

### CODE REVIEW

**Comment by wm4** [comment]
I don't think this is a good solution to whatever problem it's supposed to solve...

**Comment by mfcc64** [comment]
Yes, probably this is a hack solution, --lavfi-complex itself is also a hack.
But at least, it works.

Note: my previous solution is using auto profile [extension.mp3] etc
Thank's

**Comment by wm4** [comment]
Why is it a hack and how could it be improved?

What are you trying to do?

**Comment by mfcc64** [comment]
--lavfi-complex is a hack, but far more better than lavfi device (so I switch from ffplay to mpv as my audio player)

What I'm trying to do is to enable mpv choose lavfi-complex based on number of audio/video tracks and attached pictures

Consider this:
--lavfi-complex="0:0:1:10:0:0: graph1"
--lavfi-complex="0:0:1:10:1:1: graph2"
--lavfi-complex="1:1:0:10:0:0: graph3"

playing video.mkv will use graph3,
playing audio.mp3 will use graph1 or graph2 based on the existence of attached picture

Thank's

**Comment by wm4** [comment]
Sure, but you just described what you've said anyway, without adding new information.

Why do you need different graphs depending on stream counts?

**Comment by mfcc64** [comment]
Because I need to, for example, show visualization when playing audio file, but don't show it when playing video file. Or show visualization with attached picture when it exists, and many others. And it is done automatically.

Thank's

**Comment by haasn** [comment]
The mpv-preferred way to configure complex, conditional logic like this would be with a profile or simple lua script.

**Comment by mfcc64** [comment]
Yes, I did it previously with auto profile, but it is limited to extension name. I don't know how to configure it with lua script, can you give me an example?

**Comment by wm4** [comment]
It's not too simple, but you can set a preload hook, query the track-list, and set the lavfi-complex option.

I think there should be a simpler way to enable audio-visualizations, though.

**Comment by mfcc64** [comment]
Changed because of segmentation fault when lavfi-complex is not set.
@wm4:
> It's not too simple, but you can set a preload hook, query the track-list, and set the lavfi-complex option.
>
> I think there should be a simpler way to enable audio-visualizations, though.
Currently, I don't understand too much about lua script. Probably I can learn it.
But I think this approach is simpler than using lua script.

**Comment by wm4** [comment]
> But I think this approach is simpler than using lua script.

On the surface yes, but actually it's a very intrusive special case that _somewhat_ handles what you want to do. If we did that for every problem that occurs, the command line interface would become incredibly more complex (even more than it is now), to the degree not anyone would understand it. As a consequence, all the code involved with it would quickly bitrot. So, not an option.

**Comment by mfcc64** [comment]
> On the surface yes, but actually it's a very intrusive special case that somewhat handles what you want to do. If we did that for every problem that occurs, the command line interface would become incredibly more complex (even more than it is now), to the degree not anyone would understand it. As a consequence, all the code involved with it would quickly bitrot. So, not an option.

OK, then I will try to learn lua script.
Thanks

**Comment by wm4** [comment]
Did you have success?

Anyway, I want to provide a simpler way to enable such visualizations - but not sure when I get to it.

**Comment by mfcc64** [comment]
Yes I did, and now lua script is enough for my use-case.

Thank's

**Pull request closed without merging**
