### PR TITLE
Build: Fix dependencies for Cygwin environment.

### PR DESCRIPTION
**Pull request by feixm1**
This fixes the issue https://github.com/mpv-player/mpv/issues/4627

### CODE REVIEW

**Comment by wm4** [comment]
Seems ok. Can you remove the tabs?

**Comment by feixm1** [comment]
Sure. Done.

**Comment by wm4** [comment]
Trying to merge/rebase this causes a merge conflict. I'm not going to deal with that. Feel free to reopen with fixed commits.

**Comment by wm4** [comment]
Actually --squash made it simple, so merged. But I'm very unappreciative of PRs which cause more work than they solve.

**Pull request closed without merging**
