### PR TITLE
Removed deprecated APIs from libmpv (esp. opengl_cb)

### PR DESCRIPTION
**Pull request by sfan5**
This bumps the library version to 2.0, <b>forcing all API users to recompile</b>.

removed:
* opengl_cb: does not work since 0.33.0 and was deprecated in 0.29.0
* `mpv_detach_destroy`: deprecated since 2018
* `mpv_{suspend,resume}` (+ Lua functions): deprecated since 0.23.0 
* `MPV_EVENT_SCRIPT_INPUT_DISPATCH`: deprecated since 2014, was never useful
* `MPV_EVENT_{TRACKS_CHANGED,TRACK_SWITCHED,PAUSE,UNPAUSE,METADATA_UPDATE,CHAPTER_CHANGE}`: deprecated since 2014, still worked 

outstanding questions:
- [x] remove the events that were deprecated in 2014
- [x] ~~remove `mpv_get_wakeup_pipe`?~~ (kept)
  ~~Still works, replacement available. `mp.get_wakeup_pipe()` should also be removed.~~

stuff that is left and when it was deprecated:
symbol | when
---- | -----
`MPV_EVENT_IDLE` | 2020
`MPV_EVENT_TICK` | 2019
`mpv_get_wakeup_pipe` | 2018

### CODE REVIEW

**Comment by avih** [comment]
This would be the first ABI breakage since... ever (mpv 0.4 - the first real version).

While I agreed on IRC that removing opengl_cb would be fine - because presumably it's broken anyway, I now think that we shouldn't break the ABI only/mainly for this.

If there's internal mpv code which uses deprecated things - we can definitely remove/clean it.

We can also consider moving all deprecated things to one-ish place, as much as possible to avoid having noise at the code, but I don't think it currently adds a real maintenance burden, because all these things are just not used/maintained anyway.

**Comment by sfan5** [comment]
> If there's internal mpv code which uses deprecated things - we can definitely remove/clean it.

d6fcca74cb7f4e28a31c2aad13cbfd420349051d does exactly this, does not break ABI and could be merged independently.
It's what I initially started with but then decided to remove deprecated stuff entirely.

**Comment by Dudemanguy** [comment]
Overall, I have no problem with this. Nobody should still be using stuff like `MPV_EVENT_PAUSE` today. The only thing I don't think should be removed is `MPV_EVENT_TICK` since there's really not a 1:1 replacement for it.

**Comment by avih** [comment]
> Nobody should still be using stuff like

Your reply sounds like I want everyone to keep using it. I'm not.

I just think that in this case, the value (slightly cleaner code and maybe some reduced maintenance burden) is not worth the cost of breaking ABI for the first time in libmpv.

Even recompile will not be enough for code which uses the removed APIs. The client code will need to be edited by someone who understands it first - just to get it to compile at all.

While obviously that's needed anyway for APIs which got broken over the years (I presume opengl_cb is one of those), there are other APIs which are removed, where many clients can probably be functional even with them (already) no-op - like the suspend/resume ones.

The perfect example for this is our own `defaults.lua` which still has (before this PR) resume_all() code at its event loop. It's been no-op for years but the code keeps working, because the function still exists. It's not optimal of course, but it's a sort of "soft deprecation".

And the point is that all of this was already done in the past - and it's been unmodified for at least two releases.

This PR only breaks the ABI without actually changing functionality (I don't consider removing no-op/broken functions a change in functionality, because it already didn't do anything useful).

Which is the reason I think the value is not worth the cost in this case.

**Comment by Dudemanguy** [comment]
I don't see the value in never breaking the ABI unless we're shooting for some guinness world record or something. A recompile is not a big ask, api users still using deprecated functions are pretty much asking for it, and being able to just delete all this code is nicer than adding a bunch of no-ops.

**Comment by avih** [comment]
> nicer than adding a bunch of no-ops.

Nothing needs to be added. It's already no-op.

https://ludocode.com/blog/flatpak-is-not-the-future

**Review by Dudemanguy — APPROVED** [review]
LGTM, I think removing all this legacy stuff is worth it.

**Comment by jeeb** [comment]
I think that cleaning non-working things is a Good Thing, and as long as there has been a forward migration path for long enough.

For the record, I really admire Microsoft for keeping ABI compatibility between Windows versions, and that for actual OS level APIs I aspire for such stability. But mpv is not on such level in my honest opinion :) .  It's not a libc, it's not a base sound or graphics library, it's not a media framework like media foundation or DirectShow (or VFW), it's not a GUI toolkit like Qt or wx (or any of the toolkits in Windows).

Anyways, at this point the questions are:
1. whether there's anything clear which was not removed yet not due to not having had a replacement path (I see `vo_libmpv` being mentioned in some places, for example.
2. any struct/type etc changes which people would like to do as the bump is made. A major bump is a chance for changing such things.

As for actual changes being done at bump, that is generally less common. Usually when you deprecate you gate something behind `#if MPV_CLIENT_API_VERSION < XYZ` where XYZ is f.ex. current plus 1 or 2. That way when the ABI gets bumped, you automagically switch over, and the only commit left is the clean-up of now-inactive code. Alternatively, if some type etc is supposed to change at a bump, it gets similar treatment.

And yes, ABI bumps are generally not that fancy or fun, as most changes you can do do not require them (although the ABI comparator will have differing opinons on adding entries to end of structs etc being still OK or not). Only when types are wanted to be changed or actual cruft that didn't work removed (such as `opengl_cb`) you require an ABI bump.

**Comment by sfan5** [comment]
> 1. anything clear which was not removed yet not due to not having had a replacement path

As listed in the OP post this is:
* `MPV_EVENT_IDLE`: replaceable with observing property but deprecated only recently 
* `MPV_EVENT_TICK`: unclear replacement, the tick event is sent at unique but not well defined intervals
* `mpv_get_wakeup_pipe`: replacement available, but still used inside mpv which would be additional work to remove

> 2. changes which people would like to do as the bump is made

The header mentions two more that I haven't done:
```markdown
 *  - reassign enum numerical values to remove gaps
 *  - disabling all events by default
```
Renumbering enums is more trouble than it's worth, consider e.g. bindings that have to keep [a copy of the defines](https://github.com/mpv-android/mpv-android/blob/master/app/src/main/java/is/xyz/mpv/MPVLib.java#L131) in sync.
Disabling all events by default has lots of expected breakage and my main concern would have been with the `tick` even which is *not* enabled by default. So again not much reason to do it.

**Comment by avih** [comment]
> I really admire Microsoft for keeping ABI compatibility between Windows versions

For the record, I'm not against breaking ABI when it has a good value, e.g. when it stands in the way of progress or if it adds meaningful maintenance burden.

However, in this case the reason is marely "cleanup because it was declared depracated long ago".

It does not impede progress, and it does not add meaningful (and probably any) maintenance burden.

So in this case I think the reasons are not compelling enough to warrant it, especially when we weight it against the pain (to clients and distros) which is ABI breakage.

**Pull request merged**
