### PR TITLE
draw_bmp: Fix asserts for point/point functions

### LINKED ISSUE #9509: Crash on vo=wlshm with kwin when snapping to screen
### Important Information

Provide following Information:
- mpv version: Built at dc73f1ad4b235f24657ae53cf82dd18f933cc8f0 also occured on `0.34.0`
- Linux Distribution and Version: Arch linux, kernel: `5.15.2-arch1-1`
- Source of the mpv binary: Arch packages and built from head.
- If known which version of mpv introduced the problem: Unknopwn
- Window Manager and version: kwin `5.23.3`
- GPU driver and version: nvidia 495.44
- Possible screenshot or video of visual glitches: It crashes

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.\

1) Run mpv with `mpv --no-config --vo=wlshm --gpu-context=wayland Big_Buck_Bunny_1080_10s_1MB.mkv`
1) Snap the window to the right side of the monitor by dragging it until it snaps.
1) Wait about 1s and it should crash.

### Expected behavior

For there to be no crashes.

### Actual behavior

mpv crashes.

### Log file

Log : https://0x0.st/-7ub.txt

The backtrace from the crash with symbols is

```
[Switching to Thread 0x7fffdaffd640 (LWP 137097)]
(gdb) bt
#0  0x00007ffff53fad22 in raise () at /usr/lib/libc.so.6
#1  0x00007ffff53e4862 in abort () at /usr/lib/libc.so.6
#2  0x00007ffff543cd28 in __libc_message () at /usr/lib/libc.so.6
#3  0x00007ffff544492a in  () at /usr/lib/libc.so.6
#4  0x00007ffff5447d5c in _int_malloc () at /usr/lib/libc.so.6
#5  0x00007ffff54494e1 in malloc () at /usr/lib/libc.so.6
#6  0x00007ffff581aef4 in  () at /usr/lib/libwayland-client.so.0
#7  0x00007ffff581b85f in  () at /usr/lib/libwayland-client.so.0
#8  0x00007ffff581978a in wl_display_read_events () at /usr/lib/libwayland-client.so.0
#9  0x00005555556a08d1 in vo_wayland_dispatch_events
    (wl=wl@entry=0x7fffbc000bb0, nfds=nfds@entry=1, timeout=17)
    at ../video/out/wayland_common.c:1528
#10 0x00005555556a3160 in vo_wayland_wait_frame (wl=wl@entry=0x7fffbc000bb0)
    at ../video/out/wayland_common.c:1991
#11 0x00005555556a3460 in flip_page (vo=<optimized out>) at ../video/out/vo_wlshm.c:278
#12 0x000055555567915f in render_frame (vo=0x5555557bd050) at ../video/out/vo.c:971
#13 vo_thread (ptr=0x5555557bd050) at ../video/out/vo.c:1098
#14 0x00007ffff609f259 in start_thread () at /usr/lib/libpthread.so.0
#15 0x00007ffff54bc5e3 in clone () at /usr/lib/libc.so.6
```

### Sample files

https://download.blender.org/demo/movies/BBB/

### PR DESCRIPTION
**Pull request by kkartaltepe**
Some drawing functions operate on point/point instead of point/bounds
definitions. This causes off by 1 errors where drawing routines with bounds
will add the width/height to the origin point resulting in a point
outside the bounds of the original box and then pass this through to the
point/point function as the 2nd point defining the box.

This causes out of bounds memory access in general but especially
noticable when mark_rect accesses non-existant slices because it is
trying to access pixels across the slice boundary due to this off by 1.

This is an alternate solution to #9242, and also resolves #9509 for me and is clean on address sanitizer.

### CODE REVIEW

**Comment by kkartaltepe** [comment]
and to be clear i just updated the callers of mark_rect, im not totally sure about the `render_rgba` changes as im not sure about the structure of the sub_bitmap stuff (what dw/dh are supposed to represent) or if this code path is tested in my simple use of the OSD that triggered the original error.

**Comment by tantei3** [comment]
I tried this PR, and it seems like the last row and column of pixels are not used for OSD which is a regression I believe. #9242 I think doesn't cause this regression. I think you'll have to also make changes so that either you store the width + 1 in `mark_rect` or that in the drawing part you handle this off-by-one which would seem a lot more change. 

Here is the screenshot of what I observed on running `./build/mpv -vf scale=1280:720 --vo=x11 https://www.youtube.com/watch?v=aqz-KE-bpKQ --no-config` in dwm window manager with center part cropped with a black background, you can observe the last row and column being white instead of the dark color indicating they're not part of OSD rectangle.

image

**Comment by kkartaltepe** [comment]
> I tried this PR, and it seems like the last row and column of pixels are not used for OSD which is a regression I believe. #9242 I think doesn't cause this regression. I think you'll have to also make changes so that either you store the width + 1 in mark_rect or that in the drawing part you handle this off-by-one which would seem a lot more change.

Thanks for giving it a try and finding the regression, ill try and take a look for where this is used to fix the off by one. But you might be right and it may be a big mess to clean up.

**Comment by kkartaltepe** [comment]
Probably wont have time to work on this, so ill close it for now.

**Pull request closed without merging**
