### PR TITLE
Add support for Dolby Vision

### PR DESCRIPTION
**Pull request by haasn**

### CODE REVIEW

**Comment by haasn** [comment]
I suppose we should also have an option to disable it.

**Comment by Doofussy2** [comment]
Until the work is completed and fully implemented, it would be useful if there were a condition we could set for dovi to allow us set gpu-next for dovi. For HDR I use bt.2020, but that's too generic. A way to differentiate HDR10 and DoVi would be incredibly useful. Would this be possible?

**Comment by haasn** [comment]
> Until the work is completed and fully implemented, it would be useful if there were a condition we could set for dovi to allow us set gpu-next for dovi. For HDR I use bt.2020, but that's too generic. A way to differentiate HDR10 and DoVi would be incredibly useful. Would this be possible?

I'm not sure if I understood your post. You basically want a property to tell if the image has dovi metadata or not? We could definitely add that.

Also, that actually gives me an idea for how to handle the `--dolbyvision` option better: just add a `vf_format` suboption to strip dovi metadata. That way users can toggle the filter on and off at runtime, and it would still propagate to the VO correctly (since changing the filter list would flush the vo).

**Comment by Doofussy2** [comment]
> > Until the work is completed and fully implemented, it would be useful if there were a condition we could set for dovi to allow us set gpu-next for dovi. For HDR I use bt.2020, but that's too generic. A way to differentiate HDR10 and DoVi would be incredibly useful. Would this be possible?
> 
> I'm not sure if I understood your post. You basically want a property to tell if the image has dovi metadata or not? We could definitely add that.
> 
> Also, that actually gives me an idea for how to handle the `--dolbyvision` option better: just add a `vf_format` suboption to strip dovi metadata. That way users can toggle the filter on and off at runtime, and it would still propagate to the VO correctly (since changing the filter list would flush the vo).

Yes, exactly that. Being able to choose vo at runtime or other options would be amazing.

**Comment by haasn** [comment]
Refactored as discussed: removed `--dolbyvision` option, instead added `-vf format:dolbyvision` suboption (`yes`/`no` meaning respectively to apply/strip metadata).

**Comment by haasn** [comment]
I also looked into adding this as a property but I could not find a clean way to map it - it can't be part of `mp_image_params` because it's refcounted, so it can't really fit into `video-params`. Since it's a per-frame property it also inherently isn't constant for the whole stream, so there is a fundamental issue here in trying to expose it, even as a read-only property.

**Comment by haasn** [comment]
That said, what we totally *could* expose in some way is the stream-level dovi configuration record, that way you could look at things like the dovi profile level and whatnot.

**Comment by Doofussy2** [comment]
The use case I am most interested in is, using an auto-profile for dovi. Presently, I need to use vo_gpu for the hardware acceleration, and other things. So , when this gets merged and I can use mpv for dovi media, I will need to set vo_gpu_next at runtime, disable hardware acceleration and probably throw in a few other options. _Or maybe I won't?_ Will the vo be set automatically for dovi media and fall back to software decoding? I guess I should have asked that before making the request.

**Comment by haasn** [comment]
Sounds like what you *actually* want is for `vo_gpu_next` to support hardware decoding

**Comment by Doofussy2** [comment]
> Sounds like what you _actually_ want is for `vo_gpu_next` to support hardware decoding

Ideally, yes. But my CPU is strong enough. 

I may actually be confusing two separate entities. I assumed this was strictly part of vo_gpu-next, and not useable with vo_gpu. Is that a wrong assumption?

**Comment by Natural-Harmonia-Gropius** [comment]
lg amaze, dovi p5 bt709 bt1886, looks less contrast than uwp with dovi ext.
and mpv shows `tone-mapping` in frame timings page, is that normal?
mpv dovi
uwp dovi

**Comment by dyphire** [comment]
I think we should keep a separate option for dolbyvision. If `vo_gpu_next` support hardware decoding in the future, the vf filter will be not work when people use hwdec.

**Comment by haasn** [comment]
> If vo_gpu_next support hardware decoding in the future, the vf filter will be not work when people use hwdec.

Incorrect, `vf_format` can be combined with hwdec just fine.

**Comment by dyphire** [comment]
> > If vo_gpu_next support hardware decoding in the future, the vf filter will be not work when people use hwdec.
> 
> Incorrect, `vf_format` can be combined with hwdec just fine.

Oh, that would be great.

**Comment by Natural-Harmonia-Gropius** [comment]
I think we need a new steeper curve with much stronger shadow and less highlight for dovi.

top mpv, bottom uwp with dovi ext
bt.2446a is the darkest curve, but even brighter than uwp.
```ini
hdr-compute-peak=no
tone-mapping=bt.2446a
gamut-mapping-mode=clip
```
image
image
image
image

with `tone-mapping=auto` result this one, too bright.
image

**Comment by haasn** [comment]
That file looks pretty broken, can you extract that frame and upload it somewhere?

**Comment by Natural-Harmonia-Gropius** [comment]
https://1drv.ms/v/s!AlXacxDwIFe73dMI3cFcGeEBF2USlQ?e=BSkyUB
`estimated-frame-number` shows  610

**Comment by Natural-Harmonia-Gropius** [comment]
more tests

[sample1@600](https://1drv.ms/v/s!AlXacxDwIFe73dMI3cFcGeEBF2USlQ?e=BSkyUB)
[sample2@3600](https://1drv.ms/v/s!AlXacxDwIFe73dMNUz-zWKAVgDuyzw?e=VjP6Zr)
[sample3@1109](https://1drv.ms/v/s!AlXacxDwIFe73qcBr0XhpeQ7t0WMzg?e=KITRWp)

mpv.conf
```
hdr-compute-peak=no
tone-mapping=bt.2446a
gamut-mapping-mode=clip
```

`tone-mapping-mode=luma` / `tone-mapping-mode=rgb` / uwp dovi ext

**Comment by ValZapod** [comment]
> ~lg amaze, dovi p5 bt709 bt1886, looks less contrast than uwp with dovi ext. and mpv shows `tone-mapping` in frame timings page, is that normal?~
> issue about stats.

a) The file is broken, it has crazy artifacts on red on LG C9 official HW player same as Movies& TV with two DV extensions b) libplacebo does not support dynamic metadata yet (and NLQ), so **if those are present** it is its fault. Also, I will point out that Movies&TV is not the same as LG C9's reference player anyway, last one is so much better. After calibration especially :)

**Comment by Natural-Harmonia-Gropius** [comment]
reds in uwp too, maybe camera's fault……
image

**Comment by ValZapod** [comment]
> reds in uwp too, maybe camera's fault……

[cosmos-p5.zip](https://github.com/mpv-player/mpv/files/7834287/cosmos-p5.zip)

Then how the same happens with animation here? LOL. No, it is IPTPQc2 fault, I am sure.

@nica

**Comment by Natural-Harmonia-Gropius** [comment]
maybe talk red after https://github.com/mpv-player/mpv/issues/9403 soluted.
i did some tricky things……
about this lut https://trev16.hatenablog.com/entry/2020/06/07/094646
```
target-prim=bt.2020
target-lut=~~/GamutMapping_ITU-R_BT.2020_to_ITU-R_BT.709_Gamma_2.4_65x65x65.cube
```
image

**Comment by ValZapod** [comment]
> For HDR I use bt.2020, but that's too generic. A way to differentiate HDR10 and DoVi would be incredibly useful. Would this be possible?

HDR has nothing to do with 2020. It is BT.2100 and has everthing to do with the new tranfer function. Dolby Vision is identified by specific metadata  in ffmpeg

Side data:
      DOVI configuration record: version: 1.0, **profile: 5**, level: 6, rpu flag: 1, el flag: 0, bl flag: 1, compatibility id: 0

Profile 5 means it uses PQ as part of IPTPQc2 color space.

**Comment by Natural-Harmonia-Gropius** [comment]
> > For HDR I use bt.2020, but that's too generic. A way to differentiate HDR10 and DoVi would be incredibly useful. Would this be possible?
> 
> HDR has nothing to do with 2020. It is BT.2100 and has everthing to do with the new tranfer function. Dolby Vision is identified by specific metadata in ffmpeg
> 
> Side data: DOVI configuration record: version: 1.0, **profile: 5**, level: 6, rpu flag: 1, el flag: 0, bl flag: 1, compatibility id: 0
> 
> Profile 5 means it uses PQ as part of IPTPQc2 color space.

so i just set target-prim, mpv/placebo do tone-mapping from pq to bt1886 as it should be.

**Comment by ValZapod** [comment]
> do tone-mapping from pq to bt1886 as it should be.

Your display is calibrated for 2.4 gamma with black offset? Are you sure?

**Comment by Doofussy2** [comment]
> > For HDR I use bt.2020, but that's too generic. A way to differentiate HDR10 and DoVi would be incredibly useful. Would this be possible?
> 
> HDR has nothing to do with 2020. It is BT.2100 and has everthing to do with the new tranfer function. Dolby Vision is identified by specific metadata in ffmpeg

You aren't understanding my request. Until vo_gpu_next is fully implemented and uses hardware acceleration, I have to use vo_gpu for most things. I use auto-profiles to distinguish types of media. While HDR is not mutually exclusive with bt.2020, most HDR media does use that. There is no other property to distinguish HDR from SDR, I wish there were. So I use bt.2020 for the property. Dolby Vision wasn't supported, so it didn't matter. But now that Dolby Vision is supported with vo_gpu_next, for me to use it, I have to create an auto-profile specifically for Dolby Vision, so I can switch the vo and disable the hardware acceleration, and possibly other options. But it looks like that isn't going to happen, so I still won't be able to use mpv for Dolby Vision.

**Comment by Natural-Harmonia-Gropius** [comment]
> There is no other property to distinguish HDR from SDR

[hdr]
profile-cond=p["video-params/sig-peak"] > 1

[rec2020]
profile-cond=p["video-params/primaries"] == "bt.2020" and p["video-params/gamma"] == "bt.1886"

[rec2100-pq]
profile-cond=p["video-params/primaries"] == "bt.2020" and p["video-params/gamma"] == "pq"

[rec2100-hlg]
profile-cond=p["video-params/primaries"] == "bt.2020" and p["video-params/gamma"] == "hlg"

**Comment by ValZapod** [comment]
> distinguish HDR from SDR, I wish there were

It is tranfer function either HLG or PQ.

>so I still won't be able to use mpv for Dolby Vision

Well, for profile 5 you will not be able to use it at all, since the colors are reversed. There is insane anmount of profile 5 content on rarbg though. 36 pages as for now of **only** profile 5. I literally watch only DV profile 5 last 4 months? An I did not watch all, like Fauci documenatry is DV. Yeah, it is in DV, LOL.

**Comment by Doofussy2** [comment]
> > There is no other property to distinguish HDR from SDR
> 
> [hdr] profile-cond=p["video-params/sig-peak"] > 1
> 
> [rec2020] profile-cond=p["video-params/primaries"] == "bt.2020" and p["video-params/gamma"] == "bt.1886"
> 
> [rec2100-pq] profile-cond=p["video-params/primaries"] == "bt.2020" and p["video-params/gamma"] == "pq"
> 
> [rec2100-hlg] profile-cond=p["video-params/primaries"] == "bt.2020" and p["video-params/gamma"] == "hlg"

Which is more or less what I'm doing, but this doesn't allow creation of a DV profile, which is the point of the request.



> > distinguish HDR from SDR, I wish there were
> 
> It is transfer function either HLG or PQ. DV profile 5 is not tagged though in VUI but IT IS PQ.
> 
> > so I still won't be able to use mpv for Dolby Vision
> 
> Well, for profile 5 you will not be able to use it at all, since the colors are reversed. There is insane anmount of profile 5 content on rarbg though. 36 pages as for now of **only** profile 5. I literally watch only DV profile 5 for the last 4 months? An I did not watch it all, like Fauci documenatry is DV. Yeah, it is in DV, LOL. Like now I just watched Matrix 4 in DV 5 and now watched Ron’s Gone Wrong in DV and now planning on Resident evil: racoon city.

So it's not possible to correctly play profile 5 with this commit? If that is true, then my request moot.

**Comment by ValZapod** [comment]
> possible to correctly play profile 5 with this commit? If

It is possible, mostly, dynamic meta is not supported.

**Comment by Natural-Harmonia-Gropius** [comment]
> Your display is calibrated for 2.4 gamma with black offset? Are you sure?

that doesn't matter. anyway it's **gamma**.

> Professional SDR monitor
Rec.709, BT.1886 / Gamma 2.4, 100 cd/m2

who use this kind of display settings in daily? at least not for me.

**Comment by Doofussy2** [comment]
> > possible to correctly play profile 5 with this commit? If
> 
> It is possible, mostly, dynamic meta is not supported. But all reshaping and new color matrix is working.

Then I would still require a property, which appears to not be possible...

**Comment by ValZapod** [comment]
> anyway it's **gamma**

BT.1886 is 2.4 gamma on OLED.

**Comment by ValZapod** [comment]
> who use this kind of display settings in daily? at least not for me.

Then you need to use 2.2 gamma or sRGB (those most of displays are not calibrated for sRGB transfer either, it is rarger difverent from 2.2).

**Comment by ValZapod** [comment]
> would still require a property, which appears to not be possible

This can be fixed as follows: tecnically profile 5 always used PQ, so expose that as PQ. A patch should be in ffmpeg b) modify you script to switch to next if it has side-data of dovi profile 5.

**Comment by Doofussy2** [comment]
> > would still require a property, which appears to not be possible
> 
> This can be fixed as follows: tecnically profile 5 always used PQ, so expose that as PQ. A patch should be in ffmpeg b) modify your script to switch to next if it has side-data of dovi profile 5.

HDR10 is also PQ, and I'm using auto-profiles. I need to differentiate between HDR10 and Dolby Vision.

**Comment by haasn** [comment]
> I think we need a new steeper curve with much stronger shadow and less highlight for dovi.

Having looked at it in more detail, I think this sample is just terribly mastered. (Way too bright, way brighter even than the text right next to it)

I recommend testing on real blu-ray releases, not marketing/demo wank

**Comment by ValZapod** [comment]
> testing on real blu-ray releases, no

Those do not even use IPTPQc2 (is MMR done in IPT anyway there?). BTW, there appears to be a problem that black is 1, 1, 0 in HLG in YCbCr sample above. That should be fixed :)

**Pull request merged**
