### PR TITLE
manpage: link to GNOME's idle-inhibit bug

### PR DESCRIPTION
**Pull request by tomfitzhenry**
I'm glad to see GNOME are working on supporting the idle-inhibit standard!

It took me a while to find GNOME's issue. Hopefully others who read the man page will more easily be able to find the relevant issue, as of this PR.

### CODE REVIEW

**Comment by Dudemanguy** [comment]
A link is okay, but the GNOME rant in the manpage is warranted imo until they at least start using this standard.

**Comment by tomfitzhenry** [comment]
> A link is okay, but the GNOME rant in the manpage is warranted imo until they at least start using this standard.

Done.

**Comment by tomfitzhenry** [comment]
@Dudemanguy , are there other ways this PR can be improved?

**Comment by Dudemanguy** [comment]
I mean you just changed an existing link with no context. If you want to add a link to this specific issue, it needs more explanation and context.

**Comment by tomfitzhenry** [comment]
I've lost context on this PR, sorry.

**Pull request closed without merging**
