### PR TITLE
fix ffmpeg configure checks

### PR DESCRIPTION
**Pull request by pigoz**

### CODE REVIEW

**Comment by wm4** [comment]
Seems like Libav is failing. But that is ok. Just adjust the error message to say "Libav git" or "Libav 12" (the latter is not released yet).

**Comment by pigoz** [comment]
Failing on Libav git is unexpected though. Or is it?

**Comment by wm4** [comment]
Oh, right.

**Comment by wiiaboo** [comment]
List of libav/ffmpeg lib versions for reference: https://i.fsbn.eu/nkLG.txt

**Pull request closed without merging**
