### PR TITLE
vo_gpu: adjust PRNG variant used by GL shaders

### PR DESCRIPTION
**Pull request by sfan5**
see commit description

I'm not a graphics guy, so this might be the worst idea you've ever seen
~~also `gl_sc_is_gles()` feels like a terrible hack~~
@haasn

### CODE REVIEW

**Comment by haasn** [comment]
How much does the visual quality change on non-ES platforms? Is it possible we could change the code and always use the more compatible PRNG, without having to check for ES?

**Comment by jeeb** [comment]
I do tend to agree with @haasn here. If there's no real difference between the two, we might as well go with a more compatible thing always.

**Comment by sfan5** [comment]
updated.

**Comment by haasn** [comment]
re: that screenshot it seems subtly darker to me, also maybe it looks different in motion.

**Pull request merged**
