### PR TITLE
man: fix links (lua.rst)

### PR DESCRIPTION
**Pull request by lexazloy**

### CODE REVIEW

**Comment by wm4** [comment]
What is this needed for? These links work perfectly fine in the HTML build (i.e. on the website) without your changes.

**Comment by lexazloy** [comment]
On Github its not work.
Search (like example) `mpv lua api` Google will send u on Github page.

So. Its great its working on mpv site. But its must working on Github too.

**Comment by wm4** [comment]
The github rst renderer has many more problems, and if I could, I'd just disable it. You're supposed to use https://mpv.io/manual/master/ instead.

Adding these links would be pretty harmless - but the problem is that the links have to be maintained when editing the rst files (when changing the links or adding new links), and I'm not interested in this extra maintenance burden. So I'm rejecting these changes. Sorry.

**Comment by lexazloy** [comment]
> So I'm rejecting these changes. Sorry.

WHAT?? Im sooo triggered right now. :)

**Pull request closed without merging**
