### PR TITLE
f_hwtransfer: fix too aggressive preference to use direct upload format

### PR DESCRIPTION
**Pull request by kasper93**
Well, this was thinko on last minute code simplification I made. We need to check both input and output formats.

### CODE REVIEW

**Comment by llyyr** [comment]
Works

**Comment by kasper93** [comment]
Also note that the double conversion avoidance is there, but not sure it is always best. 

For example:

With double conversion avoidance (this PR):
```
[autoconvert] Converting yuv420p10 -> rgb30
[hwupload] upload rgb30 -> vaapi[rgb30]
```

Without double conversion avoidance (removed this code):
```
[autoconvert] Converting yuv420p10 -> p010
[hwupload] upload p010 -> vaapi[rgb30]
```

In first case we have more data to upload actually... so I need your opinion @Dudemanguy, @llyyr, @philipl if we want to keep it? Maybe we shouldn't try to be smart.

I wanted to preserve previous logic, because we had this avoidance in place.

**Comment by Dudemanguy** [comment]
I feel like in practice avoiding double conversion is probably more useful in the real world. e.g. llyyr's example is something that is probably reasonably common.

**Comment by kasper93** [comment]
> I feel like in practice avoiding double conversion is probably more useful in the real world. e.g. llyyr's example is something that is probably reasonably common.

llyyr's example we bug on my end. Both with and without avoidance code the upload if direct upload is possible it will use that. The difference is when direct upload is not possible what intermediate format will be used.

**Comment by Dudemanguy** [comment]
Oh I misunderstood then. Maybe it is better to remove that code then.

**Comment by kasper93** [comment]
Actually nevermind, I've just tested on my hardware. yuv420p10 -> p010 -> vaapi[rgb30] is dropping frames like crazy. yuv420p10 -> rgb30 -> vaapi[rgb30] is perfectly watchable. So it actually is better to do conversion directly as the upload is not optimized...

I will merge this PR as is to fix the existing bug.

**Comment by philipl** [comment]
Wow. Wasn't expecting the conversion during upload to be so poor. Maybe it's only done in hardware for a subset of conversions?

**Pull request merged**
