### PR TITLE
Improvements to OSC top/bottombar layouts

### PR DESCRIPTION
**Pull request by wiiaboo**
[Screenshots and sample videos of changes](https://i.fsbn.eu/pub/osc/)

### CODE REVIEW

**Comment by ChrisK2** [comment]
```
+    geo = { x = geo.x + geo.w + padX + 100, y = geo.y - 1, an = 9,
...
+    geo = { x = geo.x + geo.w + padX + 100, y = geo.y + 1, an = 3,
```

Wasn't it possible to use the vertically centered aligns (4/6) to align everything along a single vertical line instead of shifting stuff around until it happens to align?

**Comment by wiiaboo** [comment]
The point was leaving the play/pause/chapter buttons a bit larger than the text, so the pixel is for vertical centering of the baseline of the text.

The difference is barely noticeable:
image

**Comment by ChrisK2** [comment]
yeah .. but, shouldn't that be aligned automatically with the centered aligns?

**Comment by CrisBRM** [comment]
The same font and style of the default one, inside the seekbar would look the best. Bikeshedding :^]

**Comment by wiiaboo** [comment]
The font is the same everywhere. Regarding style, I went with readability. I can't read \\fs9 from 4m away from the monitor and without border it'd mix with either the seekbar (if white) or with the background (if black).

**Comment by CrisBRM** [comment]
The outer stroke should be much much thinner

**Comment by wiiaboo** [comment]
>yeah .. but, shouldn't that be aligned automatically with the centered aligns?

Track selection buttons and labels still seem 1 or 0.5px off after changing to centered \ans (and removing the +-1px mentioned above):
image

Can't tell if it's the script or libass screwing up.

**Comment by wiiaboo** [comment]
Leaving the buttons as \fs19 and the buttons' labels as \fs20 somehow fixes the alignment issues.
I separated bottombar and topbar changes in two commits for easier reviewing.

**Comment by ChrisK2** [comment]
Looks acceptable now.

**Pull request closed without merging**
