### PR TITLE
demux_mf: add support for QOI, PHM and HDR images

### PR DESCRIPTION
**Pull request by richardpl**
Adds support for some float formats: PHM and HDR and new very simple image codec QOI.

### CODE REVIEW

**Comment by sfan5** [comment]
Wouldn't it be more portable if mpv could retrieve this information from libav some day? (maybe it already can, who knows)

**Comment by jeeb** [comment]
> Wouldn't it be more portable if mpv could retrieve this information from libav some day? (maybe it already can, who knows)

It seems like this module currently completely ignores any possible FFmpeg probing and does its own decisions on which decoder to open based on MIME and extension. This has negatives as far as if not mapped - mappings need to be added manually, but on the other hand you don't get random mis-detections that are possible with data-based probing being too trigger happy.

So the answer is: it would already be possible to utilize lavf/lavc to probe the codec to utilize, but that should probably be its own change if we want to bring in extension or data based probing from those libraries :) .

**Review by jeeb — APPROVED** [review]
LGTM. Checked that

>  img2dec/img2 has > IMAGEAUTO_DEMUXER(phm,       PHM) , and libavcodec has AV_CODEC_ID_PHM as "phm"

> hdr being AV_CODEC_ID_RADIANCE_HDR and img2/img2dec have IMAGEAUTO_DEMUXER_EXT(hdr,   RADIANCE_HDR, HDR)

> qoi is AV_CODEC_ID_QOI, and img2 has > IMAGEAUTO_DEMUXER(qoi,       QOI)

(so the extension is utilized in lavf and the codec name matches the one added in the PR)

**Comment by sfan5** [comment]
> So the answer is: it would already be possible to utilize lavf/lavc to probe the codec to utilize, but that should probably be its own change if we want to bring in extension or data based probing from those libraries :) .

I wasn't thinking probing since the code specifically seems to avoid that, but I bet it's possible to get a list of a extensions and demuxers from ffmpeg.
Would save the work of updating this all the time.

**Pull request merged**
