### PR TITLE
vf_d3d11vpp: ensure width and height is even

### PR DESCRIPTION
**Pull request by kasper93**
Fixes: bbb3d5ba78b2423393bc65e9d5f13f0ab62d3c4d

### CODE REVIEW

**Comment by kasper93** [comment]
@ofseed: this should fix your issue

**Comment by hooke007** [comment]
Does it block users to use sth like `scale=2.1`? Why?

**Comment by kasper93** [comment]
> Does it block users to use sth like `scale=2.1`?

No.

**Comment by ofseed** [comment]
This PR indeed solved the problem. Thank you very much!

**Pull request merged**
