### PR TITLE
demux_lavf: fix minor memory leaks 

### PR DESCRIPTION
**Pull request by rolandjon**
this fix  https://github.com/mpv-player/mpv/issues/8713,  make asan and valgrind happy.

### CODE REVIEW

**Comment by avih** [comment]
Why did you open a new PR?

**Comment by rolandjon** [comment]
> Why did you open a new PR?

Maybe it's redundant, but just for a clean submit message, and the code itself hasn't changed. --)

**Comment by avih** [comment]
You can change an existing PR by updating your commit locally and force-pushing your branch.

And now you get a chance to try it out, because the ` (#8713)` part should not be there. so remove it please.

Usually the commit message refers to an existing issue number only if it existed before the PR was open. E.g. there was a bug at issue #ABCD and a PR is made to fix it, and the commit message mentions that it fixes #ABCD.

**Comment by avih** [comment]
OK, the last commit looks good, but now we have three commits instead of one.

To make it one commit, squash the commits locally, and force-push.

**Comment by avih** [comment]
Thanks!

**Comment by rolandjon** [comment]
@avih @Akemi ,thanks for your patience !  --)

**Comment by avih** [comment]
Sure. Thanks for the fix.

**Pull request merged**
