### PR TITLE
options: add options to control OSD bar marker size and style

### PR DESCRIPTION
**Pull request by na-na-hi**
This adds `--osd-bar-marker-scale`, `--osd-bar-marker-min-size`, and `--osd-bar-marker-style` options which can be used to customize OSD bar marker size and style. In addition to the existing triangle style, a new style option is added to draw markers as lines.

Fixes: https://github.com/mpv-player/mpv/issues/15134

### CODE REVIEW

**Review by kasper93 — APPROVED** [review]

**Comment by VimWei** [comment]
Thanks! Cool!

**Comment by objspathfind** [comment]
> This adds `--osd-bar-marker-scale`, `--osd-bar-marker-min-size`, and `--osd-bar-marker-style` options which can be used to customize OSD bar marker size and style. In addition to the existing triangle style, a new style option is added to draw markers as lines.
> 
> Fixes: #15134

Hi na-na-hi,

I'm incredibly excited about this feature for customizing OSD bar marker size and style - it's exactly what I've been looking for! Unfortunately, I tried to download the artifacts but the links seem to have expired. Since I don't have the technical skills to build from the source code myself, would it be possible for you to provide updated download links? 

This feature would be tremendously helpful for my use case, and I'd really appreciate any assistance you could offer.

Thank you so much for your work on this!

**Comment by kasper93** [comment]
> would it be possible for you to provide updated download links?

It's merged in the main tree, you can use https://nightly.link/mpv-player/mpv/workflows/build/master

(see also https://mpv.io/installation)

**Comment by objspathfind** [comment]
Thank you for the quick reply, kasper93!

I checked out the links you provided, but it seems the builds there are only up to Sep 29, 2024. The osd-bar-marker customization feature I'm looking for was added after that date (it appears to have been merged in October).

Would there be any way to get a build that includes this newer feature? Thanks again for your help!

**Comment by kasper93** [comment]
> I checked out the links you provided, but it seems the builds there are only up to Sep 29, 2024.

I will assume you are on macOS. Use those builds https://github.com/mpv-player/mpv/actions/runs/13731155583

**Comment by objspathfind** [comment]
Thank you so much, kasper93! I've successfully downloaded the build from the link you provided, and the osd-bar-marker customization feature is working perfectly!

**Pull request merged**
