### PR TITLE
vo_opengl: clean up ewa_lanczos code

### PR DESCRIPTION
**Pull request by haasn**
This fixes compatibility with GLES 2.0 and makes the code a bit neater
in general.

### CODE REVIEW

**Comment by haasn** [comment]
Also added a check to enable indirect scaling for polar filters, since that caused massive performance issues and unexpected results for subsampled input.

**Comment by olifre** [comment]
Neat - with this applied, I "only" get 86 % GPU usage at 2x upscaling (from 720p to Full HD) with `vo=opengl-hq:lscale=ewa_lanczos:lradius=16:dither-depth=6` (but I agree using settings like that is a bit overkill...).

**Comment by haasn** [comment]
How the hell can your GPU even process ewa_lanczos:lradius=16 in realtime?!

**Comment by olifre** [comment]
> I guess with a slightly beefier GPU and no color management it makes sense. Still, I hope nobody in their right mind actually uses that many taps. :)

Exactly ;-). No colourmanagement here (yet), and the integrated display can do 120 Hz, but only 6 bits depth as far as I can deduce from dithering effects. 
It's a GK104M [GeForce GTX 880M] (Kepler) with 8 GiB VRAM which is sitting in my laptop. It can only go that fast with power supply attached, of course - and if I do that for more than a minute, I need a good pair of headphones... but it manages realtime using the 346.35 binary blob on Linux. 
I did not yet test NNEDI3 under Windows with it...

**Comment by haasn** [comment]
NNEDI3 is somewhere on my distant TODO list. Need to understand how the algorithm works first :)

**Comment by olifre** [comment]
> NNEDI3 is somewhere on my distant TODO list. Need to understand how the algorithm works first :)

Glad to hear that - after having a short look at an implementation of it, I got a rough understanding of the meaning of distant (although I know the basics of NN, I know almost nothing about image processing) - good luck at that! :-)

**Comment by AirPort** [comment]
Great patch, with this applied I'm able to use ewa_lanczos3 on my laptop's old low-end nvidia card, which is impossible for me with the current "vanilla" code (it cause severe framedropping even for "little" upscaling). Are there any chances for this to be merged? :)

**Pull request closed without merging**
