### PR TITLE
vo_dmabuf_wayland: rewrite around wl_list

### PR DESCRIPTION
**Pull request by Dudemanguy**
vo_dmabuf_wayland worked by allocating entries to a pool and then having a lot of complex logic dealing with releasing buffers, pending entries, etc. along with some other not so nice things. Instead, we can rewrite this logic so that the wl_buffers created by the imported dmabuf is instead stored in a linked list, wl_list. We can simply append our buffers to the list when needed and destroy everything at the end. On every frame, we can check the ids of our surfaces and reuse existing buffers, so in practice there will only ever be a handful at a time. Some other small changes where made in an attempt to organize the vaapi/drmprime code a little better as well. Overall, it's much simpler to handle like this.

This conflicts with #11241 of course, so it'll have to be rebased a bit after that gets in. Shouldn't affect anything though. @boxerab and/or @philipl, if you guys could test this to make sure I didn't break drmprime, that would be appreciated.

### CODE REVIEW

**Comment by boxerab** [comment]
tested with vaapi - unfortunately buffers are being rejected, and there are memory leaks at exit.

Keep in mind that the buffer pool is designed to:
1. avoid leaks by re-using buffers
2. avoid Wayland buffer creation by re-using buffers - buffer creation is not free

I think a buffer pool is a necessary evil for this vo.

**Comment by Dudemanguy** [comment]
The memory leaks were my bad. I forgot to destroy a couple of things when the buffer creation fails. Should be fixed now.

>avoid leaks by re-using buffers
>avoid Wayland buffer creation by re-using buffers - buffer creation is not free

This does that too. What command line are you passing exactly? I've just realized that this stutters for some reason if you use the autoconvert filter and don't explicitly pass `--vaapi`.

**Comment by boxerab** [comment]
> What command line are you passing exactly? I've just realized that this stutters for some reason if you use the autoconvert filter and don't explicitly pass `--hwdec`. Pausing and then seeking seems to fix that for some reason.

This was a known issue fixed in current upstream. You have to clear buffers after reset or resize, twice - once before the next frame is displayed and once after.

**Comment by Dudemanguy** [comment]
>You have to clear buffers after reset or resize, twice - once before the next frame is displayed and once after.

I'm trying to hopefully eliminate having to do that. At least with this, I've not had the need for constantly clearing out the buffers (resize, seek, etc. seems fine). I'd rather hunt down whatever it is about the autoconvert that causes this.

**Comment by Dudemanguy** [comment]
>I've just realized that this stutters for some reason if you use the autoconvert filter and don't explicitly pass --hwdec. 

Should be fixed now. I realized that what was actually happening was that the very first frame was constantly flashing. I'm not really sure why this occurred. I verified that the initial src image was being destroyed, but anyways I simply worked around it by unconditionally destroying just the very first buffer. Seems to work.

**Comment by Dudemanguy** [comment]
>I simply worked around it by unconditionally destroying just the very first buffer

Updated this yet again. I found some videos that actually flickered for me anyways, and they flicker on master as well. What I found was that the very initial buffers created needed to be cleared out, so I implemented this by marking them all to be completely destroyed when the VO first initially tries to reuse buffers. After that, it continues on as normal.

**Comment by boxerab** [comment]
I tested the latest with vaapi - much better now. I did see an issue :
1. play an nv12 video (hw decoding)
2. hold the left arrow button down for a while (seek back)
3. eventually decode will fail and fall back to software mode

**Comment by boxerab** [comment]
> > I simply worked around it by unconditionally destroying just the very first buffer
> 
> Updated this yet again. I found some videos that actually flickered for me anyways, and they flicker on master as well. What I found was that the very initial buffers created needed to be cleared out, so I implemented this by marking them all to be completely destroyed when the VO first initially tries to reuse buffers. After that, it continues on as normal.

Can you share one of those videos that flickers on master ?

**Comment by Dudemanguy** [comment]
>I did see an issue :

Ah yes, I'm resetting way too much. Really, I only need to do this when a file is loaded I think.

>Can you share one of those videos that flickers on master ?

I'm silly and just realized that it happens for me on any yuv420 or yuv420p10 video. I suspect it's because the autoconvert filter kicks in there and for some reason that causes this weird artifact. It's probably better to try and solve that than use these weird workarounds.

**Comment by Dudemanguy** [comment]
There's actually multiple things that can cause the stutter/flickering artifact we were seeing and I think I figured it out. The autoconvert is a bit of a red herring; it's not specifically related to that filter but rather the outputted format.

1. Simply not making enough buffers causes flicker in certain cases. You cannot rely on merely having enough unique IDs from the hwdec (well at least VAAPI anyway). It won't always create enough buffers. Simply just altering the logic to create more buffers fixes this. On the formats that worked correctly (like NV12), I artificially restricted the amount of buffers was created, and it created the same flicker/stutter. To my knowledge, there's no real way to know what a "good" number is since it varies depending on the format. What I ended up going with was 2 * num_planes + 1. It's not really based on anything other that "it works". For a 3 plane format, you end up with at least 7 buffers total which is totally reasonable so should be OK.

2. Not really surprising, but all buffers have to be destroyed whenever a new file loads. The surface IDs can be non-unique across files which makes the VO mistakenly try to reuse buffers when it shouldn't. Otherwise, you'll get flicker. Clearing out the buffers is probably good anyway otherwise you could theoretically grow forever in memory. Master handles this by clearing on any reset which includes loading a file + any seeking. We shouldn't need to do anything on seek though. At least not with this, so I just added a VOCTRL which was trivial.

Of course, all this is based on what happens with vaapi. No clue about drmprime. That said, most of this same logic should hold there. If it happens to need more/less buffers that can easily be changed. Overall, I'm pretty happy with this and it should be a good improvement over master assuming I didn't break drmprime. There's some improvements that could be made when detecting the hwdec type since we have mapping code now, but that can be saved for a different change.

**Comment by boxerab** [comment]
Looks better. Unfortunately, it crashes when video gets resized. Try playing this clip - at 18 seconds the dimensions change and the vo crashes. 

[reschange.zip](https://github.com/mpv-player/mpv/files/10716164/reschange.zip)

That is another reason why upstream resize will clear out the buffers. You can't recycle old buffers that are set to old video dimensions.

**Comment by Dudemanguy** [comment]
I was clearing the buffers on a reconfig, but it threw a compositor on specifically weston (not sway). Thanks for noticing it. The fix is to simply always immediately destroy buffers in that case instead of waiting until the next draw_frame call. Should be good now.

**Comment by boxerab** [comment]
Better. I still see flicker on formats that require hw upload, for example `yuv422p10le`.

**Comment by Dudemanguy** [comment]
That didn't generate enough buffers (only 3). Trying to guess off of planes apparently doesn't work. That format had only 1 plane so the calculation didn't enforce enough (seems to need 4). I just gave in and made this always create at least 8. yuv420p requires 7 for me, so we'll just leave it at that for now. Should be good.

**Comment by boxerab** [comment]
Indeed, this fixes the problem. I ran through all of my vaapi tests and everything looks good. 
I will try to test on rockchip tomorrow.

**Comment by Dudemanguy** [comment]
@boxerab: Are you OK with merging this even though drmprime hasn't been tested yet? It's a definite improvement w/ regards to VAAPI at least. On paper most of it should be the same.

**Comment by boxerab** [comment]
> @boxerab: Are you OK with merging this even though drmprime hasn't been tested yet? It's a definite improvement w/ regards to VAAPI at least. On paper most of it should be the same.

My feeling is that we could use more testing before merging. Hopefully @philipl has some time to try on rockchip ?
Also, we need to test on still images, as I believe there was an issue for that case with resize.

**Comment by Dudemanguy** [comment]
>Also, we need to test on still images, as I believe there was an issue for that case with resize.

That works with this.

>My feeling is that we could use more testing before merging. Hopefully @philipl has some time to try on rockchip ?

Would it be possible for you to compile a newer version of weston on your rockchip?

**Comment by boxerab** [comment]
> Would it be possible for you to compile a newer version of weston on your rockchip?

I am running on plasma-wayland, not weston. It would be simpler if you could just temporarily revert, on the branch,
your changes to remove v2 dmabuf support. Then I could easily test it.

**Comment by philipl** [comment]
If you can be patient, I can test late next week. I'm going to be really busy with other things for the next few days.

**Comment by Dudemanguy** [comment]
>It would be simpler if you could just temporarily revert, on the branch, your changes to remove v2 dmabuf support. Then I could easily test it.

Should I just permanently revert it? I only dropped it because I thought no one needed it and v4 is much better, but if your actual rockchip device requires v2 it seems like we should add it back. It's not too much code.

>If you can be patient

I have some other things I want to change but are being blocked by this so I'm not feeling very patient admittedly ;).

**Comment by boxerab** [comment]
> Should I just permanently revert it?

yes, revert it in master would be a good idea, and on branch

**Comment by Dudemanguy** [comment]
I'll pull in #11326 soon unless someone objects.

Unfortunately, this is blocked on really weird drmprime behavior for the time being at least.

**Comment by Dudemanguy** [comment]
@boxerab: It's been a while but I finally got a rockpro64 which let me finally test drmprime. All I had to do was make one small tweak and it works just fine for me in weston and sway now. Did you want to give this another go to see if you can break it?

**Comment by boxerab** [comment]
> @boxerab: It's been a while but I got a rockpro64 which let me finally test drmprime. All I had to do was make one small tweak and it works just fine for me in weston and sway now. Did you want to give this another go to see if you can break it?

great! unfortunately, my laptop with my entire testing environment and test files recently died, so can't do much testing atm. If it works for you on rockpro64 and intel, then it's probably fine - perhaps @LaserEyess or @philipl can do a little more testing.

**Comment by philipl** [comment]
Sorry, I wasn't able to test. My last attempt to dust off my rockchip machine saw it fail to do anything useful. @Dudemanguy if you have been able to test directly and see it working, then I think we're good to go. My testing isn't going to do anything more profound.

**Comment by Dudemanguy** [comment]
Thanks guys. I'll give this one a few more tests and probably will pull it in later this week. I've been blocked on some things I've wanted to do for dmabuf-wayland so I'll be nice to finally solve this.

**Pull request merged**
