### PR TITLE
Revert "options: disable vsfilter blur compat by default"

### PR DESCRIPTION
**Pull request by rcombs**
This reverts commit 3d17e19c2c5ca80f916411e7e61126cac8443baa.

This caused files which did not set ScaledBorderAndShadow, and had non-matching subtitle and video resolutions, to act as if the _display resolution_ was the video resolution. This meant that those files rendered with a very thin stroke on displays with resolution higher than the script res.

The performance issues specified in #7435 weren't actually specific to this case, and can happen with a variety of files.

The option's name is also somewhat misleading: setting the storage size affects blur, but it also affects stroke, which is far more important for the vast majority of scripts.

### CODE REVIEW

**Comment by rcombs** [comment]
To clarify, this isn't just VSFilter compatibility, this affects any script without ScaledBorderAndShadow being rendered at a resolution that doesn't match that of the video. If we want a "just do the sane thing and ignore compatibility concerns" option, it should be to set the storage res to the same as the _sub_ res, whereas the current behavior effectively uses the _display_ res.

**Comment by astiob** [comment]
While thin borders are arguably the right behaviour if a file does not set ScaledBorderAndShadow (it’s literally in the name), there’s another bad effect:

If a file does not set ScaledBorderAndShadow and uses 3D transforms, `--sub-ass-vsfilter-blur-compat=no` causes the 3D transforms to depend on the display resolution: things actually rotate and fly around as the mpv window is resized.

**Comment by astiob** [comment]
Ha, turns out that’s a libass bug and it shouldn’t be doing that. Never mind.

**Review by jeeb — APPROVED** [review]
LGTM.

Thanks for adding the extra explanation in place.

**Pull request merged**
