### PR TITLE
Drop TravisCI after migrating FreeBSD

### PR DESCRIPTION
**Pull request by jbeich**
Example: https://github.com/jbeich/mpv/runs/3156369962

### CODE REVIEW

**Comment by jeeb** [comment]
Thanks for this.

Yeah, I did notice that macOS-based hack since Github doesn't yet have:
* FreeBSD images for the runners
* Nested virtualization support in the Azure instances they provide access to.

**Comment by TheOneric** [comment]
iinm this depends on VirtualBox being preinstalled, but the [`macos-11.0` image](https://github.com/actions/virtual-environments/blob/55fe7979f268d2400fb2e0c5ef92971eaa872e9e/images/macos/macos-11-Readme.md) does not have VirtualBox pre-installed anymore. Apparently after installing VirtualBox manually, a [Kernel Extension needs to be enabled](https://formulae.brew.sh/cask/virtualbox) before it can be used. Can this be done in GHA, i.e. will this continue to be possible once `macos-latest` switches to `macos-11.0`?

**Comment by jeeb** [comment]
@TheOneric Thanks for reminding me of that :) .

Yes, this should definitely utilize `macos-10.15` specifically instead of `macos-latest` in that case.

**Review by jeeb — APPROVED** [review]
LGTM

**Pull request merged**
