### PR TITLE
etc/mpv.desktop: add audio/vnd.wave

### PR DESCRIPTION
**Pull request by Vonfry**

### CODE REVIEW

**Comment by sfan5** [comment]
`audio/vnd.wave` seems to be for referencing specific codecs in these files ([RFC](https://datatracker.ietf.org/doc/html/rfc2361)). But in any case if we're doing this would make sense to add `video/vnd.avi` too.

**Comment by Vonfry** [comment]
I haven't a vnd.avi file. But mpv 0.36.0 works on the vnd.wave files I downloaded today. Is there some method to test vnd.avi before adding it?

**Comment by sfan5** [comment]
The mime type list has not changed since 0.29.0. Are you saying the behavior regressed?

**Comment by Vonfry** [comment]
I mean an audio/vnd.wave file can be opened in mpv, but I don't know
whether video/vnd.avi can be opened as well.

In the newest commit, video/vnd.avi has been added into the mime type
list, but it isn't tested.

**Comment by sfan5** [comment]
But if you say a vnd.wave file can be opened by mpv 0.36.0 already, why do we need to add it to the MIME list?
Or do you mean just that it's possible by opening it manually?

I don't have an AVI file on hand anyway, not important to test that.

**Comment by Vonfry** [comment]
> Or do you mean just that it's possible by opening it manually?
Right, open it manually.

**Review by sfan5 — APPROVED** [review]

**Pull request merged**
