### PR TITLE
osc: use custom symbols for window controls

### PR DESCRIPTION
**Pull request by philipl**
I didn't know these existed originally, but I've now been
educated. And as we now have access to an un-maximize character,
I added the logic to set the icon based on the maximized state.

### CODE REVIEW

**Comment by philipl** [comment]
Note that on my machine, these symbols cause libass to print a warning:

```[osd/libass] Glyph 0x1F5D6 not found, broken font? Trying all charmaps```

But it does find the glyph in another font and everything looks fine. That warning might be considered a problem. Not sure how to fix it (I really don't want to use a custom font glyph just to shut that warning up when the system has the glyph). Maybe we could blacklist the glyph numbers and suppress the message?

**Comment by wm4** [comment]
That's the advantage of the OSD font approach.

> Maybe we could blacklist the glyph numbers and suppress the message?

Do you suggest we parse libass messages? No.

**Comment by downthomas** [comment]
IIRC, mpv looks for OSD symbols in mpv-osd-symbols.
The otf file is in mpv/sub/osd_font.otf.
The source is at mpv/TOOLS/mpv-osd-symbols.sfdir/.
So those glyphs could be added to mpv-osd-symbols.
That would fix the error message.

**Comment by philipl** [comment]
I've updated the change to use custom symbols that I copied into our osd font. That addresses all the libass warnings and cross platform alignment issues.

**Comment by wm4** [comment]
Seems nice. LGTM.

**Comment by keithbowes** [comment]
> IIRC, mpv looks for OSD symbols in mpv-osd-symbols.
> The otf file is in mpv/sub/osd_font.otf.

How to install this font really needs to be documented.  I moved osd_font.otf to $XDG_DATA_HOME/fonts and I'm still just getting a bunch of question marks in the OSC.
2020-02-08-182619_grim

**Comment by Akemi** [comment]
it does not need to be installed, it's embedded in the binary.

**Comment by keithbowes** [comment]
> it does not need to be installed, it's embedded in the binary.

Then how come most of the symbols show up as question marks?  Only the play and pause symbols render correctly, but only because it uses Code2001 as the mpv-osd-symbols font.  If I move the Code2001 font out of my font path, the play and pause symbols show up as question marks too.  (IIRC, I only got Code2001 because older versions of mpv would complain if it couldn't be found.)

Anyway I've added this to my ~/.config/mpv file to stop showing all the question marks:
```
osd-level=3
osd-msg3=${?pause==yes:▮▮}${!pause==yes:▶ } ${time-pos} / ${duration} (${percent-pos}%)
osc=no
```

It would be lovely if there were a simpler way (preferably one that didn't entail disabling OSC), but i couldn't find it.

**Comment by Akemi** [comment]
who knows. you are replying to a closed PR instead of opening an issues where we ask you to provide certain infos so we could possibly identify the problem on your end. like this it's just like looking into a crystal ball.

**Comment by keithbowes** [comment]
> you are replying to a closed PR

An obviously broken PR.

**Comment by Akemi** [comment]
your point being? if it isn't obvious, that doesn't help you resolve the problem neither does it help us find your problem to resolve it. i still suggest, to go the proper way of reporting an issue instead of arguing here and wasting your and my time.

**Comment by wm4** [comment]
This is why the "lock conversation" button exists.

**Pull request merged**
