### PR TITLE
vo_vdpau: Implement rotation support

### PR DESCRIPTION
**Pull request by philipl**
VDPAU has explicit support for rotating surfaces, and it is far less
expensive than using the normal rotation filter (which would require
reading video frames back into system memory), it is desirable to
implement the VO rotation capability.

To do this, we need to render the video frames to an output surface,
without rotation, and then render from that surface to the final
output surface to apply the rotation. It is important that the
intermediate surface is the same size as the final one (only not
rotated) so that hqscaling can be applied if requested by the user.

(hqscaling is a mixer capability and so takes effect when the video
surface is rendered to an output surface)

Finally, we must remember to explicitly clear the final output
surface as VDPAU only auto-clears output surfaces when rendering video
surfaces.

### CODE REVIEW

**Comment by wm4** [comment]
Looks good. Did you test whether it works with panscan etc.?

**Comment by philipl** [comment]
panscan looks correct. What else would you like me to check?

**Comment by wm4** [comment]
Fine then.I'll merge in a moment.

**Comment by wm4** [comment]
Merged, thanks.

**Pull request closed without merging**
