### PR TITLE
sd_lavc: support rendering bitmap subtitles with libaribcaption

### PR DESCRIPTION
**Pull request by vroad**
[libaribcaption](https://github.com/xqq/libaribcaption) is a library for decoding / rendering ARIB STD-B24 based TV broadcast captions (subtitles). The library supports ouputting decoded subtitles in two ways: ASS subtitles or bitmap subtitles. Building recent version of ffmpeg with libaribcaption also enables ARIB subtitles rendering on mpv.

Currently mpv only supports rendering ARIB subtitles with ASS subtitles driver when libaribcaption codec is in use, which renders poorly compared to bitmap subtitles driver. ASS subtitles lack black transparent background that makes subtitles more readable. Subtitles decoded with libaribcaption render best when rendered with bitmap subtitles driver. 

**New mpv commandline option: sd-lavc-o**

On ffplay you can use `-sub_type=bitmap` option to render ARIB subtitles as bitmap.
There is currenly no way to set the same option to subtitle decoders on mpv unfortunately, so I added one. This would also allow configuring other libaribcaption options like font from mpv.

**libaribcaption support**

mpv only uses bitmap subtitles driver only for codecs listed here: https://github.com/mpv-player/mpv/blob/6234a709202282d8a8bfffd0ee4f9d80561dd4b9/sub/sd_lavc.c#L79-L89

To render subtitles correctly when `sub_type` is set to `bitmap`, I added some code that choose subtitles driver based on the value of this option.
Since ffmpeg's libaribcaption codec defaults to ASS subtitles, just adding `AV_CODEC_ID_ARIB_CAPTION` to the list breaks rendering, because mpv expects bitmap subtitles, and the codec still outputs ASS subtitles.

**Building**
* ffmpeg must be built with `--enable-libaribcaption`. I used this revision: https://github.com/FFmpeg/FFmpeg/tree/2f8690c5d450b984640bd27dd7fd3a96d77ecc6b
* mpv must be built with `-Ddvbin=enabled` if you want to test ASS subtitles support too.
* I built ffmpeg with [forked libaribcaption](https://github.com/vroad/libaribcaption/tree/fix-pkgconfig) becuase it does not install correctly on NixOS

**Running**

Tested on NixOS 22.11. Without `--cache=no`, subtitles does not show up until I seek (Probably because of this issue): https://github.com/mpv-player/mpv/issues/9646

libaribb24 probably has the same problem as libaribcaption and this PR may fix it, I just haven't tested with libaribb24 yet.

Do I need to send m2ts files to mpv developers for testing?

Rendering subtitles with bitmap subtitles driver:

```
mpv --deinterlace \
--sd-lavc-o-add=sub_type=bitmap \
--sd-lavc-o-add=font='Rounded M+ 1m for ARIB' \
--cache=no \
--sid=1 \
/path/to/video.m2ts
```

Rendering subtitles with ASS subtitles driver (Requires mpv to be built with `-Ddvbin=enabled`):

```
mpv --deinterlace \
--sd-lavc-o=sub_type=ass \
--cache=no \
--sid=1 \
/path/to/video.m2ts
```

mpv defaults to ASS subtitles if sub_type is not set:

```
mpv --deinterlace \
--cache=no \
--sid=1 \
/path/to/video.m2ts
```

### CODE REVIEW

**Comment by dyphire** [comment]
Both libaribcaption and libaribb24 default to outputting subtitles in ass format for rendering, and this default behavior is also followed in ffmpeg. mpv should maintain the same behavior, but the fix patch seems good.

**Comment by vroad** [comment]
I followed @dyphire 's suggestion and updated PR branch, but his comment is gone? 🤔

**Comment by dyphire** [comment]
> I followed @dyphire 's suggestion and updated PR branch, but his comment is gone? 🤔

Ah, that's just my personal opinion, and later I thought it would be up to the maintainers to review whether this behavior change was reasonable.

**Comment by vroad** [comment]
@dyphire 
I changed my mind, mpv should follow libraries' default as you said.

VLC exposes libaribcaption (and libaribb24?)'s option in easy-to-understand GUI, mpv's GUI/CLI interface does not.
Instead, mpv's CLI interface exposes libaribcaption options directly via sd-lavc-o option. Following ffmpeg's default probably make it easy to understand mpv's behavior for users, I guess.

I removed the code for changing default value for sub_type to bitmap from PR. If everyone thinks that changing default value for sub_type is a good idea, we can do it later with another PR.

**Comment by Dudemanguy** [comment]
@vroad: Not sure if you're still interested in this but coincidentally 02a20b4ebe29cb7d488ceaf39fb5a50c2443295a just added `--sub-lavc-o` so if you want to pick this up from there that would be appreciated.

**Comment by kasper93** [comment]
Similar change would be needed for `AV_CODEC_ID_DVB_TELETEXT` to fix https://github.com/mpv-player/mpv/issues/13471

**Comment by kasper93** [comment]
Superseded by https://github.com/mpv-player/mpv/pull/13752

I've made it work also for teletext and checked actual context defaults too, not only our options.

**Pull request closed without merging**
