### PR TITLE
VO shablo

### PR DESCRIPTION
**Pull request by tokideveloper**
VO "shablo" is a new video output driver that renders frames in a text terminal by combining the 8 or 16 ANSI foreground and background colors with shaded block characters (U+32, U+2591, U+2592, U+2593, U+2588). It's based on VO tct and perhaps it could be merged with tct in the future.

Please note:

- Consult the manual for interesting options.
- I'm unsure about my changes in the files "/wscript_build.py", "/video/out/vo.c", and "/Copyright".
- Some terminals, e.g. gnome-terminal, really merge the foreground and the background color when a shaded block comes up. Those results might appear nicer.
- Sometimes, when started in a terminal which does not merges the colors, blocks appear brighter than calculated (e.g. light gray 1/4 + black 3/4 = dark gray, but could appear lighter than dark gray). Maybe, it depends on the monitor. Maybe, I can find a solution for that problem.

I agree that my changes can be relicensed to LGPL 2.1 or later.

### CODE REVIEW

**Comment by thebombzen** [comment]
How is this any different than the existing --vo=tct?

**Comment by thebombzen** [comment]
Or rather, how is it any different other than the fact that you re-implement existing mpv functionality but do it wrong this time?

**Comment by SoniEx2** [comment]
LGTM just needs hexchat support

**Comment by haasn** [comment]
I'd like to re-iterate my question of “why not extend vo_tct”? I don't think we need more than one terminal-based output renderer, even if it supports multiple modes internally.

**Comment by haasn** [comment]
It's also incredibly slow (way too slow for realtime over here, even without dithering). Your man page changes don't compile, and the output looks completely wrong since it assumes the basic 8/16 colors are sensible. (In practice, they normally aren't - You should be using the 16-255 color palette to rectify this)

**Comment by bjin** [comment]
FWIW, there are already ffmpeg filters for color palette generation/usage purposes. Even with dithering support. Not sure how to properly use ffmpeg filters in vo code though.

**Comment by thebombzen** [comment]
Your colorspace conversions also aren't done correctly. Notice that in `r_g_b_2_x_y_z` you do not take into account transfer characteristics, i.e. you do not scale sRGB to XYZ using the [sRGB transfer function](https://en.wikipedia.org/wiki/SRGB#Specification_of_the_transformation). (This is just one example.)

The good news is mpv already has existing code to do this correctly. It seems to me like you're re-inventing the wheel rather than building upon the existing working vo_tct. You say your idea is based on vo_tct and could be merged, but it makes more sense to make changes to vo_tct in the first place rather than rewriting it from scratch and then trying to merge in bits and pieces of your rewritten code.

**Comment by tokideveloper** [comment]
> How is this any different than the existing --vo=tct?

tct depends on terminals capable of 24bit color for both foreground and background color. Passing --vo-tct-256 lets tct depend on terminals capable of the 256 colors palette. However, shablo depends on terminals capable of only 8, respectively 16, colors. No combination of --vo-tct-* works to give good results on such terminals, in my view.

There are some more internal differences, but the mentioned dependency should be enough at this point. If you like to know more differences then I can list them here.

> Or rather, how is it any different other than the fact that you re-implement existing mpv functionality but do it wrong this time?

I'm open to hear what I could do better (see below).

Also, I'd like to hear how I can reach nice output on 16-colors terminals with the given functionality.

> Your colorspace conversions also aren't done correctly. Notice that in r_g_b_2_x_y_z you do not take into account transfer characteristics, i.e. you do not scale sRGB to XYZ using the sRGB transfer function. (This is just one example.)

Thank you! I think that this has to do with what I've been looking for when I said this in my opening post:

> Sometimes, when started in a terminal which does not merges the colors, blocks appear brighter than calculated (e.g. light gray 1/4 + black 3/4 = dark gray, but could appear lighter than dark gray). Maybe, it depends on the monitor. Maybe, I can find a solution for that problem.

So, I see that I should have studied the related topics thoroughly.

> The good news is mpv already has existing code to do this correctly. It seems to me like you're re-inventing the wheel rather than building upon the existing working vo_tct. You say your idea is based on vo_tct and could be merged, but it makes more sense to make changes to vo_tct in the first place rather than rewriting it from scratch and then trying to merge in bits and pieces of your rewritten code.

I see what you mean here and I think it's a way to consider. I'll think about it.

**Comment by tokideveloper** [comment]
> I'd like to re-iterate my question of “why not extend vo_tct”? I don't think we need more than one terminal-based output renderer, even if it supports multiple modes internally.

I know your question and more and more I think that you are right. So, I'd like to know if it's worth doing so. That's why I started this pull request.

**Comment by tokideveloper** [comment]
> It's also incredibly slow (way too slow for realtime over here, even without dithering).

That's funny because on my machine it's faster than both tct and caca playing the same videos. Only creating the lookup table at startup should be slow. Okay, I'll work on this.

> Your man page changes don't compile,

I'm sorry. I should have asked for help before and get it right. I'll try to correct this in the days or even later. Meanwhile, please look at the /DOCS/man/vo.rst.

> and the output looks completely wrong since it assumes the basic 8/16 colors are sensible. (In practice, they normally aren't - You should be using the 16-255 color palette to rectify this)

There is the option --vo-shablo-color-palette-preset=\<preset\> where \<preset\> is currently one of vga|cmd|termapp|putty|mirc|xterm|human. The option is to let shablo know what the colors 0-15 look like. See [here](https://en.wikipedia.org/wiki/ANSI_escape_code#3.2F4_bit) for the color palettes currently implemented. In the future, I plan to offer an option to enter an arbitrary palette directly by its #RRGGBB values.

**Comment by tokideveloper** [comment]
> FWIW, there are already ffmpeg filters for color palette generation/usage purposes. Even with dithering support. Not sure how to properly use ffmpeg filters in vo code though.

Thank you for this hint. Maybe, I can get it work that way.

**Comment by tokideveloper** [comment]
@all: Currently, I've bad and expensive Internet access. So, my next reaction will be in a week or something. Meanwhile, I'll consider all your comments and see what I can/could/should do. Thank you for your patience and thank you for all your pro tips!

**Comment by tokideveloper** [comment]
Hello, again. While I didn't have Internet access the last days, I tried to fix some bugs and such. This includes:

- fix manpage
- take care of gamma correction (as far as possible)
- lazy lookup table value calculation (removes time-consuming precalculation at startup while having 8 bit per channel now)

So, hopefully, it's better now.

I'm quite sure that there are still errors in the code, so, I think it would be okay if we could view my work here as a prototype.

I'm still interested in making it work and work well. So, I think some main issues are:

- use already available libs/functions/codes/programs/frameworks due to reduce errors and code duplication
- merge it with tct (by moving/reimplementation or whatsoever), resulting in just one tct
- optimization where appropriate

[bjin commented](https://github.com/mpv-player/mpv/pull/4951#issuecomment-333927905):
> FWIW, there are already ffmpeg filters for color palette generation/usage purposes. Even with dithering support. Not sure how to properly use ffmpeg filters in vo code though.

As far as I can see in the [ffmpeg Documentation](https://ffmpeg.org/ffmpeg-all.html), ffmpeg supports palettes of 256 colors only. shablo, however, can "create" up to 376 colors. Of course, I could reduce the palette but this would be a loss of a third, which is not desirable in my view. Rather, I'd like to see ffmpeg expand this limit.

I still didn't touch the tct code since I'd like to see my prototype working isolated first because I fear of getting more issues when implementing buggy code into existing code.

**Comment by tokideveloper** [comment]
Now, I see that there is a failed check. It's about missing fabs, pow and cbrt functions. On my computer, compiling works. So, what have I done wrong?

Due to lack of Internet access, I'll come back here in a few days (hopefully).

**Comment by cmdrkotori** [comment]
Have you included math.h?

**Comment by tokideveloper** [comment]
> Have you included math.h?

Yes ... I thought. But it seems that it vanished later on. Strange ...
Thank you!

**Comment by tokideveloper** [comment]
Hello, everyone,
It seems to work now. You may try it if you like.
I'd like to know

- how you find it
- if it's worth to continue on it, and if yes:
- what I should do to make it accepted by the mpv-player team (with respect to the posts above)

Thank you!

**Comment by lachs0r** [comment]
That’s a nice project but it will only be worth something to us if you address the issues outlined in the previous posts. To begin with, vo_tct is more of a gimmick, and I’d rather not have more of the same.

**Comment by haasn** [comment]
Maybe if we had a VO plugin system like VLC, exotic VOs like this could be maintained as independent plugins rather than as part of mpv. But as it stands, I agree that there's no gain for needlessly bloating the codebase here for code nobody will ever want to use, test or maintain.

**Comment by SoniEx2** [comment]
tbh mpv is a good way to benchmark your terminal emulator.

[alacritty](https://github.com/jwilm/alacritty) is still the fastest terminal emulator I know of.

**Pull request closed without merging**
