### PR TITLE
Consistent configuration/example files installation

### PR DESCRIPTION
**Pull request by czarkoff**
While not really issues, these are inconsistencies that I find irritating:
* Waf installs `encoding_profiles.conf` to `CONFDIR`, but other installation files are installed into `DOCDIR`.
* `example.conf` is a filename for `mpv.conf` example. Other examples' names are the same with configuration files they are examples of.

### CODE REVIEW

**Comment by wm4** [comment]
The first thing is is fully intentional. encoding_profiles.conf is actually parsed on loading, and actually contains active settings. The other conf files are fully documented and are just examples.

The second commit would be acceptable, though.

**Comment by czarkoff** [comment]
I would avoid installing files directly to `/etc`, but it is your project and you know better.

I have a hidden agenda with this issue: in OpenBSD all files in packages are checksumed, so we can't install to `/etc` - if somebody will edit the file, its checksum wouldn't match during package update or removal. Instead we install to example directory, and copy files to `/etc` during package installation. With old-configure I could simply override config directory during packaging stage; now, that I have to use waf, it becomes an issue.

**Comment by pigoz** [comment]
@czarkoff do `--confdir` or `--docdir` help? See `./waf configure --help`

**Comment by czarkoff** [comment]
Not really. `cofigure --confdir` also sets location where mpv looks for configuration files at runtime. In other stages of built process `--confdir` is silently ignored.

**Comment by pigoz** [comment]
Well it's not like most users would edit config files directly in the `confdir`. I think using a read only path for the confdir might be an acceptable solution.

Otherwise how do other OpenBSD ports handle? A lot (most?) of software out there installs default config files to `etc`.

**Comment by czarkoff** [comment]
Most software doesn't use build systems as limited and rigid as waf.
```
make CONFDIR=/etc
make CONFDIR=/usr/local/share/example/progname/ install
```

**Comment by wm4** [comment]
Yeah, most software uses cmake these days, or MSVC+Xcode project files.

**Comment by czarkoff** [comment]
@wm4 I see increasing amounts of pure makefile-based configuration. In my experience, these are easiest to write, most readable and by far more flexible.

**Comment by wm4** [comment]
So you want the 10kloc shell vomit back that mplayer had?

**Comment by czarkoff** [comment]
@wm4 I sort of liked `old-configure` and `old-makefile`. I have to admit, waf produces better results, but mostly because old buildsystem was much less tested.

**Comment by czarkoff** [comment]
And 1500 lines of old-* don't look as bad as 53967 lines of waf.

**Comment by wm4** [comment]
>And 1500 lines of old-*

Because it supported only desktop Linux (and maybe OpenBSD if you hacked it a bit).

**Comment by czarkoff** [comment]
I have no clue about building software on OSX, but MinGW support would not double that number. Assuming that nothing from old build system is reusable on OSX, there is still about 50k lines of overhead with waf. And making waf handle unit tests in adequate fashion would add yet more overhead.

**Comment by pigoz** [comment]
^ that should fix your problem, hopefully

**Comment by czarkoff** [comment]
Yes, it helps.

**Comment by czarkoff** [comment]
I dropped the `encoding-profiles.conf` commit, so now the question boils down to `example.conf` → `mpv.conf`.

**Comment by wm4** [comment]
Looks ok, will apply later. (Maybe you could add "etc: " as prefix, but I can do that myself.)

**Comment by wm4** [comment]
Pushed that commit.

**Comment by czarkoff** [comment]
Could you please also push 968bcfd3ba8e5585d878d8176d02220c04e09487?

**Comment by pigoz** [comment]
> Could you please also push 968bcfd by @pigoz?

@czarkoff: pushed

**Pull request closed without merging**
