### PR TITLE
Wayland cleanups and bugfixes

### PR DESCRIPTION
**Pull request by atomnuker**

### CODE REVIEW

**Comment by atomnuker** [comment]
Ping @giselher  
Do you know if any compositor has implemented these, because mutter 3.20 doesn't seem to support them.

**Comment by wm4** [comment]
Anyway, I'm ok with this change. It can always be readded later as Wayland matures.

**Comment by atomnuker** [comment]
Updated PR to fix recent regression.

**Comment by wm4** [comment]
Still looks a bit odd. Why does it need to process wayland events if only the wakeup pipe was signalled?

Also, you can always flush the wakeup pipe after the poll, independently of whether the wayland FD was signalled or not. (You can check the pipe FD before flushing the pipe just to avoid a redundant syscall.)

**Comment by atomnuker** [comment]
wl_display_dispatch_pending() doesn't block and can be called from other threads, so I thought it wouldn't hurt to dispatch any queued events (of which we have none since we don't use that feature, but maybe we could in the future) which happened during polling.
Removed it, also moved the dispatch and the display flush closer to the poll since that's what the documentation says.

**Comment by wm4** [comment]
Merged.

**Pull request closed without merging**
