### PR TITLE
osc: add volume and fullscreen button

### PR DESCRIPTION
**Pull request by wiiaboo**
New glyphs in osd font:
image
Muted; <33% vol; <66% vol; <=100% vol; >100% (volume-max).

Bottombar with volume and fullscreen buttons:
image

Box with volume button:
image

### CODE REVIEW

**Comment by wm4** [comment]
OK I guess.

Might need adjustment later whatever we do with those btn events.

**Comment by pavelxdd** [comment]
Hello, I've tested this PR, and only FS icon is visible, volume icon is invisible for me, thought the mouse up/down hotkeys work over it.
There're a lot of messages like this in console:
`[osd/libass] Glyph 0xE10C not found, selecting one more font for (mpv-osd-symbols, 400, 0)`

**Comment by wiiaboo** [comment]
If you tested by only using osc.lua you also need to compile mpv so the osd font has the new glyphs.

**Comment by pavelxdd** [comment]
No, I patched https://github.com/mpv-player/mpv/pull/4326.diff and recompiled mpv.
Just tried again, still no volume icon.

**Comment by wiiaboo** [comment]
osd_font.otf is a binary file, you can't use .diff to patch it.

**Comment by pavelxdd** [comment]
Oops, my bad, sorry.

**Comment by wiiaboo** [comment]
`git fetch origin pull/123/head:pr123` → checkout PR 123 to branch called "pr123". Easier than using .diff or .patch.

**Comment by wiiaboo** [comment]
@pavelxdd have you tested with the osd-font already?

**Comment by pavelxdd** [comment]
@wiiaboo, yes, it works perfect.

**Comment by shinchiro** [comment]
A little nitpick. IMO, in box layout, volume icon should be placed below fullscreen icon to make it consistent with sub,audio icon placed in left side

**Pull request merged**
