### PR TITLE
osc: add slimbottombar and slimtopbar layouts

### PR DESCRIPTION
**Pull request by b6boost**
These layouts essentially remove the playlist arrows, title and cache line from the normal bar layouts.

I agree that my changes can be relicensed to LGPL 2.1 or later.

### CODE REVIEW

**Comment by wiiaboo** [comment]
Would be easier to accept this if you managed to reduce the duplication of code between all the bar layouts.

**Comment by b6boost** [comment]
Ok, I've combined the creation of slim and full-size bars into a single function. How does it look?

**Comment by wiiaboo** [comment]
I was thinking more of a couple of functions to create the title line and the seekbar line. And between all four layouts you'd just change the order of them and not add a title line for the slim ones.

Haven't had time to check if you can actually do that or the new code lately.

**Comment by b6boost** [comment]
Kinda lost interest in this and don't really have time to work on it... May come back later.

**Pull request closed without merging**
