### PR TITLE
context_drm_egl: use eglCreatePlatformWindowSurfaceEXT if available

### PR DESCRIPTION
**Pull request by sfan5**

### CODE REVIEW

**Comment by philipl** [comment]
Thanks for doing this, but could do with a proper description.

**Comment by sfan5** [comment]
I wouldn't know what to put there except "This is identical to eglCreateWindowSurface but should be preferred as part of EGL's platform extension."

**Comment by philipl** [comment]
Even that's useful. Good to have some record of the motivation.

**Review by philipl — APPROVED** [review]

**Comment by evelikov** [comment]
Usually you'd want to check any of the extensions before using the function pointer. Since implementations can provide an invalid pointer otherwise.

**Comment by sfan5** [comment]
You mean `EGL_EXT_platform_base`?

**Comment by evelikov** [comment]
Yes either the base extension `EGL_EXT_platform_base` or any of the extensions that build on top of it `EGL_MESA_platform_gbm` `EGL_MESA_platform_surfaceless` `EGL_EXT_platform_wayland` `EGL_EXT_platform_x11` `EGL_EXT_platform_xcb`

**Pull request merged**
