### PR TITLE
Warning message for vo_vaapi & vo_vdpau

### PR DESCRIPTION
**Pull request by sfan5**

### CODE REVIEW

**Comment by CounterPillow** [comment]
It might be reasonable to add a `--warn-compatibility-vo` option which defaults to `yes`, so people can use `--no-warn-compatibility-wo` or put `warn-compatibility-vo=no` in their config files to hide the warning if they understand the implications. Could also apply to xv and x11 then.

**Comment by DanOscarsson** [comment]
I only use vdpau and have no issues with OSD, scaling or screenshots.
Why do you see it as low quality?
My tests with VO being opengl do not give better picture I can see, or audio/video sync.
For normal video viewing, from what I can see, vdpau is as good or better then opengl (cannot test vulkan as my card does not support it). Only when looking at video with HDR I need to use opengl (vo=gpu). 10 bit frames and HDR will not really be good under Linux before it is supported by the graphics driver, like the NVIDIA driver. Someday I will switch to vulkan but first it needs to be able to give feedback on when frames are displayed. Vdpau have good display queueing and feedback.
So what makes vdpau low quality for most videos/users?
I can see no reason to switch to vo=gpu before I can see that looking at a video gets better.

**Comment by CounterPillow** [comment]
>I only use vdpau and have no issues with OSD, scaling or screenshots.

Good for you, but that doesn't hold true for all files on all systems.

>Why do you see it as low quality?

It is a black box into which we feed video data, which means usually you probably get something like bilinear scaling.

> My tests with VO being opengl do not give better picture I can see, or audio/video sync.

Try `profile=gpu-hq`

>For normal video viewing, from what I can see, vdpau is as good or better then opengl

False, the shader based VO can do dithering, tonemapping, proper colorspace transformations, debanding, higher quality scaling, etc.

>10 bit frames and HDR will not really be good under Linux before it is supported by the graphics driver

False, mpv can and does dither 10-bit video down to 8-bit with the GPU VO, which means the output doesn't require driver support for 10butts.

> I can see no reason to switch to vo=gpu before I can see that looking at a video gets better.

And you don't have to, this is a warning, because most users who set the vdpau VO actually wanted to use the vdpau hwdec instead.

**Comment by DanOscarsson** [comment]
Yes, I am sure there are situations where vo GPU is better. But I primarily use mpv for movies and tv series. And display on a TV in 24 Hz. What parameters should I use with vo gpu to really see that it gets better then using vdpau as vo?
I have also noted from my tests vo gpu can take more time to do things (like setting up shaders) which may make vo gpu worse for slower systems as that may result in video frames missing intended vsync.
Anyway, I would not mind the warning if I could really feel that for normal viewing of moves and tv series vo gpu clearly showed that it is better.

**Comment by CounterPillow** [comment]
>What parameters should I use with vo gpu to really see that it gets better then using vdpau as vo?

The previous comment already explicitly gives some suggestions. `profile=gpu-hq` and `video-sync=display-resample`. I suspect your reasons for ignoring this and asking for the same information again are not well-intentioned, therefore I have no desire to regurgitate everything my previous comment said.

>I have also noted from my tests vo gpu can take more time to do things (like setting up shaders) which may make vo gpu worse for slower systems as that may result in video frames missing intended vsync.

Shader compilation happens at the start, not inbetween frames. If you are on a system where the GPU VO somehow misses vsync intervals due to a very slow OpenGL implementation, you are in a tiny minority and can ignore the warning as you are using the vdpau VO for compatibility.

**Comment by aufkrawall** [comment]
> 10 bit frames and HDR will not really be good under Linux before it is supported by the graphics driver

It works fine on 8 bit SDR displays. Dithering and tonemapping of `--vo=gpu` still don't disable `--gpu-dumb-mode` (afair), so `--vo=gpu` runs on many of the slowest GPUs if their driver support is not an issue. I use it on a Gemini Lake SoC myself.

**Comment by xantoz** [comment]
> Yes, I am sure there are situations where vo GPU is better. But I primarily use mpv for movies and tv series. And display on a TV in 24 Hz. What parameters should I use with vo gpu to really see that it gets better then using vdpau as vo?

```profile=gpu-hq --video-sync=display-resample```

**Comment by wm4** [comment]
+1, it's probably too early to remove those, but on the other hand I bet a lot of users get tricked into using them, thinking they're better.

**Pull request merged**
