### PR TITLE
stats.lua: fix ass-escape while persistent_overlay=yes

### LINKED ISSUE #9022: `persistent_overlay=yes` cause the `{` missing
### Important Information

Provide following Information:
- mpv version
commit 70c9d8d5d704764e35098843d1c9a788ee21beb6
- Windows Version
20h2
- Source of the mpv binary
built by the toolchain of shinchiro
- If known which version of mpv introduced the problem
commit 70c9d8d5d704764e35098843d1c9a788ee21beb6 (or earlier)
- Possible screenshot or video of visual glitches
see below

### Reproduction steps

1. start the mpv with the option: `persistent_overlay=yes` in the stats.conf
2. check stats list 4

The key `{` still works, it is just the display error.

### Expected behavior
Snipaste_2021-07-20_18-11-43

### Actual behavior
Snipaste_2021-07-20_18-09-06

### Log file
[osd.log](https://github.com/mpv-player/mpv/files/6847430/osd.log)

### PR DESCRIPTION
**Pull request by avih**
mpv has two methods to display output from text input:
- show-text (scripting: mp.osd_message) has ass disabled by default
  (escaped), and the property osd-ass-cc can control escaping.
- osd-overlay (scripting: mp.set_osd_ass or mp.create_osd_overlay)
  has ass enabled (unescaped), and osd-ass-cc is NOT supported.

By default, stats.lua uses mp.osd_message which does support escaping.
That's persistent_overlay=no.

When using persistent_overlay=yes then mp.set_osd_ass is used.

Due to this, the no_ASS(..) function - which is supposed to escape
ass, simply returned its input unmodified when persistent_overlay
is enabled.

This is not a new issue, and the filters on page 1 use no_ASS() to no
avail in persistent mode, however, this content (filter name and value
strings) rarely actually needs escaping, and users didn't notice.

However, the new page 4 (keys) does break visibly when no_ASS doesn't
work, because it tries to escape arbitrary key-names and command
strings, and at the very least the key '{' is bound by default, which
is displayed incorrectly if escaping doesn't work.

Fix this by rolling our own escaping when using mp.set_osd_ass,
similar to how the mpv code does it for mp.osd_message (substrings
replacements).

However, this means that the set_ASS(..) function can no longer
behave correctly because escaping requires going through the whole
content string rather than only inserting a marker.

Luckily, other than at no_ASS, set_ASS was only used at one place
(text_style), which is only called from two places:
- generate_graph() only needs to restore styles - not to enable ass.
- add_header() is only used at the begining of page output, and
  uses set_ASS to enable ass initially when using mp.osd_message.

So remove the set_ASS function, and instead enable ass directly at
print_page using osd-ass-cc when mp.osd_message is used.

Fixes #9022

### CODE REVIEW

**Comment by avih** [comment]
@Argon- I'd appreciate if you could have a look. Thanks.

**Comment by avih** [comment]
Oops, typo at the unicode codepoint - I used the UTF-8 sequence for U+2600 instead of U+2060 (WORD-JOINER).

Patch updated.

**Comment by avih** [comment]
I really should be more careful. Removed accidental space left at the string when escaping backslash. Patch updated.

**Comment by Argon-** [comment]
> @Argon- I'd appreciate if you could have a look. Thanks.

Will do, might take me until the weekend though, sorry! Hope there's no hurry.

Fascinating that nobody noticed this problem for such a long time...

**Comment by garoto** [comment]
> Fascinating that nobody noticed this problem for such a long time...

Perhaps because `persistent_overlay=yes` is a somewhat niche option for likewise usecases. I don't even know if i can spot the difference between `true` and `false` with my current config,

**Comment by Argon-** [comment]
> Perhaps because `persistent_overlay=yes` is a somewhat niche option for likewise niche usecases.

Well it was only implemented because of multiple and continuous requests so I always assumed it was used by at least a few people

**Comment by Argon-** [comment]
LGTM 👍🏻

`set_ASS` was less about escaping and actually more about activating ASS formatting, which is off by default in `mp.osd_message` (or at least was?). So when I implemented `persistent_overlay` I probably didn't even think about the need to escape certain characters.

**Comment by avih** [comment]
> which is off by default in `mp.osd_message` (or at least was?)

Still is, as the comment says:
```lua
    -- the page functions assume we start in ass-enabled mode.
    -- that's true for mp.set_osd_ass, but not for mp.osd_message.
```

Thanks.

**Pull request merged**
