### PR TITLE
x11: use GLX with the Nvidia proprietary driver, use EGL otherwise

### PR DESCRIPTION
**Pull request by Gusar321**

### CODE REVIEW

**Comment by jeeb** [comment]
@Gusar321 thanks for the contribution, but it would be nice to know a little story regarding "why?".

The end result is that instead of checking for an extension, instead the GL vendor is checked for. That much is understandable :) .

**Comment by Gusar321** [comment]
See the comments in #5298 as to why, especially the last one. AMD users want to use hardware decoding, but it fails without any clear indication from mpv's side as to why it failed. The reason for the failure is that mpv picks GLX due to the existence of the vdpau_interop extension, but VAAPI only works with EGL. I've had several instances helping people get hardware decoding to work that ended with "oh yeah, I forgot, you need --gpu-context=x11egl"

The current mpv behavior is dumb IMO, why does the vdpau_interop extension matter when the user doesn't even intend to use VDPAU?

Though if #5298 gets merged, AMD/VAAPI will work out of the box, but Nvidia/VDPAU will break, it'll then be Nvidia users who will need to specify additional options, because VDPAU is GLX-only. So this PR is a compromise, that doesn't screw either AMD or Nvidia users. This PR is also a kludge, opening a GLX context just to check the vendor string doesn't feel right, there should be a better way to decide between GLX and EGL. But this was the easiest way to implement what I wanted.

**Comment by jeeb** [comment]
Thanks for the explanation.

Yes, sounds like the original kludge-check has outlived its usefulness :) I will have to ask around if this happens to hit Nouveau as well, or if that has a different Mesa/Nouveau-specific vendor string.

**Comment by jeeb** [comment]
Also for the majority of nvidia users, nvdec is preferred I think. VDPAU would mostly be limited to older devices which do not have support on the nvdec side.

**Comment by jeeb** [comment]
As for an older nvidia with nouveau:
```
server glx vendor string: SGI
client glx vendor string: Mesa Project and SGI
OpenGL vendor string: nouveau
```

**Comment by wm4** [comment]
The way it was implemented used to make sense before vaapi made more sense than vdpau on AMD. It tried to use GLX when vdpau was available, and all drivers that provided vdpau required using it for hwdec. Now everything is different: AMD basically requires vaapi and EGL, and on nvidia you need to use nvdecode (not sure if that works on GLX, but it does on EGL just fine). Using GLX makes no sense anymore, except for legacy drivers.

The default will be switched to always use EGL; pull request rejected.

**Pull request closed without merging**
