### PR TITLE
ao_opensles: fix delayed audio

### PR DESCRIPTION
**Pull request by sfan5**
thanks to @xyzz for pointing this out

I agree that my changes can be relicensed to LGPL 2.1 or later.

### CODE REVIEW

**Comment by tomty89** [comment]
While it might *seem* right, as we switched from "double buffering" to "single buffering", I am not sure if actually right.

According to the documentation of `ao_read_data`, this means the second enqueue (the first actual "callback") is triggered at the end of the playback of the first. Only then the delay would be of the length of the buffer itself.

And that doesn't sound right. And I don't suppose programmatically it could be triggered at some vague point like "nearly the end" or similar. It appears to me that the only sensical approach would be to enqueue the next buffer right after the first got received. That's why I proposed https://github.com/mpv-android/mpv-android/issues/200#issuecomment-521616645.

But certainly I am having a lot of assumptions here. So change to however that works. I am not exactly a "user" of the delay anyway.

**Comment by tomty89** [comment]
Say each buffer is 250ms:
enqueue first (kickstart in `resume()`) -> play first and enqueue second simultaneously (0)
first playback finish, play second and enqueue third simultaneously (250)
second playback finish, play third and enqueue fourth simultaneously (500)
third playback finish, play fourth and enqueue fifth simultaneously (750)
...

As you can see, the first buffer takes 250ms to finish, while each of the buffers that follows takes 500ms to.

**Comment by sfan5** [comment]
I've just tested your patch and it does not fix the issue.

**Comment by tomty89** [comment]
I have also come up with this:
```
diff --git a/audio/out/ao_opensles.c b/audio/out/ao_opensles.c
index 8c24320406..b3faa42e9e 100644
--- a/audio/out/ao_opensles.c
+++ b/audio/out/ao_opensles.c
@@ -39,6 +39,7 @@ struct priv {
     int bytes_per_enqueue;
     pthread_mutex_t buffer_lock;
     double audio_latency;
+    int64_t last;

     int frames_per_enqueue;
     int buffer_size_in_ms;
@@ -76,13 +77,21 @@ static void buffer_callback(SLBufferQueueItf buffer_queue, vo
id *context)
     struct priv *p = ao->priv;
     SLresult res;
     double delay;
+    int64_t now;

     pthread_mutex_lock(&p->buffer_lock);

-    delay = 2 * p->frames_per_enqueue / (double)ao->samplerate;
+    delay = p->frames_per_enqueue / (double)ao->samplerate;
+    now = mp_time_us();
+    if (p->last) {
+      p->last = now - p->last;
+      if (p->last < 1000000LL * delay)
+       p->last = 1000000LL * delay - p->last;
+    }
     delay += p->audio_latency;
     ao_read_data(ao, &p->buf, p->frames_per_enqueue,
-        mp_time_us() + 1000000LL * delay);
+        now + p->last + 1000000LL * delay);
+    p->last = now;

     res = (*buffer_queue)->Enqueue(buffer_queue, p->buf, p->bytes_per_enqueue);
     if (res != SL_RESULT_SUCCESS)
@@ -236,6 +245,7 @@ static void reset(struct ao *ao)
 static void resume(struct ao *ao)
 {
     struct priv *p = ao->priv;
+    p->last = 0;
     buffer_callback(p->buffer_queue, ao);
 }

```
If I show `p->last` with `MP_ERR`, its values seem to make sense, which roughly alternate between 0 and 1 buffer. It also seem to compensate the start-up time of the actual playback.

But if it doesn't work better than this PR in reality, never mind then.

**Comment by sfan5** [comment]
Your new patch causes playback to stall constantly, dropping frames. Audio is in sync though.

**Comment by tomty89** [comment]
I guess we don't really need to constantly "re-calibrate" the delay like that.

Perhaps this will still do some good though:
```
diff --git a/audio/out/ao_opensles.c b/audio/out/ao_opensles.c
index 8c24320406..3fa1349522 100644
--- a/audio/out/ao_opensles.c
+++ b/audio/out/ao_opensles.c
@@ -39,6 +39,7 @@ struct priv {
     int bytes_per_enqueue;
     pthread_mutex_t buffer_lock;
     double audio_latency;
+    int resumed;

     int frames_per_enqueue;
     int buffer_size_in_ms;
@@ -79,10 +80,13 @@ static void buffer_callback(SLBufferQueueItf buffer_queue, vo
id *context)

     pthread_mutex_lock(&p->buffer_lock);

-    delay = 2 * p->frames_per_enqueue / (double)ao->samplerate;
+    delay = p->frames_per_enqueue / (double)ao->samplerate;
     delay += p->audio_latency;
-    ao_read_data(ao, &p->buf, p->frames_per_enqueue,
-        mp_time_us() + 1000000LL * delay);
+    if (p->resumed)
+        ao_read_data(ao, &p->buf, p->frames_per_enqueue,
+            mp_time_us() + 1000000LL * delay);
+    else
+        p->resumed = 1;

     res = (*buffer_queue)->Enqueue(buffer_queue, p->buf, p->bytes_per_enqueue);
     if (res != SL_RESULT_SUCCESS)
@@ -236,6 +240,7 @@ static void reset(struct ao *ao)
 static void resume(struct ao *ao)
 {
     struct priv *p = ao->priv;
+    p->resumed = 0;
     buffer_callback(p->buffer_queue, ao);
 }

```

As the kickstart enqueue can often take longer (for the backend to start or something like that I guess), which makes the delay inaccurate. Other than that, it's probably fine to simply have now + buffer length as the delay.

**Comment by tomty89** [comment]
I wonder if this is necessary:
```
diff --git a/audio/out/ao_opensles.c b/audio/out/ao_opensles.c
index 8c24320406..839a8ed10c 100644
--- a/audio/out/ao_opensles.c
+++ b/audio/out/ao_opensles.c
@@ -35,7 +35,7 @@ struct priv {
     SLBufferQueueItf buffer_queue;
     SLEngineItf engine;
     SLPlayItf play;
-    void *buf;
+    void *buf, *slc;
     int bytes_per_enqueue;
     pthread_mutex_t buffer_lock;
     double audio_latency;
@@ -66,6 +66,8 @@ static void uninit(struct ao *ao)

     free(p->buf);
     p->buf = NULL;
+    free(p->slc);
+    p->slc = NULL;
 }

 #undef DESTROY
@@ -79,7 +81,7 @@ static void buffer_callback(SLBufferQueueItf buffer_queue, void
 *context)

     pthread_mutex_lock(&p->buffer_lock);

-    delay = 2 * p->frames_per_enqueue / (double)ao->samplerate;
+    delay = p->frames_per_enqueue / (double)ao->samplerate;
     delay += p->audio_latency;
     ao_read_data(ao, &p->buf, p->frames_per_enqueue,
         mp_time_us() + 1000000LL * delay);
@@ -163,7 +165,8 @@ static int init(struct ao *ao)
     p->bytes_per_enqueue = p->frames_per_enqueue * ao->channels.num *
         af_fmt_to_bytes(ao->format);
     p->buf = calloc(1, p->bytes_per_enqueue);
-    if (!p->buf) {
+    p->slc = calloc(1, p->bytes_per_enqueue);
+    if (!p->buf || !p->slc) {
         MP_ERR(ao, "Failed to allocate device buffer\n");
         goto error;
     }
@@ -236,7 +239,16 @@ static void reset(struct ao *ao)
 static void resume(struct ao *ao)
 {
     struct priv *p = ao->priv;
-    buffer_callback(p->buffer_queue, ao);
+    SLresult res;
+
+    pthread_mutex_lock(&p->buffer_lock);
+
+    res = (*p->buffer_queue)->Enqueue(p->buffer_queue, p->slc,
+                                      p->bytes_per_enqueue);
+    if (res != SL_RESULT_SUCCESS)
+        MP_ERR(ao, "Failed to resume: %d\n", res);
+
+    pthread_mutex_unlock(&p->buffer_lock);
 }

 #define OPT_BASE_STRUCT struct priv
```
It introduces significant latency upon `resume()`, but will probably prevent frame drops between the first and second enqueue after `resume()` because the delay set for the former will always be inaccurate.

But again, it's only my guess base on the logging of `mp_time_us()`, if you don't experience any problem with only this PR and/or experience nothing but adverse effect with the above patch, then perhaps this PR should just get merged.

**Comment by LukePulverenti** [comment]
Just a heads up. We (Emby) have been testing this fix and have gotten positive feedback about it.

**Comment by jeeb** [comment]
@tomty89 we should look into this, but for now let's get this in since it seems like this would for now improve the results.

**Pull request merged**
