### PR TITLE
vo_opengl: add credits to NNEDI3 shader

### PR DESCRIPTION
**Pull request by bjin**
Add credits to several existing implementation of NNEDI3 shader.

@zachsaw Please take a look

### CODE REVIEW

**Comment by zachsaw** [comment]
@bjin Looks good.

Not sure about the license change though - the shader implementation is more of a derivative work of SEt's OpenCL NNEDI3 which is LGPLv3 (tritical himself accepts SEt's LGPLv3 license for the GPU implementation). We additionally have the approval of all the parties involved on top of that.

If the derivative work is based on MPDN Extensions' NNEDI3 HLSL implementation rather than tritical's original implementation, then it stands to reason that the license has to be LGPLv3. In fact, tritical explicitly gave me permission to release NNEDI3 as LGPLv3 in the form of MPDN's HLSL implementation.

That said, LGPLv3 is a rather permissive license - there's no reason why you can't make it compatible with MPV.

**Comment by bjin** [comment]
@wm4 Assuming it's derivative work,  would a "--enable-lgpl3" configure flag an option?

**Comment by wm4** [comment]
If you think this code must be LGPL3, we'll have to remove it again.

**Comment by wm4** [comment]
I've merged this commit as-is for now.

@zachsaw: LGPLv3 is unacceptable for us. Which parts exactly do you think should be copyrighted under LGPLv3?

**Comment by wm4** [comment]
@bjin: also, I thought the license issue was taken care of. So on what exactly is the mpv code based on?

**Comment by bjin** [comment]
@wm4 I somehow believe it's not derivative work, but if an actual clean room reimplementation is required in this case, then as suggested by @zachsaw, my implementation is mostly a derivative work of SEt's OpenCL kernel. There is some improvement from the HLSL shader, but none of these is inherited in the reimplementation I believe. (@zachsaw Could you verify this? since details of some of your improvement is actually not documented)

I will try to reach SEt to see if relicensing is an option or not.

**Comment by bjin** [comment]
Close in favor of #2555 

As the shader license is still unclear, remove nnedi3 for now to save us from potential legal issues.

I'm still waiting for response from SEt, let's see if relicensing is an option or not.

**Comment by haasn** [comment]
@bjin I assume there has been no response from SEt? I too would be interested in reimplementing NNEDI3 in mpv, and I would be following the OpenCL version as the reference for mine. (Not the HLSL version from MPDN nor the existing GLSL version)

**Comment by bjin** [comment]
@haasn Yes, no response from SEt. Do you plan to do it in clean room to get rid of the license issue?

**Comment by haasn** [comment]
I don't understand the algorithm or the optimizations involved well enough to do a clean room. I would try doing a 1:1 port of the OpenCL version, including all the tricks he uses to process multiple pixels at the same time. (Rather than mpv's version, which is like an order of magnitude slower for executing the full loop for every single pixel)

**Pull request closed without merging**
