### PR TITLE
gitignore: ignore /.cache

### PR DESCRIPTION
**Pull request by Coeur**

### CODE REVIEW

**Comment by Dudemanguy** [comment]
Is there something that generates a `.cache` directory in here?

**Comment by Coeur** [comment]
My Meson build did so. Not sure why.

**Comment by Dudemanguy** [comment]
Hmm that doesn't seem right. Meson only supports out-of-tree builds.

**Comment by eli-schwartz** [comment]
What was inside this directory? Meson doesn't contain any direct code to do such a thing, though it's not beyond reason that a tool it invoked decided to do so on its own.

**Comment by Coeur** [comment]
I'm not able to reproduce for now, so let's close the PR.
If I reproduce, I'll give more details.

**Pull request closed without merging**
