### PR TITLE
youtube-dl_mpv.sh: use curly braces and double quotes consistently

### PR DESCRIPTION
**Pull request by vitorgalvao**

### CODE REVIEW

**Comment by wm4** [comment]
Merged. Though note that mpv now uses youtube-dl directly.

**Comment by vitorgalvao** [comment]
Interesting, I missed that addition. This script could then be removed, right?

**Comment by wm4** [comment]
Yeah. Though some sites don't work with native support (missing cookies/useragent).

**Comment by shdown** [comment]
Actually `$video_url` was left unquoted deliberately, as `youtube-dl` may produce multiple URLs.
They may not contain whitespace and `set -f` (what is it for now?) disables globbing (including expansion of `?`, which they can contain), so that was safe.

**Comment by wm4** [comment]
Oops. In any case, I think the builtin script should be improved instead.

**Comment by wm4** [comment]
>Yeah. Though some sites don't work with native support (missing cookies/useragent).

This is fixed now.

Is there still a reason why youtube-dl_mpv.sh should exist?

**Pull request merged**
