### PR TITLE
DOCS: add a simple note about `shift+`

### PR DESCRIPTION
**Pull request by hooke007**
https://github.com/mpv-player/mpv/issues/9060

### CODE REVIEW

**Comment by Argon-** [comment]
This is not what was said in #9060. Whether this works depends on the user. "No support" is simply not true. I think this would require a more elaborate explanation and I'm not sure if that's actually useful to potentially confused users. Maybe a hint that they might want to try `!` is more useful.

**Comment by hooke007** [comment]
> "shift+<letter/number>" is usually registered as one key without modifier. For instance `shift+2` is usually registered as key name `@`, `shift+e` registers as `E`, `alt+shift+2` as `alt+@` (or `meta+@` on some systems), etc. However, without shift, the base name is used normally, like `2` or `alt+2` etc.

It seems also remind users not to use shift+<letter>.

**Comment by hooke007** [comment]
Thanks, I see the new commit. So, close this PR?

**Comment by avih** [comment]
Thanks, pushed as 6b828113 , changed the note to:
```
The ``Shift`` modifier requires some attention. For instance ``Shift+2`` should
usually be specified as key-name ``@`` at ``input.conf``, and similarly the
combination ``Alt+Shift+2`` is usually ``Alt+@``, etc. Special key names like
``Shift+LEFT`` work as expected. If in doubt - use ``--input-test`` to check
how a key/combination is seen by mpv.
```

**Pull request closed without merging**
