### PR TITLE
OSD: implement multiple OSD_EXTERNALs.

### PR DESCRIPTION
**Pull request by torque**
:warning: This really probably shouldn't be merged just yet.

#### Rationale
The (currently undocumented) Lua API function `mp.set_osd_ass` is very useful and powerful because it allows drawing in the mpv window with positioned and formatted text as well as vector graphic primitives. 
This makes it the most versatile way to display messages for the user and create interactive scripts. However, it's terribly limited because it is global. Any script that uses it will overwrite what any other script has drawn.

#### Possible Solutions
1. Concatenate all OSD draw calls in Lua.
  - Pros: easy to implement.
  - Cons: All scripts must share a virtual OSD resolution, which makes positioning and sizing troublesome.

2. Extend current OSD API to support a variable number of layers.
  - Pros: eliminates the need for shared virtual resolutions.
  - Cons: the entire OSD system is designed to work with a set number of OSDs, which causes a lot of trouble.

3. Implement a new API specifically for script OSDs.
  - Pros: solves the cons of the first two.
  - Cons: requires changing all the VO's to support the new API, more code to maintain.

#### This PR
I've implemented a very hacked-up version of solution 2. While I don't think this is ready for prime-time yet, I'm submitting it because I'm hoping to get some feedback. While I personally think that solution 3 is probably the best in the long run, I don't know enough about mpv's internals to do that well.

##### Details

The particular solution this patch employs is to turn all of the OSD types into linked lists. The only one that ends up having more than one element is `OSDTYPE_EXTERNAL`. When the OSDs are being rendered, the linked list is iterated through and all resulting bitmaps are joined into a single `sub_bitmaps` struct. This keeps each member of the linked list from overwriting the bitmaps of the previous members, but it also probably destroys the caching, because the cache is not designed to cope with this. I don't really understand the OSD cache, so I'm not sure what the best way to fix this is.

The actual layer ordering of the OSDs is controlled by Lua. The new Lua OSD API consists of a registration function that returns a closure to be used for actually updating the OSD. The function signature of the closure is the same as the old `mp.set_osd_ass` api.

Things to do:
- [ ] Play nicely with the OSD caches.
- [ ] Don't leak memory.
- [ ] Remove unnecessary comments.
- [ ] Increase code quality?
- [ ] Investigate alternate solutions.
- [ ] Make part of documented Lua API.

### CODE REVIEW

**Comment by wm4** [comment]
One possible alternative: add multiple osd objects useable for scripts, like OSDTYPE_EXTERNAL0 to OSDTYPE_EXTERNAL7. If a script wants to set an overlay, assign one of them to it (i.e. you allocate from a fixed set of free objects). Then hope the static number is enough for all use-cases. This would possibly simplify it a bit.

>Cons: All scripts must share a virtual OSD resolution, which makes positioning and sizing troublesome.

Why?

>Cons: requires changing all the VO's to support the new API, more code to maintain.

The sub_bitmaps lists (coming from ASS_Images) can just be concatenated, and should not require changes in the VO. Your PR actually tries to accomplish something like this.

(Actually I'd love if all OSD images could be in the same format, so different OSD "types" are not even distinguished in the VOs. But judging from discussions on the IRC channel, it looks like RGBA ASS_Images are actually inefficient, so we'd still need multiple formats - so it looks like this won't happen after all.)

**Comment by wm4** [comment]
PS: I'm also wondering what API Lua should export at all. With as of this PR, multiple scripts could add arbitrary layers and cover other script's layers. And mouse input is handled separately from this too. It's a recipe for chaos, but I don't know what could be done to prevent this. (Short of letting one script manage the mouse input and screen output of other scripts, which would end up as some sort of freaky X11-like abomination.)

**Comment by torque** [comment]
>One possible alternative: add multiple osd objects useable for scripts, like OSDTYPE_EXTERNAL0 to OSDTYPE_EXTERNAL7. If a script wants to set an overlay, assign one of them to it (i.e. you allocate from a fixed set of free objects). Then hope the static number is enough for all use-cases. This would possibly simplify it a bit.

This would be a much more clean way of implementing it within the constraints of the current OSD design. While I'm not crazy on the idea of a set number of OSDs, this would definitely be better than the current situation of only having one.

>>Cons: All scripts must share a virtual OSD resolution, which makes positioning and sizing troublesome.

>Why?

Basically, the problem is that the window doesn't have a fixed aspect ratio (e.g. watching a 4:3 video fullscreen on a 16:10 monitor will force the window aspect ratio to 16:10 by pillarboxing). When there is an aspect ratio mismatch, the placement of the OSD in the window will change. This can probably be manually compensated for by knowing the window size, the window margins, and the virtual resolution, but it seems silly to me to be unscaling things just so libass can re-scale them. As a visual example, the line `mp.set_osd_ass(1280, 720, [[{\an7\pos(0,0)\p1\bord0\shad0\1c&HCAB296&}m 540 360 l 1180 360 1180 720 540 720]])` looks like [this](https://dl.dropboxusercontent.com/u/60473660/16.9.png) on a 1280x720 window and like [this](https://dl.dropboxusercontent.com/u/60473660/16.10.png) on a 1280x800 window.

For example, I currently have a script that draws a 2px tall progress bar at the bottom of the window at all times. The most straightforward way to accomplish this is to keep the OSD always at the same resolution as the window. I might play around with this a little to see if I can get it to work with a fixed-resolution OSD, though.

>The sub_bitmaps lists (coming from ASS_Images) can just be concatenated, and should not require changes in the VO. Your PR actually tries to accomplish something like this.

You're right. I'll look into this.

>PS: I'm also wondering what API Lua should export at all. With as of this PR, multiple scripts could add arbitrary layers and cover other script's layers. And mouse input is handled separately from this too. It's a recipe for chaos, but I don't know what could be done to prevent this. (Short of letting one script manage the mouse input and screen output of other scripts, which would end up as some sort of freaky X11-like abomination.)

Hmm, right. I pretty much completely forgot about the mouse when I was working on this. I don't have any ideas about this currently, but I'll think about it.

**Comment by wm4** [comment]
>While I'm not crazy on the idea of a set number of OSDs, this would definitely be better than the current situation of only having one.

Sounds like the way to go then. Maybe it can be cleaned up later (when we have refcounting and rendering ahead ASS subs?).

>This can probably be manually compensated for by knowing the window size, the window margins, and the virtual resolution, but it seems silly to me to be unscaling things just so libass can re-scale them.

Actually there's already tons of weird scaling (also for mouse coordinates), which was supposed to do "the right thing", but actually is just confusing. Maybe always using screen pixels would simplify it. Then the script would have to take care of things like differing aspect ratios manually, and would have a very good chance at getting pixel-perfect drawing right too.

(Things like vo_xv complicate this: vo_xv has to render OSD directly into the unscaled video, because Xv is shit.)

**Comment by torque** [comment]
>Actually there's already tons of weird scaling (also for mouse coordinates), which was supposed to do "the right thing", but actually is just confusing. Maybe always using screen pixels would simplify it. Then the script would have to take care of things like differing aspect ratios manually, and would have a very good chance at getting pixel-perfect drawing right too.

Yes, the mouse scaling has been an annoyance to me, as I had to write [some code](https://github.com/torque/mpv-url-overlay/blob/master/src/CoordinateTranslator.moon) to translate mouse coordinates from the OSD resolution to the window resolution to the video resolution. To be honest, forcing the OSD to always match the window resolution would allow all of the concatenation and layering to be done purely in Lua. As you mentioned in IRC, though, this would not look as good when the window was being resized (e.g. when enlarging the window, a subtitle positioned at the bottom of the window would stick at its old position until the script updated it for the new resolution). Personally, I don't think this is a major concern, but I don't tend to do any resizing besides switching between fullscreen and windowed.

I have no problem with going this direction, if it seems reasonable. I'm not sure how we'd work around noncompliant vo's though.

**Comment by wm4** [comment]
>To be honest, forcing the OSD to always match the window resolution would allow all of the concatenation and layering to be done purely in Lua.

Sounds like the way to go, then.

> As you mentioned in IRC, though, this would not look as good when the window was being resized (e.g. when enlarging the window, a subtitle positioned at the bottom of the window would stick at its old position until the script updated it for the new resolution).

Yes, that's a problem. It could probably be done by handling the resolution switch lazily, and somehow synchronizing all scripts so they resize at the same time (but I'm not sure if it can work, and it's certainly not simple).

> I'm not sure how we'd work around noncompliant vo's though.

The mouse coordinates are already translated in this case (by input.c, so before any Lua considerations), so the only special thing about vo_xv (and similar) is that mouse and OSD coordinates can be different from the actual window size. So what matters is ``mp_osd_res.w/h``.

**Comment by torque** [comment]
I was thinking about this a little bit, and the only problem I can think of with doing the layering in Lua is that if/when other scripting language interfaces are implemented, those other languages would not be able to play well with it, so the layering would probably need to be eventually rewritten in C.

On the other hand, the Ruby branch seems pretty dead and the Javascript PR doesn't look like it's going to be merged any time soon, so maybe I shouldn't worry about it. Though I'd rather not add code that has a high probability of needing to be changed in the future.

Anyway, planning on getting back to messing around with this soon.

**Comment by wm4** [comment]
If the layering can be done in Lua, then it'd probably be rather easy to do in C too, because no new mechanisms would be required at this point.

**Comment by wm4** [comment]
Obsoleted by 75a36662cb6bb0c8a2aeb3a4034d3f8dc745bbdd; although better ways to handle this are still needed.

**Pull request closed without merging**
