### PR TITLE
man/options: Document cuda hwdec.

### PR DESCRIPTION
**Pull request by philipl**
Ideally, you shouldn't need enter any text here, and your commit messages should
explain your changes sufficiently (especially why they are needed). Read
https://github.com/mpv-player/mpv/blob/master/DOCS/contribute.md for coding
style and development conventions. Remove this text block, but if you haven't
agreed to it before, leave the following sentence in place:

I agree that my changes can be relicensed to LGPL 2.1 or later.

### CODE REVIEW

**Comment by wm4** [comment]
Thanks, merged.

**Comment by Kagami** [comment]
@philipl could you elaborate please?

>10bit HEVC is currently not supported but we can add support after CUDA 8 is released

2048ad2b8af1becddb70cad2a7adc0361b779443 states there are support:

>Final note: I mentioned HEVC Main10. While there is no 10bit output
>support, NvDecode can return dithered 8bit NV12 so you can take
>advantage of the hardware acceleration.

**Comment by philipl** [comment]
10bit support requires building ffmpeg with a modified header. You need to take the Cuda 7.5 header and copy over a change from the video sdk 7.0 version of the header.  I'm hoping the Cuda 8 header has this change in it. 

You cannot build ffmpeg directly against the video sdk header so it's all a mess right now.

**Comment by Kagami** [comment]
Could you please provide this header file with all needed changes? I will try to build ffmpeg using it.

**Comment by Kagami** [comment]
Btw, CUDA 8 RC is already released: https://developer.nvidia.com/cuda-release-candidate-download

**Comment by philipl** [comment]
Yes, but that has a five year old header in it. It's older than the one in 7.5.

**Comment by philipl** [comment]
@Kagami: https://gist.github.com/philipl/6dc26c8f267781dd4760e24a6f31a7e4

**Comment by Kagami** [comment]
Thanks, but it turned out that I can't actually test it on my videocard… Though it's great to finally have hardware acceleration for HEVC Main10 on Linux.

**Comment by amietn** [comment]
@Kagami @philipl Works perfectly with the modified ffmpeg and cuda headers. HEVC Main 10 4k 60 fps on Linux :) Thanks a lot

**Pull request closed without merging**
