### PR TITLE
Update filters and add ewa_lanczos4sharpest

### PR DESCRIPTION
**Pull request by haasn**

### CODE REVIEW

**Comment by haasn** [comment]
Should probably fix this bug first, needs to be tested

```diff
diff --git a/video/out/filter_kernels.c b/video/out/filter_kernels.c
index 888215f1de..76983e7e2f 100644
--- a/video/out/filter_kernels.c
+++ b/video/out/filter_kernels.c
@@ -116,7 +116,8 @@ static double sample_window(struct filter_window *kernel, double x)
 static double sample_filter(struct filter_kernel *filter, double x)
 {
     // The window is always stretched to the entire kernel
-    double w = sample_window(&filter->w, x / filter->f.radius * filter->w.radius);
+    double r = (filter->f.blur ? filter->f.blur : 1.0) * filter->f.radius;
+    double w = sample_window(&filter->w, x / r * filter->w.radius);
     double k = w * sample_window(&filter->f, x);
     return k < 0 ? (1 - filter->clamp) * k : k;
 }
```

**Comment by Artoriuz** [comment]
Are the radii of `jinc`, `ewa_lanczos`, `ewa_hanning` and `ewa_ginseng` really supposed to be `3` now instead of `3.2383154841662362`?
Doesn't libplacebo use `3.2383154841662362` for the raw `ewa_lanczos` as well?

**Comment by haasn** [comment]
> Are the radii of `jinc`, `ewa_lanczos`, `ewa_hanning` and `ewa_ginseng` really supposed to still be `3` instead of `3.2383154841662362`? Doesn't libplacebo use `3.2383154841662362` for the raw `ewa_lanczos` as well?

I guess we could change this also for consistency, though note that fractional polar samplers are a bit less optimized in `vo_gpu` than in `vo_gpu_next`.

**Comment by haasn** [comment]
Updated, now I'm happy with this series

**Comment by Jules-A** [comment]
Aww you already merged, was going to ask if you could map Hermite. It seems to been talked about highly by quite a few people lately and I've been testing it lately and not having to set extra params and having it show up in osd would be nice.

**Comment by JimboTHX1138** [comment]
I'm confused. So what is the sharpest filter now. ewa_lanczossharp or ewa_lanczos4sharpest?

**Comment by dokur0chan** [comment]
`ewa_lanczos4sharpest`

**Pull request merged**
