### PR TITLE
Fix DVB channel switching

### LINKED ISSUE #2568: DVB channel switching broken
I was just made aware of the problem that DVB channel switching does not work anymore with current mpv. 
A bisect shows the following commit broke it:
a609877f00889a5cb5fe3e4e2877eec49cc90ab0

A gist from running mpv and switching a channel at that commit looks like:
https://gist.github.com/olifre/79758fa0c4473a4a4931
It seems lavf does not fully attempt to redetect everything, I don't see a second max-analyze-duration being reached etc. 

Since I am unsure how to fix, but have the hardware to test: Please tell me any further information that could help!

### PR DESCRIPTION
**Pull request by olifre**
This fixes #2568 . 

I am not sure this is the best solution, I am open for discussion. 
The solution is two-staged: Everything related to "state" which should be persisted as long as DVB may be used (channel lists, current channel,. FDs etc.) is now separated into a separate state-structure. 
A pointer to this state-structure is persisted via a static pointer in stream_dvb. 
If the state-structure exists, it is picked up during dvb_open(). 
If a channel-switch is requested, the state is flagged and destruction of state will be prevented ONCE during dvbin_close(). Otherwise, state is destructed (and FDs cleaned up etc.) as usual. 
This should prevent any leaks at end of process. 
I can confirm channel switching works again with this solution, but maybe there is a better way or place e.g. to hook up the state-destruction / persist the state, if so, I am open to change.

### CODE REVIEW

**Comment by wm4** [comment]
This looks good, except the global state bit. You need to find a way to pass this through somehow.

**Comment by olifre** [comment]
I just added the title-metadata getter. 

> This looks good, except the global state bit. You need to find a way to pass this through somehow.

With global state bit, you mean the static pointer - or the "switching_channel" flag? 
Do you have an idea on where to store it, or to where / whom to push it through?

**Comment by wm4** [comment]
The ``global_dvb_state`` variable.

We could probably decide that it's fine if only 1 DVB stream can ever be active (even if e.g. libmpv is used and multiple libmpv contexts are created at the same time). But then there should be some reliable mechanism to let opening the stream fail if it's already in use, instead of allowing that two stream instances use the same state. A global mutex to protect the variable and an in-use bit could be used.

**Comment by olifre** [comment]
> We could probably decide that it's fine if only 1 DVB stream can ever be active (even if e.g. libmpv is used and multiple libmpv contexts are created at the same time). 

I agree. Technically, for the same card, it's anyways kind of impossible to technically create different stream_dvb instances, since once it's tuned it's tuned - one would have to enforce that the different stream instances would treat different cards, or enforce those that are on the same card to share transponder and then rewrite the way the demuxing of the stream from the card is done. 
I think that would be overly complicated - I already implemented `--dvbin-full-transponder` last year which allows to use (or record) the full transponder information with a single stream instance. Anything other than that is not really a "player" usecase anymore (mythtv or tvheadend are projects centered on fully treating such complex cases). 


> But then there should be some reliable mechanism to let opening the stream fail if it's already in use, instead of allowing that two stream instances use the same state. A global mutex to protect the variable and an in-use bit could be used.

Sounds like a good idea, better safe than sorry! I'll implement something.

**Comment by olifre** [comment]
Like this? I believe I protected all usage-bit-flipping,. and also creation and destruction of the state, by the global mutex. 
I'll next look into the dvb-channel-name property.

**Comment by wm4** [comment]
Seems fine.

**Comment by olifre** [comment]
> Seemsfine. 

Ok. Then two more questions on the dvb-channel-name property... 

At the moment it seems to me I need to do a `talloc_strdup` when returning a string via an arg from the stream-control (and subsequenty push that pointer through my function `mp_property_dvb_channel_name`). Is that correct? It seems the `m_property` code takes care of deallocation. 
Or is there a more efficient way (I already have all program names allocated in the channel list)? 
The second question is related: If I am given a string via "arg" for a property which is to be set, it seems I do not need to take ownership / should not deallocate, is this correct?

This looks really convenient, but of course is not extremely efficient, that's why I am asking (I am almost finished with the implementation already, but when testing mpv with `--title='${dvb-channel-name}'` which one probably should not do it's terribly slow).

**Comment by olifre** [comment]
As you can see, I implemented the dvb-channel-name property assuming the ownership of the strings is as outlined in my last comment. 
I also implemented "switch" for dvb-channel-name and added default bindings (just the tv-bindings "h" and "k", but for DVB they are "H" and "K") and documented the new bindings and properties in the manpage. 
Is this ok? Should there also be some addition to some changelog? 
In addition to what is added now, I personally also found a keybinding for "cycle program" very useful. When running: 
```mpv "dvb://VOX" --dvbin-full-transponder=yes```
then "cycle program" switches between channels on the same transponder. 
I am not sure whether there should be a default keybinding for this (I myself use "-" for this, but that's not pretty intuitive - and I guess "J" as the letter in between "H" and "K" may be intuitive, but "j" is cycling subtitles already...). 
If you don't think there should be a default binding for cycle-program (after all mpv is also about free configuration), I'd add a comment to `options.rst` to the section for `dvbin-full-transponder` mentioning the possibility to cycle programs, since it's probably not so obvious straightaway.

**Comment by olifre** [comment]
I have rebased all on current master and added a comment to options.rst hinting to the possibility to cycle the program property to switch between the TS channels in full-transponder mode. After some thinking, I believe it's really not to useful to be bound to some key by default. 

With this I am finished with this patchset ( unless you find something, that is ;-) ) and we could also close #2568 after it is in. 


One related thing: I found that in DEMUXER_CTRL_IDENTIFY_PROGRAM (in lavf: demux_lavf_control) where the cycling of the TS-program is handled, it would be possible to access the AVProgram::metadata for example to update the media-title of the selected TS-program. 
I am not sure if this metadata is always useful - for DVB, however, ffmpeg fills it in a useful manner:

key | value
--- | ------
service_name | Das Erste HD
service_provider | ARD

which one in principle could use in the demuxer to update the media-title information. According to avformat.h these metadata-keys are mostly generic. 
From the listed properties in avformat.h, one could for example in DEMUXER_CTRL_IDENTIFY_PROGRAM do something like:
- if "title" is present, export that. 
- otherwise, fall back to service_name. 
Just a suggestion, I am not sure whether that makes things worse in other cases.

**Comment by wm4** [comment]
Looked at the changes; generally looks ok. Made 2 minor comments. Also, maybe you could change the commit messages from ``foo: Bar.`` to ``foo: bar``.

>One related thing: I found that in DEMUXER_CTRL_IDENTIFY_PROGRAM (in lavf: demux_lavf_control) where the cycling of the TS-program is handled, it would be possible to access the AVProgram::metadata for example to update the media-title of the selected TS-program. 

Yes, that could be done. If you find an unintrusive way to do this...

**Comment by olifre** [comment]
> Looked at the changes; generally looks ok. Made 2 minor comments. Also, maybe you could change the commit messages from foo: Bar. to foo: bar.

Thanks! I think I fixed everything. Sadly I (and subsequently my editor) always keep falling back to tabs due to my daily work with tab-space-mixed indentation. Sorry for that! 



> Yes, that could be done. If you find an unintrusive way to do this...

I am unsure whether I was intrusive - the last three commits do:
- Update metadata from AV_PROGRAM in demux_lavf on program switch, and accept that on the player-side afterwards. 
- "service_name", if present, is preferred as media-title (since if it's there, it's a better information than other metadata I expect). 
An alternative solution to preferring "service_name" over "title" in the media-title property would be to hide that preference in demux_lavf, i.e. copy the "service_name" tag to the "title" tag inside the demuxer. That's also not very nice, though. 

During that development I found another strangeness: When starting mpv with any mpegts stream, it seems to be not really well defined which is the default chosen program. 
It also seems `cur_program` in the `lavf_priv` structure in `demux_lavf` is never explicitly initialized (it's only initialized after the first program switch - which itself depends on the initially undefined `cur_program`...). 
Is that a bug in demux_lavf, or am I missing something? 
I would also not really know how to query the cur_program initially in a good way to fix this issue (and I'm back at work starting tomorrow, so my time will be more limited now :-( ).

**Comment by wm4** [comment]
>It also seems cur_program in the lavf_priv structure in demux_lavf is never explicitly initialized (it's only initialized after the first program switch - which itself depends on the initially undefined cur_program...). 

It's initialized to 0. Is that a problem? Anyway, this program switching code is something that was barely confirmed to work last time I had to touch it.

**Comment by olifre** [comment]
> It's initialized to 0. Is that a problem?

Again you are right, as I find now, I missed the zero-initialization. 
It's not really a problem - I now understand why the program choice appeared to be "random" to me in the case of a DVB-TS: 
It's just that the program which is chosen is program 0 from the TS, but the order in which ffmpeg identifies the several programs in the TS depends on the order in which it receives the header-information from the full transponder DVB-stream ("when we tune in"). 
This means if I start mpv right now on a selected channel with `dvbin-full-transponder` it will may choose a different `program 0` than if I restart mpv a minute later, and often the chosen program does of course not match what the user expected from specifying with `dvb://somechannel` in the `dvbin-full-transponder` case since the demuxer chooses the program from all channels available in the full transponder datastream. 

Since that would be hard to overcome (`stream_dvb` would have to instruct `demux_lavf` somehow to choose a specific set of video+audio streams, and define the cur_program, this would be somewhat intrusive) and `dvbin-full-transponder` is anyways a special mode, I'll just add another commit tonight documenting this expected behaviour for the `dvbin-full-transponder` option. 
Thanks!

**Comment by wm4** [comment]
>stream_dvb would have to instruct demux_lavf somehow to choose a specific set of video+audio streams, 

It's even worse: the player frontend decides what streams are to be selected, and the demuxer has no say in this. (Though at demuxer opening, the demuxer can set default flags for each stream.)

**Comment by olifre** [comment]
> It's even worse: the player frontend decides what streams are to be selected, and the demuxer has no say in this. (Though at demuxer opening, the demuxer can set default flags for each stream.)

I see - and this is also the meaningful way to do it. Having the demuxer, or even dvb_stream decide on the streams the player should select would be somewhat confusing. 

I have now documented this expected behaviour in the last commit of the set, 
and removed the really unnecessary explicit metadata query from the player side after program switch. 
With this, it seems done and working as expected. Thanks for all!

**Comment by wm4** [comment]
Seems all ok. So you're fine with merge?

**Comment by olifre** [comment]
> Seems all ok. So you're fine with merge?

Thanks! Yes, from my side, all seems to be working fine (and I see no other issues currently concerning DVB in my setup).

**Comment by wm4** [comment]
Merged, thanks.

**Pull request closed without merging**
