### PR TITLE
wayland: read xcursor theme from XCURSOR_* env

### PR DESCRIPTION
**Pull request by emersion**
This allows compositors to set the theme and size from user
configuration.

I agree that my changes can be relicensed to LGPL 2.1 or later.

### CODE REVIEW

**Comment by haasn** [comment]
Aside from the ugly code duplication, your usage of `getenv` contains a race condition. The process environment is not constant, i.e. the second call to `getenv` can return NULL after the first one already returned something non-NULL, leading to segfault. You should store the result of the first `getenv` call instead of retrieving it from the environment twice.

As an aside, `atoi` is evil in general. It will produce undefined behavior on a number of invalid inputs, for example too-large numbers. Use `strotol` instead.

**Comment by emersion** [comment]
Thanks for your review. Pushed a new version addressing your comments.

**Comment by atomnuker** [comment]
I think it should be the compositor's job to give clients the default theme, not a client's job to override it with an archaic, if used, environmental variable.
wl_cursor_theme_load is documented such that if NULL is used as the theme name a default will be picked.

**Comment by emersion** [comment]
>I think it should be the compositor's job to give clients the default theme, not a client's job to override it with an archaic, if used, environmental variable.
wl_cursor_theme_load is documented such that if NULL is used as the theme name a default will be picked.

`NULL` for the theme name is the same as `"default"`, so it's actually hardcoded just like the size.

I'm working on a long-term solution for this issue. It'll involve writing a new protocol. It'll require compositor support as well as client support. I'm sure standardizing a new protocol will take at least months.

This solution has the upside of being very simple and it always works, regardless of compositor support. IMHO it's a good short-term solution, it's better than hardcoding these values. It doesn't do any harm. It's also already used by Qt, GLFW and most X11 clients (think xwayland).

>I agree, even on X11. At least the DEs I’ve used are able to set a global cursor theme so that it works everywhere, including mpv.

X11 has nothing to do with this. It works differently on Wayland.

**Comment by haasn** [comment]
LGTM with the changes, but I haven't tested (don't have wayland set up).

**Comment by atomnuker** [comment]
Still I'd like for the theme environmental variable to not be parsed and be left as NULL. I understand about the size, but considering the protocol supports having the compositor signal a default theme there's no reason not to fix compositors instead.

**Comment by emersion** [comment]
All right. The size issue is more annoying than advanced cursor image configuration, so I updated the patch to only use `XCURSOR_SIZE`. I'll work on the protocol for a longer term solution.

**Comment by emersion** [comment]
Bump

**Comment by emersion** [comment]
Bump

**Comment by emersion** [comment]
Ping?

(BTW, started to work on a [better solution](https://github.com/swaywm/wlroots/pull/1324), but I don't expect this to be reviewed anytime soon because of a lack of reviewers)

**Comment by emersion** [comment]
Bump

(Update: GNOME folks want to use D-Bus for cursor size configuration instead, please reply to the thread if you care: https://lists.freedesktop.org/archives/wayland-devel/2018-December/039756.html)

**Comment by emersion** [comment]
Bump again

**Comment by haasn** [comment]
Given that the plan of "fixing compositors" doesn't seem to be moving forwards at an acceptable rate, I'd say merge this patch. On the scale of "workarounds for crappy environments" in mpv, this seems pretty harmless.

Code LGTM as pointed out before

**Comment by CounterPillow** [comment]
>Update: GNOME folks want to use D-Bus for cursor size configuration instead

Things 100% of Wayland systems have running: a wayland compositor.

IPC mechanism 100% of Wayland systems speak: wayland.

Things GNOME thinks should provide a core function of wayland: dbus.

Where do they get these clowns from?

**Comment by emersion** [comment]
Any chance to get this merged?

**Comment by wm4** [comment]
This is seriously shitty, but I guess an acceptable workaround until GNOME take off their asshat.

**Pull request merged**
