### PR TITLE
mac: compatibility for older dev tools

### LINKED ISSUE #14310: mpv 0.38.0 Cannot be Built on macOS 10.15
### Important Information

- mpv version: 0.38.0
- Platform version: macOS 10.15 w/ Xcode 12.4
- Meson version: 1.4.1

### Reproduction Steps

The IINA project is planning to use the latest version of mpv for the next release. As mpv claims to support macOS 10.15 or later in the current readme, we decide to build libmpv on a 10.15 mac as the dependency of IINA, and bump the system requirement for IINA to 10.15. We tried to build mpv without any custom flags to reproduce the issue:

- Install dependencies
- `meson setup build`
- `meson compile -C build`

### Expected Behavior

mpv should build normally.

### Actual Behavior

mpv failed to compile due to usage of newer macOS APIs. For instance:
https://github.com/mpv-player/mpv/blob/112fa549beb52ab3d75999c8d8a82936e13001c4/osdep/mac/log_helper.swift#L23
`Logger` is only available for macOS 11+.

See the attached `build_error.log` for more details.

### Log File

[build_error.log](https://github.com/user-attachments/files/15598765/build_error.log)
[meson_setup_build.log](https://github.com/user-attachments/files/15598767/meson_setup_build.log)
[meson-log.txt](https://github.com/user-attachments/files/15598768/meson-log.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of parameters, and conditions used in "Reproduction Steps".
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.

### PR DESCRIPTION
**Pull request by Akemi**
https://developer.apple.com/documentation/foundation/nslocking/4059821-withlock available from macOS 10.10 but xcode 14+ required. xcode 14.0 introduced swift 5.7

logger is a macOS 11 feature. ~~i hope the runtime check works like that.~~ otherwise the initialisation of the logger has to move to init or a computed property.

Fixes #14310

### CODE REVIEW

**Comment by uiryuu** [comment]
`AVSampleBufferAudioRendererOutputConfigurationDidChangeNotification` is a [macOS 12+ feature](https://developer.apple.com/documentation/avfoundation/avsamplebufferaudiorendereroutputconfigurationdidchangenotification), so this line must be behind a version check as well.
https://github.com/mpv-player/mpv/blob/5158a3d779ed5b6bcd41b4a0573847abc08dcb66/audio/out/ao_avfoundation.m#L318

**Comment by Akemi** [comment]
@ruihe774 see comment above. how broken would avfoundation be without that notification on macOS <=12? is there a possible workaround for older versions or should we just put the whole ao behind a macOS 12 guard?

**Comment by ruihe774** [comment]
> @ruihe774 see comment above. how broken would avfoundation be without that notification on macOS <=12? is there a possible workaround for older versions or should we just put the whole ao behind a macOS 12 guard?

Sorry for my late reply. According to the [doc](https://developer.apple.com/documentation/avfoundation/avsamplebufferaudiorendereroutputconfigurationdidchangenotification):

> The output configuration of the playback hardware might change during the playback session if other apps play content in different formats. In these cases, the media content format doesn’t match the hardware configuration which would produce suboptimal rendering of the enqueued media data. When the framework detects such mismatch it posts this notification, so an app can flush the renderer and re-enqueue the sample buffers from the current media playhead, which configures the hardware based on the format of newly enqueued sample buffers.

So it is completely OK ignoring this notification.

**Comment by Akemi** [comment]
i added a build time and runtime checks for the two features that are used in avfoundation and need at least macOS 11.3 or 12.

**Pull request merged**
