### PR TITLE
Bundle waf

### PR DESCRIPTION
**Pull request by czarkoff**
This allows building mpv without internet access, reduces risk of MitM attacks and otherwise makes more sense then downloading blob at configuration time. FWIW it seems to be a common practice to bundle waf script.

This PR updates waf to latest version - 1.8.19 - which (in my testing) works fine with mpv.

I have a hidden agenda as well: fetching waf unnecessarily complicates the port of mpv for OpenBSD which I maintain.

### CODE REVIEW

**Comment by rr-** [comment]
Doesn't bundling a minified / obfuscated version break GPL?

**Comment by pigoz** [comment]
We can never accept this since our tarball would not be DFSG compliant anymore.

**Comment by wm4** [comment]
I don't want this either, we're trying to avoid such blobs in git.

You could just package waf separately, or add it as a patch.

There's no MITM risk btw.

**Comment by czarkoff** [comment]
@rr- Redistributing something verbatim doesn't break GPL.

@pigoz How does 3-clause BSD license violate DFSG?

**Comment by pigoz** [comment]
@czarkoff waf is a self extracting binary. So Debian treats it as "obfuscated code" making it non DFSG compliant.

**Comment by czarkoff** [comment]
It is a mere tarball concatinated with some code. It is not even a binary.

**Pull request closed without merging**
