### PR TITLE
ao_pipewire: let sound server determine latency 

### LINKED ISSUE #11467: Ability to set default latency for pipewire
### Expected behavior of the wanted feature

`mpv` should have a possibility not to set any `node.latency` in `pipewire` ao which would result in latency being set to default value from pipewire configuration (`default.clock.quantum`). Currently it is always set to fixed value and defaults to `20ms`:
https://github.com/mpv-player/mpv/blob/e1727553f164181265f71a20106fbd5e34fa08b0/audio/out/ao_pipewire.c#L883-L888

Note [documentation](https://github.com/mpv-player/mpv/blob/e1727553f164181265f71a20106fbd5e34fa08b0/DOCS/man/ao.rst) already suggests there is a possibility to set `native` value:
https://github.com/mpv-player/mpv/blob/e1727553f164181265f71a20106fbd5e34fa08b0/DOCS/man/ao.rst#L153-L157

But this seems to be copy & paste from pulseaudio ao since unlike pulseaudio, pipewire ao does not support `native` value.

### PR DESCRIPTION
**Pull request by t-8ch**
Fixes #11467 

@jpalus Could you test this?

### CODE REVIEW

**Comment by jpalus** [comment]
Confirmed it works fine. Thanks @t-8ch!

One thing to consider is whether to keep current default of `20ms` or whether it should be changed to `native`. PipeWire defaults to rate `48000` and quantum `1024` which translates to buffer `21.33ms` so basically equivalent. However `native` would pick up automatically default quantum customization. I don't have strong opinion here though and I'm fine with either default.

**Comment by jpalus** [comment]
Also it would be good to explain in docs what `native` actually means. While it is presented as a possibility it is not stated what it does exactly. Same goes for pipewire output.

**Comment by t-8ch** [comment]
> One thing to consider is whether to keep current default of 20ms or whether it should be changed to native. 

We can change it after the new functionality was available for some time to shake out potential bugs.
And if someone argues for the change then.

> Also it would be good to explain in docs what native actually means.

Good point.

**Comment by philipl** [comment]
Seems to work as intended for me here. Mind you, I also bumped the buffer size to max and didn't see the stuttering I saw before, so maybe some of the other changes have helped there as well.

**Comment by Traneptora** [comment]
Should we leave this hanging or merge it? It's really not my area of knowledge so I don't want to merge it unless it's good to go.

**Comment by t-8ch** [comment]
From my POV it's ready to merge

**Review by philipl — APPROVED** [review]

**Pull request merged**
