### PR TITLE
sub: make sub-ass-override actually work during runtime

### LINKED ISSUE #12386: sub-ass-override does not switch subtitle appearance while watching
### Important Information

Provide following Information:
- mpv version: 0.36
- Windows Version: Windows 10 21H1
- Source of the mpv binary: Sourceforge (shinchiro)

### Reproduction steps

Load a video file accompanied by formatted subtitles in ass format. Use overridden ass styles (`--sub-ass-styles=`). Add the `<KEY> cycle-values sub-ass-override "no" "yes"` option to input.conf to switch the subtitle design between built-in and custom while watching a video. Press this key while watching a video (when it is not paused).

### Expected behavior

By pressing the key, the subtitle design will change from what it was to what the user selected.

### Actual behavior

There is no change in design. The subtitles remain with the same design as they were. Also, the next phrase in the subtitles disappears, or the next 2-3 after the one at the moment the user pressed the key. If you rewind time forward and backward, all the phrases become visible.

You can avoid this by entering `cycle-values sub-ass-override "no" "yes"` when the video is paused, and then reloading the subtitles (for example, `set sid 0`, then `set sid 1`)

### Log file

https://pastebin.com/8Jt5c6AF

### PR DESCRIPTION
**Pull request by Dudemanguy**
The other options related to sub-ass styles have the UPDATE_SUB_HARD flag, and it is needed for this one here as well since the ass objects need to be destroyed and recreated to change to the new option. There is one catch however. That change alone doesn't make the option change immediately take affect on the current subtitle if the video is playing (the same is true with the other related options). It works during pause because mpv forces a refresh seek in that case. We can make it work during the playing case as well by forcing the refresh seek when we get an UPDATE_SUB_HARD. It feels like a bit of a sledgehammer, but I couldn't think of a better way to get the subtitle to actually display, and it did technically happen in the pause case. Fixes #12386.

### CODE REVIEW

**Comment by Lypheo** [comment]
Couldn’t you avoid refresh seeks altogether and instead add a small cache of recently decoded demux packets to sd_ass and decode its contents when UPDATE_SUB_HARD is received?

**Comment by Dudemanguy** [comment]
That's not a bad idea. I think if we just hold onto the last packet, that could work.

**Comment by Dudemanguy** [comment]
Implemented it just now. Also fixed `UPDATE_SUB_FILT` while I was at it.

**Comment by Dudemanguy** [comment]
Hmm, the subtitle style actually doesn't update if you're near the end of the duration of the sub. Not sure why that is. The ass is completely reinitialized. I'll add back the old refresh logic for now since that works in the pause case at least and makes this a strict status improvement over the status quo. I'll see if I can think of something in the meantime.

**Comment by Lypheo** [comment]
> Hmm, the subtitle style actually doesn't update if you're near the end of the duration of the sub. Not sure why that is. 

My guess is because the next subtitle line is close and has already been prefetched and decoded. That's why I initially suggested a small cache of multiple packets.

**Comment by Dudemanguy** [comment]
Okay sorry for the delay, got back to this one. Should actually work now.

**Comment by Lypheo** [comment]
Why not just redecode both pkts though? Would also catch cases with overlapping lines.

**Comment by Dudemanguy** [comment]
You're right. I didn't want to be "wasteful" but there's no reason to not just decode both since this is only ever done on a specific kind of option change. Updated.

**Comment by Dudemanguy** [comment]
Small change to make sure the redecode doesn't happen for sd_lavc. It wasn't harmful to do so, but it is indeed wasteful there since it `UPDATE_SUB_FILT` and `UPDATE_SUB_HARD` are only relevant for sd_ass.

**Pull request merged**
