### PR TITLE
Fix a warning with --disable-iconv

### PR DESCRIPTION
**Pull request by jleclanche**

### CODE REVIEW

**Comment by wm4** [comment]
This introduces a bug: the function returns nothing, and most compilers will decide this is undefined behavior and compile garbage.

Also, you're not supposed to compile without iconv. Thus PR rejected. I might remove --disable-iconv entirely.

**Comment by jleclanche** [comment]
>  I might remove --disable-iconv entirely.

Please do. It makes no sense to have a --disable flag and not support it.

**Comment by wm4** [comment]
Currently it's supported, and the warning you got is harmless.

**Comment by jleclanche** [comment]
I know it's harmless, but if you say "you're not supposed to compile without iconv", then it should definitely be removed... :)

**Pull request closed without merging**
