### PR TITLE
video: Fix depth=0 on textures downloaded from ra

### PR DESCRIPTION
**Pull request by averne**
As per https://github.com/mpv-player/mpv/blob/master/video/out/gpu/ra.h#L130
Writing my own RA and I hit an issue by assuming depth couldn't be null.

### CODE REVIEW

**Comment by Dudemanguy** [comment]
What is this needed for?

**Comment by averne** [comment]
Hi, I am working on an mpv port for the Nintendo Switch. Part of that work includes my own ra backend using [deko3d](https://github.com/devkitPro/deko3d), a homebrew graphics API.
So when I encountered this behavior it triggered a crash in my code, and the behavior looked incorrect so I made this PR. However it doesn't fix any actual mpv bug, as far as I know.

**Comment by Dudemanguy** [comment]
So according to the code comments in `ra.h`, your fix is actually correct. When dimensions are set to 2, the depth (d) should be set to 1. Looking at some other uses of `struct ra_tex_params params` in the code, they all explicitly set the d to 1 if dimensions are also set to 2. So this change LGTM.

For the commit messages, could they be changed to:

`video: initialize depth=1 on screenshot textures`
`vf_gpu: initialize depth=1 on target textures`

And then if you could briefly explain in the commit message that this is what the code comments say should be done and what is done in the rest of the code, that'd be great.

**Comment by averne** [comment]
Done

**Review by Dudemanguy — APPROVED** [review]
Thanks, looks good.

**Comment by sfan5** [comment]
I think adding an assert for this to `ra_tex_create` would be reasonable.

**Pull request merged**
