### PR TITLE
DOCS/man: Re-wrapped and fixed some spelling and punctuation errors.

### PR DESCRIPTION
**Pull request by brgmnn**
Re-wrapped quite a lot of lines to 80 characters in the man-pages where
there were inconsistencies in line lengths. Also added some missing
punctuation (such as missing full stops) to several places and fixed one
or two spelling errors.

### CODE REVIEW

**Comment by brgmnn** [comment]
I know there's a lot of lines changed but the vast majority of them are just re-wrapping lines to 80 characters in the man pages. I used `gq` with vim for re-wrapping with my text width set to 80. Most of the man pages seem to be wrapped at 80 characters but a few had sections where the wrapping was inconsistent. I also fixed some minor punctuation and spelling errors.

**Comment by wm4** [comment]
Please no. That's just a huge number of changes for exactly what purpose? It just breaks git blame.

And mixing automatic indentation changes with other changes isn't good either. It's hard to review.

**Comment by brgmnn** [comment]
Ok, I wanted to help and contribute and wasn't sure what to start with. Would it be useful to submit a change with only the small punctuation/spelling fixes?

**Comment by wm4** [comment]
Yep.

**Comment by brgmnn** [comment]
I've changed the commit to only be a few grammatical errors I spotted. Hopefully this helps! Sorry for the huge pull request earlier :S

**Comment by wm4** [comment]
Adjusted commit messages and merged. Thanks.

**Pull request closed without merging**
