### PR TITLE
Added seed to RNG

### PR DESCRIPTION
**Pull request by jonatanhal**
Hello!
I've been using MPV for a while now & It's been great. One thing I've noticed is that I tend to get alot of the same files playing when playing a playlist, So I sat down & did this very basic change to seed the RNG.

(small disclaimer: first pull-request, bear with me)

### CODE REVIEW

**Comment by wm4** [comment]
I don't know, for me the shuffle is different every time I start mpv.

What OS are you on?

**Comment by jonatanhal** [comment]
Linux.

It's not a big deal, just something that's been bugging me for a while now =)

**Comment by wm4** [comment]
glibc?

I'm just confused that it seems to work fine for me, without extra seeding.

**Comment by jonatanhal** [comment]
Yep, glibc. (Arch Linux), manpages mention that if not seeded, rand will be seeded with 1.

```
$ ldd --version
ldd (GNU libc) 2.21
...
```

**Comment by m45t3r** [comment]
Well, actually this is pretty easy to test:

    $ cat test.c
    #include <stdio.h>
    #include <stdlib.h>

    int main(void)
    {
        printf("%d\n", rand());
    }
    $ gcc test.c
    $ for i in `seq 10`; do ./a.out; done
    1804289383
    1804289383
    1804289383
    1804289383
    1804289383
    1804289383
    1804289383
    1804289383
    1804289383
    1804289383

**Comment by wm4** [comment]
Actually we do have this already, and had it for a long time: https://github.com/mpv-player/mpv/blob/master/osdep/timer.c#L36

(Not particularly fond of this, though.)

**Comment by wm4** [comment]
Whoops, forgot to close this.

**Pull request closed without merging**
