### PR TITLE
mxfile.cpp

### PR DESCRIPTION
**Pull request by ujjwalsrivastav**
hacktober-accepted

Read this before you submit this pull request:
https://github.com/mpv-player/mpv/blob/master/DOCS/contribute.md

Reading this link and following the rules will get your pull request reviewed
and merged faster. Nobody wants lazy pull requests.

### CODE REVIEW

**Comment by jeeb** [comment]
Seems to be a completely irrelevant random file. Please never do this again.

**Comment by ujjwalsrivastav** [comment]
Okay
At least i am trying to contribute why you tag a spam
If the contribution is irrelevant then don't merge it .

**Comment by CounterPillow** [comment]
Because it is spam. You're spamming to get a free t-shirt. You did not actually try to contribute anything. You are a blight upon society.

**Comment by ujjwalsrivastav** [comment]
Hey look, i'm just trying to get a free t-shirt and try to participate in
an event and do some open-source.I'm not but i'm sure You are a blight upon
society .but i am not aware that your type of dumbmind people also there
who just try to be oversmart ,actually you are not even worth a penny.
lousy little brat , go and whine somewhere else.

thank you

**Comment by garoto** [comment]
Amazing how shitters like OP get a free pass while shitting all over the place on this garbage platform willy nilly.

It's completely fucking bonkers.

**Comment by haasn** [comment]
Calm down, the PR is marked as spam, which meant they were banned from hacktoberfest. So that's something at least.

**Pull request closed without merging**
