### PR TITLE
Added SBV (SubViewer) as another sub_ext (supported autoload file extension)

### LINKED ISSUE #11934: External subtitle file extensions are not documented
The manual section on Subtitles:
https://mpv.io/manual/master/#subtitles
currently does not tell anything about the supported subtitle file formats.

Only hint that I could find in the source code was `mpv/player/external_files.c`
`static const char *const sub_exts[] = {"utf", "utf8", "utf-8", "idx", "sub", "srt", "rt", "ssa", "ass", "mks", "vtt", "sup", "scc", "smi", "lrc", "pgs", NULL};`

My concrete inquiry: Youtube Studio offers to download subtitle files as:
- [SubRip](http://en.wikipedia.org/wiki/SubRip#SubRip_text_file_format) gets downloaded with a `.SRT` extension
-  [WebVTT](https://en.wikipedia.org/wiki/WebVTT) gets downloaded with a `.VTT`  extension
- [SubViewer](http://en.wikipedia.org/wiki/SubViewer) gets downloadded with a `.SBV` extension.
  - Seems more widely known on the Internet with the `.SUB` extension.
  - `sub` is part of the `sub_exts` list.
  - So should I simply rename `.sbv` to `.sub` and be good with it?
  - Or could mpv consider to add `sbv` as a synonym file extension which calls up the same parser?

### PR DESCRIPTION
**Pull request by porg**
This fixes #11934 with @Dudemanguy 's [agreement](https://github.com/mpv-player/mpv/issues/11934#issuecomment-1671924562)

### CODE REVIEW

**Comment by Dudemanguy** [comment]
See [contribute.md](https://github.com/mpv-player/mpv/blob/master/DOCS/contribute.md).

**Comment by porg** [comment]
- I'm no developer. Did the best to my abilities.
- Please honor my efforts. And correct what's not right. I'm overburdened by this.
- I don't need any mention of my name or so. I have no problem if all the changes just appear under your name.
-   I just want to help make the product + manual better (in this and my other contributions from today).

**Comment by porg** [comment]
Yes please do it on my behalf.

**Comment by Dudemanguy** [comment]
Added in 13c6e060e2316d12e34d2983dcc15eecef645900.

**Pull request closed without merging**
