### PR TITLE
wscript: split libandroid from egl-android

### PR DESCRIPTION
**Pull request by tomty89**
Follow-up for #6972 (and #6000).

### CODE REVIEW

**Comment by tomty89** [comment]
@sfan5 @jeeb

**Comment by sfan5** [comment]
I don't think `libandroid` is a good name for that.
`android` checks for an android-specific header, `libandroid` for the corresponding library. But those can only ever appear together.

What's the point of this anyway?
If you want to build without graphical features, `--disable-vulkan --disable-gl` should work just fine.

**Comment by tomty89** [comment]
@sfan5 Yeah I'm also thinking about that. Perhaps it should be android-nw (which stands for NativeWindow). If in the future mpv(-android) targets at only api level 26 or higher, we should just need to change the lib check from `android` to `nativewindow`.

The reason for this is, `video/out/android_common.c`, which is pulled by the build option `android`, brings linkage to libandroid.so.

**Comment by sfan5** [comment]
Hmm? I don't see any api level restriction on the functions android_common.c uses, in fact mpv-android builds fine with `__ANDROID_API__=21`.

> The reason for this is, `video/out/android_common.c`, which is pulled by the build option `android`, brings linkage to libandroid.so.

Breaks in what way? The only problem I can see is it *not* being linked, which could be fixed by moving `check_cc(lib=['android'])` to the `android` dep.

**Comment by tomty89** [comment]
Apparently Native Window symbols are provided in both libandroid and libnativewindow (which seems to be introduced since API 26): https://developer.android.com/ndk/guides/stable_apis#android_native_application_apis. Not sure if it is like a new drop-in replacement or what. It is not exactly relevant to this PR anyway, other than maybe being a factor for the naming / description.

See https://github.com/termux/termux-packages/pull/4477. Hmm I have just realized that libandroid.so should be available just like libOpenSLES.so and the problem is actually `-landroid` somehow not being used in the final linking. (Although I am still not gonna like the fact that we will have a pointless extra linkage to an Android library. `libOpenSLES` is pretty much like an exception in Termux.)

**Comment by tomty89** [comment]
@sfan5 Hmm, have I done it wrong? I can't even get it to add `-landroid`: https://github.com/termux/termux-packages/pull/4478

**Comment by wm4** [comment]
So whatever happened to this?

**Comment by tomty89** [comment]
Closing. In Termux we are doing this: https://github.com/termux/termux-packages/blob/6ec4ea0bec26aea1f719f4ce89532503190a60ed/packages/mpv/wscript.patch
I guess that's what you want to do upstream as well?

**Pull request closed without merging**
