### PR TITLE
console/stats: don't overwrite color and alpha of `osd-back-color`

### PR DESCRIPTION
**Pull request by christoph-heinrich**
The background from `--osd-back-color` is [mutually exclusive](https://github.com/mpv-player/mpv/blob/2dc8e70093d9f80a01696f059ff02784bcb7b5f0/sub/ass_mp.c#L66-L72) with text shadows and ASS apparently uses the color and alpha set for shadows (`\4c` and `\4a`) for that background.
console and stats were always overwriting those values, effectively ignoring the actual values set in `--osd-back-color`.

Replicate the check done in ass_mp.c and only set shadow color and alpha when there actually are shadows.

### CODE REVIEW

**Comment by hooke007** [comment]
`osd-back-color` will draw another curtain. One of them must be removed :-)

**Comment by christoph-heinrich** [comment]
Ah I see, I didn't realize that would apply here.

By removing `\\4a&H99&` (shadow alpha) and `\\4c&H000000&` (shadow color) from `local style` it actually respects the values from `osd-back-color`, but then the shadow doesn't look the same when  `osd-back-color` isn't set.

We could check if it'll draw a background box (alpha from `osd-back-color` is not 0) and not apply the shadow style in that case. Would that be fine or do you have a better idea?

**Comment by hooke007** [comment]
> We could check if it'll draw a background box (alpha from osd-back-color is not 0) and not apply the shadow style in that case.

Only if the new drawn box could match the area of console as perfectly as `osd-back-color`, it would be the better idea.

**Comment by christoph-heinrich** [comment]
> Only if the new drawn box could match the area of console as perfectly as `osd-back-color`, it would be the better idea.

That was meant as a replacement to what I'm doing now, so it would only have the background when `osd-back-color` is set, in the set color and alpha, and otherwise it'll have little bit of shadow as it already does by default.

**Comment by hooke007** [comment]
It seems I found another bugs. With setting `osd-back-color=1`, osd, stats and console show 3 different colors.

**Comment by christoph-heinrich** [comment]
> It seems I found another bugs. With setting `osd-back-color=1`, osd, stats and console show 3 different colors.

That's because stats and console set the alpha for shadows, which is what is used by the box that gets drawn by `osd-back-color`. That's why I suggested only setting that in the console when no box gets drawn.

stats actually has a `alpha` option, but it sets all alpha (so transparent background also means transparent text).

**Comment by christoph-heinrich** [comment]
The background on console and stats now matches that of OSD messages.
The description of the `alpha` option from stats didn't need to be adjusted as it's description already says it applies only to the text.

**Comment by hooke007** [comment]
Have you missed sth?
Snipaste_2023-05-01_01-49-32

**Comment by christoph-heinrich** [comment]
Looks to me like you have `shadow_y_offset` set.

**Comment by hooke007** [comment]
Nope, config is clear.

**Comment by christoph-heinrich** [comment]
I can only get a similar result when I set `osd-shadow-offset` and `osd-shadow-color` while also having the check for shadows fail despite `osd-back-color` having an alpha of 0.

Can you check if the `has_shadow` in stats.lua is true if you use `--osd-back-color=0/0/0/0` and false for `--osd-back-color=0/0/0/1`?
If that's not the case then the check must fail for you for some reason. For that property I get a string formatted as `#00000000` where the 0s are hex values for ABGR. My code simply cuts out the alpha and checks for `00`.

**Comment by hooke007** [comment]
Only stats has shadow.

**Comment by hooke007** [comment]
fixed in https://github.com/mpv-player/mpv/commit/12238df51568beff1d924018c1bbdb1cd4912270

**Comment by christoph-heinrich** [comment]
I forgot to update title/description after I completely changed the approach and got this to work months ago.

**Review by Dudemanguy — APPROVED** [review]
Got lost in the PR backlog but seems to work here.

**Pull request merged**
