### PR TITLE
DOCS: keybindings correction and consistency

### PR DESCRIPTION
**Pull request by christoph-heinrich**
Capitalization makes a difference for letter keys, so we should use the correct one.

Also the formatting of some keybindings was inconsistent.

@Akemi can you please confirm that `Command` works on macOS?

### CODE REVIEW

**Comment by hooke007** [comment]
Shouldn't RST support the syntax like `<kbd>Ctrl</kbd> + <kbd>+</kbd>` ? <kbd>Ctrl</kbd> + <kbd>+</kbd>
It's clearer than `ctrl++`

**Comment by christoph-heinrich** [comment]
> Shouldn't RST support the syntax like `<kbd>Ctrl</kbd> + <kbd>+</kbd>` ? Ctrl + + It's clearer than `ctrl++`

I haven't found anything like `<kbd>` in the RST documentation.

> Also I think `ctrl++` is not actually correct. It might be Ctrl + Shift + =.

It depends on the keyboard layout if <kbd>shift</kbd> is required or not.
A keybinding like `A show-text hi` also requires shift to be pressed together with <kbd>a</kbd> (unless caps-lock is on).

**Review by Dudemanguy — APPROVED** [review]
LGTM. Can anyone on macOS verify if the button is called `Command` or `command` however?

**Comment by Akemi** [comment]
i am not quite sure how to answer the question.

the key itself is called **Meta** within mpv. which is also a thing on other platforms.
https://github.com/mpv-player/mpv/blob/master/etc/input.conf#L18
https://github.com/mpv-player/mpv/blob/master/input/keycodes.h#L233
https://github.com/mpv-player/mpv/blob/master/input/keycodes.c#L231

Apple calls it Command or command, depending on context. it's written **command** on keyboards.

**Comment by kasper93** [comment]
Could we just use `⌘` in docs?

**Comment by Dudemanguy** [comment]
I threw unicode in the docs other day so if that works for mac users I say that's good.

**Comment by Akemi** [comment]
Apple itself uses **Command** in their shortcut docs https://support.apple.com/en-us/HT201236#:~:text=Command%20(or%20Cmd)%20⌘

i mean Alt is also called Option on macOS and uses `⌥`. i am not sure if we should uses icons now since it wouldn't be consistent. especially if we spell everything else in full.

**Comment by Dudemanguy** [comment]
Heh, how about just `Command` then like before?

**Comment by Akemi** [comment]
i think that would be the best for consistency.

**Comment by christoph-heinrich** [comment]
If that's what apple is calling it then we should too.

**Pull request merged**
