### PR TITLE
player/command: fix udata talloc parent

### PR DESCRIPTION
**Pull request by tsl0922**
typo?

### CODE REVIEW

**Comment by kasper93** [comment]
I can't check now, what it suppose to be, but there is the same here:
https://github.com/mpv-player/mpv/blob/9cee44147a1f14777015e008100ef6bbd7a2b91e/player/command.c#L3865

**Comment by tsl0922** [comment]
@rcombs can you look at it?

> I can't check now, what it suppose to be, but there is the same here:
> 
> https://github.com/mpv-player/mpv/blob/9cee44147a1f14777015e008100ef6bbd7a2b91e/player/command.c#L3865

Both were introduced in #11437, @rcombs can you check it?

**Comment by kasper93** [comment]
I just checked, this has to be without `&` in both cases. It is probably never used, because else it would assert on `ta_dbg_check_header`...

**Comment by tsl0922** [comment]
> I just checked, this has to be without `&` in both cases. It is probably never used, because else it would assert on `ta_dbg_check_header`...

OK. Updated the PR to include both.

**Review by rcombs — APPROVED** [review]
AFAIK these are never used, so they should be harmless, but this seems reasonable. Alternately, they could probably be `NULL`.

**Review by kasper93 — APPROVED** [review]

**Pull request merged**
