### PR TITLE
ci: disable Werror for libplacebo subproject build

### PR DESCRIPTION
**Pull request by kasper93**
See also: https://code.videolan.org/videolan/libplacebo/-/merge_requests/616

### CODE REVIEW

**Comment by kasper93** [comment]
> In general I'd rather disable warnings rather than having to patch libplacebo and I don't see why it should apply recursively anyway.

Like mentioned on IRC, I don't see a way to not apply recursively looking at documentation here https://mesonbuild.com/Wrap-dependency-system-manual.html

**Review by Dudemanguy — APPROVED** [review]
LGTM

**Comment by sfan5** [comment]
Can we apply this workaround in meson.build itself instead of all the ci scripts?

**Comment by Dudemanguy** [comment]
Technically yes, but it's the scripts that are setting Werror in the first place.

**Comment by sfan5** [comment]
Ah it's a direct meson option, disregard that.

**Pull request merged**
