### PR TITLE
osc: time display configuration options

### PR DESCRIPTION
**Pull request by teohhanhui**
Total time and ms

### CODE REVIEW

**Comment by teohhanhui** [comment]
#2019

**Comment by ChrisK2** [comment]
Add to documentation.

**Comment by teohhanhui** [comment]
Typo in the docs commit. Will squash...

**Comment by wm4** [comment]
"timecode" doesn't mean what you think it means.

**Comment by teohhanhui** [comment]
@wm4 Are my changes correct? Sorry if I used the wrong term, but I'm just following the style of whatever is already there...

**Comment by wm4** [comment]
A timecode is some sort of synchronization signal, while what we have here is a timestamp. (And yes, the existing code also got this term wrong.)

**Comment by wm4** [comment]
Merged.

**Comment by ChrisK2** [comment]
We'll fix the timecode/timestamp thing later in the whole file.

**Pull request closed without merging**
