### PR TITLE
Accept webdav:// and webdavs:// urls as an alias for http:// and https://

### PR DESCRIPTION
**Pull request by kbios**
Treat them as http:// and https:// respectively, and inform kde that they are supported via X-KDE-Protocols. This allows to play files on webdav archives directly on kde (ie with dolphin), avoiding the (potentially extremely slow) local copying performed by kio. #11080

### CODE REVIEW

**Comment by sfan5** [comment]
I get the intention but surely KDE is in a much better position to automatically attempt opening webdav as `http(s)://...` instead of adding this feature to every application.
(By "attempt" I mean check if the desired application advertises support for http and then use that rather than local copying).

**Comment by kbios** [comment]
> I get the intention but surely KDE is in a much better position to automatically attempt opening webdav as `http(s)://...` instead of adding this feature to every application. (By "attempt" I mean check if the desired application advertises support for http and then use that rather than local copying).

The problem with kde opening webdav as http unconditionally is that in many cases it makes sense to go with the local copy instead: for example if you need to edit the file and save it. Only for programs that access the file as a read-only stream it makes sense to ignore all the webdav features and treat it as a simple http stream.

**Comment by kbios** [comment]
Soo any chance this could be merged? It solves a real problem with minimal changes, and I think it could be expanded in the future to actually take advantage of webdav features (for example to load external subtitles)

**Comment by thebombzen** [comment]
LGTM

**Comment by adiprasetya** [comment]
@kbios can you commit dav:// or davs:// to treat them like http:// https:// as well? Thunar

**Comment by kbios** [comment]
> @kbios can you commit dav:// or davs:// to treat them like http:// https:// as well? Thunar

As far as I understand the problem with Thunar (and other gio/gvfs-based apps) is that there isn't a way to advertise support for specific protocols (like X-KDE-Protocols for KDE).

There is X-GIO-NoFuse, but you can use that only if you support all the protocols supported by gio.

So while it would be easy to make mpv accept dav:// urls, Thunar wouldn't know that it can actually pass such urls.

**Comment by Y0J1G3N** [comment]
I'm currently using GNOME, and its file manager Nautilus only supports dav://  and davs://. After modifying the source code to replace "webdav" with "dav" and compiling it using mpv-build, I was able to play dav:// URLs successfully. I would like to request adding support for dav://  and davs:// protocols.

**Pull request merged**
