### PR TITLE
meson: limit vk-khr-display to posix systems

### PR DESCRIPTION
**Pull request by llyyr**
This only works on DRM anyway, even if the vulkan header exists

### CODE REVIEW

**Comment by llyyr** [comment]
This doesn't work for my own Windows 10 system, and based on user reports it doesn't work for them either. And I was also able to find other information online that suggest this [doesn't work correctly](https://themaister.net/blog/2018/09/09/the-state-of-window-system-integration-wsi-in-vulkan-for-retro-emulators/) on Windows, if it does at all, either. 

However, this does mean that it's _supposed_ to work on Windows, so I guess we probably shouldn't disable this. I'll wait for someone with a Windows 11 Nvidia system to confirm whether this works or not I suppose. I don't see any reason why they wouldn't just use full screen exclusive mode though.

**Comment by kasper93** [comment]
> meson: limit vk-khr-display to posix systems

Could you explain why? And how the is related to posix systems?

**Comment by Dudemanguy** [comment]
It probably doesn't currently have any practical use outside of bsd/linux, but I don't think this extension is supposed to be OS-specific.

**Comment by llyyr** [comment]
Yeah, I wasn't aware that it _is_ supposed to work on Windows. It doesn't work for me at all, and I don't know anyone for whom it does work, but there's no harm in leaving it there.

**Pull request closed without merging**
