### PR TITLE
HTTPS protocol is more secure than HTTP protocol.

### PR DESCRIPTION
**Pull request by uos-hl**
HTTPS protocol is more secure than HTTP protocol.

### CODE REVIEW

**Comment by Akemi** [comment]
please read our contribution guidelines, especially the part about commit messages https://github.com/mpv-player/mpv/blob/master/DOCS/contribute.md

pls also remove the unrelated commit, that has already been merged(?).

**Comment by uos-hl** [comment]
> 请阅读我们的贡献指南，尤其是关于提交消息的部分https://github.com/mpv-player/mpv/blob/master/DOCS/contribute.md
> 
> 请同时删除已经合并的无关提交（？）。

**Comment by uos-hl** [comment]
> > 请阅读我们的贡献指南，尤其是关于提交消息的部分https://github.com/mpv-player/mpv/blob/master/DOCS/contribute.md
> > 请同时删除已经合并的无关提交（？）。

**Comment by uos-hl** [comment]
> please read our contribution guidelines, especially the part about commit messages https://github.com/mpv-player/mpv/blob/master/DOCS/contribute.md
> 
> pls also remove the unrelated commit, that has already been merged(?).

Thank you for your suggestion. The modification has been completed.

**Comment by Dudemanguy** [comment]
Superseded by #9114

**Pull request closed without merging**
