### PR TITLE
using msg.log("trace", ...) instead of msg.trace(...) as latter was c…

### PR DESCRIPTION
**Pull request by muditk98**
…ausing script to fail
I agree that my changes can be relicensed to LGPL 2.1 or later.

### CODE REVIEW

**Comment by TheAMM** [comment]
[`msg.trace` was implemented two years ago](https://github.com/mpv-player/mpv/commit/1afdeee1ad8bca1c703e741002fa3b882d162968). Consider updating your mpv instead of pushing outdated fixes to master?

**Comment by muditk98** [comment]
Sorry, I had just assumed that the mpv release in Ubuntu 18.04 would be up to date. Turns out, it is v0.27.2. 
If I am reading this correct `msg.trace` was implemented in v0.28. Maybe we can push a new release to the repository?

**Comment by Akemi** [comment]
no idea what you mean we already have a newer release on the repo with 0.29. if ubuntu doesn't update the repo there is really nothing we can do about.

**Comment by CounterPillow** [comment]
Ubuntu is outdated on purpose, that's the whole philosophy behind stable distributions. mpv developers have no influence over this.

**Pull request closed without merging**
