### PR TITLE
console: show suggestions for completion

### PR DESCRIPTION
**Pull request by christoph-heinrich**
Tab completion now temporarily shows a colored table of all potential completions
between the log messages and prompt.
The table automatically adjusts its column count depending on the space available.

As there is no way of knowing the exact width in characters, this is an estimate
and can be adjusted with the new option `font_hw_ratio`.
I expect the default value to work for everyone who doesn't set their own font.

The spacing between the columns also adjusts automatically, depending on
how much space is left.

suggestions_screenshot

### CODE REVIEW

**Comment by christoph-heinrich** [comment]
Refactored it a bit, the only new line going over 80 characters is now 272 and I think that can stay that way.
This conflicts with #10315 because both add a new option at the same place.

**Comment by christoph-heinrich** [comment]
Had to rebase due to conflicts.

**Comment by haasn** [comment]
image

On my end it looks misaligned

**Comment by christoph-heinrich** [comment]
No idea why that happens for you. `-` is treated just like every other character.
image

**Comment by haasn** [comment]
> Do you have hidpi-scaling or something?

I don't know. How would I check?

**Comment by christoph-heinrich** [comment]
`print-text ${display-hidpi-scale}`

I'm currently rebasing on master and looking at the code it should already handle scaling :thinking:

**Comment by avih** [comment]
I'm guessing he's not using monospace font.

**Comment by christoph-heinrich** [comment]
It looks like a monospace font and everything lines up perfectly when you consider wrapping exactly at the point where the 3rd column would begin.

**Comment by haasn** [comment]
> `print-text ${display-hidpi-scale}`
> 
> I'm currently rebasing on master and looking at the code it should already handle scaling thinking

That prints `1.000` for me.

**Comment by christoph-heinrich** [comment]
The table formatting supports utf8 encoding now. That shouldn't really make a difference because currently all commands and properties use ascii characters, but that will avoid problems in case that changes at some point.

@haasn I can only replicate how it looks for you by doubling `font_hw_ratio`, so you should be able to fix it by halving yours. No idea why that's necessary for you.

@avih Does the default value work for you?

**Comment by avih** [comment]
> @avih Does the default value work for you?

I didn't try it.

**Comment by garoto** [comment]
I imagine you've contemplated this before, but how much work would be needed for the script to cycle between all possible completions with every <kbd>TAB</kbd> keypress?

**Comment by christoph-heinrich** [comment]
I'd expect that to be pretty hard to do, sure would be nice though.
It's out of the scope of this PR, but maybe someone will make it happen after this gets in.

**Comment by christoph-heinrich** [comment]
The rows are now from the bottom up instead of from the top down (first row at the bottom), that's better because the last column isn't always full, and so a when the table gets cut of at the top, less suggestions get cut off.

It's also a little bit simpler and faster. Especially noticeable (when resizing the window) was precalculating the utf8 lengths instead of always calculating them on the fly.

I've also tried filling the table column-wise instead of row-wise so that all but the last row is completely filled up, but as it turns out that often results in long suggestions being next to each other instead of on top of each other, resulting in wider columns. Wider columns lead to less columns fitting on the screen, increasing the total row count and thus fewer visible suggestions (when there are enough that they get cut off at the top).

**Comment by christoph-heinrich** [comment]
@haasn does still not work correctly for you? It has worked fine on all setups I've tried it on.

**Comment by Dudemanguy** [comment]
So now that I finally try this, I also seem to have the same issue as haasn with misaligned elements.

2023-10-07-003252_415x66_scrot

Setting `font_hw_ratio` to random doesn't really make any difference for me. It's still misaligned. I also don't really care though. This is useful functionality.

**Comment by christoph-heinrich** [comment]
> So now that I finally try this, I also seem to have the same issue as haasn with misaligned elements.

I wish I know how to reproduce this. Does it also happen with `--no-config`?

> Setting `font_hw_ratio` to random values doesn't really make any difference for me.

Based on that image it looks like it thinks it can fit twice as many characters in a line as it actually does, just like is the case for haasn. `font_hw_ratio` is the scaling factor there, so this not making a difference is weird.

Alternatively we could use a more sophisticated width estimation method that I made for uosc, but it's close to 400 lines of code, so not sure that's worth it here.

**Comment by guidocella** [comment]
You can maybe clarify "This has to be a monospaced font for the completion suggestions to be aligned correctly.".  I also plan to keep using `sans-serif` because it looks better and I don't mind if the completions aren't aligned perfectly, and they will often fit in 1 line anyway.

**Comment by Dudemanguy** [comment]
If it wasn't for the discussion already in this thread, I wouldn't have even expected the elements to line up.

**Comment by christoph-heinrich** [comment]
> You can maybe clarify "This has to be a monospaced font for the completion suggestions to be aligned correctly.".

Done.

**Review by Dudemanguy — APPROVED** [review]
LGTM. See no reason to leave this in limbo.

**Pull request merged**
