### PR TITLE
keeps get_extension() from throwing an error when playing e.g. youtube

### PR DESCRIPTION
**Pull request by bitingsock**

### CODE REVIEW

**Comment by bitingsock** [comment]
er, nvm it breaks

**Comment by bitingsock** [comment]
actually its just my terminal emulator breaking. windows cmd runs it correctly; comemu is shitting

**Comment by wm4** [comment]
OK, but remote the tabs.

**Comment by wm4** [comment]
Pushed as 0121d00478bcbf38cc88c71b40d70804b1fb1588. I fixed the indentation (no tabs), and adjusted the commit message.

**Pull request closed without merging**
