### PR TITLE
10.14 crashes

### PR DESCRIPTION
**Pull request by rcombs**
cc: @Akemi 
Apple apparently doesn't recommend using ICNS for icons anymore, and instead recommends PNG.
I think the event tap now fails to create if the application doesn't have assistive-device permissions.

### CODE REVIEW

**Comment by Akemi** [comment]
so far we always prefixed the commits with "osx:", though i would be fine to use "mac:" from now on since the osx moniker is dead anyway.

the event tap changes seem good, i would even say checking for success should have been done anyway even before. i think it would be nice to have the explanation that assistive-device permissions are needed now in the commit message body. also a warning or a verbose output that the event tap couldn't be obtained would be nice. so we know when an issue about media key input is reported that it isn't because the event tap wasn't obtained.

the icon change seems kinda weird tbh. do you have any source for that? i kinda have the feeling the NSData allocation is the problem here and following patch might fix it:

```
diff --git a/osdep/macosx_application.m b/osdep/macosx_application.m
index 66daa45909..1930c3f3be 100644
--- a/osdep/macosx_application.m
+++ b/osdep/macosx_application.m
@@ -125,7 +125,7 @@ static const char macosx_icon[] =
 - (NSImage *)getMPVIcon
 {
     NSData *icon_data = [NSData dataWithBytesNoCopy:(void *)macosx_icon
-                                             length:sizeof(macosx_icon)
+                                             length:sizeof(macosx_icon)-1
                                        freeWhenDone:NO];
     return [[NSImage alloc] initWithData:icon_data];
 }
```

**Comment by rcombs** [comment]
You're right; trimming the trailing 0 byte fixed it. Re-pushed with that change.
Trying to add the log line; I'm not sure how to get at the relevant structure, since `input_ctx` is opaque here?

**Comment by Akemi** [comment]
think this change could work for us? i made the cocoa_init_media_keys() function sync and return true on success.

**Comment by rcombs** [comment]
Sorry for the late reply; my 10.14 machine's in the shop, so I can't test that change at the moment, but afaict there's nothing particularly 10.14-specific about it, so LGTM.

Re: other problems with the media-keys event tap, it's probably worth switching to `MPRemoteCommandCenter` for 10.12+ and disabling the old mechanism altogether there. See here for some example code: https://github.com/plexinc/plex-media-player/commit/c02b6869b2ce211d8a0d5e61a3c5d60708fae78f

**Comment by Akemi** [comment]
seems like my commit broke something else anyway (opening files via bundle). i will think about a different approach for the output.

yeah, `MPRemoteCommandCenter` i still on my todo list but it's pushed down all the time.

**Comment by sidneys** [comment]
@rcombs @Akemi 

This PR does not fix the 10.14 `NSImage`-related crash for me.

**Comment by sidneys** [comment]
@Akemi 
@rcombs 

Good News, i just tested @rcombs `10.14-crashes` branch on #5953 with a fresh user profile on Mojave DP3 (XCode 10b), and everything went smoothly, thus the proposed changes may be enough to prevent the NSImage-related crash.

However, i think it would be a more sane and clean approach to use PNG images as runtime macOS icon replacements, as this format is less problematic when stringified, and reading via file2string does not require the "-1" arbitrary length hack (whose strange behaviour on Mojave still remains unexplained).

Cheers
S

**Comment by Akemi** [comment]
yeah, we can switch to PNGs with another PR and do it properly for the bundle too at the same time.

**Comment by Akemi** [comment]
anyway this LGTM. i left the output on fail out for now, since there isn't really a fail proof way to output it because of the async nature of it. rewriting the mechanic would probably be needed.

i also added a small description to both commits.

**Comment by aplsms** [comment]
Guys,
Where you expected new release with these fixes?

**Comment by Akemi** [comment]
there is no ETA.

**Comment by jeeb** [comment]
Pushed as ada4f7c6006fc60189987b3ee012e7f4ced9926e and 1842a932d37638c910f4471d85e81554076c3d2c to master.

Noticed that `video/out/cocoa_common.m` was attempting to do the same sort of loading so I also fixed that the same way as well as added a basic comment. Former commit only got a single bit of white space to one of the if statements.

Thank you for your contribution.

**Pull request closed without merging**
