### PR TITLE
Support for F13-F24 keys

### LINKED ISSUE #10595: Unable to bind F13 key onwards in input.conf
### Important Information

Provide following Information:
- mpv version:
- Windows Version: Windows 11
- Source of the mpv binary: Shinichiro's builds

### Reproduction steps

Try to bind F13-F24 keys onwards to any option

### Expected behavior
The option should work if you press the F13-F24 keys

### Actual behavior
It doesn't work

### Log file

```
[input] Unknown key 'F17' at C:/Program Files/MPV/MPV-EASY Player/mpv/mpv/input.conf:7
[input] Unknown key 'F18' at C:/Program Files/MPV/MPV-EASY Player/mpv/mpv/input.conf:8
mpv 0.34.0-438-g0f30b0757f Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
 built on Wed Aug 31 06:21:29 2022
FFmpeg library versions:
   libavutil       57.34.100
   libavcodec      59.42.103
   libavformat     59.30.100
   libswscale      6.8.104
   libavfilter     8.46.103
   libswresample   4.9.100
FFmpeg version: git-2022-08-29-4fce3bab6
```

### PR DESCRIPTION
**Pull request by t-8ch**
This adds support for the F13-F24 additional function keys to the core of mpv and several input bindings.

X11 and Wayland were completely tested on Linux. (Please note that by default the physical F13-F24 keys are mapped to different symbols for evdev-based keymaps. This mapping has to be undone with a custom keymap option)

W32 has not been tested, but the additional keys are documented on https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes

@shinchiro maybe you could test it?

Cc @rp1231

Fixes #10595

### CODE REVIEW

**Comment by haasn** [comment]
macOS goes up to `kVK_F20` it seems (`osdep/macosx_events.m`)

**Comment by t-8ch** [comment]
@haasn I added macos, too. Untested though.

**Comment by haasn** [comment]
LGTM

**Comment by Akemi** [comment]
tested on macOS from F13 to F19. can't test F20 since i only have F keys up to 19.

**Comment by hooke007** [comment]
WIN32: Work up to f22 here but no response for f23/24.
[test.log](https://github.com/mpv-player/mpv/files/9479173/test.log)

**Comment by t-8ch** [comment]
@hooke007 F23 typo fixed in #10605

**Comment by hooke007** [comment]
Yes I see and f23 works here while f24 still not. Cannot find out why...

**Pull request merged**
