### PR TITLE
config: auto profiles for media

### PR DESCRIPTION
**Pull request by DanOscarsson**
Add auto loaded configuration profiles for selected media contents.
Will be loaded late after media tracks are selected so some
options may not work as expected.

My need for having special versions of options related to media contents are no longer needed with this.

### CODE REVIEW

**Comment by wm4** [comment]
Sorry, no. This should be done by scripts.

An example is here: https://github.com/wm4/mpv-scripts/blob/master/auto-profiles.lua

It should be possible to write much less awkward to use scripts than auto-profiles.lua though, which tries to be generic.

**Comment by DanOscarsson** [comment]
I am not sure you can through lua load profiles at the correct moment - my media profiles are loaded after tracks are selected but before AO/VO are set up.
The auto-profiles.lua loads at start and on idle, if I understand it correctly, which is not the time when the media profiles need to be loaded.

**Comment by wm4** [comment]
Lua scripts can synchronously load profiles using "hooks" (see manpage). Basically they can block loading at certain points. auto-profiles.lua does not do this, but could probably be extended to do so. (Though a script doing what your C changes do would be much simpler.)

If there are loading phases that can't be hooked yet, but which would be important for profiles, then new hooks should probably be added.

**Comment by DanOscarsson** [comment]
Yes you would need a new hook to enable this from lua. But it is nicer to not needing lua and it is simpler in C.

Also, the lua scripts does not come as part of mpv so of you extend the configuration handling through lua you will always be required to get an update version of a lua script. And you have to compile mpv with lua.

**Comment by wm4** [comment]
Then use cplugins.

**Pull request closed without merging**
