### PR TITLE
github: automatically close issues that ignore the issue template

### PR DESCRIPTION
**Pull request by Akemi**
needs this app to be installed https://github.com/offu/close-issue-app

i am not sure if this will be actually useful. i tried it on my fork https://github.com/Akemi/mpv/issues?q=is%3Aopen+is%3Aissue

another one that might be useful and i was looking into https://github.com/dessant/label-actions

### CODE REVIEW

**Comment by avih** [comment]
I'm not fond of this.

While it's definitely annoying to get reports which are missing important info, we can already close them without further explanation except the tag.

But issues are not always black and white, and users are people and not computers (most devs too...). Personally I don't think it's worth the PITA to file new issues with such strict enforcement. Sure, it will probably reduce the bad reports at least a bit, but I just don't think it's worth the pain to whoever reports an issue.

I think, but I don't know if it's possible, that instead of outright rejection, it would be better to display something like "Your issue appears to be missing critical information: log file, BAR, BAZ, and is highly likely to be closed without further notice.". Is something like that possible?

**Comment by Akemi** [comment]
there might be some apps/workflows that do something like this there:
https://probot.github.io/apps/
https://github.com/marketplace

**Comment by Akemi** [comment]
> Personally I don't think it's worth the PITA to file new issues with such strict enforcement. Sure, it will probably reduce the bad reports at least a bit, but I just don't think it's worth the pain to whoever reports an issue.

imo that just shows that the report doesn't really care and/or is lazy. i personally don't want to deal with such people.

one of the advantages of a bot closing such issues, is that none of the devs can be directly attacked anymore for closing issues.

**Comment by avih** [comment]
> one of the advantages of a bot closing such issues, is that none of the devs can be directly attacked anymore for closing issues.

I'm willing to be a frontend on this and close any issue which other devs consider as missing critical information.

**Comment by Akemi** [comment]
> I'm willing to be a frontend on this and close any issue which other devs consider as missing critical information.

i don't think this is in any way an appropriate measure.

**Comment by Akemi** [comment]
alternatively we could do something like:
1. label issues by some pattern, https://github.com/marketplace/actions/auto-labeler
2. close issues after X mins/hours/days with a specific label, https://github.com/marketplace/actions/close-issues-with-label

some other alternatives are:
close by titles from issue templates and reopen when issue is properly updated https://github.com/marketplace/actions/auto-close-issues
alternate regex labeler https://github.com/marketplace/actions/regex-issue-labeler

**Comment by thebombzen** [comment]
Keep in mind that some issues might not follow the template to the letter but there was some effort put into them beyond "help it don't work !!!1111". Like there's more than just "total garabage" vs "well-thought out tested reproduced issues." Which requires us to draw a line *somewhere* with something like this, and I'm not too fond of that.

**Comment by Akemi** [comment]
i believe everyone is aware of that.

another idea i can throw into the room. every issue template has a designated label, so we could theoretically close all issues that don't have any label assigned (after x minutes, since labels seem to get assigned shortly after issue creation(?)).

**Comment by Akemi** [comment]
additionally to that that we could also add a line like "Please delete this line" at the top of every issue template, to catch those that don't read the issue template and just hit submit.

**Comment by Akemi** [comment]
just to reiterate, all possibilities:
1. close issues based on the issue body, checks for the existence of template titles and closes if not found
    - error prone when titles are deleted, but the issue is otherwise fine
    - doesn't close issues that are not filled out
    - no time to intervene
2. label issues by some pattern (similar to 1.) and close issues with a specific label after x mins/hours/days
    - error prone when titles are deleted, but the issue is otherwise fine
    - depending on the pattern we chose, it will be more or less error prone
    - doesn't close the issue immediately and we have time to intervene
3. close all issues without a label (all opened issues have a default label from the template used), close all issues with a specific line from the template that should be deleted before submit
    - probably the least error prone way
    - we can be certain that an issue template was chosen or someone else already looked over it when a label exists
    - if a line that was supposed to be deleted before submitting exists we can be certain the issue template wasn't read properly
    - this won't close issues where the issue template was just deleted and something of their own was written, whether that content is bad or good can't be really evaluated with simple rules or at all
4. just leave it as is and keep doing the closing manually

there is one special case for all the methods that won't we caught properly. the case that a newly registered use is redirected to the "new issue" page without a template. though an issue opened that way is very unlikely to have the infos we want/need.

**Comment by avih** [comment]
Personally I think 2 is the best. It makes a point, and it will get closed automatically, but still gives a chance to intervene, and hopefully also give users the motivation to edit an issue (for the better) on their own.

**Comment by Akemi** [comment]
do you only prefer 2 because of the two stages? since it's still error prone. or would you rather prefer a mix of 2 and 3?

**Comment by avih** [comment]
Because I'm not fond of automatic and immediate closure, and because I think it covers the needs that the original patch tries to address (do correct me if I'm wrong).

Also, it sounds to me relatively simple procedure and hopefully not too hard to support, so also from a practical and simplicity point of view.

**Comment by Akemi** [comment]
this was stalled too long from my side and i can't find the time atm to test was i wanted to test.

**Pull request closed without merging**
