### PR TITLE
Fix spelling in user-facing documentation

### PR DESCRIPTION
**Pull request by a1346054**

### CODE REVIEW

**Comment by avih** [comment]
Please keep this PR only for documentation fixes, and change the commit title accordingly.
Also, don't delete empty lines, and don't delete trailing spaces. The main reason for not fixing harmless spaces etc is that it makes it harder to track changes via git history.

You can open a different PR to fix user facing messages in code/scripts.

I'm not sure about the license changes. Either way, not in this PR. I suggest to discuss it on IRC first (#mpv-devel on libera).

Don't open a PR to change comments/spacing/style in code.

Don't open a PR to change scripts (quoting etc) if the code is not wrong.

**Comment by a1346054** [comment]
Rebased without removal of trailing whitespace, I'm still looking into how to cut it all up so that github makes it separate pull requests.

**Comment by avih** [comment]
> I'm still looking into how to cut it all up so that github makes it separate pull requests.

I suggest to not think too much about it. just make a copy of your source tree (or a branch). Then, in this PR/branch - remove anything which isn't documentation fixes.

Then, if you want open another PR from the changes which you backed-up/branched, it shouldn't be hard.

**Comment by a1346054** [comment]
Hopefully all is good now, split it up into this pull request, and #9153 and #9154.

**Comment by avih** [comment]
Thanks for the update, changes look good, but please change the commit title to:
```
DOCS and github templates: fix typos
```

Thanks.

**Comment by a1346054** [comment]
So I should make it a single commit with that title, instead of two commits?

**Comment by avih** [comment]
> So I should make it a single commit with that title, instead of two commits?

Sorry, like this is fine. Missed the actual commits titles.

**Comment by avih** [comment]
Thanks.

**Pull request merged**
