### PR TITLE
cocoa: update screen fps only if necessary

### PR DESCRIPTION
**Pull request by Akemi**
to split an earlier PR. also added another indisputable commit since those variables are completely unused.

### CODE REVIEW

**Comment by wm4** [comment]
Status?

**Comment by Akemi** [comment]
this should be good to go. maybe @pigoz didn't see it.

**Comment by pigoz** [comment]
Yes it's good, I forgot about this. sorry!

**Comment by pigoz** [comment]
Thanks, cherry-picked into master. Sorry for the delay.

**Pull request closed without merging**
