### PR TITLE
Add support for mkv crop and rotation

### PR DESCRIPTION
**Pull request by kasper93**
Blocked by https://github.com/mpv-player/mpv/pull/12307

### CODE REVIEW

**Comment by kasper93** [comment]
Marked as draft, because it will have to be rebased after the other PR is merged.

**Comment by kasper93** [comment]
@Dudemanguy: Since we merged all the related PRs, this could go in too. It is pretty straightforward change.

**Comment by Dudemanguy** [comment]
Totally forgot about this... code looks fine. Does anyone have any samples? And I guess the ProjectionPoseRoll thing would be mainly for phones?

**Comment by kasper93** [comment]
> Does anyone have any samples?

crop: https://archive.org/download/BBC_Top_of_the_Pops_1979_12_25/BBC_Top_of_the_Pops_1979_12_25.mkv

rotate: https://github.com/hubblec4/Matroska-Playback/tree/master/files/Rotate

>  And I guess the ProjectionPoseRoll thing would be mainly for phones?

Probably. Not so much of them in mkv though.

**Review by Dudemanguy — APPROVED** [review]
Works fine.

**Pull request merged**
