### PR TITLE
demux_cue: auto-detect CUE sheet charset

### PR DESCRIPTION
**Pull request by wnoun**
Ideally, you shouldn't need enter any text here, and your commit messages should
explain your changes sufficiently (especially why they are needed). Read
https://github.com/mpv-player/mpv/blob/master/DOCS/contribute.md for coding
style and development conventions. Remove this text block, but if you haven't
agreed to it before, leave the following sentence in place:

I agree that my changes can be relicensed to LGPL 2.1 or later.

### CODE REVIEW

**Comment by sfan5** [comment]
Should have an option to override the detected charset, `mp_charset_guess` was designed for this.

**Comment by wnoun** [comment]
add `--demuxer-cue-codepage`

**Comment by wm4** [comment]
Should be fine. Can you rebase so it can be merged?

**Comment by wnoun** [comment]
rebased

**Pull request merged**
