### PR TITLE
player: add --auto-window-resize option

### PR DESCRIPTION
**Pull request by Dudemanguy**
mpv's window resizing logic always automatically resized the window
whenever the video resolution changed (i.e. advancing forward in a
playlist). This simply introduces the option to make this behavior
configurable. Every windowing backend would need to implement this
behavior in their code. This commit implements it for Wayland and X11.

Related issue: https://github.com/mpv-player/mpv/issues/9325

### CODE REVIEW

**Comment by Dudemanguy** [comment]
I took a peek at the windows code and I think the required change is trivial so I went ahead and added it to this.

**Comment by occivink** [comment]
Another relevant case is when setting `video-aspect-override`, the window is automatically resized to match the new video ratio and avoid black bars. 
With this new option enabled, the window size stays the same as expected.

**Comment by Dudemanguy** [comment]
P.S. if someone could test if the Windows change actually works correctly, that would be nice. mac was left out since swift makes my head spin.

**Comment by dyphire** [comment]
I tested it on windows, and the option of `auto-window-resize` works correctly.

**Comment by Dudemanguy** [comment]
Thanks for confirming. I think this is OK to merge (unless there's still some disagreements over the implementation). It's missing mac support, but no one can do that other than @Akemi anyways.

**Comment by anonish** [comment]
I have always used

`geometry=1920x1080+0+0
no-keepaspect-window
force-window=yes
keep-open=yes
idle=yes`

and never had the window auto-resize on me on switching videos (either through playlist skip, playlist end, or dragging a new video into the window), is this going to change anything?

**Comment by Dudemanguy** [comment]
For your configuration, no. The main thing this does is prevent auto-resizing without having to specify an arbitrary geometry (i.e. it'll just stay at whatever the first value in the playlist happens to be).

**Pull request merged**
