### PR TITLE
Wayland cursor fixes

### PR DESCRIPTION
**Pull request by Dudemanguy**
I think this is the right fix for all the bad cursor stuff I screwed up. I tested it in all the main 4 compositors and the autohide/fullscreening stuff all works as it should. The fix is basically just removing a bunch of dumb stuff and then setting some bools to their initial values in vo_opts instead of assuming they're false.

### CODE REVIEW

**Comment by wm4** [comment]
Looks sane. 

set_cursor_visibility still returns VO_NOTAVAIL (ignored by the caller) if there's no pointer (whatever that means), so that situation depends on luck. Not sure when that happens - before the window is visible?

**Comment by wm4** [comment]
PS: see handle_cursor_autohide(). It does:
```
    if (mouse_cursor_visible != mpctx->mouse_cursor_visible)
        vo_control(vo, VOCTRL_SET_CURSOR_VISIBILITY, &mouse_cursor_visible);
```
So if you just discard that value, you'll only be called when it actually changes.

**Comment by Dudemanguy** [comment]
Ah, so there's no need to worry about someone using mpv without a seat thing. Cool.

**Comment by Dudemanguy** [comment]
>Ah, so there's no need to worry about someone using mpv without a seat triggering that function. Cool.

Confirmed that this is wrong and `set_cursor_visibility` can still execute. I moved the `wl->pointer` check to `vo_wayland_control` instead.

**Pull request merged**
