### PR TITLE
vf_vapoursynth: copy Dolby Vision side data from the source frame

### PR DESCRIPTION
**Pull request by chainikdn**
Fixing https://github.com/mpv-player/mpv/issues/10438

### CODE REVIEW

**Comment by sfan5** [comment]
This seems flawed, isn't HDR metadata dependent on the content of the image? So if the VS script (substantially) changes the frame the old metadata won't be useful anymore.

**Comment by haasn** [comment]
Shouldn't we copy all HDR metadata then, not just DoVi?

**Comment by chainikdn** [comment]
> Shouldn't we copy all HDR metadata then, not just DoVi?

probably, yes... you should know better.
where they are? inside mp_image::ff_side_data "other side data we don't care about"? :)
in fact nobody ever complained about HDR10+ videos so I suppose static HDR data is enough for most of a real-life content

**Comment by haasn** [comment]
> > Shouldn't we copy all HDR metadata then, not just DoVi?
> 
> probably, yes... you should know better. where they are? inside mp_image::ff_side_data "other side data we don't care about"? :) in fact nobody ever complained about HDR10+ videos so I suppose static HDR data is enough for most of a real-life content, while DoVi videos are just unwatchable w/o this patch

No, I mean the stuff in `mp_colorspace`. Or where is that funneled in and out of vapoursynth frames?

**Comment by chainikdn** [comment]
`mp_colorspace` is inside `mp_image_params fmt_in`, copied to the output frame here: https://github.com/mpv-player/mpv/blob/ba20f60addaa4ebdd9f6be25464c1b46a7f1f576/video/filter/vf_vapoursynth.c#L275

**Comment by chainikdn** [comment]
fixed crash at eof

**Comment by elexor** [comment]
Can this also pass though hdr 10 properly? I noticed any hdr video loaded with a vpy filter losses it's hdr brightness even if the image is unchanged.

**Pull request closed without merging**
