### PR TITLE
osdep/timer-win2: use Waitable Timer for sleeping

### PR DESCRIPTION
**Pull request by kasper93**

### CODE REVIEW

**Comment by avih** [comment]
The commit message really should explain what problem it solves, what are the tradeoffs, if any, and why it's worth the change and additional code.

Also, `mp_end_hires_timers` takes an argument for a reason, you shouldn't call it with a fixed value.

**Comment by avih** [comment]
> In practice Windows kernel does not really go below 0.5ms

The kernel, sure, but the timer period needs to match for this to work, and the official API `TimeBeginPeriod` takes an integer ms value (using the kernel API can set 0.5, but we don't do that).

So currently we can't go below 1ms anyway, and we already do support 1ms, so I personally don't see the value here.

**Comment by kasper93** [comment]
> So I don't think there's a practical value here

Like I said on IRC, I implemented this for libplacebo, so might as well improve the code here. Of course given that `mp_sleep_us` is not used anywhere makes this patch really dummy. `mp_sleep_us` is used in 5 places total, 3 on Windows. And only vo_null uses it for something that matters. So indeed it may be not practical, but in the same time only issue is code size?

> Also, mp_end_hires_timers takes an argument for a reason, you shouldn't call it with a fixed value.

Changed that, I still don't like the fact we introduce 30% error on 50ms sleeps, but probably those long sleeps are not worth caring about anyway, so it is fine.

> So currently we can't go below 1ms anyway, and we already do support 1ms, so I personally don't see the value here.

We can, and we do this this code. Also remember you don't start sleep on slice start always, so setting the sleep time more precisely can reduce the overshoot.

requested vs actual sleep times:
```
100 us -> 518.0 us
100 us -> 516.2 us
100 us -> 476.8 us
10 us  -> 515.8 us
10 us  -> 517.0 us
10 us  -> 517.5 us
1 us  -> 11.1 us
1 us  -> 12.7 us
1 us  -> 10.6 us
```

**Comment by avih** [comment]
> requested vs actual sleep times:
> 
> ```
> 100 us -> 518.0 us
> 100 us -> 516.2 us
> 100 us -> 476.8 us
> 10 us  -> 515.8 us
> 10 us  -> 517.0 us
> 10 us  -> 517.5 us
> 1 us  -> 11.1 us
> 1 us  -> 12.7 us
> 1 us  -> 10.6 us
> ```

To be honest, I don't get how this works.

We do use `timeBeginPeriod(1)`, so presumably the system timers res is 1ms.

I can guess how the 1-10 us might work (maybe with a busy-wait loop at the kernel side?) but I don't get how the 500 us seems to work.

I don't think it would spin for 500us, and otherwise I don't get how it can reliably sleep for 0.5 ms when the system timers are 1ms...

Thoughts?

**Comment by kasper93** [comment]
@avih:

While this is interesting topic, I think I don't really want to start reverse engineering what Windows kernel does. I have pretty good understanding what gives us best precision and that's enough for me at this moment.

Also timer resolution is not straight forward, because since Windows 10 2004 update, resolution set by `timeBeginPeriod`, should be per group of processes that requested it. While this is true for Sleep(Ex), waitable timer seems to follow the global timer resolution.

Also this, from docs https://learn.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-setwaitabletimer: 
> APIs that deal with timers use various different hardware clocks. These clocks may have resolutions significantly different from what you expect: some may be measured in milliseconds (for those that use an RTC-based timer chip), to those measured in nanoseconds (for those that use ACPI or TSC counters).

So it is not as straight forward. I measured in recent `plplay`, limiting target fps to 50fps and observing vsync interval, that is limited by the sleep.

```
For 50Hz target:
WAITABLE_TIMER_HIGH_RESOLUTION, NtSetTimerResolution(1ms), timeBeginPeriod(unset): 20 +- 0.28 ms
WAITABLE_TIMER_HIGH_RESOLUTION, NtSetTimerResolution(0.5ms), timeBeginPeriod(unset): 20 +- 0.10 ms
Sleep, NtSetTimerResolution(1ms), timeBeginPeriod(unset): 20 +- 7.05 ms
Sleep, NtSetTimerResolution(1ms), timeBeginPeriod(1ms): 20 +- 0.71 ms
Sleep, NtSetTimerResolution(0.5ms), timeBeginPeriod(1ms): 20 +- 0.46 ms
```

Sorry for formatting, I just copied my messages from IRC.  I'm just happy with waitable timer performance, and I think it was worth implementing this few more lines of code, for reduced vsync timing jitter.

**Pull request closed without merging**
