### PR TITLE
Wasapi format search

### PR DESCRIPTION
**Pull request by kevmitch**
This PR addresses the problem #1376. It also makes the search for compatible hardware formats more sane and systematic. Most of the time (i.e., in shared mode) this format search never actually happens, because wasapi is able to request an appropriate format. However in exclusive mode, the only way to find a compatible format is trial and error.

### CODE REVIEW

**Comment by wm4** [comment]
Seems generally ok. Does it always try to find the highest quality format possible, even if the decoder output is less?

I'm also wondering whether all this code could somehow be made reusable for other AOs, but maybe not.

Also, mostly unrelated to these changes, how does channel map negotiation work? Especially hw devices probably support only certain channel maps, because they don't remix audio.

I also have some nits about your use of spaces; sometimes there is a space too many between syntax elements, and sometimes spaces are missing. I suppose they're not important enough that I point them out individually, but if you feel it, please fix them.

**Comment by kevmitch** [comment]
The basic idea is that it will try the native format of the clip (or whatever is initially requested through the ao structure). If that doesn't work, it tries to get the shared mode format. If that doesn't work, or if it is in exclusive mode, it falls back to loop over calls to IAudioClient::IsFormatSupported with (from inner to outer) sample formats, sample rates and channels. 

The loop starts with the sample rate and channel map initially requested by the ao and loops over the sample formats formats tried are 64,32 float, then 32,24,24(32),20(24),20(32),16 int. Then it tries increasing the sample rate by integer multiples of that initially requested and finally falls back to a hard-coded list of sample rates in decreasing order. 

If none of the above are supported, it reduces the number of channels by one and repeats until it reaches mono after which it fails if no suitable format has been found. This is admittedly not perfect because as you said, there are different channel maps. It is however an improvement over the previous behaviour which merely tried 5.1 followed by stereo ignoring quad or three speaker setups entirely. I am however open to suggestions as to how to improve channel map iterations. I can't however directly test them as I only have stereo hardware. I was hoping just to deal with problems on a case by case basis. 

The 

    bits = FFMAX(16, bits);

code is still needed as the comment suggests because it is still possible that the ao (or even GetMixFormat) may request 8 bits, which should be refused.

It may be useful to generalize something like this for all aos. It would require a bit of redesigning and abstraction for whatever is the analogue of IAudioClient::IsFormatSupported. Are other aos as dumb as wasapi exclusive mode about what formats they actually support?

**Comment by kevmitch** [comment]
Oh, and about the spaces, sorry, I'm trying to follow the guidelines, but my natural style is more condensed, so I miss some. I think I see some of the missing spaces, but too many? Do you mean that I should prefer

    if ( try_format(ao, bits, bits, af_fmt_is_float(ao->format),
 ao->samplerate, ao->channels) )
return true;

    if (try_format(ao, bits, bits, true, samplerate, channels))




    sing sing spaces, buspaces, bu

**Comment by kevmitch** [comment]
. . . oops
I should prefer?

    if (try_format(ao, bits, bits, af_fmt_is_float(ao->format),
                          ao->samplerate, ao->channels) )
         return true;

over 

    if ( try_format(ao, bits, bits, af_fmt_is_float(ao->format),
                          ao->samplerate, ao->channels)  )
         return true;



    sing sing spaces, buspaces, bu

**Comment by wm4** [comment]
Yes

**Comment by wm4** [comment]
> it reduces the number of channels by one and repeats until it reaches mono after which it fails if no suitable format has been found. This is admittedly not perfect because as you said, there are different channel maps. It is however an improvement over the previous behaviour which merely tried 5.1 followed by stereo ignoring quad or three speaker setups entirely.

Other AOs get the set of supported channel maps from the device, and then use chmap_sel.c to determine a good fallback.

**Comment by kevmitch** [comment]
merged

**Comment by kevmitch** [comment]
I'll look into improving the exclusive mode channel map selection, but for now, this is still an improvement.

**Pull request closed without merging**
