### PR TITLE
osx: menu improvements

### LINKED ISSUE #4797: Menu Bar improvements: Missing items and shortcuts
The following standard shortcut is missing: *Hide Others* (bound to *⌥⌘H*).

### PR DESCRIPTION
**Pull request by nathan**
- Improve user experience for preferences menu items:

    Instead of telling the user to create files/directories herself if no configuration file already exists, create an example one in `~/.config/mpv` (from [etc/input.conf](https://github.com/nathan/mpv/blob/osx-menu-improvements/etc/input.conf) or [etc/mpv.conf](https://github.com/nathan/mpv/blob/osx-menu-improvements/etc/mpv.conf)) and open it.

- Add missing standard menu items: (fixes #4797)
    - mpv > Services
    - mpv > Hide Others
    - mpv > Show All
    - File > Close
    - Edit > Delete

### CODE REVIEW

**Comment by Akemi** [comment]
lowercase changes are okay, though i would prefer to combine this with other cosmetic changes if there are any more needed.

creating any (config) file(s) shouldn't be part of the menu code. if at all it should reside in the core itself, especially for cross platform consistency. i believe it was previously decided not to create any config files, hence why the menu works as it works.

i see the close menu item actually makes some sense for the about menu. i left it out purposely since close and quit are the same in mpv's case. though it would make the most sense with a proper implementation of issue #1377.

imo standard menu items shouldn't be added for the sake of it, they should actually be useful or do something at all. 'Hide Others' and 'Show All' are fine. what is the reason for the 'Delete' and 'Services' menu items?

some remarks for the 'Hide Others' menu item. i don't like how you implemented the key mask. it should be more flexible for possibly other combinations. i would prefer a 'modifier' dict entry where the modifier mask is set directly. probably need to wrap them in a NSNumber. also the KeyMasks you used are deprecated, use the [new ones](https://github.com/mpv-player/mpv/blob/d355cb618ce8586e75a87918a8b7d16b3a06edef/osdep/macosx_compat.h#L53).

also i am not too happy about this PR. like i said on the issue i would rather like to discuss possible changes to the menu bar beforehand instead of merging several individual commits just for some menu items. you could have joined the discussion and could have gotten some feedback too. i also would like to have the new menubar in a new release beforehand, so people can actually test the current one and give their feedback in that issue. i doubt many have seen it yet.

**Comment by nathan** [comment]
> what is the reason for the 'Delete' and 'Services' menu items?

Both [Delete](https://developer.apple.com/macos/human-interface-guidelines/menus/menu-bar-menus/#edit-menu) and [Services](https://developer.apple.com/macos/human-interface-guidelines/menus/menu-bar-menus/#app-menu) are recommended in the HIG:

- Delete is another standard Edit menu item, corresponding to the Delete key. It's present in almost all the built-in apps, and the majority of third-party ones. (It's enabled when you're editing text, like in the Open URL dialog.)
- Services are a system thing, and that submenu should probably be part of the Apple menu, but since it's not, every app should provide it. If you have global or text services (especially ones bound to a key), it's annoying if they don't work just because an app forgot to include the Services menu.

> close and quit are the same in mpv's case

This is true for a lot of apps that only have one main window; the convention is to provide them both (e.g., Dictionary, Notes, Photo Booth, Photos, Reminders). (The most OS X-y thing to do would be to implement #1377 and keep the app open when there are no windows visible, so Quit and Close do different things.)

> i would prefer a 'modifier' dict entry where the modifier mask is set directly. probably need to wrap them in a NSNumber. also the KeyMasks you used are deprecated, use the new ones.

Fixed.

> creating any (config) file(s) shouldn't be part of the menu code. if at all it should reside in the core itself, especially for cross platform consistency.

Since "open-this-file-in-the-default-editor" is very platform-specific, it seems like a lot of unnecessary complexity to plug that into some trivial core functionality to create config files, especially when that functionality isn't used on other platforms. I was trying to keep the changes small/self-contained, but I can try to implement it in the core if you want.

> i believe it was previously decided not to create any config files, hence why the menu works as it works.

Where? All I could find was: "if no config file is found an alert is shown which asked the user to create one. this could probably improved" from the original menu PR.

**Comment by Akemi** [comment]
i don't see any reason for the 'Delete' item. mpv is not really Text centric and if one wants to delete some selected text in the Open URL dialog they can just hit backspace instead of using a menu item without a shortcut. as an example Terminal doesn't have a Delete item even though it has a few places with text inputs.

i don't use anything concerning the Service menu. can you give me a specific example, in the case of mpv, where that would be helpful?

personally i am a bit against adding a 'Close' menu item as long as mpv doesn't fundamentally do something different between quit and close. though i can't really argue against it since even some Apple Apps quit on close when no windows are left open. but yeah like we both said #1377 would be the 'best solution'.

i never said "open-this-file-in-the-default-editor" should be plugged into a core functionality, i believe. it's just about the 'creating a config file' case. mpv could create one when none is found on init. that would even get rid of some complexity, in the menu code, since we can be sure a file exists. that's also what i was referring to what was rejected before, if i remember correctly. the discussion about that wasn't part of that PR since it was decided ways before. it was either a closed issue or discussion on irc. if you want a definite answer about that you have to wait for a reply from @wm4.

**Comment by nathan** [comment]
> i don't see any reason for the 'Delete' item. mpv is not really Text centric and if one wants to delete some selected text in the Open URL dialog they can just hit backspace instead of using a menu item without a shortcut. as an example Terminal doesn't have a Delete item even though it has a few places with text inputs.

QuickTime player is probably a better app for comparison, and it includes the Delete menu item. I'm not sure what the harm is in including it.

> i don't use anything concerning the Service menu. can you give me a specific example, in the case of mpv, where that would be helpful?

It's not so much a useful-for-mpv-specifically thing as it is an annoying-if-it's-not-there thing. I have "General" services (don't require any input) I use all the time that are bound to keyboard shortcuts, and they work in every app except mpv since every app except mpv has a Services menu. Apple [says](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/SysServices/Articles/menu.html#//apple_ref/doc/uid/20000851-BBCDFIDD):

> The Services menu is included in the default nib file created by Xcode and Interface Builder for Cocoa applications. If the application’s menu is instead created programmatically, **you need to designate a Services menu using the `NSApplication` method `setServicesMenu:`**.

**Comment by Akemi** [comment]
there is no harm, i just don't see it as necessary. then let me ask the same. what is the harm in just leaving it out? if we go by that we could include many more menu items.

like i said i don't use the service menu, so i don't quite know what can be done with it. hence why i ask for a specific example. if it breaks system intended workflows (also user specified) then it should definitely be included. i kinda thought this needed some kind of context or input to work, but since you said those don't need an input i made a small test with Automator. so yeah definitely a menu item that should be there. thx for clarifying this,  i just wanted to understand the usefulness/necessity of it.

**Comment by nathan** [comment]
> there is no harm, i just don't see it as necessary. then let me ask the same. what is the harm in just leaving it out? if we go by that we could include many more menu items.

I don't think there are many more that would ever be enabled / do anything.

There isn't much harm in leaving it out, except for that it's a standard menu item and users expect to see it there.

**Comment by Akemi** [comment]
i don't expect to see it there since there is nothing to delete, besides the small case of the Open URL panel. not even all Apple Apps, with text input, have that item. so it's just a standard menu items, but not mandatory or necessary.

**Comment by nathan** [comment]
Not mandatory, but recommended, i.e., include it if you don't have a reason not to. Most apps have it.

**Comment by Akemi** [comment]
we don't have a reason to include it.

**Comment by Akemi** [comment]
i don't want config creation in the menu code. it should be moved to the core. when i inquired again there was no real opposition to creating a standard config file when none exists, but i couldn't get a consensus on how and what should be done. there were discussions about an option to create one, that it shouldn't be done without a user input, what should be in the config (the example config was rejected), etc. it would be best to either open an issue/feature request about this or another PR, to start discussions about it.

with that being said, please remove `osx: improve user experience for preferences menu items` and change the other thing(s) i mentioned. i would prefer the title of the cosmetic fixes to be just "osx: cosmetic fixes" and having an explanation in the commit description. you can also merge the menu bar commits into one and explain the changes in the commit description.

**Comment by kevmitch** [comment]
The menu stuff was addressed in #5424. As stated by @Akemi, config generation is really a separate issue that should be handled more generically. Someone can open a new PR if they have an implementation for that.

**Pull request closed without merging**
