### PR TITLE
vo_opengl: context_drm_egl: Don't create a new framebuffer for every frame

### PR DESCRIPTION
**Pull request by fhvwy**
Should fix the problem that @LongChair was seeing earlier.

### CODE REVIEW

**Comment by LongChair** [comment]
@fhvwy : the patch looks good, but it doesn't completely behaves as expected for some reason i didn't understand yet.
The `gbm_surface_lock_front_buffer` will return to different bo pointers that alternate at each call, which is expected to be back & front buffers.
When we start, the first bo doesn't have user data and we set it to one FB that we created. On next frame call, we get the second bo, but it seems that this one has already some userdata associated (why??).
The consequence if that seems to be that when the bo est destroyed, we get the callback called but it seems to be on either ones of the bos, just one gets called. And i have seen that it can the the one that we didn't create the FB for.

**Comment by LongChair** [comment]
I will add some debug log i added so that it can make more sense :
```
[vo/gpu] drm_egl_swap_buffers: using bo =0x7f9c22b680
[vo/gpu] update_framebuffer_from_bo Created FB 60
[vo/gpu] update_framebuffer_from_bo setting FB userdata to 60 for bo=0x7f9c22b680
[vo/gpu] drm_egl_swap_buffers: using bo =0x7f9c27b6a0
[vo/gpu] update_framebuffer_from_bo for bo=0x7f9c27b6a0 returned FB 66 from user_data
[vo/gpu] drm_egl_swap_buffers: using bo =0x7f9c22b680
[vo/gpu] update_framebuffer_from_bo for bo=0x7f9c22b680 returned FB 60 from user_data
[vo/gpu] drm_egl_swap_buffers: using bo =0x7f9c27b6a0
[vo/gpu] update_framebuffer_from_bo for bo=0x7f9c27b6a0 returned FB 66 from user_data
framebuffer_destroy_callback Removing FB: 66
```

The destroy callback seems to be randomly destroying either the one that we created or the one that we didn't. In the log above, it created the FB 60 and releases the FB 66.

**Comment by LongChair** [comment]
Scratch what i have said before , the first bo is created in the eariler init function for which i didn't see the log as it was much above.
So both FB seems to be created fine, but only one FB is released. it seems that one callback only is called. So we're probably missing something in the uninit.

**Comment by fhvwy** [comment]
It works for me (all bos and framebuffer objects are freed) on both Intel and AMD.  Can you work out where the references have gone on your platform?

**Comment by LongChair** [comment]
I will investigate further on RockChip. seems that the active bo (the one displayed) doesn't get freed.
I don't use bo outside of the context_drm_egl. but maybe so framebuffer is holding a ref on it.

**Comment by LongChair** [comment]
OK i think the missing bo release is more likely a mali driver issue. so looks good to me :)

**Comment by wm4** [comment]
Merged.

**Pull request closed without merging**
