### PR TITLE
Improve interactive sub-speed option

### PR DESCRIPTION
**Pull request by CyberShadow**
- Apply new sub-speed values during playback
- Improve OSD formatting
- Add default keybindings (Z/X, to complement z/x for sub-delay)
- Save sub-speed value when resuming playback

I agree that my changes can be relicensed to LGPL 2.1 or later.

#3516

### CODE REVIEW

**Comment by wm4** [comment]
Merged. I didn't merge the "input.conf: Add default keybindings for sub-speed" commit, because changing that during playback seems awfully obscure. If you really want it in, please make a new PR with it, so we can discuss it with proper context.

**Comment by CyberShadow** [comment]
Thanks!

Since this is a configurable option, I don't object to dropping the default keybinds commit. However, I can present my use case regarding the "awfully obscure" part, and leave the decision up to you.

I've been watching a TV show, and for a certain range of episodes, the subtitles that `subliminal` finds have been out-of-sync. The discrepancy grows linearly (and considerably so - a 2 minute difference towards the episode's end), so one needs to either constantly keep shifting the subtitle delay with z/x, or set the correct subtitle speed on mpv's command line. However, the correct speed factor also differs from episode to episode, so it required repeatedly Q-uitting mpv to adjust the timings throughout the episode.

In lieu of a dedicated UI for fixing subtitle timings such as the one implemented in mpc-hc, I found that an interactive way to adjust the subtitle speed made it much easier to quickly sync the subtitles without stopping playback.

By the way, if the option is added without default keybindings, perhaps it could be mentioned at the bottom of input.conf (the "not assigned by default" section), in the interests of discoverability?

**Comment by wm4** [comment]
Could be PAL vs. NTSC. I usually fix it on the commandline, or use the`sub-step` command to resync them during playback.

> In lieu of a dedicated UI for fixing subtitle timings such as the one implemented in mpc-hc, 

What do they have?

> By the way, if the option is added without default keybindings, perhaps it could be mentioned at the bottom of input.conf (the "not assigned by default" section), in the interests of discoverability?

Sure, that wouldn't harm. I'm just worried about adding new default bindings for such special purposes, because the existing default bindings are already kind of odd and full of strange stuff (who really wants to adjust "saturation" or change the V4L analogue tuner channel?).

**Comment by CyberShadow** [comment]
> Could be PAL vs. NTSC. I usually fix it on the commandline, or use thesub-step command to resync them during playback.

That was my first guess, but I've had to tweak the factor from one episode to another.

> What do they have?

This page describes it better:

http://nknu.net/sync-your-subtitles-with-mpc-hc/

It's probably out of scope for mpv.

> I'm just worried about adding new default bindings for such special purposes, because the existing default bindings are already kind of odd and full of strange stuff (who really wants to adjust "saturation" or change the V4L analogue tuner channel?).

Sure. Anyway, as I said, I don't mind either way.

**Comment by wm4** [comment]
> http://nknu.net/sync-your-subtitles-with-mpc-hc/

Sounds bit like the sub-step command, but writing to the subtitles is indeed out of scope.

**Comment by CyberShadow** [comment]
> Sounds bit like the sub-step command, but writing to the subtitles is indeed out of scope.

Just to eliminate the possibility of misunderstanding:

`sub-step` only adjusts delay, not speed, correct?

As I understand, mpc-hc's sub-resync feature allows adjusting two subtitles in order to interpolate and extrapolate the correct timings for the other ones. This implies adjusting their speed as well.

In the particularly pathological examples I encountered, without a speed adjustment, one would need to adjust the subtitle delay every 4 minutes to prevent them getting out of sync for more than 10 seconds - which is why, as I understand, `sub-delay` and `sub-step` would not be sufficient.

One idea is to have `mpv` perform the same inter/extrapolation when the user changes `sub-delay` or uses `sub-step`, using the current position, the file start, and previous adjustments as reference points. This would also avoid the need to adjust `sub-speed` directly.

**Comment by wm4** [comment]
> sub-step only adjusts delay, not speed, correct?

Correct.

> As I understand, mpc-hc's sub-resync feature allows adjusting two subtitles in order to interpolate and extrapolate the correct timings for the other ones. This implies adjusting their speed as well.

Oh I see. Yes, I suppose that could be done as some sort of extension.

**Pull request closed without merging**
