### PR TITLE
cli: more flexibility with date reporting

### PR DESCRIPTION
**Pull request by qyot27**
This allows for users to completely disable the 'built on' line if `--disable-build-date` is used (superseding #6046), and adds a few new options and information:

* The date of the most recent change to git HEAD is now printed underneath the binary build date.  This way, comparing the build date and the git commit date can easily show whether it's just a new build of an old commit or not.
* Adds an option to use date's RFC 3339 formatting (purely cosmetic).  Still reports in local time with timezone offset.  I actually debated whether to use date's ISO 8601 option or not, but I prefer the spacing in RFC 3339.
* Adds an option to format as the non-offset UTC date.  This means that the git commit date will be completely reproducible, for users that need that.
* Adds an option to disable the git commit date line completely, like the corresponding one for omitting the build date.
* Adds *.orig to the list in .gitignore, mostly just because fixing up these patches made me realize that it wasn't included there already.

RFC and UTC options can be used together.  I can't say I'm entirely happy with the wording for the commit date (I just tried to make it concise; the first version was 'most recent change commited on' which made aligning the build date with it look ridiculous), so I'm open to suggestions there.

### CODE REVIEW

**Comment by Hrxn** [comment]
Status? Who needs to be pinged?

**Comment by qyot27** [comment]
There's three more commits I added yesterday that make mpv's own version reports more descriptive.

* Copyright always gets printed on a new line.
* Reports both master and HEAD git hashes.
* Shows merged branches (useful to see what HEAD consists of, if it differs from master).

I still need to probably add some guarding so this only shows up for git builds, though.

**Comment by qyot27** [comment]
Sooo...over the past few months I had been experiencing some issues with mpv not being able to play back youtube-dl-parsed streams from several sites - including YouTube itself.  It would report that FFmpeg was hitting a 404 when attempting to parse the stream from the given URL.

Finally fed up with it, I went looking for which version of mbedtls and/or FFmpeg was at fault and tried bisecting it.  But due to some of the API changes in both FFmpeg and mpv between the last working build I had on hand (from last November) and now, it wasn't immediately obvious when the breakage occurred and where.  Eventually, I confirmed that it didn't exist in the upstream repos of any of the involved projects - it was in the patch in this pull request that makes sure the Copyright info is on a new line.

Yes, it was that stupid.  That assuredly sounds and feels wrong, I know, but the minute I remove that new line, it starts working just the way it's supposed to.  This is a piece of code that - as far as I can tell - only touches the info generated by `version.sh` that gets queried by the cli interface via `version.c`, and I can't think of any reason why this would start to impact mpv's networking capabilities with youtube-dl being able to correctly serve external video.  Just for the sake of it working, I've stepped the PR back a bit with a new commit, but this definitely seems like something that needs looking at inside either the youtube-dl wrapper or whatever other part of mpv is actually causing this to occur.

**Comment by qmega** [comment]
user agent?

**Comment by qyot27** [comment]
Truth be told, the additional configure options that interlock were mostly to cover my bases as experimentation snowballed.  `disable-build-date` not showing the `built on` line was the thing that prompted it all to begin with (and it was a commit I didn't care enough about to open a PR for when it was first mentioned years ago).

Depending on the view of the rest of the info shown, it could be consolidated to `disable-dates`, which would remove both the build date and the git date lines entirely.  If determinism is desired, a second option for `deterministic-dates` could consolidate the RFC and UTC options together and provide only that combination.

The git branch info is the part I see as more important than the date formatting, though.

**Comment by wm4** [comment]
I don't know how a "deterministic date" would work.
Isn't all that is needed an option that overrides the date/git info with a string provided to configure?

**Comment by qyot27** [comment]
Providing an option to format the area with a date style would be ideal, yes (essentially, just making the date format configurable like the options for GNU Date allow, although making sure both it and Git report the same formatting might be tricky).  If there isn't one provided when invoking that option, or using a placeholder like 'none', fall back to the `--disable-dates` option and omit the lines entirely.

I used 'deterministic' only because that's the term Debian was using for the overall idea of 'deterministic builds'.  A fully reproducible unique date tied to a singular revision with no overlap possible.  The only one that meets this criteria is the git date formatted for UTC+0, since the dates are unique to the revision in git anyway, but the UTC formatting removes the possibility of differing values due to time zone offsets.

**Comment by wm4** [comment]
Why the hell should the date format be configurable?

**Comment by qmega** [comment]
@qyot27 To clarify my earlier comment, I'm pretty sure the reason the newline was breaking things is that mpv's version string is used as the user agent for network requests (both lavf and ytdl). The extra newline probably broke the HTTP request (ending headers early or something).

Including the branch stuff in the version used as user agent (and the `mpv-version` property) doesn't feel right to me anyway. Maybe that should go in a separate string that only gets printed by `--version`? Newlines wouldn't be a problem then.

**Comment by wm4** [comment]
@qyot27 ping. Either simplify this, or close and possibly revisit it later.

**Comment by qyot27** [comment]
Yeah, possibly revisiting it at a later time is the most likely scenario.

**Pull request closed without merging**
