### PR TITLE
P3

### PR DESCRIPTION
**Pull request by kodabb**
DCI P3 is the one used by cinema projection and uses a different white point
DISPLAY P3 is the one used by Apple and shares the same primaries, but uses a standard d65 white point

### CODE REVIEW

**Comment by jeeb** [comment]
(at least they match with wikipedia)

**Comment by kodabb** [comment]
:tada:

**Comment by haasn** [comment]
Maybe `display-p3` -> `d65-p3`? Dunno, too late now.

**Comment by kevmitch** [comment]
Do we want to fix with @haasn's suggestion? Is there a spec somewhere that provides some guidance on nomenclature? Couldn't find anything obvious following a few links from the Wikipedia page.

**Comment by kodabb** [comment]
Apple calls it "display p3" in their dev documentation [1] so I think we should stick to that

[1] https://developer.apple.com/documentation/coregraphics/cgcolorspace/1408916-displayp3

**Comment by ValZapod** [comment]
The correct name for primaries is P3-D65, of course. Display P3 is P3-D65 plus perfect sRGB transfer, while we care about HDR that uses PQ transfer. And of course ITU docs tell us about P3-D65.

Of course in reality HDR displays are only using 2020 and are managing (hope QD-OLED will fix that) to P3-D65 with tall volume there on display. https://www.itu.int/md/R15-WP6C-C-0407/en

**Pull request merged**
