### PR TITLE
vf_d3d11vpp: add NVIDIA RTX Video HDR support

### PR DESCRIPTION
**Pull request by kasper93**
Fixes: #13352

### CODE REVIEW

**Comment by Johnnycyan** [comment]
Is this the correct way to try to enable it in mpv.conf? Sorry if it's not I did try to understand the docs relating to it but not sure I understood correctly. When I used these settings, it did not enable so that's why I'm asking.

```
gpu-api=d3d11
hwdec=d3d11va
vf=d3d11vpp=nvidia-true-hdr=1
```

**Comment by Johnnycyan** [comment]
> Not sure if it works as expected.
> 
> ```
>  d3d11-output-csp=srgb
>  vf=d3d11vpp=format=nv12:nvidia-true-hdr
> ```
> 
> It does output hdr. But I could not oberserve the RTX HDR indicator is active.

hmm when I use the same settings mine doesn't output HDR at all. But as far as the indicator in the Nvidia program goes I've found it to be unreliable.

**Comment by kasper93** [comment]
As I understand this is inverse tone mapping solution, so you want to play SDR and output HDR. Maybe try
```
vf=d3d11vpp=format=p010:nvidia-true-hdr
```

> It does output hdr. But I could not oberserve the RTX HDR indicator is active.

So, it does convert to HDR, but does not trigger the indicator, weird. It might be connected to some other Windows HDR options.

**Comment by Johnnycyan** [comment]
> So, it does convert to HDR, but does not trigger the indicator, weird. It might be connected to some other Windows HDR options.

When I directly hack Nvidia RTX HDR onto mpv using NvTrueHDR it also doesn't trigger the indicator, for some reason it's just weird like that.

**Comment by kasper93** [comment]
I don't know what is suppose to be an output from the processor. I suspect they output PQ or bt.2020?
```
d3d11-output-csp=pq # or d3d11-output-csp=bt.2020
vf=d3d11vpp=format=p010:nvidia-true-hdr
```
would be the configuration to use, but not sure, if we also should notify swapchain about some hdr ranges and where we would get that or hardcode HDR1000.

Needs testing, I cannot help here.

Also use vo=gpu, because vo=gpu-next signals HDR differently, with `--target-colorspace-hint`

**Comment by kasper93** [comment]
On the d3d11vpp side, there isn't much I can change. The processor extension is enabled. Whether it depends on other factors like input/output formats is another story, and I cannot test it without the hardware. However, all those parameters are already configurable in mpv, so it should be possible to make it work somehow. Otherwise, someone else would need to implement the missing pieces.

**Comment by kasper93** [comment]
So what is the consensus on this one? Is doing something? Can this be merged? Without actual hardware it is hard to say from my side. As far as processing itself goes it should be properly enabled, I don't see any other changes needed, except automation for autohdr and so on, but this can be done in lua script.

**Comment by hooke007** [comment]
> Can this be merged

Yes, and let more users test together.

**Comment by kasper93** [comment]
Ok, let's see. We can improve it if needed.

**Comment by Johnnycyan** [comment]
Yeah I never got it to work either

**Comment by softworkz** [comment]
> hwdec=nvdec-copy

Need to use d3d11va

**Comment by aloola18** [comment]
> > hwdec=nvdec-copy
> 
> Need to use d3d11va

doesn't work for me. I tried no, yes, auto, auto-copy. nothing works.
Nvidia RTX HDR turned on in the Nvidia control panel
Windows HDR turned on

Nvidia Super Res did work for me though.

**Comment by softworkz** [comment]
Did you also set --target-colorspace-hint=yes ?

**Comment by Steinheausser** [comment]
Using the above mpv.conf suggestions by everybody here didn't seem to be making any difference to the picture. I tried these in various combinations:

>  d3d11-output-csp=srgb # d3d11-output-csp=pq # or d3d11-output-csp=bt.2020
>  vf=d3d11vpp=format=nv12:nvidia-true-hdr

&
> --target-colorspace-hint=yes
&
using vo=gpu-api, using d3d11 output, etc mentioned in some previous issue  threads. 



The below conf lines I found on a chinese forum seemed to greatly change the picture.  Perhaps these lines are implicitly implied by other users, but I write them explicitly here in case it helps somebody. Whether it is even working as intended I'm also not sure. Here's the lines:

> gpu-context=d3d11
> gpu-api=d3d11
> icc-profile-auto=yes
> tone-mapping=bt.2390 
> target-peak=xxx #your actual brightness 

(not sure what actual brightness means here. I put 1100 which is my monitors' peak brightness in nits and it seems to work well enough.)

**Comment by askasys-code** [comment]
I really don't understand how this work, I tried everything I know.
The official wiki it's not clear, nvidia-true-hdr alone is not enough to activate the function.

**Comment by vermi5** [comment]
Yeah, I think I've tried every combination of settings posted here. Never got it to work, even though the log says it's enabled.

[output.txt](https://github.com/user-attachments/files/17938780/output.txt)

**Comment by kasper93** [comment]
I don't have hardware to test this. I cannot help you. Someone need to debug what is needed. Video processor itself is enabled.

**Comment by CANNONGH** [comment]
> I don't know what is suppose to be an output from the processor. I suspect they output PQ or bt.2020?
> 
> ```
> d3d11-output-csp=pq # or d3d11-output-csp=bt.2020
> vf=d3d11vpp=format=p010:nvidia-true-hdr
> ```
> 
> would be the configuration to use, but not sure, if we also should notify swapchain about some hdr ranges and where we would get that or hardcode HDR1000.
> 
> Needs testing, I cannot help here.
> 
> Also use vo=gpu, because vo=gpu-next signals HDR differently, with `--target-colorspace-hint`

On my 4070Ti PC, the processing is better with vo=gpu-next than with vo=gpu. Are there any plans to support RTX HDR even when using vo=gpu-next?

**Pull request merged**
