### PR TITLE
vo_opengl: fix srgb replacement options

### PR DESCRIPTION
**Pull request by rossy**

### CODE REVIEW

**Comment by wm4** [comment]
Does this (and the existing code) actually work?

**Comment by rossy** [comment]
Ah, sorry, I was only trying to get the error message to be correct. After looking at m_config.c, I don't think it does.

**Comment by haasn** [comment]
I'm not sure what's wrong with OPT_REPLACED, here. This is the error message:

```Warning: option srgb was replaced with target-prim=srgb:target-trc=srgb and might be removed in the future.```

It reads pretty normally to me. But you're right, it should be target-prim=bt709, not target-prim=srgb. In fact, it would probably be better to make it so that target-prim=srgb and target-prim=bt709 both work (and map to the same thing).

**Comment by rossy** [comment]
> I'm not sure what's wrong with OPT_REPLACED, here.

I think OPT_REPLACED makes the old option act as an alias for the new one, where OPT_REMOVED just prints an error message.

**Comment by haasn** [comment]
Ah, you're right. I never even realized that it still functions as an alias. Okay, I agree with OPT_REMOVED then.

**Pull request merged**
