### PR TITLE
builtin.conf: remove debanding from high-quality profile

### PR DESCRIPTION
**Pull request by kasper93**

### CODE REVIEW

**Comment by kasper93** [comment]
> Is there a specific reason?

Read commit message.

**Comment by Akemi** [comment]
we had this discussion a few times before and i always thought and said; debanding should not be the default for a high quality preset, since the assumption should be the usage of a 'perfect'/best source.

the problem with debanding:
- debanding is inherently destructive
- there is no one default to 'fix' them all
- only useful for bad sources (or everything that is streamed lol)

filter that possibly increase the quality only in certain cases (and decrease it in others) should be opt-in instead of opt-out.

i personally also deactivated it and put a toggle on the 'd' key, as proposed here, to only activate it if visually needed.

though in the end i fine with either.

**Comment by Jules-A** [comment]
What about reducing grain/strength rather than disabling completely?

**Comment by Akemi** [comment]
the last two comments are imo wrong.

1. i have had various sources where the defaults killed details especially in background details
2. i never encoded anything with the assumption that a TV or a media player does debanding, i filter and encode in a way that the outcome is the best without any more (intrusive) filtering (ignoring needed filter like dithering, scaling, etc). i don't know anyone who encodes/filter by that assumption.

**Comment by Jules-A** [comment]
>i don't know anyone who encodes/filter by that assumption.

I don't have enough experience to comment on non-anime sources but Crunchyroll/Funimation/Hidive all have a large amount of (mostly older) content that has banding.

**Comment by kasper93** [comment]
> mpv's deband algorithm is very lightweight and significantly increases quality on the vast majority of content

I don't agree with that. I can say the opposite. That it does not increase quality with the vast majority content. Debanding is needed for some content, but I argue not the vast majority of it. YMMV depending what you watch and where you source your movies, but in the end of the day mpv cannot know it and shouldn't by default enable debanding. It is useful, but it should be opt-in.

> mpv's default debanding settings are tuned to be universal for both good and bad sources. 

After recent increase of strength? Overall if the source does not need debanding it should not be applied, not only because of real detail loss, but also because dbanding itself is heavy on gpu processing.

> What about reducing grain/strength rather than disabling completely? Not as a default for debanding but for GPU-HQ defaults.

default debanding settings should be tuned for best results, but also not applied if not needed. No point in adding pointless filtering which can only reduce quality if there is no banding in the first place.

> i have had various sources where the defaults killed details especially in background details

+1

> i never encoded anything with the assumption that a TV or a media player does debanding, i filter and encode in a way that the outcome is the best without any more (intrusive) filtering (ignoring needed filter like dithering, scaling, etc). i don't know anyone who encodes/filter by that assumption.

That's the main point, there are 
1) high-quality sources that doesn't need debanding
2) already debanded sources that doesn't need further processing
3) low-quality banded sources that needs debanding

Only in case if 3) debanding should be enabled and it is user choice.

> I don't have enough experience to comment on non-anime sources but Crunchyroll/Funimation/Hidive all have a large amount of (mostly older) content that has banding.

That's the problem, if we tune mpv only for anime content, sure debadning likely is needed, but for live-action movies it is not always needed.

Maybe it is true that most live streams and anime content need debanding, but in the same time there is probably equally large number of sources that doesn't need it and I argue it should be opt-in feature. 

But I won't push it so hard, if community decides that debanding is good by default, I'm fine with that.

**Comment by Akemi** [comment]
> > i don't know anyone who encodes/filter by that assumption.
> 
> I don't have enough experience to comment on non-anime sources but Crunchyroll/Funimation/Hidive all have a large amount of (mostly older) content that has banding.

i don't disagree. i agree that most sources are shit. though they don't encode by the assumption that anything else does the debanding. they just do dumb transcodes of various sizes and resolutions and mostly care about their bandwidth (or rather their profit in this case). it's just 'low effort' encoding without the goal to have the best/good 'quality'.

**Comment by Hrxn** [comment]
I agree with this commit as well..

Explanations have already been given. It doesn't really make sense for FHD material (unless the encode is already fucked up), let alone 4K -  and then it gets computationally costly enough.

debanding should be thought of as a method to fix bad source material, and as Akemi and others have pointed out, it should be opt-in.

It can also easily be used with an auto profile, here's what I currently have in my config:

```

[LQ]
profile-cond=get('video-params/average-bpp') and get('video-params/average-bpp') < 24
profile-restore=copy
deband=yes
deband-range=8
deband-grain=24
deband-threshold=48
deband-iterations=4

```

**Disclaimer**: I've found this via web search, don't ask me I have no fucking clue (tm). While it works (theoretically), I've found that this condition gets triggered by source material that is already "good enough", so I end up manually toggling off the debanding.
I'm all ears for suggestions on how to improve this.

**Comment by Dudemanguy** [comment]
I'm totally OK with removing debanding. It's trivial to just make an autoprofile that turns on debanding for a Subsplease file or whatever you're watching.

**Comment by paulguy** [comment]
Would it be worthwhile to make the default parameters for debanding maybe more aggressive/fit for especially low quality content since the consideration for default parameters no longer has the constraint that it's intended to be on as part of a high quality profile?  That is, effective for cases where one would notice it's especially needed?

**Comment by llyyr** [comment]
> Would it be worthwhile to make the default parameters for debanding maybe more aggressive/fit for especially low quality content since the consideration for default parameters no longer has the constraint that it's intended to be on as part of a high quality profile? That is, effective for cases where one would notice it's especially needed?

Yes, I will open a PR for this later after testing out how aggressive it can be with a variety of content

**Comment by LightArrowsEXE** [comment]
Rather than tying debanding to `D`, I think it'd be better to set it to `h` (which I believe is currently unused?). This makes it even just a tiny bit easier to quickly enable/disable debanding for the user, as it requires one less key stroke. If not, I think swapping around the hotkeys for deinterlacing and debanding would be better, seeing as debanding is going to generally be more relevant than deinterlacing for most current-day sources.

**Comment by haasn** [comment]
LGTM

Bitrates have gone up, and the recent bump in deband strength invalidates much of the preexisting arguments.

**Comment by raptordaking** [comment]
I agree this is a good change and would also suggest the default bind for debanding be set to `h`, that is where I've had it for a few years now as it was not used for anything else at the time and that still seems to be the case? As Light said this would leave `D` for a possible bind for IVTC or related and debanding could be activated with a single key press instead of `Shift+d` which is very unintuitive imo when a seemingly free key is available.

**Comment by sfan5** [comment]
My opinion: Banding is everywhere, in YouTube videos, in Anime, in the movie releases that average users download.

I think having debanding as a default in the high-quality profile is reasonable.
After all high quality doesn't mean "my source is high quality" (or we wouldn't need scalers) but "play this back in high quality".

If the recent changes to debanding defaults invalidate the one-size-fits-all idea, then I'd rather see them adjusted again.
(see https://github.com/mpv-player/mpv/pull/12441#issuecomment-1728234133 for a comparison)

**Comment by guidocella** [comment]
I think b would be better than h since it's also unused and banding starts with b.

**Comment by LightArrowsEXE** [comment]
> I think b would be better than h since it's also unused and banding starts with b.

Personally, I'm fine with either. I just think it's better to not touch `d` since that is a pre-established key, but also using a lowercase letter is a bit nicer on the user since this key is more relatively likely to be pressed frequently.

**Comment by kasper93** [comment]
Changed keybind to `h` as it is more accessible than `D` and `d` is already taken.

> My opinion: Banding is everywhere, in YouTube videos, in Anime, in the movie releases that average users download.

Agreed. But the main issue is the amount of banding. Insignificant amount of banding is not that problematic and for the heavy banded sources like older youtube or twitch you have to use at least deband-threshold=64 to make a difference, which already is proven to destroy detail too much on high quality source. 

> If the recent changes to debanding defaults invalidate the one-size-fits-all idea, then I'd rather see them adjusted again.

I'd like that too, but at this point I think we cannot agree on the one-size-fits-all config. For heavily banded source material, that needs debanding we need stronger processing, for everything less stronger processing has adverse effect and removes image details.

We changed from 64 to 32, which arguably didn't remove much banding, making this option useless. Than we increased to 48 (current) and it is middle ground that still is not best. And above that, debanding itself is heavy on gpu, which we cannot mitigate with any settings. I think it should be enabled when it is necessary. I personally just toggle it when I start noticing banding and it bothers me. 

----- 

My opinion about keybind:
- `d` should stay for deinterlacing, just for the sake of not changing established key
- `D` is not convince to use, lower case letter is better
- `h`  is ok
- `b` is maybe better for `banding`, but it is at the middle of spacebar, wouldn't it be easy to hit it accidentally? When pausing?

But honestly either `b` or `h` is fine for me.

**Comment by sfan5** [comment]
> I'd like that too, but at this point I think we cannot agree on the one-size-fits-all config.

I did some quick (admittedly not exhaustive) testing and maybe the current defaults are good enough™?
threshold=32 indeed does just about nothing while threshold=64 might risk destroying too much detail.

for completeness: the commits that changed deband options are 12ffce0f224056f91a20c9f0b197f4973931efbe & 2fd5b9b4dda14c858f24548801da587dea747cac

> And above that, debanding itself is heavy on gpu, which we cannot mitigate with any settings.

Now I think this is really not an argument. `high-quality` is already heavy by using the most demanding scalers we have, despite only minor visual differences.

> but it is at the middle of spacebar, wouldn't it be easy to hit it accidentally?

does this happen to people? it doesn't to me
You're out of luck here anyway because there's a bunch of keys you can hit to make mpv misbehave with no way to fix it unless you *know* what you did.

**Comment by llyyr** [comment]
`h` or `b` for debanding makes no intuitive sense, `D` is free and pressing shift isn't a huge inconvenience. I'm in favor of using `D` for debanding over the others, or possibly swapping `d` and `D`

**Comment by wiwaz** [comment]
Good change, don't mind the keybind aslong as its a key that only requires a single keystroke. No `D` please, we have several unused keys to bind to instead.

**Comment by llyyr** [comment]
> I don't think there's any previous precedent on keybinds being "intuitive".

That doesn't mean we can't start now...

Either way, if pressing Shift is so hard then my vote is for `b`

**Comment by aufkrawall** [comment]
> I did some quick (admittedly not exhaustive) testing and maybe the current defaults are good enough™? threshold=32 indeed does just about nothing while threshold=64 might risk destroying too much detail.

Ack, 32 does hardly do anything more than processing inherent 8 bit banding, which is pretty much unnoticeable vs. real world content/compression-banding.

**Pull request merged**
