### PR TITLE
dvbin code cleanup

### PR DESCRIPTION
**Pull request by sfan5**
this felt like a waste of time

### CODE REVIEW

**Comment by olifre** [comment]
Many many thanks!

Reading through the changes, all of that LGTM. Most of the cruft has been inherited that way from `mplayer`, and while I added new functionality, I never came around doing an actual cleanup like this, so this is greatly appreciated. 

I can give the code a test with actual hardware tomorrow (while I don't see any code change which would break things, it might be better to confirm for completeness).

**Comment by sfan5** [comment]
I tested with DVB-T2 FWIW, feel free to test more.

**Comment by olifre** [comment]
Thanks! I'll be with my DVB-S2 hardware tomorrow. I also have DVB-T2 here, but then I can already skip testing that ;-) .

**Comment by olifre** [comment]
@sfan5 Done, I tested with the DVB-S hardware using both DVB-S and DVB-S2 delivery systems, also tested channel switching between channels from one channel list with different delivery systems (using the `dvbin-channel-switch-offset` property, which triggers the code part with the DVB state being kept between switches) and tested `--dvbin-full-transponder`, so even the more exotic things are covered. 

Nothing broke (as expected from the changes) and verbose output also looks much better / more in line with all else now. 

Thanks again for uncrustifying this! :+1:

**Review by olifre — APPROVED** [review]

**Comment by sfan5** [comment]
Thanks for testing.

**Pull request merged**
