### PR TITLE
Add window screenshots support to vo_drm

### PR DESCRIPTION
**Pull request by rr-**

### CODE REVIEW

**Comment by rr-** [comment]
As far as I'm concerned, the new reference is freed by whatever is responsible  for taking the screenshot, so there are no memory leaks. Please correct me if I'm wrong though.

**Comment by wm4** [comment]
>As far as I'm concerned, the new reference is freed by whatever is responsible for taking the screenshot, so there are no memory leaks. Please correct me if I'm wrong though.

This is correct.

>Also the framebuffer used in this commit is exactly the one used to copy byte-by-byte to the final destination. Adding DRM-related functions just to get the same thing would be an overkill.

One problem I see with this: you write to the cur_frame without calling ``mp_image_make_writeable()``. So either you add this call every time you make a write access to cur_frame, or you use ``mp_image_new_copy()`` to return the screenshot instead.

As it is, the VO could draw a new frame to the same memory the screenshot encoder is using to write an image.

**Comment by rr-** [comment]
I thought these were thread-safe. Updating in a sec to `mp_image_new_copy`.

**Comment by wm4** [comment]
Merging.

>I thought all of these calls were synchronous. 

They are, but not what happens after them.

**Comment by wm4** [comment]
Merged.

**Pull request closed without merging**
