### PR TITLE
console.lua: cycle through completions

### PR DESCRIPTION
**Pull request by guidocella**

### CODE REVIEW

**Comment by N-R-K** [comment]
(Haven't looked at the code just testing it out)

In which order does the completion cycle for you? For me it's down to up and left to right. Which is weird, usually it's up to down.

Also the visuals for the "selected" entry seems very unappealing and easy to miss.

image

I'd try something like bolding the text + use of different color instead.

**Comment by guidocella** [comment]
> In which order does the completion cycle for you? For me it's down to up and left to right. Which is weird, usually it's up to down.

That's the orders the completions are presented in, I also didn't notice the order at first, but I assume that the logic is that they extend upwards from the console line, while in shells they expand downward.

> Also the visuals for the "selected" entry seems very unappealing and easy to miss.

We wanted to invert the background color but it's not feasible because each ASS event has either a shadow or background color, and by drawing only the selected completion as its own ASS event it would no longer be placed correctly.

> I'd try something like bolding the text + use of different color instead.

Any suggestion for the color?

**Comment by N-R-K** [comment]
> We wanted to invert the background color but [...]

I see.

> Any suggestion for the color?

`#fabd2f`, `#fe8019` or `#fb4934` should be decent choices, me thinks. Pick whichever one looks good to you, as long as it has decent contrast with the rest of the options and is easy to pick out visually.

**Comment by guidocella** [comment]
I went with `#fabd2f` + bold for now.

**Review by N-R-K — APPROVED** [review]
Looks better now. The down to up is a bit jarring but it's something I can get used to, so it's not a big deal. (And it makes some sense. In zsh/shell the completions are shown *below* the cursor extending downwards, but here the completions are shown *above* the cursor, so it extending upwards seems logical.)

**Review by christoph-heinrich — APPROVED** [review]

**Comment by christoph-heinrich** [comment]
> The down to up is a bit jarring

It shouldn't be hard to make it expand below the input line and have suggestions be top to bottom. Care needs to be taken with the lines calculation and the clipping, in case anyone cares enough to actually change it.

**Comment by guidocella** [comment]
> It shouldn't be hard to make it expand below the input line and have suggestions be top to bottom. Care needs to be taken with the lines calculation and the clipping, in case anyone cares enough to actually change it.

I think that moving the input line every time you show and hide suggestions while you're typing would be even more jarring.

**Review by Dudemanguy — APPROVED** [review]

**Pull request merged**
