### PR TITLE
command: make it possible to set chapters via lua plugins

### PR DESCRIPTION
**Pull request by hahiserw**
fixes issue #3402

### CODE REVIEW

**Comment by avih** [comment]
Is this specific to lua in any way (identifiers, naming wise)? it _seems_ to me just enabling setting chapters via property, possibly also available via client APIs or even input commands?

**Comment by wm4** [comment]
>Is this specific to lua in any way (identifiers, naming wise)? 

No.

>it seems to me just enabling setting chapters via property, possibly also available via client APIs or 

Correct.

>even input commands?

No, because this can't create mpv_nodes.

**Comment by wm4** [comment]
Merged, thanks. I made some modifications on it in commit
68d2903cb1f3095070636ebb9e696594cc71f6c4 rather than extending the review - I hope that's ok. I also fixed a Lua wrapper bug in 2361ec35aa2438cb6c4e9976eecc856d3b123447, which could influence this.

**Comment by wm4** [comment]
(The only actual problem with your PR was that it leaked memory - I found that later, so I just included the fix in my commit.)

**Comment by hahiserw** [comment]
Cool, glad I could help. :)

**Pull request closed without merging**
