### PR TITLE
DOCS: improve note for sub-scale 

### PR DESCRIPTION
**Pull request by llyyr**

### CODE REVIEW

**Comment by hooke007** [comment]
It's misleading. `sub-ass-override=scale` dosn't affect srt at all

**Comment by llyyr** [comment]
The note is about ASS subtitles

**Comment by hooke007** [comment]
No. This part is telling users how to change plain text sub's font size while not changing ASS

**Comment by llyyr** [comment]
sub-scale is not for changing font size, and sub-font-size already exists for plaintext subs.

Nothing should be broken when using sub-scale for plaintext subs, so the note isn't for that. sub-scale may result in broken subtitles like seen in #11789 if used without sub-ass-override=scale.

Here's the original message:

> This affects ASS subtitles as well, and may lead to incorrect subtitle rendering. Use with care, or use ``--sub-font-size`` instead.

From my interpretation it's saying that this option affects ASS subtitles (true)

And it may lead to incorrect subtitle rendering in them (also true)

So use with care, or use --sub-font-size instead (misleading because sub-font-size only affects plaintext subs)

The note wasn't for sub-scale breaking plaintext subs, and directing them to sub-font-size instead. At least that's my interpretation of it. Please let me know what you think I got wrong

**Comment by hooke007** [comment]
The original explaination is important. It shouldn't be removed.
I cannnot understand why it was talking about ASS.
If you want to add your personal comprehension, it could be append.

**Comment by llyyr** [comment]
I could add a note that tells users to use sub-font-size if they just want to change the font-size for plaintext, I guess. But no other option in the manual is written like that, you'd be writing similar notes for dozens of options...

**Comment by hooke007** [comment]
> I could add a note that tells users to use sub-font-size if they just want to change the font-size for plaintext

The original manual already did it.

**Comment by llyyr** [comment]
> The original manual already did it.

The original manual did not, in fact, do that. It was talking about ASS subtitles, not plaintext. And then recommend an option that would never work on ASS subtitles.

Either way, this is an extremely pointless discussion to be having. I'll just leave it as it is and let users figure out sub-ass-override=scale exists.

**Comment by hooke007** [comment]
> And then recommended an option that would never work on ASS subtitles.

As i said , original msg is clear and simple : "This part is telling users how to change plain text sub's font size while not changing ASS"
It is not telling you how to change ASS.

**Comment by llyyr** [comment]
You're right, that appears to have been the intended interpretation. It's a bit awkward, and more people could definitely have the same misunderstanding as me, but I don't think it's worth it to push a change just for that

**Pull request closed without merging**
