### PR TITLE
Cocoa: update mouse position after going full screen.

### PR DESCRIPTION
**Pull request by torque**
When going full screen, the call to signalMousePosition in setFrameSize
does not return the correct mouse coordinates, so the mouse position
needs to be updated again after the transition to full screen is
finished.

### CODE REVIEW

**Comment by pigoz** [comment]
After ce239f1577cc this should not be relevant anymore, since a signalMousePosition would be triggered by the call of windowDidBecomeKey in `window.m/cocoa_common.m`

**Comment by torque** [comment]
Okay, let me update and check.

**Comment by torque** [comment]
Okay, just checked a clean build from current master (d7f04e2) and the problem I was attempting to fix with these commits persists, so let me better explain what I'm trying to fix here.

##### The first commit
With my 640x480 test video, when going from the initial window (centered on my 1280x800 screen) to fullscreen, the call to `signalMousePosition` from `setFrameSize` signals the mouse location as (0,800). I don't know exactly why this is, but I assume it has something to do with `signalMousePosition` being called during the transition. Since this point is one pixel below the bottom pixel of the window, it gets clamped to (0, 799). The mouse position is not updated from this point until there is a mouse move event. I noticed this bug because I have a script that shows OSD when the mouse hovers the bottom 40 pixels of the window, and the display gets stuck when transitioning to fullscreen because of this. Calling `signalMousePosition` right after switching to full screen doesn't fix the wrong mouse position being reported, but it at least automatically updates the mouse position correctly without requiring movement.

##### The second commit
with the same test video, in fullscreen, if I move the mouse cursor to the bottom right hand side of my screen and then exit, the MOUSE_LEAVE key is never called.  The cursor is no longer over the video window (which is centered in the middle of the monitor), so the key should be called. I believe the cause of this is pretty simple: the full screen 1280x800 `NSTrackingArea` does not trigger a `mouseExited` event before it is removed because the mouse never leaves it. Likewise, the new 640x480 `NSTrackingArea` that is created by `updateTrackingAreas` has never had the mouse enter it, so it also does not trigger the `mouseExited` event.

**Comment by wm4** [comment]
What's with this? Do we accept or reject this? cc @pigoz

**Comment by wm4** [comment]
>What's with this? Do we accept or reject this? cc @pigoz

Last ping.

**Comment by pigoz** [comment]
IIRC we decided on IRC that we didn't want to merge this (in July)

**Comment by wm4** [comment]
OK then.

**Pull request closed without merging**
