### PR TITLE
Patch 3

### PR DESCRIPTION
**Pull request by kungfubeaner**
Read this before you submit this pull request:
https://github.com/mpv-player/mpv/blob/master/DOCS/contribute.md

Reading this link and following the rules will get your pull request reviewed
and merged faster. Nobody wants lazy pull requests.

### CODE REVIEW

**Comment by Dudemanguy** [comment]
Can you explain what this is trying to do? Also please read the [contributing.md](https://github.com/mpv-player/mpv/blob/master/DOCS/contribute.md) document. See the lint output as well.

**Comment by kungfubeaner** [comment]
The original file has some quirks with on top only while playing during playlists.  If a new file loads like playing the next episode it loses its on top setting.   This one keeps settings regardless of loading a new file.  Sorry about the trouble though.  Github didn't seem this complicated when I contributed to Marco for MATE desktop.  I dont know if the interface changed or I just forgot how to use github after years.

**Comment by kungfubeaner** [comment]
Anyway go ahead and delete this sorry for the trouble, I meant to contribute not cause headaches but I don't have time to deal with this have family errands to attend to.

**Comment by Dudemanguy** [comment]
This my first time actually looking at this script but it looks overly complicated actually. Not sure what the point of all the `was_ontop` business is. But okay I'll close this.

**Pull request closed without merging**
