### PR TITLE
osc: bottombar/topbar: make chapter markers slightly bigger

### PR DESCRIPTION
**Pull request by wiiaboo**
1px to 2px squares.
Also move them away from the seekbar.

### CODE REVIEW

**Comment by wiiaboo** [comment]
The order of the 

Before:
image

After:
image

The reversal of the top markers values was unintended and the `+1-1` are unnecessary.

**Comment by wiiaboo** [comment]
The box/slimbox layouts don't need the change since they use a border.

**Comment by ChrisK2** [comment]
Alright, here is my solution: Instead of messing around in the render-logic, use existing functionality (and make sure it works as intended). I simply increased the gap to 2 so that little (and bigger) triangles will be drawn:

screen shot 2016-12-25 at 06 13 09
screen shot 2016-12-25 at 06 04 46
screen shot 2016-12-25 at 06 11 58

I kept the change for the nibbles though since that can be really hard to see due to the aliasing at low resolutions.

**Comment by wiiaboo** [comment]
Doesn't that make the `else` part dead code?

**Comment by ChrisK2** [comment]
The "else -- draw 2x1px nibbles" else? No, that's still needed for the box layout which still uses a gap of 1.

**Comment by wiiaboo** [comment]
Hm, for some reason I thought box and slimbox had the same 1.5 gap.
The changes in the knob code are just code cosmetic, right?
Fixup everything and ok to merge?

**Comment by ChrisK2** [comment]
Yes, I just wrapped it to 80 col. Otherwise fine from my end.

**Pull request merged**
