### PR TITLE
zsh completion: actually make pcre optional

### LINKED ISSUE #7240: Zsh completion does not works with macOS Catalina preinstalled zsh
### mpv version and platform

0.30.0
macOS Catalina (10.15.1)
installed by `brew install mpv`

### Reproduction steps

Use macOS preinstalled zsh, type `mpv --` then press TAB

### Expected behavior

`zsh: do you wish to see all 972 possibilities (780 lines)?`

### Actual behavior

output this error and completion does not works.
```
generate_arguments:9: failed to load module `zsh/pcre': dlopen(/usr/lib/zsh/5.7.1/zsh/pcre.so, 9): image not found
generate_arguments:9: -pcre-match not available for regex
```

`/usr/lib/zsh/5.7.1/zsh/pcre.so` does not exist on macOS Catalina, the preinstalled zsh does not seem support PCRE.

the zsh installed by brew does not have this problem.

### PR DESCRIPTION
**Pull request by qmega**
Hopefully fixes #7240.

### CODE REVIEW

**Comment by ixearth** [comment]
I just tried, it still does not works on macOS Catalina preinstalled zsh, but does not show errors anymore.
`mpv -` TAB shows
`No matches for: `files', `media file', `URL', `URL prefix', or `file'`
and `mpv --` TAB
`No matches for: `files', `media file', `URL', `URL prefix', `corrections', or `file'`

**Comment by qmega** [comment]
Hmm. This might be a different problem from the PCRE thing.

Just to make sure: You're testing this in a fresh zsh session after replacing the script, right? If not, old stuff will be cached.

I have tested this myself now, and the script works as before on my machine (including the performance benefit of pcre when present). I also tried disabling pcre to confirm that the expressions work with the POSIX regex engine, and they do.

I guess the script isn't parsing any options out of the list on your system, but I don't know why. The only wild guess that comes to mind so far (since you said brew's version with pcre works) is that Apple provides a non-compliant implementation of POSIX regex... which kind of sounds like something Apple would do, but still doesn't feel super likely.

This needs to be debugged on your machine, I suppose. Running the contents of `generate_arguments` as a regular script with some prints along the way would be a good start, if you're comfortable with doing that. Otherwise I can try to make you a test script later.

It would be helpful to know if anyone else on Catalina had the same problem / could reproduce this. Our resident Mac people are @Akemi and @Argon-, and I believe the latter uses zsh, but AFAIK neither is using Catalina.

**Comment by Argon-** [comment]
Yes, zsh but no Catalina here. Can't upgrade atm due to software incompatibilities, unfortunately.

**Comment by ixearth** [comment]
> Just to make sure: You're testing this in a fresh zsh session after replacing the script, right? If not, old stuff will be cached.

yeah, I started a fresh zsh session after replace that script. also tried to remove `~/.zcompdump`

> Running the contents of `generate_arguments` as a regular script with some prints along the way

Just create a zsh script which contains `generate_arguments` function and `generate_arguments` ?
output:
`generate_arguments:7: command not found: --list-options`
after replace `${(@f)$($words[1]` with `mpv`, it succeed without output anything.
(both macOS zsh and brew zsh)

@qmega I would like to if you provide test script.

**Comment by qmega** [comment]
Try this: [mpv_zsh_gen_args_test.txt](https://github.com/mpv-player/mpv/files/3963167/mpv_zsh_gen_args_test.txt)
Had to upload as txt because github. Also not sure what the path for zsh on mac is, guessed /bin/zsh. Just running it with `/path/to/zsh mpv_zsh_gen_args_test.txt` should work though.

**Comment by ixearth** [comment]
macOS zsh is located at `/bin/zsh`
brew zsh is located at `/usr/local/bin/zsh` which linked to `/usr/local/Cellar/zsh/5.7.1/bin/zsh`

```
$ /bin/zsh --version
zsh 5.7.1 (x86_64-apple-darwin19.0)
$ /usr/local/bin/zsh --version
zsh 5.7.1 (x86_64-apple-darwin19.0.0)
```

[output_of_mpv_zsh_gen_args_test.txt](https://github.com/mpv-player/mpv/files/3963366/output_of_mpv_zsh_gen_args_test.txt)
both version of zsh give the same output (I have tried to edit the shebang, and diff the output)

**Comment by qmega** [comment]
Okay, progress at least. Nothing's matching the regex for an option description line. Now just to figure out why...

It's really weird that the brew version would have the same results, though. You said completion works fine with the brew version, right? Are you sure you weren't running with the system zsh both times? (That would happen regardless of the shebang if you ran it with `zsh` instead of `./whatever`.)

Let's try to narrow down what's breaking the regex.
Try this please: [regex_tests.txt](https://github.com/mpv-player/mpv/files/3963527/regex_tests.txt)

My best guess now is that `\s`/`\S` are to blame, which, though they work on my system, don't actually appear to be part of the POSIX standard based on a cursory look. The script tests some replacements for those and other little variations I thought of just to try and tease out what your system's parser doesn't like.

**Comment by ixearth** [comment]
completion works fine with the brew version, Am sure I run the the script with each zsh.

tried both edit shebang and then `./mpv_zsh_gen_args_test.sh` or `/bin/zsh mpv_zsh_gen_args_test.sh` and `/usr/local/bin/zsh mpv_zsh_gen_args_test.sh` , all of these command have the same output

the output of of regex_test.sh with each zsh also have the same output.
[output-of_regex_tests.txt](https://github.com/mpv-player/mpv/files/3963888/output-of_regex_tests.txt)

**Comment by qmega** [comment]
Okay, so it was `\s`/`\S`. I guess glibc implements them so I didn't notice that they weren't actually POSIX-compatible.

Please try the updated PR.

(The brew version doing the same thing actually makes sense, because I didn't even attempt to enable PCRE in the test scripts so both versions were using system regex. Which is fine, because that's what we wanted to test. Just wasn't thinking straight about that.)

**Comment by ixearth** [comment]
@qmega Thanks I just tried 5454c23, it works both on brew and macOS Catalina version of zsh.

**Comment by qmega** [comment]
Ready to merge, then.

Thanks for testing.

**Pull request merged**
