### PR TITLE
js: implement mp.msg.trace()

### PR DESCRIPTION
**Pull request by TheAMM**
To match the new Lua helper introduced in 1afdeee1ad8bca1c703e741002fa3b882d162968.

### CODE REVIEW

**Comment by kevmitch** [comment]
@avih pointed out on IRC that both this and 1afdeee were missing documentation. 

Does 3c4667c862dba05d89d0fd24a198bb49c8c47cb8 look acceptable? It adds documentation for both into a single commit with this PR. Was thinking about splitting it up, but thought it was getting kind of silly to have 3 commits for this.

**Comment by TheAMM** [comment]
Yap.

**Comment by TheAMM** [comment]
🤷‍♂️

**Comment by kevmitch** [comment]
merged.

**Pull request closed without merging**
