### PR TITLE
A few fixes to the vo_gpu_next options system

### PR DESCRIPTION
**Pull request by haasn**

### CODE REVIEW

**Comment by Jules-A** [comment]
Seems to have fixed https://github.com/mpv-player/mpv/issues/12227 although that's using the auto-build from this PR rather than Shinchiro's.

**Comment by dyphire** [comment]
Ah, this PR has already been merged. In fact, I would like to request that the `libplacebo-opts` option can be applied after running.
Currently, it can only be set during initialization, and cannot be applied through console commands or auto profile when the player is running.

**Comment by haasn** [comment]
To be honest, I don't know where that limitation is coming from. The vo_gpu_next code applies it per-frame, so it must be the mpv options system?

**Comment by dyphire** [comment]
> To be honest, I don't know where that limitation is coming from. The vo_gpu_next code applies it per-frame, so it must be the mpv options system?

Sorry, after using this PR for testing, I found that it works normally with `--no-config --vo=gpu-next`. So this is just a certain bug in my configuration.

**Pull request merged**
