### PR TITLE
Avoid buffering frames in the VO when using vo_mediacodec_embed

### PR DESCRIPTION
**Pull request by tmm1**
Fixes playback issues on some mediacodec hardware.

### CODE REVIEW

**Comment by wm4** [comment]
I don't appreciate the necessity for this much, but if it's the only way to prevent stalls, ok. I think this breaks display-sync, and possibly has an effect on frame dropping.

**Comment by kevmitch** [comment]
Seems like this is an exceptional case (mixed interlaced encode) and that normally, multi frame queue works fine, and as @wm4 suggests is even necessary for fully proper functionality. Is the stall you're talking about an indefinite deadlock or just a stutter? 

Sorry I'm not familiar with the intimate details of the frame queue, but would it be possible to simply drain the queue whenever one of these transitions occur?

**Comment by tmm1** [comment]
> I think this breaks display-sync, and possibly has an effect on frame dropping.

mediacodec does its own display-sync, and also drops frames itself if necessary. Neither of these seem to affect vo_mediacodec_embed.

> Is the stall you're talking about an indefinite deadlock or just a stutter?

The player deadlocks infinitely.

> Sorry I'm not familiar with the intimate details of the frame queue, but would it be possible to simply drain the queue whenever one of these transitions occur?

I'm not sure how you would manually drain the queue, nor is there an easy way to detect the interlacing change or deadlock since all that state is internal to the android decoder.

IMHO this is the best solution, and anyone using vo_mediacodec_embed in the first place realizes they are giving up advanced features already.

**Comment by kevmitch** [comment]
fair enough

**Pull request merged**
