### PR TITLE
*.py: fix some format issues in python codes, such as indent, new blank line

### PR DESCRIPTION
**Pull request by jnozsc**
previous pr https://github.com/mpv-player/mpv/pull/7354

### CODE REVIEW

**Comment by jnozsc** [comment]
cc @wm4  thanks

**Comment by wm4** [comment]
Seems to be OK. But the commit message subject line is a bit too long. Can I change it to "*.py: cosmetic changes"? Or suggest anything else.

**Comment by jnozsc** [comment]
fixed

**Comment by wm4** [comment]
OK, thanks.

**Pull request merged**
