### PR TITLE
ao_opensles: clear buffer queue in reset()

### PR DESCRIPTION
**Pull request by tomty89**
Avoid resume() from causing SL_RESULT_BUFFER_INSUFFICIENT ("Failed to Enqueue: 7" when seek or resume from pause).

I agree that my changes can be relicensed to LGPL 2.1 or later.

### CODE REVIEW

**Comment by tomty89** [comment]
Fixes #5442

**Comment by wm4** [comment]
Also CC @jeeb

**Comment by jeeb** [comment]
Thanks for the contribution. Am building it for testing until I can properly get to reviewing it :) .

**Comment by xyzz** [comment]
Wouldn't using a single buffer cause audio drop outs? e.g. if it finishes playing the buffer, fires a callback, then mpv fills the buffer with the new audio data, meanwhile it has nothing to play.

the [documentation](https://developer.android.com/ndk/guides/audio/opensl/opensl-prog-notes.html) also mentions

> For Android 4.2 (API level 17) and earlier, a buffer count of two or more is required for lower latency. Beginning with Android 4.3 (API level 18), a buffer count of one is sufficient for lower latency.

(that said, we don't and probably shouldn't support anything earlier than api level 21)

**Comment by tomty89** [comment]
@xyzz You are right, on Bluetooth audio we need to call `buffer_callback()` twice (hence `numBuffers` to be 2) so that there will be no drop out on resume from pause and old playback position (`Q`), tho these seem to be the only cases where it matters.

I am going to ditch the third commit. Before that, in case I am wrong again, do you have any justification for the `buf1`/`buf2`/`curbuf` switch? Coz I failed to see their point even with consideration of the aforementioned.

**Comment by xyzz** [comment]
If you go back to using double buffering you kind of need two buffers, right? So I'm not sure what you're asking re: the switch between curbuf/buf1/buf2.

**Comment by tomty89** [comment]
@xyzz In the original code there's a `curbuf` indicating whether buffer_callback() should use `buf1` and `buf2` in a specific call, but that doesn't seem useful to me because `ao_data_read()` and `Enqueue()` are protected by the `pthread_mutex_lock()` thing, no? (So even if I just use a `buf` instead of `buf1` and `buf2`, `buf` will never be accessed a `buffer_callback()` call before another is finished)

**Comment by xyzz** [comment]
After you pass the buffer through Enqueue it might be used in-place so if you start writing into it it will start playing the new data

**Comment by tomty89** [comment]
@xyzz Hmm I don't know. That doesn't sound right to me. I suppose I would get frequent audio jump if that were case? Yet I am not experiencing anything like that when I do two buffers with only a `buf`

I am still not entirely sure about doing two buffers, coz while it works better on Bluetooth audio, it seems to occasionally cause the same problem on wired audio that Bluetooth audio has with one buffer...Maybe I should just bail and leave everything as is :\

**Comment by xyzz** [comment]
47d5047c-a167-473b-97ec-0cc73790c396

**Comment by wm4** [comment]
Is there any reason to raise the device buffer size? (Personally I was kind of hoping to reduce the size of the AO device buffers to reduce general latency to actions like muting or pausing.)

**Comment by tomty89** [comment]
@wm4 For Bluetooth audio, as mentioned in the commit message. Also see #4672 . I am actually being very conservative on this. It doesn't seem to noticeably add latency to play/pause cycle anyway (even when on on wired audio) as long as it is less than 1000ms.

Speaking off play/pause, I find it sad that "pull" doesn't do one-to-one direct mapping to drivers' pause/resume functions. We could have avoided touching the buffer queue at all and *only* changes the SL play states between PLAYING and PAUSED if it does.

**Comment by wm4** [comment]
Yeah, but should bluetooth really affect the cases where it works? In general I'd expect the audio API to expose this somehow. But I don't know.

The pull API wasn't really written with the assumption that pausing/resuming the device API even makes sense. It can pretty much only work correctly if the read audio fragments are very tiny. That goes in hand with the audio APIs it was written for. Even if pausing were supported, we'd have no way of knowing how far playback has progressed. But if you see a way how to do this, why not. I'll probably want to remove the duplication between pull/push anyway (and port the remaining AOs like ALSA to it, maybe), which might require something like that. But in general, the separation between pull/push was meant to be like this:
- pull: the audio API does not have an API visible audio buffer and associated controls like pausing or reading current playback position, buffer is fully provided by application and the device samples from it in periodic intervals using a callback
- push: the audio API has a full, potentially huge buffer, with all necessary operations like pausing or draining, potentially requires new data in irregular intervals, and provides a way to read the current playback position to compensate for irregularities

**Comment by tomty89** [comment]
@wm4 Well IMHO Android almost makes no sense at this. AFAIK there's a way to get so-called optimal sample rate / buffer size with Java code (essential by talking to what's behind OpenSLES directly, i.e. AudioTrack / AudioManager whatsoever). Even then I am not sure whether the method will dynamically get you different values as per the current output audio device (internal/bluetooth/usb...), and whether the values are really optimal (well I mean the buffer size, the rate will be simply the final mix rate).

From the tests I've done, 200ms as device/SL buffer size is the minimum requirement for seemingly-dropout-free playback on Bluetooth audio (aptX for the record). Having soft buffer larger than 200ms (like what Termux has been doing) can work as a workaround, but on cases like play/pause, not even that could help.

As for the play/pause thing, I tried to hack the sles driver and "pull" in some nasty way (like abusing unused function names) to test the SL play state thing, it seem to work really nice (IIRC no more "pop" sound upon *both* pause and resume and lower latency). However, I don't think I know enough to overhaul this generally coz it affects other drivers.

**Comment by tomty89** [comment]
```
$ git diff audio/out/pull.c{~,}
diff --git a/audio/out/pull.c~ b/audio/out/pull.c
index fc8844a..1677f9f 100644
--- a/audio/out/pull.c~
+++ b/audio/out/pull.c
@@ -257,8 +257,8 @@ static void reset(struct ao *ao)

 static void pause(struct ao *ao)
 {
-    if (!ao->stream_silence && ao->driver->reset)
-        ao->driver->reset(ao);
+    if (!ao->stream_silence && ao->driver->pause)
+        ao->driver->pause(ao);
     set_state(ao, AO_STATE_NONE);
 }

@@ -266,7 +266,7 @@ static void resume(struct ao *ao)
 {
     set_state(ao, AO_STATE_PLAY);
     if (!ao->stream_silence)
-        ao->driver->resume(ao);
+        ao->driver->drain(ao);
 }

 static bool get_eof(struct ao *ao)
$ git diff audio/out/ao_opensles.c{~,}
diff --git a/audio/out/ao_opensles.c~ b/audio/out/ao_opensles.c
index 5357ab4..7ac3229 100644
--- a/audio/out/ao_opensles.c~
+++ b/audio/out/ao_opensles.c
@@ -220,6 +220,16 @@ static void reset(struct ao *ao)
     set_play_state(ao, SL_PLAYSTATE_STOPPED);
 }

+static void pause(struct ao *ao)
+{
+    set_play_state(ao, SL_PLAYSTATE_PAUSED);
+}
+
+static void drain(struct ao *ao)
+{
+    set_play_state(ao, SL_PLAYSTATE_PLAYING);
+}
+
 static void resume(struct ao *ao)
 {
     struct priv *p = ao->priv;
@@ -239,6 +249,8 @@ const struct ao_driver audio_out_opensles = {
     .uninit    = uninit,
     .reset     = reset,
     .resume    = resume,
+    .pause     = pause,
+    .drain     = drain,

     .priv_size = sizeof(struct priv),
     .options = (const struct m_option[]) {
$
```

**Comment by xyzz** [comment]
FWIW retrieving optimal buffer size is what we're doing in mpv-android here: https://github.com/mpv-android/mpv-android/blob/2eb7ef531da04833be895d1c4473538e0d6cd53a/app/src/main/java/is/xyz/mpv/MPVView.kt#L60

I can't test interaction with bluetooth headphones because I don't have any. Pretty weird if it requires you to set a specific buffer size - I'd expect the audio to just be delayed but maybe there's some weird interaction where mpv tries to ensure bluetooth audio is synced with the video (without being aware of it being bluetooth of course) and it causes dropouts, while a large buffer hides the issue?

**Comment by tomty89** [comment]
@xyzz Pretty sure it's some Android flaw, or maybe the aptX library (I don't have a phone without aptX support so not sure about SBC, or LDAC). The fact that on bluetooth Android doesn't feed audio to a device but an encoder might have something to do with this.

I tested with audio-only files, and I am pretty sure other Termux guys did as well, coz there's no reason to play video files on that.

Off-topic: To be honest, I don't think the optimal rate/buffer thing worth doing. It doesn't even logically make sense if you consider the fact that one doesn't always stick to the same audio device in reality. There's no way for a client to be notified that the rate has changed because of device change. On the contrary, ignoring the current optimal rate on the client side prevents any stream from being resampled twice in any case. They think they can hybridize JACK and PulseAudio, but that simply makes no sense.

**Comment by tomty89** [comment]
@xyzz Not sure if you have misunderstood btw. It doesn't require a *specific* buffer size, but *at least* 200ms (SL buffer) for seemingly-fine playback. It's not really that weird, is it? Coz if you have really low value (e.g. 20ms, 10ms...), there will dropouts on wired audio as well (probably *even when you don't* override the default 200ms soft buffer with `--audio-buffer=0`)

**Comment by xyzz** [comment]
The optimal buffer size/rate is done in mpv-android to minimize the audio latency - it increases the chance of our buffer going straight into the device/drivers without being additionally resampled by the os.

**Comment by tomty89** [comment]
@xyzz OpenSL ES / AudioTrack accepts streams at *any* rate from 8kHz to 192kHz, hence mpv will not perform resampling on audio unless you explicit instruct it to. But if you do the optimal rate thing, there can actually be cases like 44.1kHz -> 48kHz -> 44.1kHz or similar if you started playback and switch to Bluetooth/USB audio or so. In fact, the functions may not even return values *dynamically as per the current audio device where the mix is routed to*.

**Comment by tomty89** [comment]
I seem to have found some justification for the fact that Bluetooth audio needs 2 buffers and buffer size of ~200ms. The following are some logcat output captured for different audio devices:

Bluetooth Audio:
```
01-30 20:06:07.673 19693 19693 W AudioTrack: AUDIO_OUTPUT_FLAG_FAST denied by server; frameCount 16146
01-30 20:06:07.673 19693 19693 D AudioTrack: Client defaulted notificationFrames to 8073 for frameCount 16146

01-30 20:06:30.214 19736 19736 W AudioTrack: AUDIO_OUTPUT_FLAG_FAST denied by client; transfer 1, track 48000 Hz, output 44100 Hz
01-30 20:06:30.218 19736 19736 D AudioTrack: Client defaulted notificationFrames to 5862 for frameCount 17586
```
Internal Audio:
```
01-30 20:06:49.985 19838 19838 D AudioTrack: Client defaulted notificationFrames to 192 for frameCount 192

01-30 20:07:05.717 19877 19877 W AudioTrack: AUDIO_OUTPUT_FLAG_FAST denied by client; transfer 1, track 44100 Hz, output 48000 Hz
01-30 20:07:05.718 19877 19877 D AudioTrack: Client defaulted notificationFrames to 590 for frameCount 1772
```
USB Audio:
```
01-30 20:07:32.341 19953 19953 D AudioTrack: Client defaulted notificationFrames to 480 for frameCount 480

01-30 20:07:40.989 20000 20000 W AudioTrack: AUDIO_OUTPUT_FLAG_FAST denied by client; transfer 1, track 44100 Hz, output 96000 Hz
01-30 20:07:40.991 20000 20000 D AudioTrack: Client defaulted notificationFrames to 1772 for frameCount 5316
```

If you take a look at `frameCount` for the native rate of internal and USB audio, they are `notificationFrames` times `1`, that's because the tests are performed with a build of mpv having `numBuffers` set to `1`. If the value is `2` as in the current code, `frameCount` will be `notificationFrames` times `2`.

**However, if you look at `frameCount` for the native rate of Bluetooth audio, it remains as `notificationFrames` times `2`, in spite of the fact that `numBuffers` has been reduced to `1`.** This seems to show that Bluetooth audio does need at least two buffers.

Interestingly, when mpv is not on native rate of the device, `frameCount` is `notificationsFrames` times `3`; this remains true even if I bump `numBuffers` to `4` or so (and call `buffer_callback()` for that many time in `resume()`.

If you compare the `notificationFrames` of Bluetooth audio to those of internal and USB audio, you will notice that not only they are much higher, **`notificationFrames` is higher when on native rate for Bluetooth, while they are lower when on native rate for internal and USB audio. 8073 frames/samples would be equal to around 183ms for 44100Hz (the native rate of Bluetooth audio)** This more or less matches with my listening tests (150ms is definitely no-go and 200ms seems to work fine).

By the way, in reality 192 frames / 480 frames is not large enough (with `--audio-buffer=0` anyway) for dropout-free playback on internal / USB audio respectively (in spite of the value of `numBuffers`). The double of those seems alright, which make sense to be honest because **even 960 frames is just 10ms on 96000Hz**.

**Comment by tmm1** [comment]
I have no opinion on the buffer size change, but the rest of this PR looks good to me and should be merged.

If the buffer change is controversial, it could be implemented as a new option which defaults to 50ms but can easily be increased by the user.

@tomty89 I'm curious if you have buffering issues over bluetooth with the AudioTrack based driver I wrote in https://github.com/mpv-player/mpv/pull/5589

**Comment by tmm1** [comment]
> If the buffer change is controversial, it could be implemented as a new option which defaults to 50ms but can easily be increased by the user.

Oh, it's already an option.

In that case, I'm +1 on changing the default since @tomty89's argument is that a high default is the only way to deal with cases where the audio route might change to USB or Bluetooth during playback.

Consumers who know that a single route will be used can already query `AudioManager.PROPERTY_OUTPUT_FRAMES_PER_BUFFER` for that device and force the driver to use an "optimally" sized buffer.

**Comment by jeeb** [comment]
Android build finished successfully, no issues.

**Comment by Hrxn** [comment]
So #5442 can be closed?

**Pull request merged**
