### PR TITLE
command: add read-only focused property

### PR DESCRIPTION
**Pull request by guidocella**
Add a property that returns whether the window is focused, currently
only for X11 and Wayland.

My use cause for this is having an equivalent of pause-when-minimize.lua
for tiling window managers: make mpv play only while it's in the current
workspace or is focused (I'm fine with either one but prefer focus).
On X I do this by observing display-names, which is empty when the
rectangles of the display and mpv don't intersect, but on Wayland its
value doesn't change when mpv leaves the current workspace (and the same
check doesn't work since the geometries still intersect).

This could later be made writable as requested in #6252.

### CODE REVIEW

**Comment by Dudemanguy** [comment]
There's no compositor-independent way to get the focused window in wayland. You should remove that part altogether.

**Comment by guidocella** [comment]
I only needed this for Wayland though. I'll add it only to x11 as aked if you consider it useful to others, otherwise I'll patch my personal build since it works on the compositors I tested, or find some other hack to replicate the behavior I have on X of only playing while mpv is visibile, unless there's a better way to do it I'm not aware of.

**Comment by Dudemanguy** [comment]
Well one thing you could do for wayland is check the toplevel state. If the window is not active, you know for sure it's not focused. On second thought, if a window is active and has keyboard input, it's probably OK to consider it focused. I don't think it's possible for it to not be focused. This wouldn't work on clients running without any seats, but that's probably fine.

**Comment by wm4** [comment]
Generally looks OK. I think the way these attributes are passed from the VO to the frontend sucks, so I may change them all after this is merged.

You should squash these commits. The 2nd commit message can be appended to the 1st.

**Comment by Dudemanguy** [comment]
The wayland part looks fine now. Thanks.

**Comment by guidocella** [comment]
I fixed a mistake in the commit message: compositors set activated AFTER keyboard focus.

**Pull request merged**
