### PR TITLE
Adding help HotKey

### PR DESCRIPTION
**Pull request by Meeknix**
Helo
MPV is a great software and had many hotkey to change speed, move to a chapter, change subtitle, etc
But the keyboard shortcut  are not the same between some release or if you 've changed it from the conf file.
So I think it will be very helpful to have a standard hotkey (for example "h" or "?")  to show a summary page of these active shortcut.
Thanks to think about it.
MN

### CODE REVIEW

**Comment by avih** [comment]
Are you opening a pull request? Or is that a question?

I'm going to assume it's a question and not a pull request, but do correct me if I'm wrong.

The answer is that we don't have an objection to add some builtin keyboard help, but it's work and someone needs to do that, and so far no one did that.

But there's also another problem, because users can change the keys at `input.conf`, and scripts can also add key bindings. So should this help display the keys before the user (and scripts) changed them? or after?

After is probably more correct, and for that we already have some solution: run `mpv --input-test --idle --force-window` and press keys - and mpv will print what the key is bound for.

If you or someone want to open a pull request to add such help, we can look at that.

For now, the short answer is that we don't have help, but we do have `--input-test` to display what each key is bound to.

**Comment by Meeknix** [comment]
Yes I confirm this is a feature request
I note  the `mpv --input-test --idle --force-window` command 
And Ihave a question :
It's not possible to read the config file with the key binding and show it in a display after pressing a key ?
And Thank you very much for all the job
MN

**Comment by CogentRedTester** [comment]
It is of course possible with a script. I actually wrote [onehttps://github.com/CogentRedTester/mpv-search-page) some time ago which provides some basic functionality for viewing keybinds.

**Comment by avih** [comment]
> It's not possible to read the config file with the key binding and show it in a window after pressing a key

If by "the config file" you mean your own `input.conf`, then no - there is no built in command to do that.

Personally I don't think it would be a good command to add - because it's your config file, and you can open it whenever you want in an editor or print its content at the shell or display it in any other way you like - it's your file.

Also, consider that this file can be very big - many pages, with comments and empty lines etc - but only small files can fit at the mpv window.

If all you want is to print your own `input.conf` to the terminal/console when you press a key, then you can add this javascript file to you `scripts/` directory as file `print-input.js`:
```js
mp.add_key_binding("alt+i", "print-input-conf", function() {
    print(mp.utils.read_file("~~/input.conf"));
})
```

And then press `alt+i`, or change the key to any other combination you prefer.

You will need to run mpv from the terminal in order to be able to see the printout, and you will also need to have mpv with javascript support for this to work.

**Comment by Akemi** [comment]
we already have a feature request like this #2590

**Pull request closed without merging**
