### PR TITLE
[RFC] wm4 commits v2 (don't remove DVB support, optical disc support, big endian support &c.)

### PR DESCRIPTION
**Pull request by xantoz**
Same as #6127 but with some of the more controversial commits (+ commits dependent on those) removed.

### CODE REVIEW

**Comment by richardpl** [comment]
The last commit log is not safe to read for young children.

**Comment by xantoz** [comment]
@richardpl I'm not responsible for the contents of these commit messages ;-)

**Comment by haasn** [comment]
Thanks for assembling this.

@xantoz you mentioned merge conflicts. Could you please keep the wm4 commits intact and use a merge commit instead to resolve them? That way it will be clearer to reviewers what changes you specifically made.

I will be testing this PR over the coming time and report back if I run into any difficulties.

**Comment by haasn** [comment]
Found a memleak, don't know how to reproduce but should be investigatable from the leak report:

```
Blocks not freed:
  Ptr                       Bytes   C. Bytes  Name
  0x7f214c31ba90          2105512        699  ../stream/stream.c:191
  0x7f214040c0c0          2105512        821  ../stream/stream.c:191
4212544 bytes in 14 blocks.
```

**Comment by haasn** [comment]
@xantoz

> I suppose workflow would be: create new branch on top of wm4:s mpv_backup master, remove everything but the wanted commits (this includes removing commits that have already been merged to mpv master), then merge.

You don't need to remove duplicate commits. But yes, that's more or less it. Another option to consider would be using `git revert` on top of wm4's master, that way you don't have to cherry-pick anything.

**Comment by haasn** [comment]
Okay, I found a reproducing case: Open `https://youtu.be/7YatZu1GVmE` and exit the file once it's loaded and playback start. Works with `--no-config`.

I'll see if I can get it fixed.

**Comment by haasn** [comment]
Huh? Investigating the leak I can't for the life of me seem to observe it actually being allocated. I put a breakpoint on the allocation and printed out every return value and it never returns the address that it eventually complains about.

**Comment by haasn** [comment]
Fortunately, it being reproducible means I can bisect:

```
c3f7b7bd04b348aebe61896dc3c9c2fcab2c4b3e is the first bad commit
commit c3f7b7bd04b348aebe61896dc3c9c2fcab2c4b3e
Author: wm4 <wm4@nowhere>
Date:   Sat May 19 14:41:06 2018 +0200

    demux: get rid of free_demuxer[_and_stream]()
    
    Them being separate is just dumb. Replace them with a single
    demux_free() function, and free its stream by default. Not freeing the
    stream is only needed in 1 special case (demux_disc.c), use a special
    flag to not free the stream in this case.

:040000 040000 13e7610f62de3e47050af02cf931f97722a12ff1 fd0950629b092d208d62090d58fb075fb6391ad9 M	common
:040000 040000 d0f2bdfdeb5bf7dcdabcd37dcdf916abfe78da0a cd5fe32ad91a63a0bf5efd30583d7b6ebc3c0743 M	demux
:040000 040000 dab4845b56cf8a5a100d356adb35f2e097e65e3e d5de8ecbb5e268c9696a472ad63468a69a5ee7aa M	player
```

**Comment by haasn** [comment]
I've pushed a fix to https://github.com/haasn/mpv/commits/wm4_commits

Not sure how we want to organize this. But probably if xantoz ever wants to update his branch (using a merge commit), he can cherry-pick that. (Or I could take over the PR?)

**Comment by xantoz** [comment]
Note to self: Currently this version doesn't update the libmpv version correctly (should be 1.103) and some parts in interface-changes.rst and client-api-changes.rst need to be moved up to 0.30 and 1.103 respectively.

**Pull request closed without merging**
