### PR TITLE
waf update to 1.8.7 and SHA256HASH update

### PR DESCRIPTION
**Pull request by perfect7gentleman**

### CODE REVIEW

**Comment by wm4** [comment]
Is there any specific reason why we should update now?

**Comment by perfect7gentleman** [comment]
the latest and the stable

**Comment by pigoz** [comment]
We should definitely update, but not before 0.9

**Comment by wm4** [comment]
It's outdated by now.

**Comment by perfect7gentleman** [comment]
1.8.12 is out

**Pull request closed without merging**
