### PR TITLE
cocoa-cb: fix hang when flush() isn't on main queue

### LINKED ISSUE #10276: gl_layer.swift crashes with CA_ASSERT_MAIN_THREAD_TRANSACTIONS
### Important Information

mpv 7ff4a27eb600dc01d20547880056c13d6cf3e9e7 built locally on macOS 12.4 (21F79)

### Reproduction steps

Play a file with `CA_ASSERT_MAIN_THREAD_TRANSACTIONS=1` (This env var is set automatically by Instruments on Xcode 14, so it'll soon be required for profiling).

### Result

This crashes with this abbreviated log:

```
Application Specific Information:
CoreAnimation: CA_ASSERT_MAIN_THREAD_TRANSACTIONS is set and an implicit transaction wasn't created on a main thread.
abort() called

[...]

Thread 10 Crashed::  Dispatch queue: io.mpv.queue.draw
0   libsystem_kernel.dylib        	       0x189f6ad98 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x189f9fee0 pthread_kill + 288
2   libsystem_c.dylib             	       0x189eda340 abort + 168
3   QuartzCore                    	       0x19107db94 CA::CA_ABORT_ON_NON_MAIN_THREAD_TRANSACTION_PUSH() + 28
4   QuartzCore                    	       0x190ee4fa4 CA::Transaction::push(bool) + 432
5   QuartzCore                    	       0x19107de28 CA::Transaction::ensure_implicit(bool) + 296
6   QuartzCore                    	       0x190eeb100 CA::Layer::begin_change(CA::Transaction*, unsigned int, objc_object*, objc_object*&) + 84
7   QuartzCore                    	       0x190ef0184 -[CALayer setContents:] + 132
8   QuartzCore                    	       0x190f9a8e0 CAOpenGLLayerEnsureQueue(CAOpenGLLayer*) + 184
9   QuartzCore                    	       0x190f9a160 CAOpenGLLayerDraw(CAOpenGLLayer*, double, CVTimeStamp const*, unsigned int) + 140
10  QuartzCore                    	       0x190f99ee8 -[CAOpenGLLayer _display] + 584
11  mpv                           	       0x1048f11f0 GLLayer.display() + 96 (gl_layer.swift:219)
12  mpv                           	       0x1048f1354 @objc GLLayer.display() + 28
13  mpv                           	       0x1048e693c thunk for @escaping @callee_guaranteed () -> () + 28
14  libdispatch.dylib             	       0x189dda5f0 _dispatch_call_block_and_release + 32
15  libdispatch.dylib             	       0x189ddc1b4 _dispatch_client_callout + 20
16  libdispatch.dylib             	       0x189de38a8 _dispatch_lane_serial_drain + 668
17  libdispatch.dylib             	       0x189de4404 _dispatch_lane_invoke + 392
18  libdispatch.dylib             	       0x189deec98 _dispatch_workloop_worker_thread + 648
19  libsystem_pthread.dylib       	       0x189f9c360 _pthread_wqthread + 288
20  libsystem_pthread.dylib       	       0x189f9b080 start_wqthread + 8
```

I can work around this like so:
```
diff --git a/video/out/mac/gl_layer.swift b/video/out/mac/gl_layer.swift
index 6c48004f4f..21e735857b 100644
--- a/video/out/mac/gl_layer.swift
+++ b/video/out/mac/gl_layer.swift
@@ -82,8 +82,6 @@ class GLLayer: CAOpenGLLayer {
     enum Draw: Int { case normal = 1, atomic, atomicEnd }
     var draw: Draw = .normal
 
-    let queue: DispatchQueue = DispatchQueue(label: "io.mpv.queue.draw")
-
     var needsICCUpdate: Bool = false {
         didSet {
             if needsICCUpdate == true {
@@ -229,7 +227,7 @@ class GLLayer: CAOpenGLLayer {
 
     func update(force: Bool = false) {
         if force { forceDraw = true }
-        queue.async {
+        DispatchQueue.main.async {
             if self.forceDraw || !self.inLiveResize {
                 self.needsFlip = true
                 self.display()

```

But I'm not sure if everything in `display()` should be on the main thread, or if some of the non-CoreAnimation stuff should be run elsewhere. Any thoughts, @Akemi?

### LINKED ISSUE #10579: mpv freezes on macOS Ventura beta 13.0 Beta 5 (22A5331f) after update
Hi there, 
just updated yesterday my macbook pro with the new macOS Ventura 13.0 Beta 5, version 22A5331f….and  Im using the mpv 0.34.1 and it’s freezing my mac as soon as I start watching a movie with it….
I’ve been using mpv for years and yesterday I was on macOS Ventura 13 Beta 4….so something changed  the behavior of mpv 0.34.1 as Apple continues to update macOS Ventura….mpv  freezes the image and keeps freezing completely the mac when on fullscreen after a few seconds of starting a movie or something....
I removed mpv, reinstalled  it, removed the mpv.config, same thing happened... installed it with Homebrew and continues to  freeze all the time…have to close mpv because snowballs and freezes…

Please, can anyone be kind to help me with this issue?

A attached my log file link + a vid of the issue
Thanks in advance

Video:
https://user-images.githubusercontent.com/112277451/187046269-51030d5a-574a-4c90-bf2c-388958c912f3.mp4

 
mpv log file:
https://drive.google.com/file/d/1lmsPRHSq-80qK0YZeZ_W_LslPzNHdQ-K/view?usp=sharing

### PR DESCRIPTION
**Pull request by Coeur**
Fix #10276.
Fix #10579.

### CODE REVIEW

**Comment by Akemi** [comment]
this will cause other problems, like hanging on resize, timely close events that are grouped + dispatched like that, abominable render performance (in cases), probably more.

see my tests here: https://github.com/Akemi/macos_precise_timing_tests

im pretty sure, the flush is not what needs to be done on the main queue but the redrawing of the UI (eg the none flush() part within the display() function). the sad part is, it can't really be separated with the shitty CAOpenGLLayer. i have something on my mind how it could be done, but that would need testing.

on a side note, what we have atm was never intended by Apple like this and was a workaround to make opengl rendering less shitty, but i explained that pretty much extensively years ago. this worked for the longest part, but i guess nothing will last forever. if Apple killed it now, which i could understand because it's against their intention, best practice and architecture, we are going to either have a big problem, need to find a different way to accomplish the same performance, or have to hope for me to get my ass moving on the MoltenVK/Vulkan backend.

for the first remark, we will go a big step backwards in render performance and usability if Apple didn't fix alle the other problems we had prior to this backend. i doubt Apple did fix anything in that regard but i will let myself be surprised.
for the second remark, i can only see one other possibility to work around this and try to separate rendering and UI drawing. this might introduce some regression in the eye candy department.
for the third remark, it's basically done but heavy time constraints on my end just killed the progress. anyway, since the new render mechanism works on any thread this would not be a problem anymore.

shit situation but it was kinda expected that Apple might kill this at some point, like other things prior.

my recommendation is not to merge this like this. it does fix the problem but will most likely cause several other problems. i would wait for the golden master or actual release and see if Apple will revert the change causing the hang. that will buy us some time to look into other possibilities to fix this problem. the issue about profiling is shit, but a bit less important than actual playback being broken.

**Comment by Coeur** [comment]
You're right, let's wait a bit. I opened a Feedback Assistant for this.

**Comment by Coeur** [comment]
Seems "Apple will revert the change causing the hang"

**Comment by Coeur** [comment]
Apple fixed the hang in Beta 8.

**Comment by MrCrispyBacon** [comment]
@Coeur…. Go fuck yourself… you bitch!
Just update the damn mpv and move on!!!!
Overdramatic, me??? Im being complaining about this issue  for months and you waiting seating on your arse doing nothing to fix it…excuses that’s what you have!!!

**Pull request closed without merging**
