### PR TITLE
vo_lavc: set frame rate on encoder

### LINKED ISSUE #11215: Nonconforming output when reencoding video
### Important Information

- mpv 9b59d39a3ab64da0e9489ee4ce2062d4503e7cc5
- macOS 13.2 (22D49)
- Local build

### Reproduction steps

Use mpv to reencode a 24fps 1080p video to H.264.

### Expected behavior

The resulting video stream should have a reasonably sane level (i.e. between 4.0 and 5.2) and decode properly on all conforming hardware.

### Actual behavior

The resulting stream has its level tagged as 6.2, and produces decode errors and corruption on many hardware decoders (including the AVD decoder in modern Macs).

This can be mitigated by explicitly setting e.g. `--ovcopts-add=level=52`. The level seems to be set to 6.2 internally by x264 because vo_lavc:
- sets the time base to 1/24000
- doesn't set `ticks_per_frame`
- doesn't set `framerate`

So libavcodec's libx264 wrapper sets the frame rate to 24000, which of course results in an expected macroblock rate far higher than what's supported by any normal H.264 level.

I think the simplest solution here is to set a frame rate, but I'm not sure how vo_lavc can determine that. Maybe just set it to 60 for now, since it's better than the current behavior? This does indeed seem to work around the issue for me.

### Log file

https://gist.github.com/f4db31426d6c768909042bbd4476bfa4

### Sample files

This repros with a variety of inputs.

### PR DESCRIPTION
**Pull request by rcombs**
Fixes #11215.

ffmpeg was internally defaulting to 24000fps, which resulted in encoders selecting inappropriate levels and making poor ratecontrol decisions.

### CODE REVIEW

**Comment by sfan5** [comment]
Do you have more info about the implications of setting this?
I grepped libavcodec for `avctx->framerate` and e.g. rav1e or vaapi claim to use it for rate control. So should indeed not be so bad if a "wrong" value is set there.

> the impact on e.g. 120fps media shouldn't be any worse than what we already had

What *is* the impact on 120fps media? Does that patch change it at all?

**Comment by rcombs** [comment]
It's basically used for ratecontrol and to set e.g. the H.264 level. Previously, we'd set an extremely high level and have weird ratecontrol implications from the configured frame rate being far too high (24000); now, it'll be in the right general ballpark for most stuff (ranging from ~3x to ~0.5x for common frame rates).

This probably can't cause anything _too_ screwy when the configured rate is too high, but when it's too low (e.g. 120fps content) we might end up setting an H.264 level (and HRD parameters) lower than what's actually needed to decode our file. This would only affect hardware decoders, though, and those handled our output extremely poorly regardless of frame rate before this change, so I think it's a strict improvement.

All that said, if you have any clue how vo_lavc can get an actual accurate frame rate estimate for this, I'm all ears.

**Comment by sfan5** [comment]
I searched a bit and `--oautofps` used to determine the timebase via `mpi->nominal_fps` (before it was removed in f18c4175ad8e772c0005ac6280291af425c16cc2) and the following seems to do what you want:
```diff
     if (rates && rates[0].den)
         tb = rates[av_find_nearest_q_idx(tb, rates)];
 
+    encoder->framerate = av_d2q(img->nominal_fps, 65535);
     encoder->time_base = av_inv_q(tb);
 
     if (!encoder_init_codec_and_muxer(vc->enc, on_ready, vo))
```

> This would only affect hardware decoders, though, and those handled our output extremely poorly regardless of frame rate before this change

FWIW I produced one of those H.264 L6.2 encodes in mpv and it worked fine on my AMD GPU, my phone (mediacodec/Exynos) and a random Intel iGPU.

**Comment by rcombs** [comment]
Thanks, that seems to work well! I've re-pushed with that change.

How badly hardware decoders screw up with the existing code seems to vary depending on resolution, content, ratecontrol settings, and specific hardware; I've seen anything from dropped frames to bizarre motion blocking artifacts.

**Comment by sfan5** [comment]
Suggestion (not sure whats the purpose of that `* 1001 + 2`)
```diff
diff --git a/video/out/vo_lavc.c b/video/out/vo_lavc.c
--- a/video/out/vo_lavc.c
+++ b/video/out/vo_lavc.c
@@ -134,6 +134,10 @@ static int reconfig2(struct vo *vo, struct mp_image *img)
 
     encoder->time_base = av_inv_q(tb);
 
+    // Typically used for rate control with no wider implications if set wrong.
+    if (img->nominal_fps > 0)
+        encoder->framerate = av_d2q(img->nominal_fps, 65535);
+
     if (!encoder_init_codec_and_muxer(vc->enc, on_ready, vo))
         goto error;
 
```

**Comment by rcombs** [comment]
The 1001 is so that NTSC fractional rates, e.g. 24*1000/1001, yield reasonable results. 65535 isn't an absurd default, but the 1001 means that we have a decent chance of getting the exact value back even if there's been some float rounding. I got the idea from the commit you linked.

**Comment by sfan5** [comment]
I got the idea with 65535 from the time_base code talking about limits in mpeg-2. I suppose either way is fine.

**Review by sfan5 — APPROVED** [review]

**Comment by chainikdn** [comment]
This kinda breaks encoding with Vapoursynth filter enabled, cause it doesn't set "nominal_fps" value for the output frames.
Suggestion:
```
static void VS_CC vs_frame_done(void *userData, const VSFrameRef *f, int n,
                                VSNodeRef *node, const char *errorMsg)

        if (img.pkt_duration < 0)
            MP_ERR(p, "No PTS after filter at frame %d!\n", n);
+        else img.nominal_fps = 1.0/img.pkt_duration;
        res = mp_image_new_copy(&img);
```

**Comment by sfan5** [comment]
Break in what way?
Before this change it will have used 24000fps, which isn't correct either.

**Comment by chainikdn** [comment]
_before_ we could make things right by manually settings time_base via ovcopts
_now_ when encoder->framerate is set, time_base is just ignored

**Comment by sfan5** [comment]
oh, I see.
If you want to propose that change please open a PR.

**Pull request merged**
