### PR TITLE
core terminal: fix #5833 : catch \033 alone (ESC.) when buffer contains nothing else

### LINKED ISSUE #5833: esc. key does not work instantly in console
### mpv 0.27.2 with linux, Xorg
(because 0.28.2 depends on ffmpeg4, which is hard blocked in gentoo)

### Reproduction steps
1. under linux and Xorg, open a terminal (sakura in my case)
2. edit mpv/input.conf to bind an action to ESC in console for instance add this line:
`ESC quit`
3. play a file in console, for instance:
`mpv --no-video file.mp3`
4. press [Esc.] key.

### Expected behavior
This should work. (quit for instance)

### Actual behavior
User has to press [Esc.] twice, or hold it an instant before expected action occurs.
(Due to linux terminals, delaying escape key presses so as to catch special keycodes AFAIK.)

### Log file
https://0x0.st/seuk.txt

### PR DESCRIPTION
**Pull request by Arnaudv6**

### CODE REVIEW

**Comment by CounterPillow** [comment]
What happens if the buffer contains `\033` twice? To me it seems like this would just be thrown away entirely with this change.

**Comment by avih** [comment]
As I'm sure you know, it's possible that an escape sequence is not read whole in one read, such that `\033` arrives in one read, and the rest of the sequence in followup reads. This especially can happen when the terminal runs a remote application (e.g. using ssh). In such case, we do not want to interpret the beginning of the sequence as a single key press of the ESC key.

The traditional way to handle it is to use some timeout which triggers a single ESC keypress only if some time elapsed and a continuation of the sequence did not arrive.

Does your code handle it?

**Comment by Arnaudv6** [comment]
@avih: agreed, thanks, good catch! forgot that case.  
This could take me forever to get right: if you feel like it, your help is more than welcome.

I think we have an choice here, either:

- setting VTIME to 3 (usual timeout for such case is 2.5 I think)
  at the cost of running polling loop 3.3 times a second
- having both dedicated timeout and dedicated polling code for when [`e`](https://github.com/mpv-player/mpv/blob/caa5d8170efdc2f229d4e2ae0251a6d29880966e/osdep/terminal-unix.c#L207) starts with \033.

I can't say which is better?

**Comment by avih** [comment]
Sorry, I'm not familiar with the implementation details. As for choosing a timeout, I think 100-250 ms would be reasonable. I think 330 ms is too much.

**Comment by Arnaudv6** [comment]
Thanks @avih, I'll take that to devel IRC ASAP.

**Comment by wm4** [comment]
Superseded by commit 6023843, which uses a timeout to disambiguate.

**Pull request closed without merging**
