### PR TITLE
playlist: improve shuffle algorithm

### PR DESCRIPTION
**Pull request by haasn**
The old algorithm produced results which were not uniformly distributed,
i.e. some particular shuffles were preferred over others.

The new algorithm is an implementation of the Fisher-Yates shuffle which
is guaranteed to shuffle uniformly given a sufficiently uniform rand()
and ignoring potential floating-point errors.

### CODE REVIEW

**Comment by wm4** [comment]
Merged with cosmetic changes.

**Comment by rossy** [comment]
It would be nice if msvcrt had a decent rand(). I wonder if it's worthwhile using av_lfg.

**Comment by haasn** [comment]
I think the limiting factor of playlist shuffling is the user's ability to appreciate true randomness, rather than statistical biases in the PRNG.

Maybe --playlist-shuffle should actually try to mix the order up as much as possible (and avoid repeating itself) rather than generating a random order?

**Comment by Hrxn** [comment]
..Or the user's ability to appreciate such over-engineering.

(Please disregard if the old shuffle was really *that* bad)

;-)

**Pull request closed without merging**
