### PR TITLE
DOCS/options: add example for custom pitch correction filter

### PR DESCRIPTION
**Pull request by llyyr**
Apparently this isn't so obvious. I would know.

### CODE REVIEW

**Comment by DanOscarsson** [comment]
In chromium where the code is from they removed muting later on (I think that change said the sound was good enough).
Why not remove it here too?
I deleted it in my version of mpv long ago and it works fine.
I see no need of being able to mute audio at some speeds.
At least the default should be like min=0 and max=10000 so it is turned of
by default.

**Comment by llyyr** [comment]
I don't think there's any point to playing audio at such high speeds, and it causes issues with `video-sync=display-resample` stalling down to a crawl due to scaletempo2 at really high speeds. It's better to just mute the audio in that case. And it's more visible for users to modify the limit now anyway, so I think this is fine.

**Comment by DanOscarsson** [comment]
While I seldom play faster then 6 times, audio could be good for faster speeds as you can hear some relation to where your are in the video. Maybe change muting to speed=16 as a default?
While I use a modified video sync compared to standard display resample in my version of mpv, the problem with fast playing is not audio but how fast the video can be decoded.
When video frames cannot be played fast enough a/v-sync will get out of sync.

**Review by Dudemanguy — APPROVED** [review]
No strong opinions on what the max value should be, but apparently 4 is too low so seems fine.

**Pull request merged**
