### PR TITLE
ad_spdif: set codec params

### PR DESCRIPTION
**Pull request by kasper93**
It seems that we decode small portion of the audio to determine codec params. We can remember that information.

Fixes: #14178

### CODE REVIEW

**Comment by kasper93** [comment]
@mitzsch: Could you test this to see if it is what you expect?

**Comment by mitzsch** [comment]
Thanks for your work!
Unfortunately, I´m off my AVR system again for some time - so I can only test with -ao=null.

It now shows => 
image
or
image

So it now shows the codec (nice!) but not the profile. Would it be possible now to also show the profile?

image

**Comment by kasper93** [comment]
Updated, there was not so correct assumption, that got outdated over the years.

**Comment by mitzsch** [comment]
Perfect! Works!!!

image



Edit: On DTSX Files it only show DTS-HD MA (same file)

image


image

**Comment by kasper93** [comment]
To little data is decoded while probing probably. But since, the decoding anything in the first place is not that great, I doubt this will change. Unless it is required for proper playback.

Also maybe just in case it is in fact detected, it would be good to add those profiles. But since it is not detected anyway. I would not change that, unless there are playback issues.
```
diff --git a/audio/decode/ad_spdif.c b/audio/decode/ad_spdif.c
index 3f83ab240e..0f0252cb83 100644
--- a/audio/decode/ad_spdif.c
+++ b/audio/decode/ad_spdif.c
@@ -231,6 +231,8 @@ static int init_filter(struct mp_filter *da)
     case AV_CODEC_ID_DTS: {
         bool is_hd = profile == AV_PROFILE_DTS_HD_HRA ||
                      profile == AV_PROFILE_DTS_HD_MA  ||
+                     profile == AV_PROFILE_DTS_HD_MA_X  ||
+                     profile == AV_PROFILE_DTS_HD_MA_X_IMAX  ||
                      profile == AV_PROFILE_UNKNOWN;

         // Apparently, DTS-HD over SPDIF is specified to be 7.1 (8 channels)
```

**Review by sfan5 — APPROVED** [review]
code lgtm

**Comment by mitzsch** [comment]
> To little data is decoded while probing probably.

Ok, I see, but I guess it's fine with the new state introduced by this commit. Having it to show the codec + profile is a nice addition. Thanks! :)

**Pull request merged**
