### PR TITLE
vo_gpu_next/context: receive underlying API structs from libplacebo

### PR DESCRIPTION
**Pull request by jeeb**
Functions to receive the underlying vulkan,gl,d3d11 structure were
added in libplacebo version 4.182. Our current requirement for
gpu-next is 4.190, and thus we can freely utilize these helper
functions.

This conveniently also lets us get rid of related compiler warnings
about unused variables in case of opengl and d3d11 being disabled
in mpv/libplacebo.

### CODE REVIEW

**Comment by ValZapod** [comment]
Can we default  --target-trc=pq --target-prim=bt.2020 if RGB_FULL_G2084_NONE_P2020 is slected? I mean IT IS THAT dumb. I verified it the same color and brigtness with LG C9, so... Of course some HDR photos CAN be arranged.

**Comment by Obegg** [comment]
> Can we default  --target-trc=pq --target-prim=bt.2020 if RGB_FULL_G2084_NONE_P2020 is slected? I mean IT IS THAT dumb. I verified it the same color and brigtness with LG C9, so... Of course some HDR photos CAN be arranged.

I agree, it should be the default.
libplacebo was supposed to get rid of spam on mpv.conf (I remember something along those lines from haasn)

**Comment by ValZapod** [comment]
> mean IT IS THAT dumb

Also, of course that perfect HDR is not in any way affected by SDR slider in HDR menu of windows 11. While WCG content is affected in chrome and desktop too.

**Comment by jeeb** [comment]
@ValZapod First of all, you are once again off-topic. The closest to this topic of this PR is the fact that it is about gpu-next. Please stop. At best you are annoying people (including me) by doing it.

@Obegg same request for you, too.

I thought I wrote things simply enough, but let me just quote the relevant bits for you since you seem to have ignored them:

> As a **manual hack** HDR passthrough _might_ work with target-trc/primaries set to PQ/BT.2020  (if gpu-next supports that) with `d3d11-output-csp=pq`. Then of course when libplacebo gains similar swap chain color space features, just the hinting feature will suffice.

1. Manual hack (**workaround**)
2. I have to put the same swap chain color space code that is in mpv right now into libplacebo for the hinting feature to work that haasn has in libplacebo/gpu-next. It is currently only supported with Vulkan, since that's what haasn cares about.

I thought what I wrote was pretty clear enough, but apparently not. If you wish to discuss HDR somewhere, _don't do it here_.

**Comment by jeeb** [comment]
@sfan5 nicely tested this with OpenGL as well, and it did not break for him, as well as I got some nice comments on the commit message :)

Thus, I'll be puling this in soon.

**Pull request merged**
