### PR TITLE
vo_opengl: set uniform variable "pixel_size" for internal shaders

### PR DESCRIPTION
**Pull request by igv**

### CODE REVIEW

**Comment by wm4** [comment]
What for?

And if it's an optimization, what's the gain?

**Comment by igv** [comment]
Not much actually, around 2% on an Intel HD 3000.

**Comment by wm4** [comment]
Instead of opening and closing pull requests all the time, can you just repush the branch? Github will update the PR.

**Comment by igv** [comment]
this is the last one, sorry I'm new to git

**Comment by haasn** [comment]
Instead of `texture(tex, base + vec2(x, y) * pixel_size)` you can also use `textureOffset(tex, base, ivec2(x, y))`.

IMO I wouldn't worry too much about micro-optimizing NNEDI3, since there are MUCH more important optimizations to make.

**Comment by wm4** [comment]
Merged.

**Pull request closed without merging**
