### PR TITLE
ao_opensles: buffer fixes for Android O

### PR DESCRIPTION
**Pull request by tomty89**
Please see the commit messages for details.

### CODE REVIEW

**Comment by sfan5** [comment]
two things:
* According to @xyzz the second buffer was added since it "should help to get lower latency on some devices.", are you sure it shouldn't be kept?
* You should not the removal of `opensles-sample-rate` in DOCS/interface-changes.rst

**Comment by tomty89** [comment]
@sfan No offense but you tell me. Neither do I see any logic in that, nor I ever had such experience. Though I've only been using mpv on OpenSLES / Android since Android N, so I can't speak for older versions.

There is only one thing that can help to get you lower latency when work with OpenSLES: make sure the track is on sink rate. OpenSLES always create AudioTrack instance with low latency flag (that's why I included `.setFlag(256)` even when it only has effect on wired sinks). Even when the track is not on sink rate, it will still be routed to the fast mix path (as opposed to the "deep buffer" path, which is the default path for tracks created with Java, and probably JNI as well). This is not just my theory / guess but facts can be clear seen in logcat messages.

When the track is on sink rate, the buffer size is allowed to be exceptionally low

Internal:
```
Sink rate: 48000 Hz
44100 Hz: 1772 frames (40.18 ms)
48000 Hz: 192 frames (4.00 ms)
88200 Hz: 3536 frames (40.09 ms)
96000 Hz: 3848 frames (40.08 ms)
176400 Hz: 7064 frames (40.05 ms)
192000 Hz: 7688 frames (40.04 ms)
```

USB:
```
Sink rate: 96000 Hz
44100 Hz: 1772 frames (40.18 ms)
48000 Hz: 1928 frames (40.17 ms)
88200 Hz: 3536 frames (40.09 ms)
96000 Hz: 480 frames (5.00 ms)
176400 Hz: 7064 frames (40.05 ms)
192000 Hz: 7688 frames (40.04 ms)
```

That said, the value may actually be too low to be used as SL Enqueue size. (For the record they are the same as the period size of the ALSA device.) In my experience, doing more than one buffer on the SL layer does not help in such case (with our driver implementation, at least), while doubling the size does (it's still just 8ms / 10ms.)

**Comment by tomty89** [comment]
For you reference, these are what will happen when the track is routed to the deep buffer path (`.setFlags(256)` omitted), which will *never* happen when you work with OpenSLES:

Internal:
```
Sink rate: 48000 Hz
44100 Hz: 5304 frames (120.27 ms)
48000 Hz: 5772 frames (120.25 ms)
88200 Hz: 10596 frames (120.14 ms)
96000 Hz: 11532 frames (120.13 ms)
176400 Hz: 21180 frames (120.07 ms)
192000 Hz: 23046 frames (120.03 ms)
```
(Actually the sink rate is 192kHz but not 48kHz, I can give more details on that if anyone is interested.)

USB:
```
Sink rate: 96000 Hz
44100 Hz: 1772 frames (40.18 ms)
48000 Hz: 1928 frames (40.17 ms)
88200 Hz: 3536 frames (40.09 ms)
96000 Hz: 3844 frames (40.04 ms)
176400 Hz: 7064 frames (40.05 ms)
192000 Hz: 7688 frames (40.04 ms)
```

**Comment by sfan5** [comment]
> No offense but you tell me. Neither do I see any logic in that, nor I ever had such experience. 

I wasn't saying you were wrong, just asking.
I haven't worked on any of the audio code in mpv myself, so maybe @xyzz can comment on the decision to use multiple buffers.

**Comment by xyzz** [comment]
I mentioned this in https://github.com/mpv-player/mpv/pull/5443#issuecomment-360311222 I don't have anything else to add at the moment.

**Comment by tomty89** [comment]
Yeah I decided to withdraw similar patch because two-buffer seem to have helped in Bluetooth audio *for some cases* (as I mentioned in the comment following that), but two-buffer didn't even work really well in Android N for wired sinks AFAIR, and it does not help in Bluetooth audio anymore when it comes to Android O, only problematic for all types of sinks.

**Comment by tomty89** [comment]
I further added this patch:
```
diff --git a/audio/out/ao_opensles.c b/audio/out/ao_opensles.c
index 773cc23983..7b398a3cc4 100644
--- a/audio/out/ao_opensles.c
+++ b/audio/out/ao_opensles.c
@@ -40,6 +40,7 @@ struct priv {
     pthread_mutex_t buffer_lock;

     int cfg_frames_per_buffer;
+    int cfg_number_of_buffers;
 };

 static const int fmtmap[][2] = {
@@ -128,6 +129,8 @@ static int init(struct ao *ao)

     locator_buffer_queue.locatorType = SL_DATALOCATOR_BUFFERQUEUE;
     locator_buffer_queue.numBuffers = 1;
+    if (p->cfg_number_of_buffers)
+      locator_buffer_queue.numBuffers = p->cfg_number_of_buffers;

     pcm.formatType = SL_DATAFORMAT_PCM;
     pcm.numChannels = 2;
@@ -208,7 +211,11 @@ static void reset(struct ao *ao)
 static void resume(struct ao *ao)
 {
     struct priv *p = ao->priv;
-    buffer_callback(p->buffer_queue, ao);
+    if (p->cfg_number_of_buffers)
+      for (int i=0; i<p->cfg_number_of_buffers; i++)
+       buffer_callback(p->buffer_queue, ao);
+    else
+      buffer_callback(p->buffer_queue, ao);
 }

 #define OPT_BASE_STRUCT struct priv
@@ -224,6 +231,7 @@ const struct ao_driver audio_out_opensles = {
     .priv_size = sizeof(struct priv),
     .options = (const struct m_option[]) {
         OPT_INTRANGE("frames-per-buffer", cfg_frames_per_buffer, 0, 1, 96000),
+        OPT_INTRANGE("number-of-buffers", cfg_number_of_buffers, 0, 1, 8),
         {0}
     },
     .options_prefix = "opensles",
```
And no stutter occur when `cfg_number_of_buffers` is larger than 1. The only side effect when it's large than 1 is, if I seek quickly I will hear silence during the process instead of constant audio jumps.

If anyone thinks this is good/necessary, I can include it in the pull request.

Btw @jeeb

**Comment by tmm1** [comment]
This diff looks reasonable to me, and works as expected on my device.

**Comment by tomty89** [comment]
I would include it in the PR only if that's the price to get the one-buffer commit upstream though.

**Comment by jeeb** [comment]
Sorry for taking a while to respond to a lot of things, real life is a pain in the backwards inside, and most of the time you just want to be entertained after having fired up your brain for most of the working week.

As for the multiple buffers case, the documentation did note that for the older versions of Android, so that is not hard requirement since f.ex. mpv-android doesn't support those older Android versions, anyways (the GPU renderer basically worked on zarro Android 4.4.4 devices when we still had those supported).

As far as I can see the patch you attached just sets that there's two layers of queued buffers on the OpenSL ES side while both point towards the same internal buffer. That... really doesn't seem to make too much sense. So no, that that is not required for upstream to take the patch in.

Looking at the [OpenSL ES specification 1.0.1](https://www.khronos.org/registry/OpenSL-ES/specs/OpenSL_ES_Specification_1.0.1.pdf), it does say that `slBufferQueueCallback` is a:
> Callback function called when a buffer is dequeued from the buffer 
queue.

Thus I would take this as the buffer wouldn't get re-used afterwards by the implementing side. The only problem could be if the callback could take longer to complete than for the samples to get out of the audio device, thus creating stalls.

Also if we want a proper queue of buffers we should utilize such, although entries from even as far as 2012 seem to suggest that two works for most, and three could be useful for a limited set of devices ([source](https://groups.google.com/d/topic/android-ndk/hLSygQrmcPI)), although that seems to generally be about recording - not playback.

Will give this a whirl and LGTM this if it works on my device since it seems to work for @tmm1 as well.

**Comment by jeeb** [comment]
From 8.12 in the spec, you get the following points too:
> * The buffers that are queued ar
e used in place and are not required to be copied by the 
device, although this may 
be implementation-dependent. The application developer 
should be aware that modifying the content 
of a buffer after it has been queued is 
undefined and can cause audio corruption. 
> * _Once an enqueued buffer has finished playing, as notified by 
the callback notification, it 
is safe to delete the buffer or fill the buffer with new data and once again enqueue the 
buffer for playback._

So yes, while it is not kosher to touch the data after enqueuing it, after you get the callback for the buffer it's very much kosher to start using it.

**Comment by jeeb** [comment]
Was finally able to briefly test it around and it works. I'm still wondering /why/ this fixes issues for someone, and having multiple buffers in a queue totally is something I'd like to have - but on my 6.0 device I don't see any issues either way.

If we start having single-buffer related stalls we will have to see if we can make a proper configurable buffer queue thing from which you pop and to which you push things.

**Comment by tomty89** [comment]
@jeeb it appears to me that somehow when we do multiple buffers on Android O, the first `buffer_callback()`/`Enqueue()`called in `resume()` kicks off the playback, but somehow subsequent calls seem to block the playback.

Say we do two 250ms buffers, it will stall for 0.25s after the first buffer is played; if we do eight, it will stall for 1.75s.

I found a workaround for that, which is to have the soft buffer size set to the total size of the device buffers we do. I have no idea why it works though, coz I don't think there was such a problem when I was on Android N with the same version of mpv.

I even tested the device buffer size value I used on Android N, which is 200ms, but I also get the same problem with that on Android O. And I am pretty sure I didn't set `--audio-buffer` to larger than `0.2` back then.

In any case, single buffer works best for me in all circumstances and I can't really have a device buffer smaller than 250ms on Bluetooth audio anyway (unless it's as small as a couple *frames*, weird enough), otherwise I get similar problem.

**Pull request merged**
