### PR TITLE
demux_mkv: add A_MLP to mkv_audio_tags

### LINKED ISSUE #5923: mpv doesn't support Meridian Lossless Packing?
### mpv version and platform
mpv 0.28.0-583-gfae9d7744c — Windows 7, x64

### Reproduction steps
**mpv filename.mka**, where filename.mka contains MLP audio.

### Actual behavior
Error message below.

> [mkv] Unknown/unsupported audio codec ID 'A_MLP' for track 1 or missing/faulty
> [mkv] private codec data.
>  (+) Audio --aid=1 --alang=spa (*) ( 2ch 44100Hz)
> Failed to initialize a decoder for codec ''.
> Audio: no audio
> No video or audio streams selected.
>
>Exiting... (Errors when loading file)

### Log file

> [demux] Trying demuxers for level=normal.
> [mkv] Found the head...
> [mkv] + a segment...
> [mkv] Parsing seek head...
> [mkv] |+ segment information...
> [mkv] | + muxing app: libebml v1.3.0 + libmatroska v1.4.0
> [mkv] | + writing app: mkvmerge v5.8.0 ('No Sleep / Pillow') built on Sep 30 2012 10:57:14
> [mkv] | + timecode scale: 22674
> [mkv] | + duration: 216.112s
> [mkv] | + segment uid b3 6f 3e 64 59 11 11 de af 64 ce a0 8f 7a 0a 71
> [mkv] |+ segment tracks...
> [mkv] | + a track...
> [mkv] |  + Track number: 1
> [mkv] |  + Track type: Audio
> [mkv] |  + Audio track
> [mkv] |   + Sampling frequency: 44100.000000
> [mkv] |   + Channels: 2
> [mkv] |  + Codec ID: A_MLP
> [mkv] |  + Language: spa
> [mkv] |+ found cluster
> [mkv] Deferring reading cues.
> [mkv] All headers are parsed!
> [mkv] Unknown/unsupported audio codec ID 'A_MLP' for track 1 or missing/faulty
> [mkv] private codec data.
> [demux] Detected file format: Matroska
> [cplayer] Opening done: filename.mka
> [find_files] Loading external files in .
> [cplayer] Running hook: ytdl_hook/on_preloaded
> [mkv] select track 0
> [cplayer]  (+) Audio --aid=1 --alang=spa (*) ( 2ch 44100Hz)
> [ad] Codec list:
> [ad]     (no decoders)
> [ad] Failed to initialize a decoder for codec ''.
> [mkv] deselect track 0
> [cplayer] Audio: no audio
> [cplayer] No video or audio streams selected.
> [cplayer] finished playback, no audio or video data played (reason 4)
> [cplayer]
> [cplayer]
> [cplayer] Exiting... (Errors when loading file)
> [ytdl_hook] Exiting...
> [stats] Exiting...
> [osc] Exiting...

### PR DESCRIPTION
**Pull request by CounterPillow**
Fixes #5923 

I agree that my changes can be relicensed to LGPL 2.1 or later.

### CODE REVIEW

**Comment by jeeb** [comment]
If I get a verification that this works with, say, http://www.cccp-project.net/beta/test_files/mlp_sample_luckynight.mka , I will merge this.

**Comment by j605** [comment]
The patch works on the audio with the following warning but it doesn't seem to be related.
```
Playing: http://www.cccp-project.net/beta/test_files/mlp_sample_luckynight.mka
 (+) Audio --aid=1 (*) (mlp 2ch 44100Hz)
[mkv] This is a broken file! Packets with incorrect keyframe flag found. Enabling workaround.
AO: [pulse] 44100Hz stereo 2ch s16
A: 00:00:01 / 00:00:08 (15%) Cache:  1s+1MB
```

**Comment by tomty89** [comment]
```
// Deal with some FFmpeg-produced garbage, and assume all audio codecs can
    // start decoding from anywhere.
    if (strcmp(codec, "truehd") != 0)
        track->require_keyframes = true;
```
Perhaps we should add mlp to this.

**Comment by CounterPillow** [comment]
@tomty89 that doesn't get rid of the warning and just seemingly breaks seeking in the sample file.

**Comment by tomty89** [comment]
Yeah it doesn't help. Adding mlp to this seem to help getting rid of some error in seeking though:
```
    if (!strcmp(codec, "mp2") || !strcmp(codec, "mp3") ||
        !strcmp(codec, "truehd") || !strcmp(codec, "eac3"))
    {
        track->parse = true;
    }
```

**Comment by CounterPillow** [comment]
Such a change could be done in a separate PR with its implications discussed there, I don't think it's a good idea to grep for every truehd hack and wonder whether mlp should be added to it as well without more sample files and understanding of those hacks.

**Comment by jeeb** [comment]
Agreed. MLP is pretty much the origins of TrueHD (latter was developed from Meridian Lossless), but let's have that as separate change since this initially enables the support if that file works at the very least for A-B decoding. As for the sample file, I wonder how I originally created it. Some mkvtoolnix version from 2013 it seems (`libebml v1.3.0 + libmatroska v1.4.0`).

So this was not FFmpeg-produced garbage if it indeed lacks any random access points :D (unless I first used FFmpeg, and then mkvtoolnix somehow). Someone can try to reproduce with http://fate-suite.ffmpeg.org/lossless-audio/luckynight-partial.mlp and current mkvtoolnix.

**Comment by tomty89** [comment]
IMHO there's not much point adding the support if we can't even get it to work without errors and warnings. For one we have `--demuxer=lavf`, for two while libavformat supports mlp in matroska, I am not sure if that even means matroska ever "officially" supported mlp.

The reason I checked out truehd hacks was because it was based on mlp, whether that's actually relevant or not.

**Pull request merged**
