### PR TITLE
add libarchive multivolume support

### PR DESCRIPTION
**Pull request by kevmitch**
* read volumes from directory using known patterns: .rar, .r00 / .part0001.rar / 7z.001.
* use libarchive client data array for per-volume private data
* add switch, open, close callbacks
* other miscellaneous fixes.

### CODE REVIEW

**Comment by wm4** [comment]
Very nice. I've been meaning to implement this myself, but never got to it.

Does this preserve the ability to play multivolume rar files over http? (Obviously dir listing won't work over http.)

**Comment by wm4** [comment]
>Does this preserve the ability to play multivolume rar files over http? 

OK. Just tried it, and it doesn't. I think it's important, because that's what the users requesting the original rar support wanted.

**Comment by kevmitch** [comment]
Ok, I've changed the searching to do the same thing that rar.c does. But . . .

* Unlike rar.c, libarchive can't parse the files individually to tell if a given one is the last. Therefore, I just try and open them until it fails, but this spits out an ugly error message. Is there a more cautious way to tell if the stream is openable?
* The SEEK_END trick in seek_cb doesn't seem to work very well over HTTP. I get ```http: HTTP error 416 Requested Range Not Satisfiable```. It works fine if I don't add the seek_cb at all.

**Comment by wm4** [comment]
>Unlike rar.c, libarchive can't parse the files individually to tell if a given one is the last. Therefore, I just try and open them until it fails, but this spits out an ugly error message. Is there a more cautious way to tell if the stream is openable?

Does libarchive need all volumes at the beginning? If so, there's not much that can be done.

>The SEEK_END trick in seek_cb doesn't seem to work very well over HTTP. I get http: HTTP error 416 Requested Range Not Satisfiable. It works fine if I don't add the seek_cb at all.

Yes, HTTP doesn't allow range requests that would result in 0 bytes of data to read. The seek could be executed lazily.

**Comment by kevmitch** [comment]
Lazy seeking works brilliantly! 

It does appear that you need to provide libarchive with all volumes at the beginning. There's a comment in the vlc code complaining about it.

**Comment by kevmitch** [comment]
so is this good to merge? The only other think I could think of for the after the last file error message is to keep the list of files between subsequent calls to reopen_archive to at least reduce spamming for unseekable archives. But it would be a bit messy.

Should I remove the 'default': 'disable' from wscript, or was that there for other reasons?

**Comment by wm4** [comment]
Seems good enough for merge.

I'm not sure if this can replace the old rar code yet.

Also, libarchive still lacks support for non-ASCII entry filenames to be enabled by default, IMHO.

**Pull request merged**
