### PR TITLE
Remove nnedi3 prescaler

### PR DESCRIPTION
**Pull request by bjin**
The motivation behind this is about the license issue we have with nnedi3 prescaler. And with recent user hooks work by @haasn it's possible to perform prescaling solely on external shaders. 

I split out the removing of uniform buffer object into a seperate commit, just in case someone would like to reuse some of these routines.

As for the last commit removing the whole prescaling framework, not exactly sure, but as the comments I see from #3226, @haasn was also agreeing with it.

### CODE REVIEW

**Comment by haasn** [comment]
I'm sort of annoyed with the fact that the user shader version of NNEDI3 will have to hard-code the weights, which (as I understand) is slower on modern GPUs?

I'm also sort of bothered by the fact that the superxbr routine, which I wrote to be flexible and user-customizable (the mask is just a configurable array, rather than being hard-coded into the shader as before) will end up unused.

Finally, I'm bothered by the fact that user shaders implementing these passes will have to copy/paste the same code into two separate passes (rather than being able to re-use the same function), and on top of that they will have to copy paste this for every time that they want the superxbr shader to run (as a function of the input size). (Maybe we could make it so that a shader pass can have a configurable number of PASSES, where you can reference those passes inside the expressions for width/height/offset etc. as well as in the shader body?)

But on the other hand, I neither care about NNEDI3 nor super-xbr so it's not a big loss to mpv.

**Comment by wm4** [comment]
The best way nnedi could store the weights remains a mystery to me.

**Comment by paulguy** [comment]
`nnedi3-upload=shader` is much faster for me than `ubo`.  UBO is basically uselessly slow for me.  Would be interesting to see data from other people with other configurations.

nVidia GeForce GTX 960 proprietary drivers 361.18 in gentoo linux with mpv git-2b1656b

**Comment by bjin** [comment]
rebased. removed third commit, until we could find better way maintaining superxbr shader code.

**Comment by bjin** [comment]
re-pushed third commit. I have both shaders ported and moved to https://github.com/bjin/mpv-prescalers

**Comment by wm4** [comment]
Merged.

**Pull request closed without merging**
