### PR TITLE
vo_gpu_next: add chroma location to shader parameters

### PR DESCRIPTION
**Pull request by kasper93**

### CODE REVIEW

**Comment by Artoriuz** [comment]
I can confirm it works, tested with both left and centre chroma 👍

**Comment by kasper93** [comment]
@natural-harmonia-gropius: Are you interested in something like that? Would current mapping work for you?

**Comment by natural-harmonia-gropius** [comment]
> @natural-harmonia-gropius: Are you interested in something like that? Would current mapping work for you? Any suggestions?

Yeah, this makes things much easier. I did some quick test, and it works well. 😀

**Comment by kasper93** [comment]
Seems to work fine and do the job. Fill feature request if needed more properties or anything.

**Pull request merged**
