### PR TITLE
TOOLS/zsh.pl: die loudly if mpv fails to run

### PR DESCRIPTION
**Pull request by qmega**
See #1731. @hackeron Try this on the release build.

### CODE REVIEW

**Comment by wm4** [comment]
So do we want this or not? Apparently it was not needed to fix the issue.

**Comment by qmega** [comment]
I still think it's useful. It could make similar issues clearer in the future.

**Comment by hackeron** [comment]
I agree, this happened a few times in the past and currently it is hard to diagnose and there is not much output to aid in reporting an issue.

**Comment by wm4** [comment]
Merged.

**Pull request closed without merging**
