### PR TITLE
Lua 5.3 changes

### PR DESCRIPTION
**Pull request by mathstuf**
---

It at least doesn't disappear with light usage now. Probably more lurking, but this should be enough to at least play around with 5.3 (5.2 is untested since I don't have it right now).

### CODE REVIEW

**Comment by mathstuf** [comment]
@wm4 Is Lua 5.3 something you're still interested in seeing? Or is it still too hard to support in parallel to the currently supported Lua versions? FWIW, Fedora no longer ships Lua modules for 5.1 which some scripts use (posix, socket-http for `notify.lua`) which makes them harder to use.

**Comment by wm4** [comment]
Supporting 5.3 would be ok, but I still think it'd be chaos to support both 5.3 and 5.2 at once.

Does luajit support 5.3 yet?

**Comment by mathstuf** [comment]
The [luajit developer(s?)](http://www.freelists.org/post/luajit/Port-bitop-to-53,1) seem to not like 5.3, so "unlikely". [This Reddit thread](https://www.reddit.com/r/lua/comments/2zutj8/mike_pall_luajit_dislikes_lua_53/) has some discussion. Apparently even 5.2 isn't fully supported either (`_ENV` and yielding).

**Comment by enoposix** [comment]
This can be closed for the same reason as #1914.

**Pull request closed without merging**
