### PR TITLE
Thin out osc progress bar

### PR DESCRIPTION
**Pull request by da3dsoul1**
A more aesthetically pleasing thin seekbar with clearly visible chapters

image

### CODE REVIEW

**Comment by christoph-heinrich** [comment]
Very aesthetically pleasing indeed...
image

**Comment by da3dsoul1** [comment]
> Very aesthetically pleasing indeed... image

How do I replicate that? I have no such issues
image

**Comment by christoph-heinrich** [comment]
> How do I replicate that?

use a file with a longer title, or long changer names, or you set a long fixed string in osc.lua for testing.

**Comment by da3dsoul1** [comment]
> use a file with a longer title, or long changer names,

Yep, you are right, it does overlap on longer titles. I've zero knowledge in lua, anything can be done to fix/improve that?

**Comment by christoph-heinrich** [comment]
You could hide the title/chapter while hovering, or add a background behind the tooltip.

To me that doesn't really seem like an improvement over the status quo, but I also don't use the default osc so maybe someone else should weigh in on if that's a good idea or not.

**Comment by Dudemanguy** [comment]
Were you interested in working on this further? Obviously we can't accept this in the current state plus there are many problems with the commit (see the contributing.md guide). I marked it as draft for now.

**Comment by da3dsoul1** [comment]
> but I also don't use the default osc

That's the thing, most users stray off master osc because there's always a thing or two they don't like about it, and no one wants to improve on it for some reason, I don't like how stale it is.

> Were you interested in working on this further

I am, but as I said before I have zero knowledge in lua, just trying things out bit by bit, If I come up with anything I will gladly share it!

**Comment by kasper93** [comment]
Inactive and I think if we change core OSC look the changes should be more in-depth and thought out, rather than ad-hoc change.

**Pull request closed without merging**
