### PR TITLE
Mpv opengl cb drop count

### PR DESCRIPTION
**Pull request by xylosper**
First, add two functions in vo.h/vo.c:
```
void vo_increment_drop_count(struct vo *vo);
void vo_increment_drop_count_by(struct vo *vo, int64_t n);
```
which make it possible to increment the counter from any vo.

Second, use these functions in vo_opengl_cb instead of internal counter to provide the number of dropped frame by opengl-cb through `vo-drop-frame-count` property.

### CODE REVIEW

**Comment by wm4** [comment]
OK, but I think the ``vo_increment_drop_count`` function is redundant and should be dropped. Can you update the patch?

**Comment by xylosper** [comment]
In that case, is it better to rename vo_increment_drop_count_by to vo_increment_drop_count?

**Comment by wm4** [comment]
Yes, I agree with this.

**Comment by xylosper** [comment]
Okay, done.

**Comment by wm4** [comment]
Adjusted the commits, merged, thanks.

**Pull request closed without merging**
