### PR TITLE
gl_utils: add debugging output to uniforms

### PR DESCRIPTION
**Pull request by haasn**

### CODE REVIEW

**Comment by wm4** [comment]
Why, isn't this rather a case for apitrace? I'm not terribly opposed to this though - I just dislike that my attempts to remove all "partial" log message calls (which don't include newlines) is sabotaged. Also, possibly MP_TRACE would be more apprioriate for this - aren't they printed every frame?

**Comment by wm4** [comment]
To elaborate on these log calls which don't end in newlines: they are basically race conditions, and can result in broken output if another thread happens to print a log message before this thread outputs the ``\n``.

**Comment by haasn** [comment]
> Why, isn't this rather a case for apitrace?

I didn't know apitrace would let you inspect uniforms like that. Arguably, the same could be said for GLSL shader output, though. (Which is also clearly visible in the apitrace)

> I just dislike that my attempts to remove all "partial" log message calls (which don't include newlines) is sabotaged.

I thought about that, but figured an extra allocation + a bunch of talloc append calls (or whatever) would be weirder than a few disjointed calls to MP_DBG. (But then again, don't we already do that every frame either way for the shader source? Oh well)

Should probably be moved to TRACE, yeah.

> aren't they printed every frame?

Only since we don't cache them. Ideally, if/when we ever bother to cache uniforms, they would only get printed when they change.

**Comment by wm4** [comment]
It could also be built in the stack (maybe with using mp_snprintf_cat), but I guess it doesn't matter, so whatever is better.

**Comment by wm4** [comment]
I think this can be considered dropped.

**Comment by haasn** [comment]
Yes, the bottom line is that apitrace does this well enough.

**Pull request closed without merging**
