### PR TITLE
Remove support for the deprecated VK_NV_glsl_shader

### PR DESCRIPTION
**Pull request by linkmauve**
This extension is deprecated as of Vulkan 1.1.81.

I kept the `#if HAVE_SHADERC` in video/out/gpu/spirv.c and didn’t merge the shaderc backend into it because we may gain a better GLSL to SPIR-V compiler someday.

### CODE REVIEW

**Comment by haasn** [comment]
Missing interface-changes.rst, also wrong commit title.

[I already wrote this commit btw](https://github.com/haasn/mpv/commit/7c10c08661ba6fc9d4e52b2fcde051e865640746), but you can take over authorship if you want to.

**Comment by haasn** [comment]
1. I don't have push access,
2. This was only causing problems for the libplacebo branch. If it's not causing any problems on master we don't have to remove it right away.

And yeah, the wscript change is reasonable - the only reason I didn't have that in mine is because I change the dep to `libplacebo` afterwards anyway. But you're right, this commit should change the wscript as well.

**Comment by jeeb** [comment]
Cherry-picked and applied the wscript change and pushed as 5bcac8580df6fc62323136f756a3a6d1e754fe9c .
```bash
git cherry-pick 7c10c08661ba6fc9d4e52b2fcde051e865640746
git checkout bb7055d16f5ad2ab83972af74250d484922d2ddb -- wscript
git commit --amend
```

**Comment by jeeb** [comment]
Thanks to both for this btw, this was confusing people being able to build with vulkan, but not being able to actually utilize it.

**Pull request closed without merging**
