### PR TITLE
DOCS/compile-windows.md: update MSYS2 instructions

### PR DESCRIPTION
**Pull request by kevmitch**
* Use the update-core command
* CC=gcc is no longer necessary
* Don't recommend adding /mingw64/bin to the %PATH% as this can cause problems
  with other things (i.e., cygwin). Instead just copy the required DLLs where
  needed.
* Recommend winpty
* Add note about ANGLE

### CODE REVIEW

**Comment by wm4** [comment]
Last I tried, I needed `CC=gcc.exe --check-c-compiler=gcc`. This was with a mix of msys, cygwin, and MSVC, though.

**Comment by kevmitch** [comment]
I checked with a fresh MSYS2 install that it isn't needed. On the other hand, `CC=gcc.exe --check-c-compiler=gcc` doesn't appear to hurt (I found that it did at one point). I added it back along with the `--check-c-compiler=gcc` to be safe.

**Comment by rossy** [comment]
I definitely don't need the ``--check-c-compiler=gcc`` in a pure MSVC environment. I think you might need it if cl.exe is on the PATH though.

**Comment by wm4** [comment]
> I think you might need it if cl.exe is on the PATH though.

Yes. Hints how to stop waf from this nonsense would be appreciated too.

**Comment by rossy** [comment]
> Don't recommend adding /mingw64/bin to the %PATH% as this can cause problems with other things (i.e., cygwin). Instead just copy the required DLLs where needed.

I have no problem with this on pure MSYS2 systems either. Adding /mingw64/bin to the PATH just works, but copying the DLLs manually means copying a lot of DLLs.

```bash
$ ldd /mingw64/bin/mpv.exe | grep mingw64 | wc -l
75
```

The rest of the changes look good though. I've been meaning to change the instructions to use ``update-core``.

**Comment by kevmitch** [comment]
Ok, well I guess the real solution is to do a static compile. Too bad that is broken in five different ways right now. I added the %PATH% suggestion back with a warning.

**Comment by rossy** [comment]
Looks good. By the way, is it necessary to use ``CC=gcc.exe`` instead of ``CC=gcc``? (I don't really mind too much, I just think .exe extensions are kinda ugly.)

**Comment by kevmitch** [comment]
> By the way, is it necessary to use CC=gcc.exe instead of CC=gcc?

Probably not. Changed.

**Comment by wm4** [comment]
Seems fine with that.

**Pull request merged**
