### PR TITLE
osc: add seekbarstyle=knob

### PR DESCRIPTION
**Pull request by wiiaboo**
@ChrisK2

### CODE REVIEW

**Comment by wiiaboo** [comment]
Slimbox with knob looks  really nice with the second commit:
image

**Comment by ChrisK2** [comment]
Okay, but don't use it as default without performance testing.

**Comment by wiiaboo** [comment]
We'd probably need to add a circle glyph to the built-in font and use that to avoid doing the circle.

**Comment by ChrisK2** [comment]
That would probably help, as long as you don't run into weird positioning problems.

**Pull request merged**
