### PR TITLE
RFC: Rename osdep files for consistency

### PR DESCRIPTION
**Pull request by kasper93**
Only for RFC. Not finished, I only want to know if something like this would be updated, to not put more time into it if we don't want to separate things. (android change will be removed)

### CODE REVIEW

**Comment by Dudemanguy** [comment]
I don't know how everyone else feels, but I prefer the structure of having `path-unix.c`, `path-win.c`, etc. in the root of osdep with the matching header. Other random os-dependent stuff I don't mind being a subdirectory though.

**Comment by kasper93** [comment]
> I don't know how everyone else feels, but I prefer the structure of having `path-unix.c`, `path-win.c`, etc. in the root of osdep with the matching header. Other random os-dependent stuff I don't mind being a subdirectory though.

Either all or nothing in my opinion. Else we gonna have a mix of things again.

**Comment by Akemi** [comment]
it doesn't make sense to rename and move all mac/darwin related files into a darwin subfolder.
- darwin is a subset of macOS, so darwin specific things work on macOS but macOS things won't on darwin
- we have a lot of mac related code that is only working on mac since they use macOS frameworks

i suggest to just name it 'mac', like windows is also just named 'win' or 'win32'.

**Comment by kasper93** [comment]
> it doesn't make sense to rename and move all mac/darwin related files into a darwin subfolder.

Yes, I agree. There is a lot of macos specific code that I just bundled together, mostly because it was easier to make it pass on CI this way. (current version fails, but I had working one)

Maybe I will just move meson stuff. But then it is awkward, because without renaming files we have some of platform details in directory and rest not. Problem with this change is really there is not good way to do it incrementally.

**Comment by kasper93** [comment]
There is some value in separating meson files, but big refactor like that probably wouldn't be accepted so closing this.

**Pull request closed without merging**
