### PR TITLE
ao_coreaudio: handle latency change on hotplug

### LINKED ISSUE #13600: Audio latency stuck when switching to/from bluetooth output
### Important Information

Provide following Information:
- mpv 0.36.0
- macOS 14.3.1
- Source of the mpv binary or bundle: homebrew
- If known which version of mpv introduced the problem: N/A
- Possible screenshot or video of visual glitches: N/A

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

1. Start a video with a bluetooth audio device already set as system output.
2. Observe that audio is delayed appropriately to match bluetooth latency.
3. Switch system output to non-bluetooth audio device (i.e. the built-in speakers)
4. Observe that audio delay remains at same value as before.

The same happens if you start with a non-bluetooth device and switch to a bluetooth device.

### Expected behavior

When I switch from non-bluetooth audio to bluetooth (or vice-versa), the audio delay updates as expected.

### Actual behavior

When I switch from non-bluetooth audio to bluetooth (or vice-versa), the audio delay doesn't update as expected.

### Log file

Here's the log file: [output.txt](https://github.com/mpv-player/mpv/files/14441951/output.txt)

### Sample files

I've been using MKVs.

### PR DESCRIPTION
**Pull request by ruihe774**
Fix #13600

### CODE REVIEW

**Comment by ruihe774** [comment]
@Akemi would you plz review it?

**Comment by Akemi** [comment]
thanks for the fix here too.

**Comment by maflaven** [comment]
Still seeing the issue at least hot-swapping from wired speakers to bluetooth headphones. Attaching the video I was using to test too.
[output.txt](https://github.com/mpv-player/mpv/files/14810227/output.txt)

https://github.com/mpv-player/mpv/assets/6855626/d134e088-c623-413e-93fc-938ac840f5d7

**Comment by ruihe774** [comment]
> Still seeing the issue at least hot-swapping from wired speakers to bluetooth headphones. Attaching the video I was using to test too. [output.txt](https://github.com/mpv-player/mpv/files/14810227/output.txt)
> a.v-sync-test.mp4

Hmm... My fault. We need also register hotplug_cb in normal `init`

**Pull request merged**
