### PR TITLE
wayland: partially fix drag and drop handling

### PR DESCRIPTION
**Pull request by Dudemanguy**
Here for testing. See the commit for details.

### CODE REVIEW

**Comment by LaserEyess** [comment]
Does not seem to be working for me with firefox. https://0x0.st/oH5j.txt

**Comment by Dudemanguy** [comment]
Really? It works for me. I can't see why it would be possibly different (well okay I use ESR normally I guess but still...)

**Comment by LaserEyess** [comment]
Mozilla Firefox 96.0.3, I see the DND in the logs, no video starts playing. Reproducible with:

```
mpv --no-config --idle=once --force-window
```

**Comment by Dudemanguy** [comment]
I dragged a youtube link onto 96.0.3 with those options and it played as expected.

**Comment by LaserEyess** [comment]
Now I can't get DND to work at all, even on chromium. I don't know what's happening but I'm going to assume my issues are unrelated.

**Comment by LaserEyess** [comment]
I use a custom PKGBUILD that downloads github patches I'm testing and does `git apply`, that's where the `-dirty` is from. That being said, I wiped my mpv repo, re-cloned, and built it again; same result.

**Comment by Dudemanguy** [comment]
Just for the record, it turns out `focus_follow_mouse` in sway's config affects this (i.e. it works if it's `no` but  not `yes`).

**Comment by Dudemanguy** [comment]
There's one gap with this (as explained in the commit message), but I'm not sure how to handle it or who even is at fault here. This is a definite improvement from the current status quo though so I will go ahead and pull this in.

**Pull request merged**
