### PR TITLE
input: add MOUSE_ENTER keybinding.

### PR DESCRIPTION
**Pull request by torque**
There's a MOUSE_LEAVE key, so why not have a MOUSE_ENTER key as well?

Only tested on OS X.

### CODE REVIEW

**Comment by wm4** [comment]
>There's a MOUSE_LEAVE key, so why not have a MOUSE_ENTER key as well?

Because "enter" is redundant with the first mouse move event, while "leave" absolutely needs to be a separate event.

Any reason why you want/need this event?

**Comment by torque** [comment]
While mouse enter may be redundant with the first mouse move, binding to it is not the same as binding to mouse move.

For example, when the mouse leaves the window tracking area (in cocoa, at least), the mouse position stops being updated and stays at the last in-window point. From Lua it is easy to bind a callback to `mouse_leave` to check that the mouse is no longer in the window, but the only way to check that it has reentered the window without a huge number of spurious events is to store the old position and bind to `mouse_move`, check that the position has changed, and then unbind `mouse_move` until the mouse leaves again. Even if there were easy way to only bind `mouse_move` once, it'd have to be rebound each time the mouse left the window. In my opinion, these workarounds are dumb when the OS can easily send a `mouse_enter` event that serves the same purpose in a much more straightforward manner.

From a keybinding perspective, I don't know why anyone would want to bind `mouse_leave` as a key in input.conf, but if they did (e.g. maybe pausing or something), I expect they'd probably want a `mouse_enter` binding to perform a symmetric event on mouse enter. I don't even think the Lua workaround would work for input.conf, but again, I may be missing something.

Hopefully that justifies it.

**Comment by wm4** [comment]
That sounds actually good enough for a justification. Will merge and check the other platforms later.

**Comment by wm4** [comment]
Merged.

**Pull request closed without merging**
