### PR TITLE
github/issue_template: use GitHub's form schema

### PR DESCRIPTION
**Pull request by zhongfly**
Using GitHub's form schema will restrict the issue format more strictly.

preview: https://github.com/zhongfly/mpv/issues/new/choose

### CODE REVIEW

**Comment by haasn** [comment]
I think I prefer a markdown template to a github form. It's more flexible. Sometimes the sections just simply don't make sense, or it makes sense to add new sections.

People who think they're above filling out a markdown template won't be stopped by a form, either.

**Comment by avih** [comment]
> I think I prefer a markdown template ... People who think they're above filling...

+1

**Comment by philipl** [comment]
Agree with @Akemi. Just having the text area with separate instructions is a big benefit.

**Comment by zhongfly** [comment]
Thanks to @Akemi advice, I have simplified the format and added pre-filled content.
How is this now?
image

**Pull request closed without merging**
