### PR TITLE
Refactor HDR metadata

### PR DESCRIPTION
**Pull request by haasn**
Clean up some warts, improve documentation/comments, and add a new `ref_white` param that allows you to explicitly control the PQ mapping as well as adjust exposure etc.

In addition, use MaxCLL instead of mastering metadata where possible in order to infer sig_peak

### CODE REVIEW

**Comment by wm4** [comment]
Since you change this code anyway, maybe it'd be better to handle the hdr peak sanitation in `fix_image_params` in dec_video.c? It's only called when parameters change.

**Comment by haasn** [comment]
Oh, good point. I'll change it later/tomorrow

**Comment by haasn** [comment]
While working more on this HDR stuff it's come to my attention that our `ref_white` *and* `--target-brightness` along with it are both actually sort of unnecessary, because PQ has a known reference white (100 cd/m^2) according to the OOTF definition. So I've updated the PR in order to simplify this stuff again.

**Comment by haasn** [comment]
@wm4 will `fix_image_params` actually run every time the image_params change, including per-frame?

**Comment by wm4** [comment]
Yes, there is no such thing as non-per frame change in mpv on this level.

**Comment by haasn** [comment]
Great, and it even avoids spamming the same message.

Btw, there's one more commit I'd like to include in this batch: the one to fix the HLG implementation to use the real EOTF (with the OOTF baked in), but I'm hitting a brick wall trying to find the inverse OOTF (which the ITU-R specification mystically alludes to but seems to require several hours of ##math to actually find)

**Comment by haasn** [comment]
Due to the difficulty of inverting the HLG EOTF, I've instead decided to abstract mpv so that it can support more than just the EOTF, effectively allowing us to use the OETF for HLG instead, which is faciliated via a new mp_colorspace member that tells us whether it's scene-referred or display-referred.

(Which is essentially the same approach as stuff like zimg, although unlike zimg we also support other OOTFs - including the one from the BT.2100 HLG spec)

**Comment by haasn** [comment]
@wm4 this PR contains all the changes I wanted to add to it

**Comment by haasn** [comment]
Fixed some edge cases and rebased

**Comment by haasn** [comment]
Fixed some more bugs. Any feedback? Somebody else want to test it?

**Comment by wm4** [comment]
Merged.

**Pull request closed without merging**
