### PR TITLE
various: minor fix GitHub style

### PR DESCRIPTION
**Pull request by eltociear**
github -> GitHub

### CODE REVIEW

**Comment by sfan5** [comment]
there are a few more:
<pre>
osdep/macosx_menubar.m
581:                        @"name"       : @"mpv on github…",

DOCS/contribute.md
14:- Make a github pull request, or send a link to a plaintext patch created with
114:- We don't squash-merge (nor do we use github's feature that does this) because
120:- Reviewers are encouraged to look at individual commits instead of github's
</pre>

**Comment by eltociear** [comment]
@sfan5 thanks! fixed it.

**Comment by sfan5** [comment]
Looks good but please adjust the commit messages. "Update example.txt" is not meaningful.

**Comment by eltociear** [comment]
@sfan5 Changed commit message!

**Comment by sfan5** [comment]
merged as dd48a53b6594052b337a89bcecb11494207300a1

**Pull request closed without merging**
