### PR TITLE
cocoa: fix macOS 10.12 deprecation warnings

### PR DESCRIPTION
**Pull request by Akemi**
fixes the deprecation warnings on sierra.

### CODE REVIEW

**Comment by wm4** [comment]
Is it intended that this makes the Travis configure check for Cocoa legitimately fail?

**Comment by Akemi** [comment]
i have no idea. before making this PR i tested building it on 10.12 and 10.10 and both worked without a problem.

**Comment by Akemi** [comment]
i think i found the problem with building on 10.9. hope this little change will fix it.

**Comment by JCount** [comment]
I believe that the problem in this case is that Homebrew is no longer supporting 10.9, which means that there is no longer a binary package hosted for ffmpeg-stable for any version before 10.10.

**Comment by Akemi** [comment]
the problem before wasn't (we got a new error now). i just build everything with homebrew on 10.9 and it worked, though i built ffmpeg from git master.

the error now just indicates that it chocked on libass for whatever reason.

**Comment by JCount** [comment]
I didn't mean to imply the error is the same. However, unless I am misreading TOOLS/travis-deps, it will fail if it is trying to use the bottled (binary) ffmpeg from Homebrew, because it no longer exists.

(Also, for OS X Travis CI is changing the default environment to Xcode 7.3 and removing all but 3 images, including all of the 10.9 options. The details are here in this [Travis CI blog post](https://blog.travis-ci.com/2016-09-15-new-default-osx-image-coming/).)

**Comment by wm4** [comment]
So, merge or not merge?

**Comment by pigoz** [comment]
Looks like the ci error is fixed. The changes look ok, so I'd say merge :)

**Comment by wm4** [comment]
OK then, merged.

**Pull request closed without merging**
