### PR TITLE
.travis.yml: removed whitespace

### PR DESCRIPTION
**Pull request by nitish091**
.travis.yml: removed whitespace

### CODE REVIEW

**Comment by Akemi** [comment]
the commit message should adhere to our contribution guidelines. since you are a first-time contributor please read https://github.com/mpv-player/mpv/blob/master/DOCS/contribute.md

**Comment by nitish091** [comment]
@Akemi I read it. Isn't it correct?
Filename: issue_resolved

**Comment by wm4** [comment]
This commit has the commit message "Update .travis.yml", while the project conventions call for something like "travis.yml: remove stray whitespace".

The contents of this commit are OK I guess.

**Comment by nitish091** [comment]
@wm4 okay. I'll keep that in mind, next time i create a commit.

**Comment by wm4** [comment]
This gives you the opportunity to learn how to use "git amend" to correct your commit/PR. Please try it.

**Comment by Akemi** [comment]
since we can't merge it like this and nothing was done since quite a while, i will close it. if you can't amend and force push just open a new branch and PR.

**Pull request closed without merging**
