### PR TITLE
TOOLS/lua/autoload: add 'ts' to default autoload extensions

### PR DESCRIPTION
**Pull request by llyyr**
Read this before you submit this pull request:
https://github.com/mpv-player/mpv/blob/master/DOCS/contribute.md

Reading this link and following the rules will get your pull request reviewed
and merged faster. Nobody wants lazy pull requests.

### CODE REVIEW

**Comment by CogentRedTester** [comment]
`ts` is also the file extension for Typescript files, though I suppose it's relatively unlikely for typescript files to be in the same directory as media files.

**Comment by sfan5** [comment]
> `ts` is also the file extension for Typescript files, though I suppose it's relatively unlikely for typescript files to be in the same directory as media files.

If you play videos from your unorganized downloads folder that doesn't seem so implausible.

**Comment by llyyr** [comment]
Even if there are Typescript files in the directory, all that's going to happen is mpv going "Failed to recognize file format." and skipping past it

**Comment by hooke007** [comment]
Why try to add this again? https://github.com/mpv-player/mpv/pull/11873#issuecomment-1623712214

**Comment by llyyr** [comment]
> Why try to add this again?

I forgot it was already rejected

**Pull request closed without merging**
