### PR TITLE
add d3d11 backend for the Render API

### PR DESCRIPTION
**Pull request by dragonflylee**
add dxgi render api to sovle https://github.com/mpv-player/mpv/issues/5979

1. pass a `ID3D11Device` from host app when init mpv render content
2. pass backBufferResource of `ID3D11Texture2D` during call `mpv_render_context_render`

see demo for using this api https://gist.github.com/dragonflylee/a7764253efb026bd67666542910ec75e

### CODE REVIEW

**Comment by Dudemanguy** [comment]
Sorry for doing this since I'm pretty much going to shoot you down in this reply, but do we really want this? The render API/vo_libmpv is basically a Frankenstein mess in my opinion and I honestly would have proposed deprecating it if it wasn't for the fact that macOS uses it as its primary VO (hopefully this changes soon). vo_libmpv misses out on all of the improvements we make to vo_gpu_next or what is done in libplacebo (e.g. anything HDR is going to suck). It's just strictly inferior and by design it always will be.

For specifically d3d11, it's only relevant on windows and win32 already offers an extremely simple way to do native window embedding. With a few lines in your libmpv client, you can simply set the `wid` of the mpv window and then make your client's window the parent (or whatever the correct terminology is in the windows-world). You can then use `vo_gpu_next` with any graphics API backend you want and get exactly the same thing and run the exact same code you'd get from just running the mpv executable alone. This is what mpv.net does for example.

I realize the render API does need some replacement particularly for platforms that are hostile to developers like wayland. I do actually have a new API for mpv designed already that is meant to replace it. But I need to actually finish writing a demo application to convince myself that it works. It should be far simpler and much easier to maintain while still satisfying the usecase of "embed mpv in my application".

**Comment by tbertels** [comment]
Embedding mpv on Wayland requires using the render API (`vo=libmpv`).
The effort by @Dudemanguy seems not doable with the current Wayland status: https://github.com/mpv-player/mpv/issues/12486#issuecomment-1763210748

#5979 (d3d11 backend for the Render API) is still very much open.
As is #10810 (Support for libplacebo (gpu-next) in the rendering API) and it got a PR a few days ago.

So if you @dragonflylee are still up to this, you could reopen this PR.

**Comment by Dudemanguy** [comment]
Yeah feel free to bring this back. I'm not a fan of the render API but nobody has thought of anything better so oh well I guess....

dmabuf-wayland is a whole other beast but maybe we can just use something like [libwlembed](https://gitlab.xfce.org/kelnos/libwlembed) for that.

**Comment by ikas-mc** [comment]
So is there a chance this could be merged?  
We’re currently using it on Xbox and it works well.  

Now on Windows, MPV already supports passing in HWID (for classic Win32) and exporting a display swapchain (supports WinUI 2 and WinUI 3).  
If this can be merged, it would make self-drawn apps pretty easy, like Xbox corewindow-only apps.  

The GPU-next render API is going to be a big project, it will need a full refactor of the existing GPU-next code. I think that’s going to take a long time…

~~and  gpu-next currently cannot run on Xbox.~~

**Comment by kasper93** [comment]
I've taken this and refactored a bit, fixed double free and added docs. See https://github.com/mpv-player/mpv/pull/17764 Also changes to take texture, instead of swapchain and extracting its buffer, caller can do it themselves.

**Pull request closed without merging**
