### PR TITLE
WIP: vo_vaapi_wayland: add OSD

### PR DESCRIPTION
**Pull request by boxerab**

### CODE REVIEW

**Comment by boxerab** [comment]
image

**Comment by boxerab** [comment]
@Dudemanguy if you have time, can you try this out ? Key presses on overlay aren't working yet, that is a known issue. I'm trying to understand why the OSD flickers when mouse is inside window.

**Comment by Zapeth** [comment]
Whats the status of this?

I'd like to switch to `vo_dmabuf_wayland`, but without an OSD its unfortunately not really usable as a video player for me.

**Comment by Dudemanguy** [comment]
It would need to be completely re-adapted for `dmabuf-wayland`. This is pretty old.

>I'd like to switch to vo_dmabuf_wayland

Are you absolutely sure? It's a low-quality, power-efficient VO. Not exactly meant for regular use.

**Comment by Zapeth** [comment]
>  It's a low-quality, power-efficient VO.

Yeah, I want to use it for its power efficiency (battery powered device). I didn't actually notice any difference in quality compared to the default VO so I guess that would be fine for me too, though now that you've mentioned it I'll check again for peace of mind.

**Comment by Dudemanguy** [comment]
>Yeah, I want to use it for its power efficiency (battery powered device).

Ah yeah okay that's cool. I get worried sometimes that users might mistakenly think this is for generic wayland support or something.

**Comment by Dudemanguy** [comment]
Superseded by #11877. Thanks for showing how to do this though! Helped me out a lot.

**Pull request closed without merging**
