### PR TITLE
vo_opengl: dxinterop: fix compatibility issue with Vista

### PR DESCRIPTION
**Pull request by igv**
Since Vista is supported OS make dxinterop compatible with it.

### CODE REVIEW

**Comment by rossy** [comment]
Looks good, apart from that header issue. It probably needs a physical Vista machine for testing though and I don't have one of those.

**Comment by wm4** [comment]
So should I merge it?

**Comment by rossy** [comment]
Yep. Looks good to me.

**Comment by wm4** [comment]
Merged.

**Pull request closed without merging**
